-- Rollback Script for State: New Mexico | Phase: benefits_hhs
-- Generated At: 2026-06-15T19:14:56.427Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'valencia-nm', program_id = 'nm-medicaid', office_name = 'Valencia County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-valencia-nm-medicaid';
UPDATE county_offices SET county_id = 'union-nm', program_id = 'nm-medicaid', office_name = 'Union County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-union-nm-medicaid';
UPDATE county_offices SET county_id = 'torrance-nm', program_id = 'nm-medicaid', office_name = 'Torrance County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-torrance-nm-medicaid';
UPDATE county_offices SET county_id = 'taos-nm', program_id = 'nm-medicaid', office_name = 'Taos County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-taos-nm-medicaid';
UPDATE county_offices SET county_id = 'socorro-nm', program_id = 'nm-medicaid', office_name = 'Socorro County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-socorro-nm-medicaid';
UPDATE county_offices SET county_id = 'sierra-nm', program_id = 'nm-medicaid', office_name = 'Sierra County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-sierra-nm-medicaid';
UPDATE county_offices SET county_id = 'santa-fe-nm', program_id = 'nm-medicaid', office_name = 'Santa Fe County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-santa-fe-nm-medicaid';
UPDATE county_offices SET county_id = 'san-miguel-nm', program_id = 'nm-medicaid', office_name = 'San Miguel County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-san-miguel-nm-medicaid';
UPDATE county_offices SET county_id = 'san-juan-nm', program_id = 'nm-medicaid', office_name = 'San Juan County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-san-juan-nm-medicaid';
UPDATE county_offices SET county_id = 'sandoval-nm', program_id = 'nm-medicaid', office_name = 'Sandoval County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-sandoval-nm-medicaid';
UPDATE county_offices SET county_id = 'roosevelt-nm', program_id = 'nm-medicaid', office_name = 'Roosevelt County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-roosevelt-nm-medicaid';
UPDATE county_offices SET county_id = 'rio-arriba-nm', program_id = 'nm-medicaid', office_name = 'Rio Arriba County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-rio-arriba-nm-medicaid';
UPDATE county_offices SET county_id = 'quay-nm', program_id = 'nm-medicaid', office_name = 'Quay County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-quay-nm-medicaid';
UPDATE county_offices SET county_id = 'otero-nm', program_id = 'nm-medicaid', office_name = 'Otero County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-otero-nm-medicaid';
UPDATE county_offices SET county_id = 'mora-nm', program_id = 'nm-medicaid', office_name = 'Mora County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-mora-nm-medicaid';
UPDATE county_offices SET county_id = 'mckinley-nm', program_id = 'nm-medicaid', office_name = 'McKinley County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-mckinley-nm-medicaid';
UPDATE county_offices SET county_id = 'luna-nm', program_id = 'nm-medicaid', office_name = 'Luna County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-luna-nm-medicaid';
UPDATE county_offices SET county_id = 'los-alamos-nm', program_id = 'nm-medicaid', office_name = 'Los Alamos County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-los-alamos-nm-medicaid';
UPDATE county_offices SET county_id = 'lincoln-nm', program_id = 'nm-medicaid', office_name = 'Lincoln County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lincoln-nm-medicaid';
UPDATE county_offices SET county_id = 'lea-nm', program_id = 'nm-medicaid', office_name = 'Lea County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lea-nm-medicaid';
UPDATE county_offices SET county_id = 'hidalgo-nm', program_id = 'nm-medicaid', office_name = 'Hidalgo County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-hidalgo-nm-medicaid';
UPDATE county_offices SET county_id = 'harding-nm', program_id = 'nm-medicaid', office_name = 'Harding County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-harding-nm-medicaid';
UPDATE county_offices SET county_id = 'guadalupe-nm', program_id = 'nm-medicaid', office_name = 'Guadalupe County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-guadalupe-nm-medicaid';
UPDATE county_offices SET county_id = 'grant-nm', program_id = 'nm-medicaid', office_name = 'Grant County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-grant-nm-medicaid';
UPDATE county_offices SET county_id = 'eddy-nm', program_id = 'nm-medicaid', office_name = 'Eddy County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-eddy-nm-medicaid';
UPDATE county_offices SET county_id = 'do-a-ana-nm', program_id = 'nm-medicaid', office_name = 'Doña Ana County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-do-a-ana-nm-medicaid';
UPDATE county_offices SET county_id = 'de-baca-nm', program_id = 'nm-medicaid', office_name = 'De Baca County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-de-baca-nm-medicaid';
UPDATE county_offices SET county_id = 'curry-nm', program_id = 'nm-medicaid', office_name = 'Curry County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-curry-nm-medicaid';
UPDATE county_offices SET county_id = 'colfax-nm', program_id = 'nm-medicaid', office_name = 'Colfax County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-colfax-nm-medicaid';
UPDATE county_offices SET county_id = 'cibola-nm', program_id = 'nm-medicaid', office_name = 'Cibola County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-cibola-nm-medicaid';
UPDATE county_offices SET county_id = 'chaves-nm', program_id = 'nm-medicaid', office_name = 'Chaves County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-chaves-nm-medicaid';
UPDATE county_offices SET county_id = 'catron-nm', program_id = 'nm-medicaid', office_name = 'Catron County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-catron-nm-medicaid';
UPDATE county_offices SET county_id = 'bernalillo-nm', program_id = 'nm-medicaid', office_name = 'Bernalillo County storefront office', address = '', phone = '(800) 283-4465', email = '', website = 'https://www.hsd.state.nm.us/', source_url = 'https://www.hsd.state.nm.us/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-bernalillo-nm-medicaid';

COMMIT;
