-- Rollback Script for State: New Mexico | Phase: district_replacements
-- Generated At: 2026-06-15T00:01:08.538Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'valencia-nm', name = 'Valencia County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-valencia-nm';
UPDATE school_districts SET county_id = 'union-nm', name = 'Union County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-union-nm';
UPDATE school_districts SET county_id = 'torrance-nm', name = 'Torrance County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-torrance-nm';
UPDATE school_districts SET county_id = 'taos-nm', name = 'Taos County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-taos-nm';
UPDATE school_districts SET county_id = 'socorro-nm', name = 'Socorro County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-socorro-nm';
UPDATE school_districts SET county_id = 'sierra-nm', name = 'Sierra County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-sierra-nm';
UPDATE school_districts SET county_id = 'santa-fe-nm', name = 'Santa Fe County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-santa-fe-nm';
UPDATE school_districts SET county_id = 'san-miguel-nm', name = 'San Miguel County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-san-miguel-nm';
UPDATE school_districts SET county_id = 'san-juan-nm', name = 'San Juan County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-san-juan-nm';
UPDATE school_districts SET county_id = 'sandoval-nm', name = 'Sandoval County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-sandoval-nm';
UPDATE school_districts SET county_id = 'roosevelt-nm', name = 'Roosevelt County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-roosevelt-nm';
UPDATE school_districts SET county_id = 'rio-arriba-nm', name = 'Rio Arriba County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-rio-arriba-nm';
UPDATE school_districts SET county_id = 'quay-nm', name = 'Quay County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-quay-nm';
UPDATE school_districts SET county_id = 'otero-nm', name = 'Otero County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-otero-nm';
UPDATE school_districts SET county_id = 'mora-nm', name = 'Mora County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-mora-nm';
UPDATE school_districts SET county_id = 'mckinley-nm', name = 'McKinley County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-mckinley-nm';
UPDATE school_districts SET county_id = 'luna-nm', name = 'Luna County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-luna-nm';
UPDATE school_districts SET county_id = 'los-alamos-nm', name = 'Los Alamos County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-los-alamos-nm';
UPDATE school_districts SET county_id = 'lincoln-nm', name = 'Lincoln County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-lincoln-nm';
UPDATE school_districts SET county_id = 'lea-nm', name = 'Lea County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-lea-nm';
UPDATE school_districts SET county_id = 'hidalgo-nm', name = 'Hidalgo County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-hidalgo-nm';
UPDATE school_districts SET county_id = 'harding-nm', name = 'Harding County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-harding-nm';
UPDATE school_districts SET county_id = 'guadalupe-nm', name = 'Guadalupe County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-guadalupe-nm';
UPDATE school_districts SET county_id = 'grant-nm', name = 'Grant County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-grant-nm';
UPDATE school_districts SET county_id = 'eddy-nm', name = 'Eddy County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-eddy-nm';
UPDATE school_districts SET county_id = 'de-baca-nm', name = 'De Baca County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-de-baca-nm';
UPDATE school_districts SET county_id = 'curry-nm', name = 'Curry County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-curry-nm';
UPDATE school_districts SET county_id = 'colfax-nm', name = 'Colfax County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-colfax-nm';
UPDATE school_districts SET county_id = 'cibola-nm', name = 'Cibola County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-cibola-nm';
UPDATE school_districts SET county_id = 'chaves-nm', name = 'Chaves County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-chaves-nm';
UPDATE school_districts SET county_id = 'catron-nm', name = 'Catron County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-mexico.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-mexico.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-catron-nm';

COMMIT;
