-- Rollback Script for State: Georgia | Phase: dd_idd
-- Generated At: 2026-06-13T21:28:31.339Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-worth' AND county_id = 'worth-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-worth';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-wilkinson' AND county_id = 'wilkinson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-wilkinson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-wilkes' AND county_id = 'wilkes-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-wilkes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-wilcox' AND county_id = 'wilcox-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-wilcox';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-whitfield' AND county_id = 'whitfield-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-whitfield';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-white' AND county_id = 'white-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-white';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-wheeler' AND county_id = 'wheeler-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-wheeler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-webster' AND county_id = 'webster-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-webster';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-wayne' AND county_id = 'wayne-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-washington' AND county_id = 'washington-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-warren' AND county_id = 'warren-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-ware' AND county_id = 'ware-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-ware';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-walton' AND county_id = 'walton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-walton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-walker' AND county_id = 'walker-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-walker';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-upson' AND county_id = 'upson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-upson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-union' AND county_id = 'union-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-union';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-twiggs' AND county_id = 'twiggs-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-twiggs';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-turner' AND county_id = 'turner-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-turner';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-troup' AND county_id = 'troup-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-troup';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-treutlen' AND county_id = 'treutlen-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-treutlen';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-towns' AND county_id = 'towns-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-towns';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-toombs' AND county_id = 'toombs-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-toombs';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-tift' AND county_id = 'tift-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-tift';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-thomas' AND county_id = 'thomas-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-thomas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-terrell' AND county_id = 'terrell-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-terrell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-telfair' AND county_id = 'telfair-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-telfair';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-taylor' AND county_id = 'taylor-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-taylor';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-tattnall' AND county_id = 'tattnall-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-tattnall';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-taliaferro' AND county_id = 'taliaferro-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-taliaferro';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-talbot' AND county_id = 'talbot-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-talbot';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-sumter' AND county_id = 'sumter-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-sumter';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-stewart' AND county_id = 'stewart-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-stewart';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-stephens' AND county_id = 'stephens-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-stephens';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-spalding' AND county_id = 'spalding-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-spalding';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-seminole' AND county_id = 'seminole-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-seminole';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-screven' AND county_id = 'screven-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-screven';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-schley' AND county_id = 'schley-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-schley';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-rockdale' AND county_id = 'rockdale-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-rockdale';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-richmond' AND county_id = 'richmond-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-richmond';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-randolph' AND county_id = 'randolph-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-randolph';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-rabun' AND county_id = 'rabun-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-rabun';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-quitman' AND county_id = 'quitman-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-quitman';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-putnam' AND county_id = 'putnam-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-putnam';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-pulaski' AND county_id = 'pulaski-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-pulaski';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-polk' AND county_id = 'polk-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-polk';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-pike' AND county_id = 'pike-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-pike';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-pierce' AND county_id = 'pierce-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-pierce';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-pickens' AND county_id = 'pickens-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-pickens';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-peach' AND county_id = 'peach-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-peach';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-paulding' AND county_id = 'paulding-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-paulding';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-oglethorpe' AND county_id = 'oglethorpe-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-oglethorpe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-oconee' AND county_id = 'oconee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-oconee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-newton' AND county_id = 'newton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-newton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-muscogee' AND county_id = 'muscogee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-muscogee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-murray' AND county_id = 'murray-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-murray';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-morgan' AND county_id = 'morgan-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-morgan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-montgomery' AND county_id = 'montgomery-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-monroe' AND county_id = 'monroe-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-monroe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-mitchell' AND county_id = 'mitchell-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-mitchell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-miller' AND county_id = 'miller-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-miller';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-meriwether' AND county_id = 'meriwether-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-meriwether';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-mcintosh' AND county_id = 'mcintosh-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-mcintosh';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-mcduffie' AND county_id = 'mcduffie-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-mcduffie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-marion' AND county_id = 'marion-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-marion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-madison' AND county_id = 'madison-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-madison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-macon' AND county_id = 'macon-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-macon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-lumpkin' AND county_id = 'lumpkin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-lumpkin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-lowndes' AND county_id = 'lowndes-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-lowndes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-long' AND county_id = 'long-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-long';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-lincoln' AND county_id = 'lincoln-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-lincoln';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-liberty' AND county_id = 'liberty-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-liberty';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-lee' AND county_id = 'lee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-lee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-laurens' AND county_id = 'laurens-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-laurens';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-lanier' AND county_id = 'lanier-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-lanier';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-lamar' AND county_id = 'lamar-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-lamar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-jones' AND county_id = 'jones-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-jones';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-johnson' AND county_id = 'johnson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-johnson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-jenkins' AND county_id = 'jenkins-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-jenkins';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-jefferson' AND county_id = 'jefferson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-jefferson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-jeff-davis' AND county_id = 'jeff-davis-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-jeff-davis';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-jasper' AND county_id = 'jasper-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-jasper';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-jackson' AND county_id = 'jackson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-jackson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-irwin' AND county_id = 'irwin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-irwin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-houston' AND county_id = 'houston-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-houston';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-henry' AND county_id = 'henry-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-henry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-heard' AND county_id = 'heard-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-heard';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-hart' AND county_id = 'hart-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-hart';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-harris' AND county_id = 'harris-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-harris';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-haralson' AND county_id = 'haralson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-haralson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-hancock' AND county_id = 'hancock-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-hancock';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-hall' AND county_id = 'hall-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-hall';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-habersham' AND county_id = 'habersham-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-habersham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-gwinnett' AND county_id = 'gwinnett-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-gwinnett';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-greene' AND county_id = 'greene-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-grady' AND county_id = 'grady-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-grady';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-gordon' AND county_id = 'gordon-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-gordon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-glynn' AND county_id = 'glynn-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-glynn';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-glascock' AND county_id = 'glascock-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-glascock';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-gilmer' AND county_id = 'gilmer-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-gilmer';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-fulton' AND county_id = 'fulton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-fulton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-franklin' AND county_id = 'franklin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-franklin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-forsyth' AND county_id = 'forsyth-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-forsyth';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-floyd' AND county_id = 'floyd-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-floyd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-fayette' AND county_id = 'fayette-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-fayette';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-fannin' AND county_id = 'fannin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-fannin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-evans' AND county_id = 'evans-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-evans';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-emanuel' AND county_id = 'emanuel-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-emanuel';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-elbert' AND county_id = 'elbert-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-elbert';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-effingham' AND county_id = 'effingham-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-effingham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-echols' AND county_id = 'echols-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-echols';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-early' AND county_id = 'early-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-early';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-douglas' AND county_id = 'douglas-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-douglas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-dougherty' AND county_id = 'dougherty-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-dougherty';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-dooly' AND county_id = 'dooly-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-dooly';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-dodge' AND county_id = 'dodge-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-dodge';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-dekalb' AND county_id = 'dekalb-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-dekalb';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-decatur' AND county_id = 'decatur-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-decatur';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-dawson' AND county_id = 'dawson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-dawson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-dade' AND county_id = 'dade-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-dade';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-crisp' AND county_id = 'crisp-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-crisp';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-crawford' AND county_id = 'crawford-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-crawford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-coweta' AND county_id = 'coweta-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-coweta';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-cook' AND county_id = 'cook-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-cook';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-columbia' AND county_id = 'columbia-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-columbia';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-colquitt' AND county_id = 'colquitt-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-colquitt';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-coffee' AND county_id = 'coffee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-coffee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-cobb' AND county_id = 'cobb-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-cobb';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-clinch' AND county_id = 'clinch-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-clinch';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-clayton' AND county_id = 'clayton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-clayton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-clay' AND county_id = 'clay-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-clay';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-clarke' AND county_id = 'clarke-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-clarke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-cherokee' AND county_id = 'cherokee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-cherokee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-chattooga' AND county_id = 'chattooga-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-chattooga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-chattahoochee' AND county_id = 'chattahoochee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-chattahoochee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-chatham' AND county_id = 'chatham-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-chatham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-charlton' AND county_id = 'charlton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-charlton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-catoosa' AND county_id = 'catoosa-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-catoosa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-carroll' AND county_id = 'carroll-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-carroll';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-candler' AND county_id = 'candler-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-candler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-camden' AND county_id = 'camden-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-camden';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-calhoun' AND county_id = 'calhoun-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-calhoun';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-butts' AND county_id = 'butts-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-butts';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-burke' AND county_id = 'burke-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-burke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-bulloch' AND county_id = 'bulloch-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-bulloch';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-bryan' AND county_id = 'bryan-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-bryan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-brooks' AND county_id = 'brooks-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-brooks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-brantley' AND county_id = 'brantley-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-brantley';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-bleckley' AND county_id = 'bleckley-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-bleckley';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-bibb' AND county_id = 'bibb-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-bibb';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-berrien' AND county_id = 'berrien-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-berrien';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-ben-hill' AND county_id = 'ben-hill-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-ben-hill';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-bartow' AND county_id = 'bartow-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-bartow';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-barrow' AND county_id = 'barrow-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-barrow';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-banks' AND county_id = 'banks-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-banks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-baldwin' AND county_id = 'baldwin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-baldwin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-baker' AND county_id = 'baker-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-baker';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-bacon' AND county_id = 'bacon-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-bacon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-atkinson' AND county_id = 'atkinson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-atkinson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-dd-appling' AND county_id = 'appling-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-dd-appling';

COMMIT;
