-- Rollback Script for State: Georgia | Phase: early_intervention
-- Generated At: 2026-06-13T21:27:56.697Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-worth' AND county_id = 'worth-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-worth';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-wilkinson' AND county_id = 'wilkinson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-wilkinson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-wilkes' AND county_id = 'wilkes-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-wilkes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-wilcox' AND county_id = 'wilcox-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-wilcox';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-whitfield' AND county_id = 'whitfield-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-whitfield';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-white' AND county_id = 'white-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-white';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-wheeler' AND county_id = 'wheeler-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-wheeler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-webster' AND county_id = 'webster-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-webster';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-wayne' AND county_id = 'wayne-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-washington' AND county_id = 'washington-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-warren' AND county_id = 'warren-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-ware' AND county_id = 'ware-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-ware';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-walton' AND county_id = 'walton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-walton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-walker' AND county_id = 'walker-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-walker';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-upson' AND county_id = 'upson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-upson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-union' AND county_id = 'union-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-union';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-twiggs' AND county_id = 'twiggs-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-twiggs';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-turner' AND county_id = 'turner-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-turner';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-troup' AND county_id = 'troup-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-troup';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-treutlen' AND county_id = 'treutlen-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-treutlen';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-towns' AND county_id = 'towns-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-towns';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-toombs' AND county_id = 'toombs-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-toombs';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-tift' AND county_id = 'tift-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-tift';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-thomas' AND county_id = 'thomas-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-thomas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-terrell' AND county_id = 'terrell-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-terrell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-telfair' AND county_id = 'telfair-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-telfair';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-taylor' AND county_id = 'taylor-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-taylor';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-tattnall' AND county_id = 'tattnall-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-tattnall';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-taliaferro' AND county_id = 'taliaferro-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-taliaferro';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-talbot' AND county_id = 'talbot-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-talbot';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-sumter' AND county_id = 'sumter-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-sumter';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-stewart' AND county_id = 'stewart-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-stewart';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-stephens' AND county_id = 'stephens-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-stephens';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-spalding' AND county_id = 'spalding-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-spalding';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-seminole' AND county_id = 'seminole-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-seminole';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-screven' AND county_id = 'screven-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-screven';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-schley' AND county_id = 'schley-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-schley';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-rockdale' AND county_id = 'rockdale-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-rockdale';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-richmond' AND county_id = 'richmond-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-richmond';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-randolph' AND county_id = 'randolph-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-randolph';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-rabun' AND county_id = 'rabun-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-rabun';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-quitman' AND county_id = 'quitman-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-quitman';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-putnam' AND county_id = 'putnam-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-putnam';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-pulaski' AND county_id = 'pulaski-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-pulaski';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-polk' AND county_id = 'polk-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-polk';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-pike' AND county_id = 'pike-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-pike';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-pierce' AND county_id = 'pierce-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-pierce';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-pickens' AND county_id = 'pickens-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-pickens';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-peach' AND county_id = 'peach-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-peach';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-paulding' AND county_id = 'paulding-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-paulding';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-oglethorpe' AND county_id = 'oglethorpe-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-oglethorpe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-oconee' AND county_id = 'oconee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-oconee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-newton' AND county_id = 'newton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-newton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-muscogee' AND county_id = 'muscogee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-muscogee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-murray' AND county_id = 'murray-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-murray';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-morgan' AND county_id = 'morgan-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-morgan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-montgomery' AND county_id = 'montgomery-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-monroe' AND county_id = 'monroe-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-monroe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-mitchell' AND county_id = 'mitchell-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-mitchell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-miller' AND county_id = 'miller-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-miller';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-meriwether' AND county_id = 'meriwether-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-meriwether';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-mcintosh' AND county_id = 'mcintosh-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-mcintosh';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-mcduffie' AND county_id = 'mcduffie-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-mcduffie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-marion' AND county_id = 'marion-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-marion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-madison' AND county_id = 'madison-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-madison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-macon' AND county_id = 'macon-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-macon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-lumpkin' AND county_id = 'lumpkin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-lumpkin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-lowndes' AND county_id = 'lowndes-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-lowndes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-long' AND county_id = 'long-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-long';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-lincoln' AND county_id = 'lincoln-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-lincoln';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-liberty' AND county_id = 'liberty-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-liberty';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-lee' AND county_id = 'lee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-lee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-laurens' AND county_id = 'laurens-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-laurens';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-lanier' AND county_id = 'lanier-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-lanier';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-lamar' AND county_id = 'lamar-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-lamar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-jones' AND county_id = 'jones-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-jones';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-johnson' AND county_id = 'johnson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-johnson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-jenkins' AND county_id = 'jenkins-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-jenkins';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-jefferson' AND county_id = 'jefferson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-jefferson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-jeff-davis' AND county_id = 'jeff-davis-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-jeff-davis';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-jasper' AND county_id = 'jasper-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-jasper';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-jackson' AND county_id = 'jackson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-jackson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-irwin' AND county_id = 'irwin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-irwin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-houston' AND county_id = 'houston-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-houston';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-henry' AND county_id = 'henry-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-henry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-heard' AND county_id = 'heard-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-heard';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-hart' AND county_id = 'hart-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-hart';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-harris' AND county_id = 'harris-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-harris';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-haralson' AND county_id = 'haralson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-haralson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-hancock' AND county_id = 'hancock-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-hancock';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-hall' AND county_id = 'hall-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-hall';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-habersham' AND county_id = 'habersham-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-habersham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-gwinnett' AND county_id = 'gwinnett-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-gwinnett';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-greene' AND county_id = 'greene-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-grady' AND county_id = 'grady-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-grady';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-gordon' AND county_id = 'gordon-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-gordon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-glynn' AND county_id = 'glynn-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-glynn';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-glascock' AND county_id = 'glascock-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-glascock';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-gilmer' AND county_id = 'gilmer-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-gilmer';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-fulton' AND county_id = 'fulton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-fulton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-franklin' AND county_id = 'franklin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-franklin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-forsyth' AND county_id = 'forsyth-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-forsyth';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-floyd' AND county_id = 'floyd-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-floyd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-fayette' AND county_id = 'fayette-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-fayette';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-fannin' AND county_id = 'fannin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-fannin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-evans' AND county_id = 'evans-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-evans';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-emanuel' AND county_id = 'emanuel-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-emanuel';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-elbert' AND county_id = 'elbert-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-elbert';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-effingham' AND county_id = 'effingham-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-effingham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-echols' AND county_id = 'echols-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-echols';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-early' AND county_id = 'early-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-early';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-douglas' AND county_id = 'douglas-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-douglas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-dougherty' AND county_id = 'dougherty-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-dougherty';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-dooly' AND county_id = 'dooly-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-dooly';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-dodge' AND county_id = 'dodge-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-dodge';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-dekalb' AND county_id = 'dekalb-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-dekalb';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-decatur' AND county_id = 'decatur-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-decatur';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-dawson' AND county_id = 'dawson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-dawson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-dade' AND county_id = 'dade-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-dade';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-crisp' AND county_id = 'crisp-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-crisp';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-crawford' AND county_id = 'crawford-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-crawford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-coweta' AND county_id = 'coweta-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-coweta';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-cook' AND county_id = 'cook-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-cook';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-columbia' AND county_id = 'columbia-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-columbia';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-colquitt' AND county_id = 'colquitt-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-colquitt';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-coffee' AND county_id = 'coffee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-coffee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-cobb' AND county_id = 'cobb-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-cobb';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-clinch' AND county_id = 'clinch-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-clinch';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-clayton' AND county_id = 'clayton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-clayton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-clay' AND county_id = 'clay-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-clay';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-clarke' AND county_id = 'clarke-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-clarke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-cherokee' AND county_id = 'cherokee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-cherokee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-chattooga' AND county_id = 'chattooga-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-chattooga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-chattahoochee' AND county_id = 'chattahoochee-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-chattahoochee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-chatham' AND county_id = 'chatham-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-chatham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-charlton' AND county_id = 'charlton-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-charlton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-catoosa' AND county_id = 'catoosa-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-catoosa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-carroll' AND county_id = 'carroll-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-carroll';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-candler' AND county_id = 'candler-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-candler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-camden' AND county_id = 'camden-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-camden';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-calhoun' AND county_id = 'calhoun-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-calhoun';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-butts' AND county_id = 'butts-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-butts';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-burke' AND county_id = 'burke-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-burke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-bulloch' AND county_id = 'bulloch-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-bulloch';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-bryan' AND county_id = 'bryan-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-bryan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-brooks' AND county_id = 'brooks-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-brooks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-brantley' AND county_id = 'brantley-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-brantley';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-bleckley' AND county_id = 'bleckley-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-bleckley';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-bibb' AND county_id = 'bibb-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-bibb';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-berrien' AND county_id = 'berrien-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-berrien';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-ben-hill' AND county_id = 'ben-hill-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-ben-hill';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-bartow' AND county_id = 'bartow-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-bartow';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-barrow' AND county_id = 'barrow-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-barrow';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-banks' AND county_id = 'banks-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-banks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-baldwin' AND county_id = 'baldwin-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-baldwin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-baker' AND county_id = 'baker-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-baker';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-bacon' AND county_id = 'bacon-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-bacon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-atkinson' AND county_id = 'atkinson-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-atkinson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ga-ei-appling' AND county_id = 'appling-ga';
DELETE FROM state_resource_agencies WHERE id = 'ga-ei-appling';

COMMIT;
