-- Rollback Script for State: Wyoming | Phase: benefits_hhs
-- Generated At: 2026-06-15T01:50:59.997Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'weston-wy', program_id = 'wy-medicaid', office_name = 'Weston County Department of Family Services', address = '22922 U.S. Hwy 85, Suite 200, Newcastle, WY 82701', phone = '(307) 746-4657', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-weston-wy-medicaid';
UPDATE county_offices SET county_id = 'washakie-wy', program_id = 'wy-medicaid', office_name = 'Washakie County Department of Family Services', address = '1700 Robertson, Worland, WY 82401', phone = '(307) 347-6181', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-washakie-wy-medicaid';
UPDATE county_offices SET county_id = 'uinta-wy', program_id = 'wy-medicaid', office_name = 'Uinta County Department of Family Services', address = '350 City View Dr, Ste. 200, Evanston, WY 82930', phone = '(307) 789-7194', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-uinta-wy-medicaid';
UPDATE county_offices SET county_id = 'teton-wy', program_id = 'wy-medicaid', office_name = 'Teton County Department of Family Services', address = '120 West Pearl Ave, Ste. E, Jackson, WY 83001', phone = '(307) 733-7757', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-teton-wy-medicaid';
UPDATE county_offices SET county_id = 'sweetwater-wy', program_id = 'wy-medicaid', office_name = 'Sweetwater County Department of Family Services', address = '140 Commerce Drive, Ste. F, Green River, WY 82935', phone = '(307) 352-2500', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-sweetwater-wy-medicaid';
UPDATE county_offices SET county_id = 'sublette-wy', program_id = 'wy-medicaid', office_name = 'Sublette County Department of Family Services', address = '217 N. Sublette Avenue, Pinedale, WY 82941', phone = '(307) 367-4124', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-sublette-wy-medicaid';
UPDATE county_offices SET county_id = 'sheridan-wy', program_id = 'wy-medicaid', office_name = 'Sheridan County Department of Family Services', address = '224 South Main Street, Sheridan, WY 82801', phone = '(307) 672-2404', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-sheridan-wy-medicaid';
UPDATE county_offices SET county_id = 'platte-wy', program_id = 'wy-medicaid', office_name = 'Platte County Department of Family Services', address = '1556 Progress Court, Wheatland, WY 82201', phone = '(307) 322-3790', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-platte-wy-medicaid';
UPDATE county_offices SET county_id = 'park-wy', program_id = 'wy-medicaid', office_name = 'Park County Department of Family Services', address = '1501 Stampede Ave, Unit 9009, Cody, WY 82414', phone = '(307) 587-6246', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-park-wy-medicaid';
UPDATE county_offices SET county_id = 'niobrara-wy', program_id = 'wy-medicaid', office_name = 'Niobrara County Department of Family Services', address = '905 S. Main, Lusk, WY 82225', phone = '(307) 334-2153', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-niobrara-wy-medicaid';
UPDATE county_offices SET county_id = 'natrona-wy', program_id = 'wy-medicaid', office_name = 'Natrona County Department of Family Services', address = '444 W. Collins Drive, Suite 2100, Casper, WY 82601', phone = '(307) 473-3900', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-natrona-wy-medicaid';
UPDATE county_offices SET county_id = 'lincoln-wy', program_id = 'wy-medicaid', office_name = 'Lincoln County Department of Family Services', address = '1100 Pine Ave., Kemmerer, WY 83101', phone = '(307) 877-6670', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-lincoln-wy-medicaid';
UPDATE county_offices SET county_id = 'laramie-wy', program_id = 'wy-medicaid', office_name = 'Laramie County Department of Family Services', address = '1022 Airport Parkway, Cheyenne, WY 82001', phone = '(307) 777-7921', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-laramie-wy-medicaid';
UPDATE county_offices SET county_id = 'johnson-wy', program_id = 'wy-medicaid', office_name = 'Johnson County Department of Family Services', address = '381 N. Main, Buffalo, WY 82834', phone = '(307) 684-5513', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-johnson-wy-medicaid';
UPDATE county_offices SET county_id = 'hot-springs-wy', program_id = 'wy-medicaid', office_name = 'Hot Springs County Department of Family Services', address = '403 Big Horn, Thermopolis, WY 82443', phone = '(307) 864-2158', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-hot-springs-wy-medicaid';
UPDATE county_offices SET county_id = 'goshen-wy', program_id = 'wy-medicaid', office_name = 'Goshen County Department of Family Services', address = '1618 E. ''M'' St., Torrington, WY 82240', phone = '(307) 532-2191', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-goshen-wy-medicaid';
UPDATE county_offices SET county_id = 'fremont-wy', program_id = 'wy-medicaid', office_name = 'Fremont County Department of Family Services', address = '406 Center Street, Lander, WY 82520', phone = '(307) 332-4038', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-fremont-wy-medicaid';
UPDATE county_offices SET county_id = 'crook-wy', program_id = 'wy-medicaid', office_name = 'Crook County Department of Family Services', address = '102 North 5th Street, Sundance, WY 82729', phone = '(307) 283-2014', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-crook-wy-medicaid';
UPDATE county_offices SET county_id = 'converse-wy', program_id = 'wy-medicaid', office_name = 'Converse County Department of Family Services', address = '219 North Russell Avenue, Douglas, WY 82633', phone = '(307) 358-3138', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-converse-wy-medicaid';
UPDATE county_offices SET county_id = 'carbon-wy', program_id = 'wy-medicaid', office_name = 'Carbon County Department of Family Services', address = '215 W. Buffalo, Suite 359, Rawlins, WY 82301', phone = '(307) 328-0612', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-carbon-wy-medicaid';
UPDATE county_offices SET county_id = 'campbell-wy', program_id = 'wy-medicaid', office_name = 'Campbell County Department of Family Services', address = '551 Running W Drive, Suite 200, Gillette, WY 82718', phone = '(307) 682-7277', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-campbell-wy-medicaid';
UPDATE county_offices SET county_id = 'big-horn-wy', program_id = 'wy-medicaid', office_name = 'Big Horn County Department of Family Services', address = '616 2nd Ave. N., Greybull, WY 82426', phone = '(307) 765-9453', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-big-horn-wy-medicaid';
UPDATE county_offices SET county_id = 'albany-wy', program_id = 'wy-medicaid', office_name = 'Albany County Department of Family Services', address = '3817 Beech St., Suite 200, Laramie, WY 82070', phone = '(307) 745-7324', email = NULL, website = 'https://dfs.wyo.gov/about/contact-us-locations/', source_url = 'https://dfs.wyo.gov/about/contact-us-locations/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-albany-wy-medicaid';

COMMIT;
