-- Rollback Script for State: Wyoming | Phase: benefits_hhs
-- Generated At: 2026-06-14T23:24:19.101Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'weston-wy', program_id = 'wy-medicaid', office_name = 'Weston County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-weston-wy-medicaid';
UPDATE county_offices SET county_id = 'washakie-wy', program_id = 'wy-medicaid', office_name = 'Washakie County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-washakie-wy-medicaid';
UPDATE county_offices SET county_id = 'uinta-wy', program_id = 'wy-medicaid', office_name = 'Uinta County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-uinta-wy-medicaid';
UPDATE county_offices SET county_id = 'teton-wy', program_id = 'wy-medicaid', office_name = 'Teton County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-teton-wy-medicaid';
UPDATE county_offices SET county_id = 'sweetwater-wy', program_id = 'wy-medicaid', office_name = 'Sweetwater County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-sweetwater-wy-medicaid';
UPDATE county_offices SET county_id = 'sublette-wy', program_id = 'wy-medicaid', office_name = 'Sublette County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-sublette-wy-medicaid';
UPDATE county_offices SET county_id = 'sheridan-wy', program_id = 'wy-medicaid', office_name = 'Sheridan County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-sheridan-wy-medicaid';
UPDATE county_offices SET county_id = 'platte-wy', program_id = 'wy-medicaid', office_name = 'Platte County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-platte-wy-medicaid';
UPDATE county_offices SET county_id = 'park-wy', program_id = 'wy-medicaid', office_name = 'Park County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-park-wy-medicaid';
UPDATE county_offices SET county_id = 'niobrara-wy', program_id = 'wy-medicaid', office_name = 'Niobrara County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-niobrara-wy-medicaid';
UPDATE county_offices SET county_id = 'natrona-wy', program_id = 'wy-medicaid', office_name = 'Natrona County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-natrona-wy-medicaid';
UPDATE county_offices SET county_id = 'lincoln-wy', program_id = 'wy-medicaid', office_name = 'Lincoln County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lincoln-wy-medicaid';
UPDATE county_offices SET county_id = 'laramie-wy', program_id = 'wy-medicaid', office_name = 'Laramie County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-laramie-wy-medicaid';
UPDATE county_offices SET county_id = 'johnson-wy', program_id = 'wy-medicaid', office_name = 'Johnson County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-johnson-wy-medicaid';
UPDATE county_offices SET county_id = 'hot-springs-wy', program_id = 'wy-medicaid', office_name = 'Hot Springs County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-hot-springs-wy-medicaid';
UPDATE county_offices SET county_id = 'goshen-wy', program_id = 'wy-medicaid', office_name = 'Goshen County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-goshen-wy-medicaid';
UPDATE county_offices SET county_id = 'fremont-wy', program_id = 'wy-medicaid', office_name = 'Fremont County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-fremont-wy-medicaid';
UPDATE county_offices SET county_id = 'crook-wy', program_id = 'wy-medicaid', office_name = 'Crook County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-crook-wy-medicaid';
UPDATE county_offices SET county_id = 'converse-wy', program_id = 'wy-medicaid', office_name = 'Converse County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-converse-wy-medicaid';
UPDATE county_offices SET county_id = 'carbon-wy', program_id = 'wy-medicaid', office_name = 'Carbon County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-carbon-wy-medicaid';
UPDATE county_offices SET county_id = 'campbell-wy', program_id = 'wy-medicaid', office_name = 'Campbell County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-campbell-wy-medicaid';
UPDATE county_offices SET county_id = 'big-horn-wy', program_id = 'wy-medicaid', office_name = 'Big Horn County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-big-horn-wy-medicaid';
UPDATE county_offices SET county_id = 'albany-wy', program_id = 'wy-medicaid', office_name = 'Albany County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.wyoming.gov/locations', source_url = 'https://dhhs.wyoming.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-albany-wy-medicaid';

COMMIT;
