-- Rollback Script for State: Wyoming | Phase: district_replacements
-- Generated At: 2026-06-14T23:24:36.084Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'weston-wy', name = 'Weston County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-weston-wy';
UPDATE school_districts SET county_id = 'washakie-wy', name = 'Washakie County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-washakie-wy';
UPDATE school_districts SET county_id = 'uinta-wy', name = 'Uinta County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-uinta-wy';
UPDATE school_districts SET county_id = 'teton-wy', name = 'Teton County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-teton-wy';
UPDATE school_districts SET county_id = 'sweetwater-wy', name = 'Sweetwater County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-sweetwater-wy';
UPDATE school_districts SET county_id = 'sublette-wy', name = 'Sublette County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-sublette-wy';
UPDATE school_districts SET county_id = 'sheridan-wy', name = 'Sheridan County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-sheridan-wy';
UPDATE school_districts SET county_id = 'platte-wy', name = 'Platte County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-platte-wy';
UPDATE school_districts SET county_id = 'park-wy', name = 'Park County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-park-wy';
UPDATE school_districts SET county_id = 'niobrara-wy', name = 'Niobrara County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-niobrara-wy';
UPDATE school_districts SET county_id = 'lincoln-wy', name = 'Lincoln County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-lincoln-wy';
UPDATE school_districts SET county_id = 'johnson-wy', name = 'Johnson County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-johnson-wy';
UPDATE school_districts SET county_id = 'hot-springs-wy', name = 'Hot Springs County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-hot-springs-wy';
UPDATE school_districts SET county_id = 'goshen-wy', name = 'Goshen County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-goshen-wy';
UPDATE school_districts SET county_id = 'fremont-wy', name = 'Fremont County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-fremont-wy';
UPDATE school_districts SET county_id = 'crook-wy', name = 'Crook County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-crook-wy';
UPDATE school_districts SET county_id = 'converse-wy', name = 'Converse County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-converse-wy';
UPDATE school_districts SET county_id = 'carbon-wy', name = 'Carbon County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-carbon-wy';
UPDATE school_districts SET county_id = 'campbell-wy', name = 'Campbell County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-campbell-wy';
UPDATE school_districts SET county_id = 'big-horn-wy', name = 'Big Horn County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-big-horn-wy';
UPDATE school_districts SET county_id = 'albany-wy', name = 'Albany County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.wyoming.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.wyoming.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-albany-wy';

COMMIT;
