-- Rollback Script for State: Wyoming | Phase: trusted_nonprofits
-- Generated At: 2026-06-15T01:51:02.355Z

BEGIN TRANSACTION;

DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-weston-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-weston-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-weston-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-washakie-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-washakie-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-washakie-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-uinta-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-uinta-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-uinta-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-teton-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-teton-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-teton-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-sweetwater-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-sweetwater-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-sweetwater-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-sublette-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-sublette-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-sublette-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-sheridan-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-sheridan-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-sheridan-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-platte-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-platte-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-platte-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-park-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-park-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-park-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-niobrara-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-niobrara-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-niobrara-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-natrona-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-natrona-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-natrona-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-lincoln-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-lincoln-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-lincoln-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-laramie-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-laramie-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-laramie-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-johnson-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-johnson-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-johnson-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-hot-springs-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-hot-springs-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-hot-springs-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-goshen-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-goshen-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-goshen-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-fremont-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-fremont-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-fremont-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-crook-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-crook-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-crook-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-converse-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-converse-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-converse-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-carbon-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-carbon-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-carbon-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-campbell-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-campbell-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-campbell-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-big-horn-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-big-horn-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-big-horn-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-parent-albany-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-arc-albany-wy';
DELETE FROM nonprofit_organizations WHERE id = 'wy-np-rights-albany-wy';

COMMIT;
