-- Rollback Script for State: South Dakota | Phase: dd_idd
-- Generated At: 2026-06-14T15:49:03.772Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'ziebach-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'yankton-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'walworth-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'union-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'turner-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'tripp-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'todd-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'sully-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'stanley-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'spink-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'sanborn-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'roberts-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'potter-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'perkins-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'pennington-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'oglala-lakota-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'moody-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'minnehaha-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'miner-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'mellette-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'meade-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'mcpherson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'mccook-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'marshall-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'lyman-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'lincoln-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'lawrence-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'lake-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'kingsbury-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'jones-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'jerauld-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'jackson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'hyde-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'hutchinson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'hughes-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'harding-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'hanson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'hand-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'hamlin-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'haakon-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'gregory-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'grant-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'faulk-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'fall-river-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'edmunds-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'douglas-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'dewey-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'deuel-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'day-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'davison-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'custer-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'corson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'codington-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'clay-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'clark-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'charles-mix-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'campbell-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'butte-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'buffalo-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'brule-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'brown-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'brookings-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'bon-homme-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'bennett-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'beadle-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-dd-agency' AND county_id = 'aurora-sd';
UPDATE state_resource_agencies SET state_id = 'south-dakota', agency_type = 'dd_office', name = 'South Dakota Division of Developmental Disabilities', counties_served = 'aurora-sd,beadle-sd,bennett-sd,bon-homme-sd,brookings-sd,brown-sd,brule-sd,buffalo-sd,butte-sd,campbell-sd,charles-mix-sd,clark-sd,clay-sd,codington-sd,corson-sd,custer-sd,davison-sd,day-sd,deuel-sd,dewey-sd,douglas-sd,edmunds-sd,fall-river-sd,faulk-sd,grant-sd,gregory-sd,haakon-sd,hamlin-sd,hand-sd,hanson-sd,harding-sd,hughes-sd,hutchinson-sd,hyde-sd,jackson-sd,jerauld-sd,jones-sd,kingsbury-sd,lake-sd,lawrence-sd,lincoln-sd,lyman-sd,marshall-sd,mccook-sd,mcpherson-sd,meade-sd,mellette-sd,miner-sd,minnehaha-sd,moody-sd,oglala-lakota-sd,pennington-sd,perkins-sd,potter-sd,roberts-sd,sanborn-sd,spink-sd,stanley-sd,sully-sd,todd-sd,tripp-sd,turner-sd,union-sd,walworth-sd,yankton-sd,ziebach-sd', catchment_boundaries = 'Statewide coverage for all counties in South Dakota.', website = 'https://dhs.sd.gov/dd', intake_phone = '(800) 555-0100', early_intervention_contact = '(800) 555-0100', agency_intake_contact = '(800) 555-0100', eligibility_info_page = 'https://dhs.sd.gov/dd/eligibility', services_page = 'https://dhs.sd.gov/dd', appeals_info = 'Waiver decisions can be appealed within 30 days of notice.', frc_relationship = NULL, office_locations = 'South Dakota State Capitol Office', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://dhs.sd.gov/dd', source_url = 'https://dhs.sd.gov/dd', source_type = 'official', data_origin = 'curated_seed', verification_status = 'source_listed', last_scraped_at = '2026-06-13T02:29:27.571Z', confidence_score = 5, evidence_level = NULL WHERE id = 'sd-dd-agency';

COMMIT;
