-- Rollback Script for State: South Dakota | Phase: early_intervention
-- Generated At: 2026-06-15T00:27:20.736Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'ziebach-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'yankton-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'walworth-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'union-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'turner-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'tripp-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'todd-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'sully-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'stanley-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'spink-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'sanborn-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'roberts-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'potter-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'perkins-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'pennington-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'oglala-lakota-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'moody-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'minnehaha-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'miner-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'mellette-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'meade-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'mcpherson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'mccook-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'marshall-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'lyman-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'lincoln-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'lawrence-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'lake-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'kingsbury-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'jones-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'jerauld-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'jackson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'hyde-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'hutchinson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'hughes-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'harding-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'hanson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'hand-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'hamlin-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'haakon-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'gregory-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'grant-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'faulk-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'fall-river-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'edmunds-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'douglas-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'dewey-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'deuel-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'day-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'davison-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'custer-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'corson-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'codington-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'clay-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'clark-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'charles-mix-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'campbell-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'butte-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'buffalo-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'brule-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'brown-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'brookings-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'bon-homme-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'bennett-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'beadle-sd';
DELETE FROM regional_center_counties WHERE regional_center_id = 'sd-ei-agency' AND county_id = 'aurora-sd';
UPDATE state_resource_agencies SET state_id = 'south-dakota', agency_type = 'early_intervention', name = 'South Dakota Early Intervention State Office', counties_served = 'statewide', catchment_boundaries = 'statewide', website = 'https://dhhs.south-dakota.gov/earlystart', intake_phone = '', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://dhhs.south-dakota.gov/earlystart', source_url = 'https://dhhs.south-dakota.gov/earlystart', source_type = 'official_website', data_origin = 'scraped', verification_status = 'manual_review_required', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-ei-agency';

COMMIT;
