-- Rollback Script for State: Maryland | Phase: benefits_hhs
-- Generated At: 2026-06-15T19:14:18.723Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'worcester-md', program_id = 'md-medicaid', office_name = 'Worcester County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-worcester-md-medicaid';
UPDATE county_offices SET county_id = 'wicomico-md', program_id = 'md-medicaid', office_name = 'Wicomico County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-wicomico-md-medicaid';
UPDATE county_offices SET county_id = 'washington-md', program_id = 'md-medicaid', office_name = 'Washington County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-washington-md-medicaid';
UPDATE county_offices SET county_id = 'talbot-md', program_id = 'md-medicaid', office_name = 'Talbot County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-talbot-md-medicaid';
UPDATE county_offices SET county_id = 'st-mary-s-md', program_id = 'md-medicaid', office_name = 'St. Mary''s County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-st-mary-s-md-medicaid';
UPDATE county_offices SET county_id = 'somerset-md', program_id = 'md-medicaid', office_name = 'Somerset County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-somerset-md-medicaid';
UPDATE county_offices SET county_id = 'queen-anne-s-md', program_id = 'md-medicaid', office_name = 'Queen Anne''s County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-queen-anne-s-md-medicaid';
UPDATE county_offices SET county_id = 'prince-george-s-md', program_id = 'md-medicaid', office_name = 'Prince George''s County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-prince-george-s-md-medicaid';
UPDATE county_offices SET county_id = 'montgomery-md', program_id = 'md-medicaid', office_name = 'Montgomery County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-montgomery-md-medicaid';
UPDATE county_offices SET county_id = 'kent-md', program_id = 'md-medicaid', office_name = 'Kent County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-kent-md-medicaid';
UPDATE county_offices SET county_id = 'howard-md', program_id = 'md-medicaid', office_name = 'Howard County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-howard-md-medicaid';
UPDATE county_offices SET county_id = 'harford-md', program_id = 'md-medicaid', office_name = 'Harford County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-harford-md-medicaid';
UPDATE county_offices SET county_id = 'garrett-md', program_id = 'md-medicaid', office_name = 'Garrett County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-garrett-md-medicaid';
UPDATE county_offices SET county_id = 'frederick-md', program_id = 'md-medicaid', office_name = 'Frederick County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-frederick-md-medicaid';
UPDATE county_offices SET county_id = 'dorchester-md', program_id = 'md-medicaid', office_name = 'Dorchester County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-dorchester-md-medicaid';
UPDATE county_offices SET county_id = 'charles-md', program_id = 'md-medicaid', office_name = 'Charles County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-charles-md-medicaid';
UPDATE county_offices SET county_id = 'cecil-md', program_id = 'md-medicaid', office_name = 'Cecil County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-cecil-md-medicaid';
UPDATE county_offices SET county_id = 'carroll-md', program_id = 'md-medicaid', office_name = 'Carroll County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-carroll-md-medicaid';
UPDATE county_offices SET county_id = 'caroline-md', program_id = 'md-medicaid', office_name = 'Caroline County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-caroline-md-medicaid';
UPDATE county_offices SET county_id = 'calvert-md', program_id = 'md-medicaid', office_name = 'Calvert County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-calvert-md-medicaid';
UPDATE county_offices SET county_id = 'baltimore-city-md', program_id = 'md-medicaid', office_name = 'Baltimore City County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-baltimore-city-md-medicaid';
UPDATE county_offices SET county_id = 'baltimore-md', program_id = 'md-medicaid', office_name = 'Baltimore County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-baltimore-md-medicaid';
UPDATE county_offices SET county_id = 'anne-arundel-md', program_id = 'md-medicaid', office_name = 'Anne Arundel County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-anne-arundel-md-medicaid';
UPDATE county_offices SET county_id = 'allegany-md', program_id = 'md-medicaid', office_name = 'Allegany County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.maryland.gov/locations', source_url = 'https://dhhs.maryland.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-allegany-md-medicaid';

COMMIT;
