-- Rollback Script for State: Maryland | Phase: district_replacements
-- Generated At: 2026-06-14T23:59:24.198Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'worcester-md', name = 'Worcester County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-worcester-md';
UPDATE school_districts SET county_id = 'wicomico-md', name = 'Wicomico County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-wicomico-md';
UPDATE school_districts SET county_id = 'washington-md', name = 'Washington County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-washington-md';
UPDATE school_districts SET county_id = 'talbot-md', name = 'Talbot County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-talbot-md';
UPDATE school_districts SET county_id = 'st-mary-s-md', name = 'St. Mary''s County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-st-mary-s-md';
UPDATE school_districts SET county_id = 'somerset-md', name = 'Somerset County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-somerset-md';
UPDATE school_districts SET county_id = 'queen-anne-s-md', name = 'Queen Anne''s County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-queen-anne-s-md';
UPDATE school_districts SET county_id = 'kent-md', name = 'Kent County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-kent-md';
UPDATE school_districts SET county_id = 'howard-md', name = 'Howard County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-howard-md';
UPDATE school_districts SET county_id = 'harford-md', name = 'Harford County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-harford-md';
UPDATE school_districts SET county_id = 'garrett-md', name = 'Garrett County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-garrett-md';
UPDATE school_districts SET county_id = 'frederick-md', name = 'Frederick County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-frederick-md';
UPDATE school_districts SET county_id = 'dorchester-md', name = 'Dorchester County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-dorchester-md';
UPDATE school_districts SET county_id = 'charles-md', name = 'Charles County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-charles-md';
UPDATE school_districts SET county_id = 'cecil-md', name = 'Cecil County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-cecil-md';
UPDATE school_districts SET county_id = 'carroll-md', name = 'Carroll County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-carroll-md';
UPDATE school_districts SET county_id = 'caroline-md', name = 'Caroline County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-caroline-md';
UPDATE school_districts SET county_id = 'calvert-md', name = 'Calvert County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-calvert-md';
UPDATE school_districts SET county_id = 'baltimore-city-md', name = 'Baltimore City County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-baltimore-city-md';
UPDATE school_districts SET county_id = 'baltimore-md', name = 'Baltimore County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-baltimore-md';
UPDATE school_districts SET county_id = 'anne-arundel-md', name = 'Anne Arundel County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-anne-arundel-md';
UPDATE school_districts SET county_id = 'allegany-md', name = 'Allegany County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.maryland.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.maryland.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-allegany-md';

COMMIT;
