-- Rollback Script for State: Massachusetts | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:53:43.208Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'worcester-ma', program_id = 'ma-medicaid', office_name = 'Worcester County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-worcester-ma-medicaid';
UPDATE county_offices SET county_id = 'suffolk-ma', program_id = 'ma-medicaid', office_name = 'Suffolk County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-suffolk-ma-medicaid';
UPDATE county_offices SET county_id = 'plymouth-ma', program_id = 'ma-medicaid', office_name = 'Plymouth County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-plymouth-ma-medicaid';
UPDATE county_offices SET county_id = 'norfolk-ma', program_id = 'ma-medicaid', office_name = 'Norfolk County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-norfolk-ma-medicaid';
UPDATE county_offices SET county_id = 'nantucket-ma', program_id = 'ma-medicaid', office_name = 'Nantucket County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-nantucket-ma-medicaid';
UPDATE county_offices SET county_id = 'middlesex-ma', program_id = 'ma-medicaid', office_name = 'Middlesex County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-middlesex-ma-medicaid';
UPDATE county_offices SET county_id = 'hampshire-ma', program_id = 'ma-medicaid', office_name = 'Hampshire County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-hampshire-ma-medicaid';
UPDATE county_offices SET county_id = 'hampden-ma', program_id = 'ma-medicaid', office_name = 'Hampden County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-hampden-ma-medicaid';
UPDATE county_offices SET county_id = 'franklin-ma', program_id = 'ma-medicaid', office_name = 'Franklin County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-franklin-ma-medicaid';
UPDATE county_offices SET county_id = 'essex-ma', program_id = 'ma-medicaid', office_name = 'Essex County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-essex-ma-medicaid';
UPDATE county_offices SET county_id = 'dukes-ma', program_id = 'ma-medicaid', office_name = 'Dukes County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-dukes-ma-medicaid';
UPDATE county_offices SET county_id = 'bristol-ma', program_id = 'ma-medicaid', office_name = 'Bristol County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-bristol-ma-medicaid';
UPDATE county_offices SET county_id = 'berkshire-ma', program_id = 'ma-medicaid', office_name = 'Berkshire County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-berkshire-ma-medicaid';
UPDATE county_offices SET county_id = 'barnstable-ma', program_id = 'ma-medicaid', office_name = 'Barnstable County storefront office', address = '', phone = '(877) 382-2363', email = '', website = 'https://www.mass.gov/apply-for-masshealth', source_url = 'https://www.mass.gov/orgs/division-of-medical-assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-barnstable-ma-medicaid';

COMMIT;
