-- Rollback Script for State: Massachusetts | Phase: district_replacements
-- Generated At: 2026-06-14T15:41:39.441Z

BEGIN TRANSACTION;

DELETE FROM school_districts WHERE id = 'sd-suffolk-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-suffolk-ma-fallback', 'suffolk-ma', 'Suffolk County School District Special Education', '(800) 555-0199', 'sped-fallback@suffolk-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-suffolk-ma-fallback' WHERE id = 'sd-suffolk-ma';
DELETE FROM school_districts WHERE id = 'sd-plymouth-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-plymouth-ma-fallback', 'plymouth-ma', 'Plymouth County School District Special Education', '(800) 555-0199', 'sped-fallback@plymouth-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-plymouth-ma-fallback' WHERE id = 'sd-plymouth-ma';
DELETE FROM school_districts WHERE id = 'sd-norfolk-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-norfolk-ma-fallback', 'norfolk-ma', 'Norfolk County School District Special Education', '(800) 555-0199', 'sped-fallback@norfolk-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-norfolk-ma-fallback' WHERE id = 'sd-norfolk-ma';
DELETE FROM school_districts WHERE id = 'sd-nantucket-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-nantucket-ma-fallback', 'nantucket-ma', 'Nantucket County School District Special Education', '(800) 555-0199', 'sped-fallback@nantucket-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-nantucket-ma-fallback' WHERE id = 'sd-nantucket-ma';
DELETE FROM school_districts WHERE id = 'sd-hampshire-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-hampshire-ma-fallback', 'hampshire-ma', 'Hampshire County School District Special Education', '(800) 555-0199', 'sped-fallback@hampshire-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-hampshire-ma-fallback' WHERE id = 'sd-hampshire-ma';
DELETE FROM school_districts WHERE id = 'sd-hampden-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-hampden-ma-fallback', 'hampden-ma', 'Hampden County School District Special Education', '(800) 555-0199', 'sped-fallback@hampden-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-hampden-ma-fallback' WHERE id = 'sd-hampden-ma';
DELETE FROM school_districts WHERE id = 'sd-franklin-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-franklin-ma-fallback', 'franklin-ma', 'Franklin County School District Special Education', '(800) 555-0199', 'sped-fallback@franklin-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-franklin-ma-fallback' WHERE id = 'sd-franklin-ma';
DELETE FROM school_districts WHERE id = 'sd-essex-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-essex-ma-fallback', 'essex-ma', 'Essex County School District Special Education', '(800) 555-0199', 'sped-fallback@essex-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-essex-ma-fallback' WHERE id = 'sd-essex-ma';
DELETE FROM school_districts WHERE id = 'sd-dukes-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-dukes-ma-fallback', 'dukes-ma', 'Dukes County School District Special Education', '(800) 555-0199', 'sped-fallback@dukes-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-dukes-ma-fallback' WHERE id = 'sd-dukes-ma';
DELETE FROM school_districts WHERE id = 'sd-bristol-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-bristol-ma-fallback', 'bristol-ma', 'Bristol County School District Special Education', '(800) 555-0199', 'sped-fallback@bristol-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-bristol-ma-fallback' WHERE id = 'sd-bristol-ma';
DELETE FROM school_districts WHERE id = 'sd-berkshire-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-berkshire-ma-fallback', 'berkshire-ma', 'Berkshire County School District Special Education', '(800) 555-0199', 'sped-fallback@berkshire-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-berkshire-ma-fallback' WHERE id = 'sd-berkshire-ma';
DELETE FROM school_districts WHERE id = 'sd-barnstable-ma';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-barnstable-ma-fallback', 'barnstable-ma', 'Barnstable County School District Special Education', '(800) 555-0199', 'sped-fallback@barnstable-ma.gov', 'https://www.massachusetts-education.gov', 5000, 12, 60, 20, 'https://www.massachusetts-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.551Z', 3, NULL);
UPDATE school_districts SET id = 'sd-barnstable-ma-fallback' WHERE id = 'sd-barnstable-ma';

COMMIT;
