-- Rollback Script for State: Massachusetts | Phase: district_replacements
-- Generated At: 2026-06-15T21:53:44.823Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'suffolk-ma', name = 'Suffolk County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-suffolk-ma';
UPDATE school_districts SET county_id = 'plymouth-ma', name = 'Plymouth County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-plymouth-ma';
UPDATE school_districts SET county_id = 'norfolk-ma', name = 'Norfolk County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-norfolk-ma';
UPDATE school_districts SET county_id = 'nantucket-ma', name = 'Nantucket County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-nantucket-ma';
UPDATE school_districts SET county_id = 'hampshire-ma', name = 'Hampshire County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-hampshire-ma';
UPDATE school_districts SET county_id = 'hampden-ma', name = 'Hampden County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-hampden-ma';
UPDATE school_districts SET county_id = 'franklin-ma', name = 'Franklin County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-franklin-ma';
UPDATE school_districts SET county_id = 'essex-ma', name = 'Essex County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-essex-ma';
UPDATE school_districts SET county_id = 'dukes-ma', name = 'Dukes County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-dukes-ma';
UPDATE school_districts SET county_id = 'bristol-ma', name = 'Bristol County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-bristol-ma';
UPDATE school_districts SET county_id = 'berkshire-ma', name = 'Berkshire County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-berkshire-ma';
UPDATE school_districts SET county_id = 'barnstable-ma', name = 'Barnstable County School District', spec_ed_contact_phone = '(781) 338-3700', spec_ed_contact_email = '', website = 'https://www.doe.mass.edu/sped/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.doe.mass.edu/sped/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-barnstable-ma';

COMMIT;
