-- Rollback Script for State: Pennsylvania | Phase: dd_idd
-- Generated At: 2026-06-14T02:08:40.980Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-westmoreland' AND county_id = 'westmoreland-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-westmoreland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-wayne' AND county_id = 'wayne-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-washington' AND county_id = 'washington-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-venango' AND county_id = 'venango-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-venango';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-tioga' AND county_id = 'tioga-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-tioga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-schuylkill' AND county_id = 'schuylkill-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-schuylkill';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-potter' AND county_id = 'potter-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-potter';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-philadelphia' AND county_id = 'philadelphia-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-philadelphia';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-northumberland' AND county_id = 'northumberland-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-northumberland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-northampton' AND county_id = 'northampton-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-northampton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-montgomery' AND county_id = 'montgomery-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-mercer' AND county_id = 'mercer-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-mercer';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-mckean' AND county_id = 'mckean-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-mckean';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-luzerne-wyoming' AND county_id = 'wyoming-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-luzerne-wyoming' AND county_id = 'luzerne-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-luzerne-wyoming';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-lehigh' AND county_id = 'lehigh-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-lehigh';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-lebanon' AND county_id = 'lebanon-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-lebanon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-lawrence' AND county_id = 'lawrence-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-lawrence';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-lancaster' AND county_id = 'lancaster-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-lancaster';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-lackawanna-susquehanna' AND county_id = 'susquehanna-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-lackawanna-susquehanna' AND county_id = 'lackawanna-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-lackawanna-susquehanna';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-juniata-valley' AND county_id = 'mifflin-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-juniata-valley' AND county_id = 'juniata-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-juniata-valley' AND county_id = 'huntingdon-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-juniata-valley';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-greene' AND county_id = 'greene-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-franklin-fulton' AND county_id = 'fulton-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-franklin-fulton' AND county_id = 'franklin-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-franklin-fulton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-forest-warren' AND county_id = 'warren-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-forest-warren' AND county_id = 'forest-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-forest-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-fayette' AND county_id = 'fayette-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-fayette';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-erie' AND county_id = 'erie-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-erie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-delaware' AND county_id = 'delaware-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-delaware';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-dauphin' AND county_id = 'dauphin-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-dauphin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-cumberland-perry' AND county_id = 'perry-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-cumberland-perry' AND county_id = 'cumberland-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-cumberland-perry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-crawford' AND county_id = 'crawford-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-crawford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-cmsu' AND county_id = 'union-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-cmsu' AND county_id = 'snyder-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-cmsu' AND county_id = 'montour-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-cmsu' AND county_id = 'columbia-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-cmsu';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-lycoming-clinton' AND county_id = 'clinton-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-lycoming-clinton' AND county_id = 'lycoming-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-lycoming-clinton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-clearfield-jefferson' AND county_id = 'jefferson-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-clearfield-jefferson' AND county_id = 'clearfield-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-clearfield-jefferson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-clarion' AND county_id = 'clarion-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-clarion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-chester' AND county_id = 'chester-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-chester';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-centre' AND county_id = 'centre-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-centre';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-carbon-monroe-pike' AND county_id = 'pike-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-carbon-monroe-pike' AND county_id = 'monroe-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-carbon-monroe-pike' AND county_id = 'carbon-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-carbon-monroe-pike';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-cameron-elk' AND county_id = 'elk-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-cameron-elk' AND county_id = 'cameron-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-cameron-elk';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-cambria' AND county_id = 'cambria-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-cambria';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-butler' AND county_id = 'butler-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-butler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-bucks' AND county_id = 'bucks-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-bucks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-bradford-sullivan' AND county_id = 'sullivan-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-bradford-sullivan' AND county_id = 'bradford-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-bradford-sullivan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-blair' AND county_id = 'blair-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-blair';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-berks' AND county_id = 'berks-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-berks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-bedford-somerset' AND county_id = 'somerset-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-bedford-somerset' AND county_id = 'bedford-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-bedford-somerset';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-beaver' AND county_id = 'beaver-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-beaver';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-armstrong-indiana' AND county_id = 'indiana-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-armstrong-indiana' AND county_id = 'armstrong-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-armstrong-indiana';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-allegheny' AND county_id = 'allegheny-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-allegheny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-york-adams' AND county_id = 'adams-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-dd-york-adams' AND county_id = 'york-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-dd-york-adams';

COMMIT;
