-- Rollback Script for State: Pennsylvania | Phase: early_intervention
-- Generated At: 2026-06-13T21:27:55.696Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-york' AND county_id = 'york-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-york';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-wyoming' AND county_id = 'wyoming-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-wyoming';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-westmoreland' AND county_id = 'westmoreland-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-westmoreland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-wayne' AND county_id = 'wayne-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-washington' AND county_id = 'washington-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-warren' AND county_id = 'warren-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-venango' AND county_id = 'venango-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-venango';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-union' AND county_id = 'union-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-union';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-tioga' AND county_id = 'tioga-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-tioga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-susquehanna' AND county_id = 'susquehanna-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-susquehanna';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-sullivan' AND county_id = 'sullivan-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-sullivan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-somerset' AND county_id = 'somerset-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-somerset';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-snyder' AND county_id = 'snyder-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-snyder';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-schuylkill' AND county_id = 'schuylkill-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-schuylkill';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-potter' AND county_id = 'potter-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-potter';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-pike' AND county_id = 'pike-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-pike';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-philadelphia' AND county_id = 'philadelphia-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-philadelphia';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-perry' AND county_id = 'perry-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-perry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-northumberland' AND county_id = 'northumberland-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-northumberland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-northampton' AND county_id = 'northampton-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-northampton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-montour' AND county_id = 'montour-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-montour';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-montgomery' AND county_id = 'montgomery-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-monroe' AND county_id = 'monroe-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-monroe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-mifflin' AND county_id = 'mifflin-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-mifflin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-mercer' AND county_id = 'mercer-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-mercer';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-mckean' AND county_id = 'mckean-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-mckean';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lycoming' AND county_id = 'lycoming-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lycoming';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-luzerne' AND county_id = 'luzerne-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-luzerne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lehigh' AND county_id = 'lehigh-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lehigh';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lebanon' AND county_id = 'lebanon-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lebanon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lawrence' AND county_id = 'lawrence-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lawrence';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lancaster' AND county_id = 'lancaster-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lancaster';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lackawanna' AND county_id = 'lackawanna-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lackawanna';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-juniata' AND county_id = 'juniata-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-juniata';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-jefferson' AND county_id = 'jefferson-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-jefferson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-indiana' AND county_id = 'indiana-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-indiana';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-huntingdon' AND county_id = 'huntingdon-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-huntingdon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-greene' AND county_id = 'greene-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-fulton' AND county_id = 'fulton-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-fulton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-franklin' AND county_id = 'franklin-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-franklin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-forest' AND county_id = 'forest-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-forest';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-fayette' AND county_id = 'fayette-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-fayette';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-erie' AND county_id = 'erie-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-erie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-elk' AND county_id = 'elk-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-elk';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-delaware' AND county_id = 'delaware-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-delaware';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-dauphin' AND county_id = 'dauphin-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-dauphin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cumberland' AND county_id = 'cumberland-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-cumberland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-crawford' AND county_id = 'crawford-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-crawford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-columbia' AND county_id = 'columbia-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-columbia';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-clinton' AND county_id = 'clinton-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-clinton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-clearfield' AND county_id = 'clearfield-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-clearfield';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-clarion' AND county_id = 'clarion-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-clarion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-chester' AND county_id = 'chester-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-chester';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-centre' AND county_id = 'centre-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-centre';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-carbon' AND county_id = 'carbon-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-carbon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cameron' AND county_id = 'cameron-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-cameron';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cambria' AND county_id = 'cambria-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-cambria';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-butler' AND county_id = 'butler-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-butler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-bucks' AND county_id = 'bucks-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-bucks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-bradford' AND county_id = 'bradford-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-bradford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-blair' AND county_id = 'blair-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-blair';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-berks' AND county_id = 'berks-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-berks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-bedford' AND county_id = 'bedford-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-bedford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-beaver' AND county_id = 'beaver-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-beaver';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-armstrong' AND county_id = 'armstrong-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-armstrong';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-allegheny' AND county_id = 'allegheny-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-allegheny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-adams' AND county_id = 'adams-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-adams';

COMMIT;
