-- Rollback Script for State: Pennsylvania | Phase: early_intervention
-- Generated At: 2026-06-14T02:18:11.948Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-westmoreland' AND county_id = 'westmoreland-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-westmoreland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-wayne' AND county_id = 'wayne-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-washington' AND county_id = 'washington-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-venango' AND county_id = 'venango-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-venango';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-tioga' AND county_id = 'tioga-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-tioga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-schuylkill' AND county_id = 'schuylkill-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-schuylkill';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-potter' AND county_id = 'potter-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-potter';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-philadelphia' AND county_id = 'philadelphia-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-philadelphia';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-northumberland' AND county_id = 'northumberland-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-northumberland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-northampton' AND county_id = 'northampton-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-northampton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-montgomery' AND county_id = 'montgomery-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-mercer' AND county_id = 'mercer-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-mercer';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-mckean' AND county_id = 'mckean-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-mckean';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-luzerne-wyoming' AND county_id = 'wyoming-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-luzerne-wyoming' AND county_id = 'luzerne-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-luzerne-wyoming';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lehigh' AND county_id = 'lehigh-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lehigh';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lebanon' AND county_id = 'lebanon-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lebanon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lawrence' AND county_id = 'lawrence-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lawrence';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lancaster' AND county_id = 'lancaster-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lancaster';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lackawanna-susquehanna' AND county_id = 'susquehanna-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lackawanna-susquehanna' AND county_id = 'lackawanna-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lackawanna-susquehanna';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-juniata-valley' AND county_id = 'mifflin-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-juniata-valley' AND county_id = 'juniata-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-juniata-valley' AND county_id = 'huntingdon-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-juniata-valley';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-greene' AND county_id = 'greene-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-franklin-fulton' AND county_id = 'fulton-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-franklin-fulton' AND county_id = 'franklin-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-franklin-fulton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-forest-warren' AND county_id = 'warren-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-forest-warren' AND county_id = 'forest-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-forest-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-fayette' AND county_id = 'fayette-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-fayette';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-erie' AND county_id = 'erie-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-erie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-delaware' AND county_id = 'delaware-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-delaware';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-dauphin' AND county_id = 'dauphin-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-dauphin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cumberland-perry' AND county_id = 'perry-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cumberland-perry' AND county_id = 'cumberland-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-cumberland-perry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-crawford' AND county_id = 'crawford-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-crawford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cmsu' AND county_id = 'union-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cmsu' AND county_id = 'snyder-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cmsu' AND county_id = 'montour-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cmsu' AND county_id = 'columbia-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-cmsu';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lycoming-clinton' AND county_id = 'clinton-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-lycoming-clinton' AND county_id = 'lycoming-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-lycoming-clinton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-clearfield-jefferson' AND county_id = 'jefferson-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-clearfield-jefferson' AND county_id = 'clearfield-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-clearfield-jefferson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-clarion' AND county_id = 'clarion-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-clarion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-chester' AND county_id = 'chester-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-chester';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-centre' AND county_id = 'centre-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-centre';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-carbon-monroe-pike' AND county_id = 'pike-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-carbon-monroe-pike' AND county_id = 'monroe-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-carbon-monroe-pike' AND county_id = 'carbon-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-carbon-monroe-pike';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cameron-elk' AND county_id = 'elk-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cameron-elk' AND county_id = 'cameron-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-cameron-elk';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-cambria' AND county_id = 'cambria-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-cambria';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-butler' AND county_id = 'butler-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-butler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-bucks' AND county_id = 'bucks-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-bucks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-bradford-sullivan' AND county_id = 'sullivan-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-bradford-sullivan' AND county_id = 'bradford-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-bradford-sullivan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-blair' AND county_id = 'blair-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-blair';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-berks' AND county_id = 'berks-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-berks';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-bedford-somerset' AND county_id = 'somerset-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-bedford-somerset' AND county_id = 'bedford-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-bedford-somerset';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-beaver' AND county_id = 'beaver-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-beaver';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-armstrong-indiana' AND county_id = 'indiana-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-armstrong-indiana' AND county_id = 'armstrong-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-armstrong-indiana';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-allegheny' AND county_id = 'allegheny-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-allegheny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-york-adams' AND county_id = 'adams-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-york-adams' AND county_id = 'york-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-york-adams';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'york-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'wyoming-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'westmoreland-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'wayne-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'washington-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'warren-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'venango-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'union-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'tioga-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'susquehanna-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'sullivan-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'somerset-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'snyder-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'schuylkill-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'potter-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'pike-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'philadelphia-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'perry-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'northumberland-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'northampton-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'montour-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'montgomery-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'monroe-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'mifflin-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'mercer-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'mckean-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'lycoming-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'luzerne-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'lehigh-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'lebanon-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'lawrence-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'lancaster-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'lackawanna-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'juniata-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'jefferson-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'indiana-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'huntingdon-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'greene-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'fulton-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'franklin-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'forest-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'fayette-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'erie-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'elk-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'delaware-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'dauphin-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'cumberland-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'crawford-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'columbia-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'clinton-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'clearfield-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'clarion-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'chester-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'centre-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'carbon-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'cameron-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'cambria-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'butler-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'bucks-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'bradford-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'blair-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'berks-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'bedford-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'beaver-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'armstrong-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'allegheny-pa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'pa-ei-connect' AND county_id = 'adams-pa';
DELETE FROM state_resource_agencies WHERE id = 'pa-ei-connect';

COMMIT;
