-- Rollback Script for State: Pennsylvania | Phase: education_regional
-- Generated At: 2026-06-15T16:54:39.952Z

BEGIN TRANSACTION;

DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-29' AND county_id = 'schuylkill-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Schuylkill Intermediate Unit 29', counties_served = 'schuylkill-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-29';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-28' AND county_id = 'indiana-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-28' AND county_id = 'armstrong-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'ARIN Intermediate Unit 28', counties_served = 'armstrong-pa,indiana-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-28';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-27' AND county_id = 'beaver-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Beaver Valley Intermediate Unit 27', counties_served = 'beaver-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-27';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-26' AND county_id = 'philadelphia-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Philadelphia Intermediate Unit 26', counties_served = 'philadelphia-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-26';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-25' AND county_id = 'delaware-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Delaware County Intermediate Unit 25', counties_served = 'delaware-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-25';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-24' AND county_id = 'chester-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Chester County Intermediate Unit 24', counties_served = 'chester-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-24';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-23' AND county_id = 'montgomery-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Montgomery County Intermediate Unit 23', counties_served = 'montgomery-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-23';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-22' AND county_id = 'bucks-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Bucks County Intermediate Unit 22', counties_served = 'bucks-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-22';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-21' AND county_id = 'lehigh-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-21' AND county_id = 'carbon-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Carbon-Lehigh Intermediate Unit 21', counties_served = 'carbon-pa,lehigh-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-21';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-20' AND county_id = 'pike-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-20' AND county_id = 'northampton-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-20' AND county_id = 'monroe-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Colonial Intermediate Unit 20', counties_served = 'monroe-pa,northampton-pa,pike-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-20';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-19' AND county_id = 'wayne-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-19' AND county_id = 'susquehanna-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-19' AND county_id = 'lackawanna-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Northeastern Educational Intermediate Unit 19', counties_served = 'lackawanna-pa,susquehanna-pa,wayne-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-19';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-18' AND county_id = 'wyoming-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-18' AND county_id = 'luzerne-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Luzerne Intermediate Unit 18', counties_served = 'luzerne-pa,wyoming-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-18';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-17' AND county_id = 'tioga-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-17' AND county_id = 'sullivan-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-17' AND county_id = 'lycoming-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-17' AND county_id = 'bradford-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'BLaST Intermediate Unit 17', counties_served = 'bradford-pa,lycoming-pa,sullivan-pa,tioga-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-17';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'union-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'snyder-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'northumberland-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'montour-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'columbia-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Central Susquehanna Intermediate Unit 16', counties_served = 'columbia-pa,montour-pa,northumberland-pa,snyder-pa,union-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-16';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-15' AND county_id = 'perry-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-15' AND county_id = 'dauphin-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-15' AND county_id = 'cumberland-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Capital Area Intermediate Unit 15', counties_served = 'cumberland-pa,dauphin-pa,perry-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-15';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-14' AND county_id = 'berks-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Berks County Intermediate Unit 14', counties_served = 'berks-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-14';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-13' AND county_id = 'lebanon-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-13' AND county_id = 'lancaster-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Lancaster-Lebanon Intermediate Unit 13', counties_served = 'lancaster-pa,lebanon-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-13';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-12' AND county_id = 'york-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-12' AND county_id = 'franklin-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-12' AND county_id = 'adams-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Lincoln Intermediate Unit 12', counties_served = 'adams-pa,franklin-pa,york-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-12';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-11' AND county_id = 'mifflin-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-11' AND county_id = 'juniata-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-11' AND county_id = 'huntingdon-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-11' AND county_id = 'fulton-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Tuscarora Intermediate Unit 11', counties_served = 'fulton-pa,huntingdon-pa,juniata-pa,mifflin-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-11';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-10' AND county_id = 'clinton-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-10' AND county_id = 'clearfield-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-10' AND county_id = 'centre-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Central Intermediate Unit 10', counties_served = 'centre-pa,clearfield-pa,clinton-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-10';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-9' AND county_id = 'potter-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-9' AND county_id = 'mckean-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-9' AND county_id = 'elk-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-9' AND county_id = 'cameron-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Seneca Highlands Intermediate Unit 9', counties_served = 'cameron-pa,elk-pa,mckean-pa,potter-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-9';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-8' AND county_id = 'somerset-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-8' AND county_id = 'cambria-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-8' AND county_id = 'blair-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-8' AND county_id = 'bedford-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Appalachia Intermediate Unit 8', counties_served = 'bedford-pa,blair-pa,cambria-pa,somerset-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-8';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-7' AND county_id = 'westmoreland-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Westmoreland Intermediate Unit 7', counties_served = 'westmoreland-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-7';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-6' AND county_id = 'venango-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-6' AND county_id = 'jefferson-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-6' AND county_id = 'forest-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-6' AND county_id = 'clarion-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Riverview Intermediate Unit 6', counties_served = 'clarion-pa,forest-pa,jefferson-pa,venango-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-6';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-5' AND county_id = 'warren-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-5' AND county_id = 'crawford-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-5' AND county_id = 'erie-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Northwest Tri-County Intermediate Unit 5', counties_served = 'erie-pa,crawford-pa,warren-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-5';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-4' AND county_id = 'mercer-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-4' AND county_id = 'lawrence-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-4' AND county_id = 'butler-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Midwestern Intermediate Unit 4', counties_served = 'butler-pa,lawrence-pa,mercer-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-4';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-3' AND county_id = 'allegheny-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Allegheny Intermediate Unit 3', counties_served = 'allegheny-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-3';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-2' AND county_id = 'allegheny-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Pittsburgh-Mt. Oliver Intermediate Unit 2', counties_served = 'allegheny-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-2';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-1' AND county_id = 'washington-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-1' AND county_id = 'greene-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-1' AND county_id = 'fayette-pa';
UPDATE regional_education_agencies SET state_id = 'pennsylvania', agency_type = 'iu', name = 'Intermediate Unit 1', counties_served = 'fayette-pa,greene-pa,washington-pa', website = '', source_url = '', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0, evidence_level = 'manual_review_required' WHERE id = 'pa-iu-1';

COMMIT;
