-- Rollback Script for State: Pennsylvania | Phase: education_regional
-- Generated At: 2026-06-14T02:18:17.377Z

BEGIN TRANSACTION;

DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-29' AND county_id = 'schuylkill-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-29';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-28' AND county_id = 'indiana-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-28' AND county_id = 'armstrong-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-28';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-27' AND county_id = 'beaver-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-27';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-26' AND county_id = 'philadelphia-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-26';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-25' AND county_id = 'delaware-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-25';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-24' AND county_id = 'chester-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-24';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-23' AND county_id = 'montgomery-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-23';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-22' AND county_id = 'bucks-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-22';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-21' AND county_id = 'lehigh-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-21' AND county_id = 'carbon-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-21';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-20' AND county_id = 'pike-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-20' AND county_id = 'northampton-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-20' AND county_id = 'monroe-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-20';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-19' AND county_id = 'wayne-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-19' AND county_id = 'susquehanna-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-19' AND county_id = 'lackawanna-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-19';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-18' AND county_id = 'wyoming-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-18' AND county_id = 'luzerne-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-18';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-17' AND county_id = 'tioga-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-17' AND county_id = 'sullivan-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-17' AND county_id = 'lycoming-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-17' AND county_id = 'bradford-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-17';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'union-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'snyder-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'northumberland-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'montour-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-16' AND county_id = 'columbia-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-16';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-15' AND county_id = 'perry-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-15' AND county_id = 'dauphin-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-15' AND county_id = 'cumberland-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-15';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-14' AND county_id = 'berks-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-14';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-13' AND county_id = 'lebanon-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-13' AND county_id = 'lancaster-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-13';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-12' AND county_id = 'york-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-12' AND county_id = 'franklin-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-12' AND county_id = 'adams-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-12';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-11' AND county_id = 'mifflin-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-11' AND county_id = 'juniata-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-11' AND county_id = 'huntingdon-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-11' AND county_id = 'fulton-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-11';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-10' AND county_id = 'clinton-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-10' AND county_id = 'clearfield-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-10' AND county_id = 'centre-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-10';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-9' AND county_id = 'potter-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-9' AND county_id = 'mckean-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-9' AND county_id = 'elk-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-9' AND county_id = 'cameron-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-9';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-8' AND county_id = 'somerset-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-8' AND county_id = 'cambria-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-8' AND county_id = 'blair-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-8' AND county_id = 'bedford-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-8';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-7' AND county_id = 'westmoreland-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-7';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-6' AND county_id = 'venango-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-6' AND county_id = 'jefferson-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-6' AND county_id = 'forest-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-6' AND county_id = 'clarion-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-6';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-5' AND county_id = 'warren-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-5' AND county_id = 'crawford-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-5' AND county_id = 'erie-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-5';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-4' AND county_id = 'mercer-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-4' AND county_id = 'lawrence-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-4' AND county_id = 'butler-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-4';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-3' AND county_id = 'allegheny-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-3';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-2' AND county_id = 'allegheny-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-2';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-1' AND county_id = 'washington-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-1' AND county_id = 'greene-pa';
DELETE FROM selpa_counties WHERE selpa_id = 'pa-iu-1' AND county_id = 'fayette-pa';
DELETE FROM regional_education_agencies WHERE id = 'pa-iu-1';

COMMIT;
