-- Rollback Script for State: Oklahoma | Phase: early_intervention
-- Generated At: 2026-06-15T19:59:42.380Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'woodward-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'woods-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'washita-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'washington-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'wagoner-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'tulsa-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'tillman-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'texas-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'stephens-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'sequoyah-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'seminole-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'rogers-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'roger-mills-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'pushmataha-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'pottawatomie-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'pontotoc-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'pittsburg-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'payne-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'pawnee-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'ottawa-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'osage-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'okmulgee-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'oklahoma-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'okfuskee-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'nowata-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'noble-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'muskogee-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'murray-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'mcintosh-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'mccurtain-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'mcclain-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'mayes-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'marshall-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'major-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'love-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'logan-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'lincoln-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'leflore-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'latimer-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'kiowa-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'kingfisher-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'kay-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'johnston-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'jefferson-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'jackson-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'hughes-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'haskell-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'harper-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'harmon-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'greer-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'grant-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'grady-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'garvin-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'garfield-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'ellis-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'dewey-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'delaware-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'custer-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'creek-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'craig-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'cotton-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'comanche-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'coal-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'cleveland-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'cimarron-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'choctaw-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'cherokee-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'carter-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'canadian-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'caddo-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'bryan-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'blaine-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'beckham-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'beaver-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'atoka-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'alfalfa-ok';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ok-ei-agency' AND county_id = 'adair-ok';
UPDATE state_resource_agencies SET state_id = 'oklahoma', agency_type = 'early_intervention', name = 'Oklahoma Early Intervention State Office', counties_served = 'statewide', catchment_boundaries = 'statewide', website = 'https://dhhs.oklahoma.gov/earlystart', intake_phone = '', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://dhhs.oklahoma.gov/earlystart', source_url = 'https://dhhs.oklahoma.gov/earlystart', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'ok-ei-agency';

COMMIT;
