-- Rollback Script for State: Alaska | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:50:29.690Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'yakutat-ak', program_id = 'ak-medicaid', office_name = 'Yakutat County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-yakutat-ak-medicaid';
UPDATE county_offices SET county_id = 'wrangell-ak', program_id = 'ak-medicaid', office_name = 'Wrangell County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-wrangell-ak-medicaid';
UPDATE county_offices SET county_id = 'unorganized-borough-ak', program_id = 'ak-medicaid', office_name = 'Unorganized Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-unorganized-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'skagway-ak', program_id = 'ak-medicaid', office_name = 'Skagway County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-skagway-ak-medicaid';
UPDATE county_offices SET county_id = 'sitka-ak', program_id = 'ak-medicaid', office_name = 'Sitka County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-sitka-ak-medicaid';
UPDATE county_offices SET county_id = 'petersburg-borough-ak', program_id = 'ak-medicaid', office_name = 'Petersburg Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-petersburg-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'northwest-arctic-borough-ak', program_id = 'ak-medicaid', office_name = 'Northwest Arctic Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-northwest-arctic-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'north-slope-borough-ak', program_id = 'ak-medicaid', office_name = 'North Slope Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-north-slope-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'matanuska-susitna-borough-ak', program_id = 'ak-medicaid', office_name = 'Matanuska-Susitna Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-matanuska-susitna-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'lake-and-peninsula-borough-ak', program_id = 'ak-medicaid', office_name = 'Lake and Peninsula Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lake-and-peninsula-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'kodiak-island-borough-ak', program_id = 'ak-medicaid', office_name = 'Kodiak Island Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-kodiak-island-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'ketchikan-gateway-borough-ak', program_id = 'ak-medicaid', office_name = 'Ketchikan Gateway Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-ketchikan-gateway-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'kenai-peninsula-borough-ak', program_id = 'ak-medicaid', office_name = 'Kenai Peninsula Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-kenai-peninsula-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'juneau-ak', program_id = 'ak-medicaid', office_name = 'Juneau County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-juneau-ak-medicaid';
UPDATE county_offices SET county_id = 'haines-borough-ak', program_id = 'ak-medicaid', office_name = 'Haines Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-haines-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'fairbanks-north-star-borough-ak', program_id = 'ak-medicaid', office_name = 'Fairbanks North Star Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-fairbanks-north-star-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'denali-borough-ak', program_id = 'ak-medicaid', office_name = 'Denali Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-denali-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'bristol-bay-borough-ak', program_id = 'ak-medicaid', office_name = 'Bristol Bay Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-bristol-bay-borough-ak-medicaid';
UPDATE county_offices SET county_id = 'anchorage-ak', program_id = 'ak-medicaid', office_name = 'Anchorage County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-anchorage-ak-medicaid';
UPDATE county_offices SET county_id = 'aleutians-east-borough-ak', program_id = 'ak-medicaid', office_name = 'Aleutians East Borough County storefront office', address = '', phone = '(800) 478-7778', email = '', website = 'https://health.alaska.gov/dpa/Pages/default.aspx', source_url = 'https://health.alaska.gov/dpa/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-aleutians-east-borough-ak-medicaid';

COMMIT;
