-- Rollback Script for State: Alaska | Phase: district_replacements
-- Generated At: 2026-06-15T21:50:32.041Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'yakutat-ak', name = 'Yakutat County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-yakutat-ak';
UPDATE school_districts SET county_id = 'wrangell-ak', name = 'Wrangell County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-wrangell-ak';
UPDATE school_districts SET county_id = 'unorganized-borough-ak', name = 'Unorganized Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-unorganized-borough-ak';
UPDATE school_districts SET county_id = 'skagway-ak', name = 'Skagway County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-skagway-ak';
UPDATE school_districts SET county_id = 'sitka-ak', name = 'Sitka County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-sitka-ak';
UPDATE school_districts SET county_id = 'petersburg-borough-ak', name = 'Petersburg Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-petersburg-borough-ak';
UPDATE school_districts SET county_id = 'northwest-arctic-borough-ak', name = 'Northwest Arctic Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-northwest-arctic-borough-ak';
UPDATE school_districts SET county_id = 'north-slope-borough-ak', name = 'North Slope Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-north-slope-borough-ak';
UPDATE school_districts SET county_id = 'lake-and-peninsula-borough-ak', name = 'Lake and Peninsula Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-lake-and-peninsula-borough-ak';
UPDATE school_districts SET county_id = 'kodiak-island-borough-ak', name = 'Kodiak Island Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-kodiak-island-borough-ak';
UPDATE school_districts SET county_id = 'ketchikan-gateway-borough-ak', name = 'Ketchikan Gateway Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-ketchikan-gateway-borough-ak';
UPDATE school_districts SET county_id = 'kenai-peninsula-borough-ak', name = 'Kenai Peninsula Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-kenai-peninsula-borough-ak';
UPDATE school_districts SET county_id = 'juneau-ak', name = 'Juneau County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-juneau-ak';
UPDATE school_districts SET county_id = 'haines-borough-ak', name = 'Haines Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-haines-borough-ak';
UPDATE school_districts SET county_id = 'fairbanks-north-star-borough-ak', name = 'Fairbanks North Star Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-fairbanks-north-star-borough-ak';
UPDATE school_districts SET county_id = 'denali-borough-ak', name = 'Denali Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-denali-borough-ak';
UPDATE school_districts SET county_id = 'bristol-bay-borough-ak', name = 'Bristol Bay Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-bristol-bay-borough-ak';
UPDATE school_districts SET county_id = 'aleutians-east-borough-ak', name = 'Aleutians East Borough County School District', spec_ed_contact_phone = '(907) 465-2972', spec_ed_contact_email = '', website = 'https://education.alaska.gov/sped', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.alaska.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-aleutians-east-borough-ak';

COMMIT;
