-- Rollback Script for State: Alaska | Phase: trusted_nonprofits
-- Generated At: 2026-06-14T15:42:43.634Z

BEGIN TRANSACTION;

DELETE FROM nonprofit_organizations WHERE id = 'np-local-matanuska-susitna-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'np-local-anchorage-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-yakutat-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-wrangell-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-unorganized-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-skagway-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-sitka-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-petersburg-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-northwest-arctic-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-north-slope-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-matanuska-susitna-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-lake-and-peninsula-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-kodiak-island-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-ketchikan-gateway-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-kenai-peninsula-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-juneau-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-haines-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-fairbanks-north-star-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-denali-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-bristol-bay-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-anchorage-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-arc-aleutians-east-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-yakutat-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-wrangell-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-unorganized-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-skagway-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-sitka-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-petersburg-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-northwest-arctic-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-north-slope-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-matanuska-susitna-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-lake-and-peninsula-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-kodiak-island-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-ketchikan-gateway-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-kenai-peninsula-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-juneau-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-haines-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-fairbanks-north-star-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-denali-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-bristol-bay-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-anchorage-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-parent-aleutians-east-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-yakutat-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-wrangell-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-unorganized-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-skagway-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-sitka-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-petersburg-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-northwest-arctic-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-north-slope-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-matanuska-susitna-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-lake-and-peninsula-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-kodiak-island-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-ketchikan-gateway-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-kenai-peninsula-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-juneau-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-haines-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-fairbanks-north-star-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-denali-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-bristol-bay-borough-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-anchorage-ak';
DELETE FROM nonprofit_organizations WHERE id = 'ak-np-rights-aleutians-east-borough-ak';

COMMIT;
