-- Rollback Script for State: Maine | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:53:20.677Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'york-me', program_id = 'me-medicaid', office_name = 'York County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-york-me-medicaid';
UPDATE county_offices SET county_id = 'washington-me', program_id = 'me-medicaid', office_name = 'Washington County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-washington-me-medicaid';
UPDATE county_offices SET county_id = 'waldo-me', program_id = 'me-medicaid', office_name = 'Waldo County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-waldo-me-medicaid';
UPDATE county_offices SET county_id = 'somerset-me', program_id = 'me-medicaid', office_name = 'Somerset County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-somerset-me-medicaid';
UPDATE county_offices SET county_id = 'sagadahoc-me', program_id = 'me-medicaid', office_name = 'Sagadahoc County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-sagadahoc-me-medicaid';
UPDATE county_offices SET county_id = 'piscataquis-me', program_id = 'me-medicaid', office_name = 'Piscataquis County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-piscataquis-me-medicaid';
UPDATE county_offices SET county_id = 'penobscot-me', program_id = 'me-medicaid', office_name = 'Penobscot County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-penobscot-me-medicaid';
UPDATE county_offices SET county_id = 'oxford-me', program_id = 'me-medicaid', office_name = 'Oxford County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-oxford-me-medicaid';
UPDATE county_offices SET county_id = 'lincoln-me', program_id = 'me-medicaid', office_name = 'Lincoln County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lincoln-me-medicaid';
UPDATE county_offices SET county_id = 'knox-me', program_id = 'me-medicaid', office_name = 'Knox County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-knox-me-medicaid';
UPDATE county_offices SET county_id = 'kennebec-me', program_id = 'me-medicaid', office_name = 'Kennebec County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-kennebec-me-medicaid';
UPDATE county_offices SET county_id = 'hancock-me', program_id = 'me-medicaid', office_name = 'Hancock County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-hancock-me-medicaid';
UPDATE county_offices SET county_id = 'franklin-me', program_id = 'me-medicaid', office_name = 'Franklin County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-franklin-me-medicaid';
UPDATE county_offices SET county_id = 'cumberland-me', program_id = 'me-medicaid', office_name = 'Cumberland County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-cumberland-me-medicaid';
UPDATE county_offices SET county_id = 'aroostook-me', program_id = 'me-medicaid', office_name = 'Aroostook County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-aroostook-me-medicaid';
UPDATE county_offices SET county_id = 'androscoggin-me', program_id = 'me-medicaid', office_name = 'Androscoggin County storefront office', address = '', phone = '(855) 797-4357', email = '', website = 'https://www.maine.gov/dhhs/ofi', source_url = 'https://www.maine.gov/dhhs', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-androscoggin-me-medicaid';

COMMIT;
