-- Rollback Script for State: Maine | Phase: district_replacements
-- Generated At: 2026-06-15T21:53:22.290Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'washington-me', name = 'Washington County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-washington-me';
UPDATE school_districts SET county_id = 'waldo-me', name = 'Waldo County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-waldo-me';
UPDATE school_districts SET county_id = 'somerset-me', name = 'Somerset County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-somerset-me';
UPDATE school_districts SET county_id = 'sagadahoc-me', name = 'Sagadahoc County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-sagadahoc-me';
UPDATE school_districts SET county_id = 'piscataquis-me', name = 'Piscataquis County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-piscataquis-me';
UPDATE school_districts SET county_id = 'penobscot-me', name = 'Penobscot County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-penobscot-me';
UPDATE school_districts SET county_id = 'oxford-me', name = 'Oxford County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-oxford-me';
UPDATE school_districts SET county_id = 'lincoln-me', name = 'Lincoln County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-lincoln-me';
UPDATE school_districts SET county_id = 'knox-me', name = 'Knox County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-knox-me';
UPDATE school_districts SET county_id = 'kennebec-me', name = 'Kennebec County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-kennebec-me';
UPDATE school_districts SET county_id = 'hancock-me', name = 'Hancock County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-hancock-me';
UPDATE school_districts SET county_id = 'franklin-me', name = 'Franklin County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-franklin-me';
UPDATE school_districts SET county_id = 'aroostook-me', name = 'Aroostook County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-aroostook-me';
UPDATE school_districts SET county_id = 'androscoggin-me', name = 'Androscoggin County School District', spec_ed_contact_phone = '(207) 624-6713', spec_ed_contact_email = '', website = 'https://www.maine.gov/doe/learning/specialed', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.maine.gov/doe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-androscoggin-me';

COMMIT;
