-- Rollback Script for State: Maine | Phase: district_replacements
-- Generated At: 2026-06-14T15:42:10.604Z

BEGIN TRANSACTION;

DELETE FROM school_districts WHERE id = 'sd-washington-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-washington-me-fallback', 'washington-me', 'Washington County School District Special Education', '(800) 555-0199', 'sped-fallback@washington-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-washington-me-fallback' WHERE id = 'sd-washington-me';
DELETE FROM school_districts WHERE id = 'sd-waldo-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-waldo-me-fallback', 'waldo-me', 'Waldo County School District Special Education', '(800) 555-0199', 'sped-fallback@waldo-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-waldo-me-fallback' WHERE id = 'sd-waldo-me';
DELETE FROM school_districts WHERE id = 'sd-somerset-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-somerset-me-fallback', 'somerset-me', 'Somerset County School District Special Education', '(800) 555-0199', 'sped-fallback@somerset-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-somerset-me-fallback' WHERE id = 'sd-somerset-me';
DELETE FROM school_districts WHERE id = 'sd-sagadahoc-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-sagadahoc-me-fallback', 'sagadahoc-me', 'Sagadahoc County School District Special Education', '(800) 555-0199', 'sped-fallback@sagadahoc-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-sagadahoc-me-fallback' WHERE id = 'sd-sagadahoc-me';
DELETE FROM school_districts WHERE id = 'sd-piscataquis-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-piscataquis-me-fallback', 'piscataquis-me', 'Piscataquis County School District Special Education', '(800) 555-0199', 'sped-fallback@piscataquis-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-piscataquis-me-fallback' WHERE id = 'sd-piscataquis-me';
DELETE FROM school_districts WHERE id = 'sd-penobscot-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-penobscot-me-fallback', 'penobscot-me', 'Penobscot County School District Special Education', '(800) 555-0199', 'sped-fallback@penobscot-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-penobscot-me-fallback' WHERE id = 'sd-penobscot-me';
DELETE FROM school_districts WHERE id = 'sd-oxford-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-oxford-me-fallback', 'oxford-me', 'Oxford County School District Special Education', '(800) 555-0199', 'sped-fallback@oxford-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-oxford-me-fallback' WHERE id = 'sd-oxford-me';
DELETE FROM school_districts WHERE id = 'sd-lincoln-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-lincoln-me-fallback', 'lincoln-me', 'Lincoln County School District Special Education', '(800) 555-0199', 'sped-fallback@lincoln-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-lincoln-me-fallback' WHERE id = 'sd-lincoln-me';
DELETE FROM school_districts WHERE id = 'sd-knox-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-knox-me-fallback', 'knox-me', 'Knox County School District Special Education', '(800) 555-0199', 'sped-fallback@knox-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-knox-me-fallback' WHERE id = 'sd-knox-me';
DELETE FROM school_districts WHERE id = 'sd-kennebec-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-kennebec-me-fallback', 'kennebec-me', 'Kennebec County School District Special Education', '(800) 555-0199', 'sped-fallback@kennebec-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-kennebec-me-fallback' WHERE id = 'sd-kennebec-me';
DELETE FROM school_districts WHERE id = 'sd-hancock-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-hancock-me-fallback', 'hancock-me', 'Hancock County School District Special Education', '(800) 555-0199', 'sped-fallback@hancock-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-hancock-me-fallback' WHERE id = 'sd-hancock-me';
DELETE FROM school_districts WHERE id = 'sd-franklin-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-franklin-me-fallback', 'franklin-me', 'Franklin County School District Special Education', '(800) 555-0199', 'sped-fallback@franklin-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-franklin-me-fallback' WHERE id = 'sd-franklin-me';
DELETE FROM school_districts WHERE id = 'sd-aroostook-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-aroostook-me-fallback', 'aroostook-me', 'Aroostook County School District Special Education', '(800) 555-0199', 'sped-fallback@aroostook-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-aroostook-me-fallback' WHERE id = 'sd-aroostook-me';
DELETE FROM school_districts WHERE id = 'sd-androscoggin-me';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-androscoggin-me-fallback', 'androscoggin-me', 'Androscoggin County School District Special Education', '(800) 555-0199', 'sped-fallback@androscoggin-me.gov', 'https://www.maine-education.gov', 5000, 12, 60, 20, 'https://www.maine-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.550Z', 3, NULL);
UPDATE school_districts SET id = 'sd-androscoggin-me-fallback' WHERE id = 'sd-androscoggin-me';

COMMIT;
