-- Rollback Script for State: Alabama | Phase: dd_idd
-- Generated At: 2026-06-14T15:49:23.289Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'winston-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'wilcox-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'washington-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'walker-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'tuscaloosa-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'tallapoosa-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'talladega-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'sumter-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'st-clair-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'shelby-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'russell-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'randolph-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'pike-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'pickens-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'perry-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'morgan-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'montgomery-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'monroe-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'mobile-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'marshall-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'marion-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'marengo-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'madison-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'macon-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'lowndes-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'limestone-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'lee-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'lawrence-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'lauderdale-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'lamar-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'jefferson-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'jackson-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'houston-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'henry-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'hale-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'greene-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'geneva-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'franklin-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'fayette-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'etowah-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'escambia-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'elmore-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'dekalb-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'dallas-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'dale-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'cullman-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'crenshaw-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'covington-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'coosa-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'conecuh-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'colbert-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'coffee-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'cleburne-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'clay-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'clarke-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'choctaw-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'chilton-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'cherokee-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'chambers-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'calhoun-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'butler-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'bullock-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'blount-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'bibb-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'barbour-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'baldwin-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-dd-agency' AND county_id = 'autauga-al';
UPDATE state_resource_agencies SET state_id = 'alabama', agency_type = 'dd_office', name = 'Alabama Department of Mental Health', counties_served = 'autauga-al,baldwin-al,barbour-al,bibb-al,blount-al,bullock-al,butler-al,calhoun-al,chambers-al,cherokee-al,chilton-al,choctaw-al,clarke-al,clay-al,cleburne-al,coffee-al,colbert-al,conecuh-al,coosa-al,covington-al,crenshaw-al,cullman-al,dale-al,dallas-al,dekalb-al,elmore-al,escambia-al,etowah-al,fayette-al,franklin-al,geneva-al,greene-al,hale-al,henry-al,houston-al,jackson-al,jefferson-al,lamar-al,lauderdale-al,lawrence-al,lee-al,limestone-al,lowndes-al,macon-al,madison-al,marengo-al,marion-al,marshall-al,mobile-al,monroe-al,montgomery-al,morgan-al,perry-al,pickens-al,pike-al,randolph-al,russell-al,st-clair-al,shelby-al,sumter-al,talladega-al,tallapoosa-al,tuscaloosa-al,walker-al,washington-al,wilcox-al,winston-al', catchment_boundaries = 'Statewide coverage for all counties in Alabama.', website = 'https://mh.alabama.gov', intake_phone = '(800) 555-0100', early_intervention_contact = '(800) 555-0100', agency_intake_contact = '(800) 555-0100', eligibility_info_page = 'https://mh.alabama.gov/developmental-disabilities/', services_page = 'https://mh.alabama.gov', appeals_info = 'Waiver decisions can be appealed within 30 days of notice.', frc_relationship = NULL, office_locations = 'Alabama State Capitol Office', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://mh.alabama.gov', source_url = 'https://mh.alabama.gov', source_type = 'official', data_origin = 'curated_seed', verification_status = 'source_listed', last_scraped_at = '2026-06-13T02:29:27.533Z', confidence_score = 5, evidence_level = NULL WHERE id = 'al-dd-agency';

COMMIT;
