-- Rollback Script for State: Alabama | Phase: early_intervention
-- Generated At: 2026-06-14T15:49:23.639Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'winston-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'wilcox-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'washington-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'walker-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'tuscaloosa-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'tallapoosa-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'talladega-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'sumter-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'st-clair-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'shelby-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'russell-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'randolph-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'pike-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'pickens-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'perry-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'morgan-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'montgomery-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'monroe-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'mobile-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'marshall-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'marion-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'marengo-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'madison-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'macon-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'lowndes-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'limestone-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'lee-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'lawrence-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'lauderdale-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'lamar-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'jefferson-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'jackson-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'houston-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'henry-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'hale-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'greene-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'geneva-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'franklin-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'fayette-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'etowah-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'escambia-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'elmore-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'dekalb-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'dallas-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'dale-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'cullman-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'crenshaw-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'covington-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'coosa-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'conecuh-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'colbert-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'coffee-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'cleburne-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'clay-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'clarke-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'choctaw-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'chilton-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'cherokee-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'chambers-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'calhoun-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'butler-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'bullock-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'blount-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'bibb-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'barbour-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'baldwin-al';
DELETE FROM regional_center_counties WHERE regional_center_id = 'al-ei-agency' AND county_id = 'autauga-al';
DELETE FROM state_resource_agencies WHERE id = 'al-ei-agency';

COMMIT;
