-- Rollback Script for State: Connecticut | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:51:00.135Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'windham-ct', program_id = 'ct-medicaid', office_name = 'Windham County storefront office', address = '', phone = '(855) 626-6632', email = '', website = 'https://portal.ct.gov/dss', source_url = 'https://portal.ct.gov/dss', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-windham-ct-medicaid';
UPDATE county_offices SET county_id = 'tolland-ct', program_id = 'ct-medicaid', office_name = 'Tolland County storefront office', address = '', phone = '(855) 626-6632', email = '', website = 'https://portal.ct.gov/dss', source_url = 'https://portal.ct.gov/dss', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-tolland-ct-medicaid';
UPDATE county_offices SET county_id = 'new-london-ct', program_id = 'ct-medicaid', office_name = 'New London County storefront office', address = '', phone = '(855) 626-6632', email = '', website = 'https://portal.ct.gov/dss', source_url = 'https://portal.ct.gov/dss', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-new-london-ct-medicaid';
UPDATE county_offices SET county_id = 'new-haven-ct', program_id = 'ct-medicaid', office_name = 'New Haven County storefront office', address = '', phone = '(855) 626-6632', email = '', website = 'https://portal.ct.gov/dss', source_url = 'https://portal.ct.gov/dss', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-new-haven-ct-medicaid';
UPDATE county_offices SET county_id = 'middlesex-ct', program_id = 'ct-medicaid', office_name = 'Middlesex County storefront office', address = '', phone = '(855) 626-6632', email = '', website = 'https://portal.ct.gov/dss', source_url = 'https://portal.ct.gov/dss', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-middlesex-ct-medicaid';
UPDATE county_offices SET county_id = 'litchfield-ct', program_id = 'ct-medicaid', office_name = 'Litchfield County storefront office', address = '', phone = '(855) 626-6632', email = '', website = 'https://portal.ct.gov/dss', source_url = 'https://portal.ct.gov/dss', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-litchfield-ct-medicaid';
UPDATE county_offices SET county_id = 'hartford-ct', program_id = 'ct-medicaid', office_name = 'Hartford County storefront office', address = '', phone = '(855) 626-6632', email = '', website = 'https://portal.ct.gov/dss', source_url = 'https://portal.ct.gov/dss', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-hartford-ct-medicaid';
UPDATE county_offices SET county_id = 'fairfield-ct', program_id = 'ct-medicaid', office_name = 'Fairfield County storefront office', address = '', phone = '(855) 626-6632', email = '', website = 'https://portal.ct.gov/dss', source_url = 'https://portal.ct.gov/dss', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-fairfield-ct-medicaid';

COMMIT;
