-- Rollback Script for State: Connecticut | Phase: district_replacements
-- Generated At: 2026-06-15T21:51:01.792Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'windham-ct', name = 'Windham County School District', spec_ed_contact_phone = '(860) 713-6910', spec_ed_contact_email = '', website = 'https://portal.ct.gov/sde/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://portal.ct.gov/sde', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-windham-ct';
UPDATE school_districts SET county_id = 'tolland-ct', name = 'Tolland County School District', spec_ed_contact_phone = '(860) 713-6910', spec_ed_contact_email = '', website = 'https://portal.ct.gov/sde/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://portal.ct.gov/sde', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-tolland-ct';
UPDATE school_districts SET county_id = 'new-london-ct', name = 'New London County School District', spec_ed_contact_phone = '(860) 713-6910', spec_ed_contact_email = '', website = 'https://portal.ct.gov/sde/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://portal.ct.gov/sde', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-new-london-ct';
UPDATE school_districts SET county_id = 'new-haven-ct', name = 'New Haven County School District', spec_ed_contact_phone = '(860) 713-6910', spec_ed_contact_email = '', website = 'https://portal.ct.gov/sde/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://portal.ct.gov/sde', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-new-haven-ct';
UPDATE school_districts SET county_id = 'middlesex-ct', name = 'Middlesex County School District', spec_ed_contact_phone = '(860) 713-6910', spec_ed_contact_email = '', website = 'https://portal.ct.gov/sde/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://portal.ct.gov/sde', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-middlesex-ct';
UPDATE school_districts SET county_id = 'litchfield-ct', name = 'Litchfield County School District', spec_ed_contact_phone = '(860) 713-6910', spec_ed_contact_email = '', website = 'https://portal.ct.gov/sde/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://portal.ct.gov/sde', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-litchfield-ct';

COMMIT;
