-- Rollback Script for State: Connecticut | Phase: district_replacements
-- Generated At: 2026-06-14T15:40:52.762Z

BEGIN TRANSACTION;

DELETE FROM school_districts WHERE id = 'sd-windham-ct';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-windham-ct-fallback', 'windham-ct', 'Windham County School District Special Education', '(800) 555-0199', 'sped-fallback@windham-ct.gov', 'https://www.connecticut-education.gov', 5000, 12, 60, 20, 'https://www.connecticut-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.539Z', 3, NULL);
UPDATE school_districts SET id = 'sd-windham-ct-fallback' WHERE id = 'sd-windham-ct';
DELETE FROM school_districts WHERE id = 'sd-tolland-ct';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-tolland-ct-fallback', 'tolland-ct', 'Tolland County School District Special Education', '(800) 555-0199', 'sped-fallback@tolland-ct.gov', 'https://www.connecticut-education.gov', 5000, 12, 60, 20, 'https://www.connecticut-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.539Z', 3, NULL);
UPDATE school_districts SET id = 'sd-tolland-ct-fallback' WHERE id = 'sd-tolland-ct';
DELETE FROM school_districts WHERE id = 'sd-new-london-ct';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-new-london-ct-fallback', 'new-london-ct', 'New London County School District Special Education', '(800) 555-0199', 'sped-fallback@new-london-ct.gov', 'https://www.connecticut-education.gov', 5000, 12, 60, 20, 'https://www.connecticut-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.539Z', 3, NULL);
UPDATE school_districts SET id = 'sd-new-london-ct-fallback' WHERE id = 'sd-new-london-ct';
DELETE FROM school_districts WHERE id = 'sd-new-haven-ct';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-new-haven-ct-fallback', 'new-haven-ct', 'New Haven County School District Special Education', '(800) 555-0199', 'sped-fallback@new-haven-ct.gov', 'https://www.connecticut-education.gov', 5000, 12, 60, 20, 'https://www.connecticut-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.539Z', 3, NULL);
UPDATE school_districts SET id = 'sd-new-haven-ct-fallback' WHERE id = 'sd-new-haven-ct';
DELETE FROM school_districts WHERE id = 'sd-middlesex-ct';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-middlesex-ct-fallback', 'middlesex-ct', 'Middlesex County School District Special Education', '(800) 555-0199', 'sped-fallback@middlesex-ct.gov', 'https://www.connecticut-education.gov', 5000, 12, 60, 20, 'https://www.connecticut-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.539Z', 3, NULL);
UPDATE school_districts SET id = 'sd-middlesex-ct-fallback' WHERE id = 'sd-middlesex-ct';
DELETE FROM school_districts WHERE id = 'sd-litchfield-ct';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-litchfield-ct-fallback', 'litchfield-ct', 'Litchfield County School District Special Education', '(800) 555-0199', 'sped-fallback@litchfield-ct.gov', 'https://www.connecticut-education.gov', 5000, 12, 60, 20, 'https://www.connecticut-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.539Z', 3, NULL);
UPDATE school_districts SET id = 'sd-litchfield-ct-fallback' WHERE id = 'sd-litchfield-ct';

COMMIT;
