-- Rollback Script for State: Hawaii | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:51:47.142Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'maui-hi', program_id = 'hi-medicaid', office_name = 'Maui County storefront office', address = '', phone = '(800) 316-8005', email = '', website = 'https://medquest.hawaii.gov/', source_url = 'https://medquest.hawaii.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-maui-hi-medicaid';
UPDATE county_offices SET county_id = 'kauai-hi', program_id = 'hi-medicaid', office_name = 'Kauai County storefront office', address = '', phone = '(800) 316-8005', email = '', website = 'https://medquest.hawaii.gov/', source_url = 'https://medquest.hawaii.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-kauai-hi-medicaid';
UPDATE county_offices SET county_id = 'kalawao-hi', program_id = 'hi-medicaid', office_name = 'Kalawao County storefront office', address = '', phone = '(800) 316-8005', email = '', website = 'https://medquest.hawaii.gov/', source_url = 'https://medquest.hawaii.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-kalawao-hi-medicaid';
UPDATE county_offices SET county_id = 'honolulu-hi', program_id = 'hi-medicaid', office_name = 'Honolulu County storefront office', address = '', phone = '(800) 316-8005', email = '', website = 'https://medquest.hawaii.gov/', source_url = 'https://medquest.hawaii.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-honolulu-hi-medicaid';
UPDATE county_offices SET county_id = 'hawai-i-hi', program_id = 'hi-medicaid', office_name = 'Hawai''i County storefront office', address = '', phone = '(800) 316-8005', email = '', website = 'https://medquest.hawaii.gov/', source_url = 'https://medquest.hawaii.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-hawai-i-hi-medicaid';

COMMIT;
