-- Rollback Script for State: Hawaii | Phase: district_replacements
-- Generated At: 2026-06-15T21:51:48.771Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'maui-hi', name = 'Maui County School District', spec_ed_contact_phone = '(808) 305-9806', spec_ed_contact_email = '', website = 'https://www.hawaiipublicschools.org/TeachingAndLearning/SpecializedPrograms/SpecialEducation/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.hawaiipublicschools.org/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-maui-hi';
UPDATE school_districts SET county_id = 'kauai-hi', name = 'Kauai County School District', spec_ed_contact_phone = '(808) 305-9806', spec_ed_contact_email = '', website = 'https://www.hawaiipublicschools.org/TeachingAndLearning/SpecializedPrograms/SpecialEducation/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.hawaiipublicschools.org/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-kauai-hi';
UPDATE school_districts SET county_id = 'kalawao-hi', name = 'Kalawao County School District', spec_ed_contact_phone = '(808) 305-9806', spec_ed_contact_email = '', website = 'https://www.hawaiipublicschools.org/TeachingAndLearning/SpecializedPrograms/SpecialEducation/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.hawaiipublicschools.org/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-kalawao-hi';

COMMIT;
