-- Rollback Script for State: Nevada | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:54:28.925Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'white-pine-nv', program_id = 'nv-medicaid', office_name = 'White Pine County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-white-pine-nv-medicaid';
UPDATE county_offices SET county_id = 'washoe-nv', program_id = 'nv-medicaid', office_name = 'Washoe County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-washoe-nv-medicaid';
UPDATE county_offices SET county_id = 'storey-nv', program_id = 'nv-medicaid', office_name = 'Storey County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-storey-nv-medicaid';
UPDATE county_offices SET county_id = 'pershing-nv', program_id = 'nv-medicaid', office_name = 'Pershing County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-pershing-nv-medicaid';
UPDATE county_offices SET county_id = 'nye-nv', program_id = 'nv-medicaid', office_name = 'Nye County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-nye-nv-medicaid';
UPDATE county_offices SET county_id = 'mineral-nv', program_id = 'nv-medicaid', office_name = 'Mineral County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-mineral-nv-medicaid';
UPDATE county_offices SET county_id = 'lyon-nv', program_id = 'nv-medicaid', office_name = 'Lyon County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lyon-nv-medicaid';
UPDATE county_offices SET county_id = 'lincoln-nv', program_id = 'nv-medicaid', office_name = 'Lincoln County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lincoln-nv-medicaid';
UPDATE county_offices SET county_id = 'lander-nv', program_id = 'nv-medicaid', office_name = 'Lander County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lander-nv-medicaid';
UPDATE county_offices SET county_id = 'humboldt-nv', program_id = 'nv-medicaid', office_name = 'Humboldt County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-humboldt-nv-medicaid';
UPDATE county_offices SET county_id = 'eureka-nv', program_id = 'nv-medicaid', office_name = 'Eureka County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-eureka-nv-medicaid';
UPDATE county_offices SET county_id = 'esmeralda-nv', program_id = 'nv-medicaid', office_name = 'Esmeralda County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-esmeralda-nv-medicaid';
UPDATE county_offices SET county_id = 'elko-nv', program_id = 'nv-medicaid', office_name = 'Elko County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-elko-nv-medicaid';
UPDATE county_offices SET county_id = 'douglas-nv', program_id = 'nv-medicaid', office_name = 'Douglas County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-douglas-nv-medicaid';
UPDATE county_offices SET county_id = 'clark-nv', program_id = 'nv-medicaid', office_name = 'Clark County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-clark-nv-medicaid';
UPDATE county_offices SET county_id = 'churchill-nv', program_id = 'nv-medicaid', office_name = 'Churchill County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-churchill-nv-medicaid';
UPDATE county_offices SET county_id = 'carson-city-nv', program_id = 'nv-medicaid', office_name = 'Carson City County storefront office', address = '', phone = '(800) 992-0900', email = '', website = 'https://dwss.nv.gov/', source_url = 'https://dwss.nv.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-carson-city-nv-medicaid';

COMMIT;
