-- Rollback Script for State: Nevada | Phase: district_replacements
-- Generated At: 2026-06-15T21:54:30.572Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'white-pine-nv', name = 'White Pine County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-white-pine-nv';
UPDATE school_districts SET county_id = 'storey-nv', name = 'Storey County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-storey-nv';
UPDATE school_districts SET county_id = 'pershing-nv', name = 'Pershing County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-pershing-nv';
UPDATE school_districts SET county_id = 'nye-nv', name = 'Nye County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-nye-nv';
UPDATE school_districts SET county_id = 'mineral-nv', name = 'Mineral County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-mineral-nv';
UPDATE school_districts SET county_id = 'lyon-nv', name = 'Lyon County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-lyon-nv';
UPDATE school_districts SET county_id = 'lincoln-nv', name = 'Lincoln County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-lincoln-nv';
UPDATE school_districts SET county_id = 'lander-nv', name = 'Lander County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-lander-nv';
UPDATE school_districts SET county_id = 'humboldt-nv', name = 'Humboldt County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-humboldt-nv';
UPDATE school_districts SET county_id = 'eureka-nv', name = 'Eureka County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-eureka-nv';
UPDATE school_districts SET county_id = 'esmeralda-nv', name = 'Esmeralda County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-esmeralda-nv';
UPDATE school_districts SET county_id = 'elko-nv', name = 'Elko County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-elko-nv';
UPDATE school_districts SET county_id = 'douglas-nv', name = 'Douglas County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-douglas-nv';
UPDATE school_districts SET county_id = 'churchill-nv', name = 'Churchill County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-churchill-nv';
UPDATE school_districts SET county_id = 'carson-city-nv', name = 'Carson City County School District', spec_ed_contact_phone = '(775) 687-9171', spec_ed_contact_email = '', website = 'https://doe.nv.gov/Special_Education/', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://doe.nv.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-carson-city-nv';

COMMIT;
