-- Rollback Script for State: Nevada | Phase: district_replacements
-- Generated At: 2026-06-14T15:42:26.724Z

BEGIN TRANSACTION;

DELETE FROM school_districts WHERE id = 'sd-white-pine-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-white-pine-nv-fallback', 'white-pine-nv', 'White Pine County School District Special Education', '(800) 555-0199', 'sped-fallback@white-pine-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-white-pine-nv-fallback' WHERE id = 'sd-white-pine-nv';
DELETE FROM school_districts WHERE id = 'sd-storey-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-storey-nv-fallback', 'storey-nv', 'Storey County School District Special Education', '(800) 555-0199', 'sped-fallback@storey-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-storey-nv-fallback' WHERE id = 'sd-storey-nv';
DELETE FROM school_districts WHERE id = 'sd-pershing-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-pershing-nv-fallback', 'pershing-nv', 'Pershing County School District Special Education', '(800) 555-0199', 'sped-fallback@pershing-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-pershing-nv-fallback' WHERE id = 'sd-pershing-nv';
DELETE FROM school_districts WHERE id = 'sd-nye-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-nye-nv-fallback', 'nye-nv', 'Nye County School District Special Education', '(800) 555-0199', 'sped-fallback@nye-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-nye-nv-fallback' WHERE id = 'sd-nye-nv';
DELETE FROM school_districts WHERE id = 'sd-mineral-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-mineral-nv-fallback', 'mineral-nv', 'Mineral County School District Special Education', '(800) 555-0199', 'sped-fallback@mineral-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-mineral-nv-fallback' WHERE id = 'sd-mineral-nv';
DELETE FROM school_districts WHERE id = 'sd-lyon-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-lyon-nv-fallback', 'lyon-nv', 'Lyon County School District Special Education', '(800) 555-0199', 'sped-fallback@lyon-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-lyon-nv-fallback' WHERE id = 'sd-lyon-nv';
DELETE FROM school_districts WHERE id = 'sd-lincoln-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-lincoln-nv-fallback', 'lincoln-nv', 'Lincoln County School District Special Education', '(800) 555-0199', 'sped-fallback@lincoln-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-lincoln-nv-fallback' WHERE id = 'sd-lincoln-nv';
DELETE FROM school_districts WHERE id = 'sd-lander-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-lander-nv-fallback', 'lander-nv', 'Lander County School District Special Education', '(800) 555-0199', 'sped-fallback@lander-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-lander-nv-fallback' WHERE id = 'sd-lander-nv';
DELETE FROM school_districts WHERE id = 'sd-humboldt-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-humboldt-nv-fallback', 'humboldt-nv', 'Humboldt County School District Special Education', '(800) 555-0199', 'sped-fallback@humboldt-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-humboldt-nv-fallback' WHERE id = 'sd-humboldt-nv';
DELETE FROM school_districts WHERE id = 'sd-eureka-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-eureka-nv-fallback', 'eureka-nv', 'Eureka County School District Special Education', '(800) 555-0199', 'sped-fallback@eureka-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-eureka-nv-fallback' WHERE id = 'sd-eureka-nv';
DELETE FROM school_districts WHERE id = 'sd-esmeralda-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-esmeralda-nv-fallback', 'esmeralda-nv', 'Esmeralda County School District Special Education', '(800) 555-0199', 'sped-fallback@esmeralda-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-esmeralda-nv-fallback' WHERE id = 'sd-esmeralda-nv';
DELETE FROM school_districts WHERE id = 'sd-elko-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-elko-nv-fallback', 'elko-nv', 'Elko County School District Special Education', '(800) 555-0199', 'sped-fallback@elko-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-elko-nv-fallback' WHERE id = 'sd-elko-nv';
DELETE FROM school_districts WHERE id = 'sd-douglas-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-douglas-nv-fallback', 'douglas-nv', 'Douglas County School District Special Education', '(800) 555-0199', 'sped-fallback@douglas-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-douglas-nv-fallback' WHERE id = 'sd-douglas-nv';
DELETE FROM school_districts WHERE id = 'sd-churchill-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-churchill-nv-fallback', 'churchill-nv', 'Churchill County School District Special Education', '(800) 555-0199', 'sped-fallback@churchill-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-churchill-nv-fallback' WHERE id = 'sd-churchill-nv';
DELETE FROM school_districts WHERE id = 'sd-carson-city-nv';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-carson-city-nv-fallback', 'carson-city-nv', 'Carson City County School District Special Education', '(800) 555-0199', 'sped-fallback@carson-city-nv.gov', 'https://www.nevada-education.gov', 5000, 12, 60, 20, 'https://www.nevada-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-carson-city-nv-fallback' WHERE id = 'sd-carson-city-nv';

COMMIT;
