-- Rollback Script for State: New Hampshire | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:54:51.659Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'sullivan-nh', program_id = 'nh-medicaid', office_name = 'Sullivan County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-sullivan-nh-medicaid';
UPDATE county_offices SET county_id = 'strafford-nh', program_id = 'nh-medicaid', office_name = 'Strafford County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-strafford-nh-medicaid';
UPDATE county_offices SET county_id = 'rockingham-nh', program_id = 'nh-medicaid', office_name = 'Rockingham County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-rockingham-nh-medicaid';
UPDATE county_offices SET county_id = 'merrimack-nh', program_id = 'nh-medicaid', office_name = 'Merrimack County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-merrimack-nh-medicaid';
UPDATE county_offices SET county_id = 'hillsborough-nh', program_id = 'nh-medicaid', office_name = 'Hillsborough County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-hillsborough-nh-medicaid';
UPDATE county_offices SET county_id = 'grafton-nh', program_id = 'nh-medicaid', office_name = 'Grafton County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-grafton-nh-medicaid';
UPDATE county_offices SET county_id = 'co-s-nh', program_id = 'nh-medicaid', office_name = 'Coös County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-co-s-nh-medicaid';
UPDATE county_offices SET county_id = 'cheshire-nh', program_id = 'nh-medicaid', office_name = 'Cheshire County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-cheshire-nh-medicaid';
UPDATE county_offices SET county_id = 'carroll-nh', program_id = 'nh-medicaid', office_name = 'Carroll County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-carroll-nh-medicaid';
UPDATE county_offices SET county_id = 'belknap-nh', program_id = 'nh-medicaid', office_name = 'Belknap County storefront office', address = '', phone = '(844) 275-3447', email = '', website = 'https://www.dhhs.nh.gov/', source_url = 'https://www.dhhs.nh.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-belknap-nh-medicaid';

COMMIT;
