-- Rollback Script for State: New Hampshire | Phase: district_replacements
-- Generated At: 2026-06-14T15:41:08.090Z

BEGIN TRANSACTION;

DELETE FROM school_districts WHERE id = 'sd-sullivan-nh';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-sullivan-nh-fallback', 'sullivan-nh', 'Sullivan County School District Special Education', '(800) 555-0199', 'sped-fallback@sullivan-nh.gov', 'https://www.new-hampshire-education.gov', 5000, 12, 60, 20, 'https://www.new-hampshire-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-sullivan-nh-fallback' WHERE id = 'sd-sullivan-nh';
DELETE FROM school_districts WHERE id = 'sd-strafford-nh';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-strafford-nh-fallback', 'strafford-nh', 'Strafford County School District Special Education', '(800) 555-0199', 'sped-fallback@strafford-nh.gov', 'https://www.new-hampshire-education.gov', 5000, 12, 60, 20, 'https://www.new-hampshire-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-strafford-nh-fallback' WHERE id = 'sd-strafford-nh';
DELETE FROM school_districts WHERE id = 'sd-merrimack-nh';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-merrimack-nh-fallback', 'merrimack-nh', 'Merrimack County School District Special Education', '(800) 555-0199', 'sped-fallback@merrimack-nh.gov', 'https://www.new-hampshire-education.gov', 5000, 12, 60, 20, 'https://www.new-hampshire-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-merrimack-nh-fallback' WHERE id = 'sd-merrimack-nh';
DELETE FROM school_districts WHERE id = 'sd-grafton-nh';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-grafton-nh-fallback', 'grafton-nh', 'Grafton County School District Special Education', '(800) 555-0199', 'sped-fallback@grafton-nh.gov', 'https://www.new-hampshire-education.gov', 5000, 12, 60, 20, 'https://www.new-hampshire-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-grafton-nh-fallback' WHERE id = 'sd-grafton-nh';
DELETE FROM school_districts WHERE id = 'sd-co-s-nh';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-co-s-nh-fallback', 'co-s-nh', 'Coös County School District Special Education', '(800) 555-0199', 'sped-fallback@co-s-nh.gov', 'https://www.new-hampshire-education.gov', 5000, 12, 60, 20, 'https://www.new-hampshire-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-co-s-nh-fallback' WHERE id = 'sd-co-s-nh';
DELETE FROM school_districts WHERE id = 'sd-cheshire-nh';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-cheshire-nh-fallback', 'cheshire-nh', 'Cheshire County School District Special Education', '(800) 555-0199', 'sped-fallback@cheshire-nh.gov', 'https://www.new-hampshire-education.gov', 5000, 12, 60, 20, 'https://www.new-hampshire-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-cheshire-nh-fallback' WHERE id = 'sd-cheshire-nh';
DELETE FROM school_districts WHERE id = 'sd-carroll-nh';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-carroll-nh-fallback', 'carroll-nh', 'Carroll County School District Special Education', '(800) 555-0199', 'sped-fallback@carroll-nh.gov', 'https://www.new-hampshire-education.gov', 5000, 12, 60, 20, 'https://www.new-hampshire-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-carroll-nh-fallback' WHERE id = 'sd-carroll-nh';
DELETE FROM school_districts WHERE id = 'sd-belknap-nh';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-belknap-nh-fallback', 'belknap-nh', 'Belknap County School District Special Education', '(800) 555-0199', 'sped-fallback@belknap-nh.gov', 'https://www.new-hampshire-education.gov', 5000, 12, 60, 20, 'https://www.new-hampshire-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.562Z', 3, NULL);
UPDATE school_districts SET id = 'sd-belknap-nh-fallback' WHERE id = 'sd-belknap-nh';

COMMIT;
