-- Rollback Script for State: New Hampshire | Phase: district_replacements
-- Generated At: 2026-06-15T21:54:53.326Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'sullivan-nh', name = 'Sullivan County School District', spec_ed_contact_phone = '(603) 271-3741', spec_ed_contact_email = '', website = 'https://www.education.nh.gov/who-we-are/division-of-learner-support/bureau-of-special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.nh.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-sullivan-nh';
UPDATE school_districts SET county_id = 'strafford-nh', name = 'Strafford County School District', spec_ed_contact_phone = '(603) 271-3741', spec_ed_contact_email = '', website = 'https://www.education.nh.gov/who-we-are/division-of-learner-support/bureau-of-special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.nh.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-strafford-nh';
UPDATE school_districts SET county_id = 'merrimack-nh', name = 'Merrimack County School District', spec_ed_contact_phone = '(603) 271-3741', spec_ed_contact_email = '', website = 'https://www.education.nh.gov/who-we-are/division-of-learner-support/bureau-of-special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.nh.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-merrimack-nh';
UPDATE school_districts SET county_id = 'grafton-nh', name = 'Grafton County School District', spec_ed_contact_phone = '(603) 271-3741', spec_ed_contact_email = '', website = 'https://www.education.nh.gov/who-we-are/division-of-learner-support/bureau-of-special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.nh.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-grafton-nh';
UPDATE school_districts SET county_id = 'co-s-nh', name = 'Coös County School District', spec_ed_contact_phone = '(603) 271-3741', spec_ed_contact_email = '', website = 'https://www.education.nh.gov/who-we-are/division-of-learner-support/bureau-of-special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.nh.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-co-s-nh';
UPDATE school_districts SET county_id = 'cheshire-nh', name = 'Cheshire County School District', spec_ed_contact_phone = '(603) 271-3741', spec_ed_contact_email = '', website = 'https://www.education.nh.gov/who-we-are/division-of-learner-support/bureau-of-special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.nh.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-cheshire-nh';
UPDATE school_districts SET county_id = 'carroll-nh', name = 'Carroll County School District', spec_ed_contact_phone = '(603) 271-3741', spec_ed_contact_email = '', website = 'https://www.education.nh.gov/who-we-are/division-of-learner-support/bureau-of-special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.nh.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-carroll-nh';
UPDATE school_districts SET county_id = 'belknap-nh', name = 'Belknap County School District', spec_ed_contact_phone = '(603) 271-3741', spec_ed_contact_email = '', website = 'https://www.education.nh.gov/who-we-are/division-of-learner-support/bureau-of-special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.nh.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-belknap-nh';

COMMIT;
