-- Rollback Script for State: Colorado | Phase: dd_idd
-- Generated At: 2026-06-14T15:48:24.254Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'yuma-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'weld-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'washington-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'teller-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'summit-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'sedgwick-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'san-miguel-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'san-juan-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'saguache-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'routt-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'rio-grande-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'rio-blanco-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'pueblo-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'prowers-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'pitkin-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'phillips-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'park-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'ouray-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'otero-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'morgan-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'montrose-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'montezuma-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'moffat-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'mineral-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'mesa-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'logan-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'lincoln-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'las-animas-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'larimer-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'lake-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'la-plata-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'kit-carson-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'kiowa-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'jefferson-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'jackson-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'huerfano-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'hinsdale-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'gunnison-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'grand-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'gilpin-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'garfield-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'fremont-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'elbert-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'el-paso-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'eagle-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'douglas-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'dolores-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'delta-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'custer-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'crowley-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'costilla-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'conejos-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'clear-creek-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'city-and-county-of-denver-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'city-and-county-of-broomfield-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'cheyenne-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'chaffee-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'boulder-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'bent-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'baca-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'archuleta-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'arapahoe-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'alamosa-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-dd-agency' AND county_id = 'adams-co';
UPDATE state_resource_agencies SET state_id = 'colorado', agency_type = 'dd_office', name = 'Colorado Division for Developmental Disabilities', counties_served = 'adams-co,alamosa-co,arapahoe-co,archuleta-co,baca-co,bent-co,boulder-co,city-and-county-of-broomfield-co,chaffee-co,cheyenne-co,clear-creek-co,conejos-co,costilla-co,crowley-co,custer-co,delta-co,city-and-county-of-denver-co,dolores-co,douglas-co,eagle-co,el-paso-co,elbert-co,fremont-co,garfield-co,gilpin-co,grand-co,gunnison-co,hinsdale-co,huerfano-co,jackson-co,jefferson-co,kiowa-co,kit-carson-co,la-plata-co,lake-co,larimer-co,las-animas-co,lincoln-co,logan-co,mesa-co,mineral-co,moffat-co,montezuma-co,montrose-co,morgan-co,otero-co,ouray-co,park-co,phillips-co,pitkin-co,prowers-co,pueblo-co,rio-blanco-co,rio-grande-co,routt-co,saguache-co,san-juan-co,san-miguel-co,sedgwick-co,summit-co,teller-co,washington-co,weld-co,yuma-co', catchment_boundaries = 'Statewide coverage for all counties in Colorado.', website = 'https://hcpf.colorado.gov/developmental-disabilities', intake_phone = '(800) 555-0100', early_intervention_contact = '(800) 555-0100', agency_intake_contact = '(800) 555-0100', eligibility_info_page = 'https://hcpf.colorado.gov/dd-eligibility', services_page = 'https://hcpf.colorado.gov/developmental-disabilities', appeals_info = 'Waiver decisions can be appealed within 30 days of notice.', frc_relationship = NULL, office_locations = 'Colorado State Capitol Office', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://hcpf.colorado.gov/developmental-disabilities', source_url = 'https://hcpf.colorado.gov/developmental-disabilities', source_type = 'official', data_origin = 'curated_seed', verification_status = 'source_listed', last_scraped_at = '2026-06-13T02:29:27.538Z', confidence_score = 5, evidence_level = NULL WHERE id = 'co-dd-agency';

COMMIT;
