-- Rollback Script for State: Colorado | Phase: early_intervention
-- Generated At: 2026-06-15T19:56:08.973Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'yuma-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'weld-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'washington-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'teller-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'summit-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'sedgwick-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'san-miguel-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'san-juan-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'saguache-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'routt-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'rio-grande-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'rio-blanco-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'pueblo-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'prowers-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'pitkin-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'phillips-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'park-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'ouray-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'otero-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'morgan-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'montrose-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'montezuma-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'moffat-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'mineral-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'mesa-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'logan-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'lincoln-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'las-animas-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'larimer-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'lake-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'la-plata-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'kit-carson-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'kiowa-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'jefferson-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'jackson-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'huerfano-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'hinsdale-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'gunnison-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'grand-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'gilpin-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'garfield-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'fremont-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'elbert-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'el-paso-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'eagle-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'douglas-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'dolores-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'delta-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'custer-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'crowley-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'costilla-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'conejos-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'clear-creek-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'city-and-county-of-denver-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'city-and-county-of-broomfield-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'cheyenne-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'chaffee-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'boulder-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'bent-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'baca-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'archuleta-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'arapahoe-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'alamosa-co';
DELETE FROM regional_center_counties WHERE regional_center_id = 'co-ei-agency' AND county_id = 'adams-co';
UPDATE state_resource_agencies SET state_id = 'colorado', agency_type = 'early_intervention', name = 'Colorado Early Intervention State Office', counties_served = 'statewide', catchment_boundaries = 'statewide', website = 'https://dhhs.colorado.gov/earlystart', intake_phone = '', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://dhhs.colorado.gov/earlystart', source_url = 'https://dhhs.colorado.gov/earlystart', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'co-ei-agency';

COMMIT;
