import Database from 'better-sqlite3';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '../..');
const dbPath = path.join(repoRoot, 'ca_disability_navigator.db');
const frontendDbPath = path.join(repoRoot, 'frontend', 'ca_disability_navigator.db');

const db = new Database(dbPath);
const now = new Date().toISOString();
const today = now.slice(0, 10);

const records = [
  {
    id: 'ny-clinic-cohen-childrens',
    name: "Cohen Children's Medical Center",
    county_id: 'nassau-ny',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(718) 470-3000',
    email: null,
    address: '269-01 76th Avenue, New Hyde Park, NY 11040',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://childrenshospital.northwell.edu',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'childrenshospital.northwell.edu',
    next_step_type: 'call',
    next_step_label: "Contact Cohen Children's Medical Center",
    next_step_url: null,
    next_step_phone: '(718) 470-3000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'hospital_or_university_listing',
    data_quality_notes: "Main hospital phone and street address come from the official Cohen Children's Medical Center homepage.",
  },
  {
    id: 'va-clinic-chor-fredericksburg',
    name: "Children's Hospital of Richmond at VCU Fredericksburg Multispecialty Center",
    county_id: 'spotsylvania-va',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(804) 828-2467',
    email: null,
    address: '10528 Spotsylvania Avenue, Fredericksburg, VA 22408',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.chrichmond.org',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.89,
    source_name: 'chrichmond.org',
    next_step_type: 'call',
    next_step_label: 'Request an appointment',
    next_step_url: 'https://www.chrichmond.org/patient-and-family-resources/make-an-appointment/',
    next_step_phone: '(804) 828-2467',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'hospital_or_university_listing',
    data_quality_notes: 'Fredericksburg Multispecialty Center street address comes from the official CHoR homepage locations menu. Appointment phone comes from the official request-an-appointment callout on the same domain.',
  },
  {
    id: 'la-clinic-manning-childrens',
    name: "Children's Hospital New Orleans",
    county_id: 'orleans-parish-la',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(504) 899-9511',
    email: null,
    address: '200 Henry Clay Ave., New Orleans, LA 70118',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.manningchildrens.org/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'manningchildrens.org',
    next_step_type: 'call',
    next_step_label: 'Appointment Request',
    next_step_url: 'https://www.manningchildrens.org/patients-visitors/appointment-request/',
    next_step_phone: '(504) 899-9511',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'hospital_or_university_listing',
    data_quality_notes: "Main hospital street address and phone come from the official Children's Hospital New Orleans homepage footer. Appointment request URL comes from the official appointments page link on the same domain.",
  },
  {
    id: 'la-clinic-ochsner-childrens',
    name: 'Ochsner Hospital for Children',
    county_id: 'orleans-parish-la',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(866) 624-7637',
    email: null,
    address: '1514 Jefferson Highway, New Orleans, LA 70121',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.ochsner.org',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.89,
    source_name: 'ochsner.org',
    next_step_type: 'call',
    next_step_label: 'Make an appointment',
    next_step_url: 'https://www.ochsner.org',
    next_step_phone: '(866) 624-7637',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'hospital_or_university_listing',
    data_quality_notes: 'Street address comes from the official Ochsner homepage schema block. Appointment phone comes from the official Ochsner homepage call-to-schedule footer block. This row follows the checked-in Louisiana source target for Ochsner Hospital for Children.',
  },
  {
    id: 'oh-clinic-nch-autism',
    name: "Nationwide Children's Hospital Center for Autism Spectrum Disorders",
    county_id: 'franklin-oh',
    categories: 'developmental_clinic,autism_clinic,diagnostic_center',
    phone: '(614) 355-7570',
    email: 'AutismResourceClinicianTeam@NationwideChildrens.org',
    address: '700 Childrens Drive, Columbus, OH 43205',
    service_tags: 'therapy',
    serving_tags: 'autism',
    source_url: 'https://www.nationwidechildrens.org/specialties/center-for-autism-spectrum-disorders',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.86,
    source_name: 'nationwidechildrens.org',
    next_step_type: 'call',
    next_step_label: 'Schedule an Appointment',
    next_step_url: 'https://www.nationwidechildrens.org/schedule-an-appointment?spec=cc2a4833-a750-4f33-9038-a6fc87a7da59',
    next_step_phone: '(614) 355-7570',
    next_step_email: 'AutismResourceClinicianTeam@NationwideChildrens.org',
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: 1,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'Center phone and email come from the live autism specialty page. Campus address comes from the same official domain footer because the specialty page contact box does not publish a separate street address.',
  },
  {
    id: 'ga-clinic-marcus-autism',
    name: 'Marcus Autism Center',
    county_id: 'dekalb-ga',
    categories: 'developmental_clinic,autism_clinic,diagnostic_center',
    phone: '(404) 785-9400',
    email: null,
    address: '1920 Briarcliff Road, Atlanta, GA 30329',
    service_tags: 'therapy',
    serving_tags: 'autism',
    source_url: 'https://www.marcus.org/contact-us',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.92,
    source_name: 'marcus.org',
    next_step_type: 'call',
    next_step_label: 'Appointments and Referrals',
    next_step_url: 'https://www.marcus.org/care-and-services/request-an-appointment',
    next_step_phone: '(404) 785-9400',
    next_step_email: null,
    next_step_instructions: 'Doctor referral required for all new patients.',
    requirements: 'Doctor referral required for all new patients.',
    application_url: null,
    referral_url: 'https://www.marcus.org/care-and-services/request-an-appointment',
    appointment_required: 1,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'Main clinic phone and address come from the official Marcus contact page. Referral requirement comes from the official appointments page.',
  },
  {
    id: 'nc-clinic-unc-cidd',
    name: 'UNC Carolina Institute for Developmental Disabilities',
    county_id: 'orange-nc',
    categories: 'developmental_clinic,diagnostic_center',
    phone: '(919) 966-5171',
    email: null,
    address: '101 Renee Lynne Court, Carrboro, NC 27510',
    service_tags: null,
    serving_tags: 'idd_dd',
    source_url: 'https://www.med.unc.edu/cidd/contact-us/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'med.unc.edu',
    next_step_type: 'call',
    next_step_label: 'Contact CIDD',
    next_step_url: 'https://www.med.unc.edu/cidd/contact-us/',
    next_step_phone: '(919) 966-5171',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'Mainline phone and physical address come from the official UNC CIDD contact page.',
  },
  {
    id: 'in-clinic-riley-hospital',
    name: 'Riley Hospital for Children',
    county_id: 'marion-in',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '317.944.5000',
    email: null,
    address: '705 Riley Hospital Dr, Indianapolis, IN 46202',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.rileychildrens.org/contact-and-locations/riley-hospital-for-children-at-iu-health',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'rileychildrens.org',
    next_step_type: 'call',
    next_step_label: 'Schedule an Appointment',
    next_step_url: null,
    next_step_phone: '317.944.5000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'The official Riley Hospital for Children location page lists 705 Riley Hospital Dr, Indianapolis, IN 46202 and contact phone 317.944.5000. The Riley Children homepage also exposes Schedule an Appointment and the same general information phone number.',
  },
  {
    id: 'tn-clinic-monroe-carell-vanderbilt',
    name: "Monroe Carell Jr. Children's Hospital at Vanderbilt",
    county_id: 'davidson-tn',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(615) 936-1000',
    email: null,
    address: '1211 Medical Center Drive, Nashville, TN 37232',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.childrenshospitalvanderbilt.org',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'childrenshospitalvanderbilt.org',
    next_step_type: 'call',
    next_step_label: 'Make an Appointment',
    next_step_url: null,
    next_step_phone: '(615) 936-1000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Monroe Carell Jr. Children's Hospital at Vanderbilt page lists 1211 Medical Center Drive, Nashville, TN 37232 and main phone (615) 936-1000, and the same page exposes Make an Appointment as the primary patient action.",
  },
  {
    id: 'ky-clinic-golisano-uk',
    name: "Golisano Children's at UK",
    county_id: 'fayette-ky',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '859-323-5000',
    email: null,
    address: '800 Rose St. Lexington, KY 40536',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://ukhealthcare.uky.edu/golisano-childrens-uk',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'ukhealthcare.uky.edu',
    next_step_type: 'call',
    next_step_label: 'Schedule an appointment',
    next_step_url: null,
    next_step_phone: '859-323-5000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Golisano Children's at UK page lists 800 Rose St. Lexington, KY 40536 and phone 859-323-5000 in the locations section, and the same UK HealthCare site exposes Schedule an appointment as the patient action.",
  },
  {
    id: 'ne-clinic-childrens-nebraska',
    name: "Children's Nebraska",
    county_id: 'douglas-ne',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '800.833.3100',
    email: null,
    address: '8200 Dodge Street, Omaha, NE 68114',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.childrensnebraska.org/locations/childrens-nebraska',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'childrensnebraska.org',
    next_step_type: 'call',
    next_step_label: 'Book an Appointment',
    next_step_url: null,
    next_step_phone: '800.833.3100',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Children's Nebraska location page lists 8200 Dodge Street, Omaha, NE 68114. The official Book an Appointment page says families can call the referral line at 800.833.3100 to find a provider and book care.",
  },
  {
    id: 'co-clinic-childrens-colorado-springs',
    name: "Children's Hospital Colorado, Colorado Springs",
    county_id: 'el-paso-co',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '719-365-5000',
    email: null,
    address: '1400 East Boulder Street, Colorado Springs, CO 80909',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.childrenscolorado.org/locations/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'childrenscolorado.org',
    next_step_type: 'call',
    next_step_label: 'Contact location',
    next_step_url: null,
    next_step_phone: '719-365-5000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Children's Hospital Colorado locations page lists the Colorado Springs location at 1400 East Boulder Street, Colorado Springs, CO 80909 with phone 719-365-5000.",
  },
  {
    id: 'ks-clinic-great-bend-childrens',
    name: "Pediatrics: Great Bend Children's Clinic",
    county_id: 'barton-ks',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '620-792-5437',
    email: null,
    address: '1021 Eisenhower Avenue, Great Bend, KS 67530',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.kansashealthsystem.com/locations',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'kansashealthsystem.com',
    next_step_type: 'call',
    next_step_label: 'Get Care',
    next_step_url: null,
    next_step_phone: '620-792-5437',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official University of Kansas Health System locations page lists Pediatrics: Great Bend Children's Clinic at 1021 Eisenhower Avenue, Great Bend, KS 67530 with phone 620-792-5437.",
  },
  {
    id: 'al-hospital-childrens-of-alabama',
    name: "Children's of Alabama",
    county_id: 'jefferson-al',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '205-638-9100',
    email: null,
    address: '1600 7th Ave. S., Birmingham, AL 35233',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.childrensal.org/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'childrensal.org',
    next_step_type: 'call',
    next_step_label: 'Contact hospital',
    next_step_url: null,
    next_step_phone: '205-638-9100',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Children's of Alabama homepage lists 1600 7th Ave. S., Birmingham AL 35233 with phone 205-638-9100.",
  },
  {
    id: 'ct-hospital-connecticut-childrens-hartford',
    name: "Connecticut Children's Medical Center - Hartford",
    county_id: 'hartford-ct',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '860.545.9000',
    email: null,
    address: '282 Washington Street, Hartford, CT 06106',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.connecticutchildrens.org/locations/connecticut-childrens-hartford',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'connecticutchildrens.org',
    next_step_type: 'call',
    next_step_label: 'Schedule an Appointment',
    next_step_url: null,
    next_step_phone: '860.545.9000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Connecticut Children's Hartford location page lists 282 Washington Street, Hartford, CT 06106 and Call 860.545.9000.",
  },
  {
    id: 'hi-hospital-kapiolani-medical-center',
    name: 'Kapiolani Medical Center for Women & Children',
    county_id: 'honolulu-hi',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(808) 983-6000',
    email: null,
    address: '1319 Punahou Street, Honolulu, HI 96826',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.hawaiipacifichealth.org/kapiolani/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'hawaiipacifichealth.org',
    next_step_type: 'call',
    next_step_label: 'Contact hospital',
    next_step_url: null,
    next_step_phone: '(808) 983-6000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'The official Kapiolani page lists 1319 Punahou Street Honolulu, HI 96826 and (808) 983-6000.',
  },
  {
    id: 'id-hospital-st-lukes-childrens-boise',
    name: "St. Luke's Children's Hospital: Boise",
    county_id: 'ada-id',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(208) 706-5437',
    email: null,
    address: '190 E. Bannock St., Boise, ID 83712',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://stlukesonline.org/en/specialties-services/st-lukes-childrens/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'stlukesonline.org',
    next_step_type: 'call',
    next_step_label: 'Location details',
    next_step_url: null,
    next_step_phone: '(208) 706-5437',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official St. Luke's Children's page lists 190 E. Bannock St., Boise, ID 83712 and (208) 706-5437 for St. Luke's Children's Hospital: Boise.",
  },
  {
    id: 'ia-hospital-stead-family-childrens',
    name: "Stead Family Children's Hospital",
    county_id: 'johnson-ia',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '1-888-573-5437',
    email: null,
    address: '200 Hawkins Drive, Iowa City, IA 52242',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://uihc.org/childrens',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'uihc.org',
    next_step_type: 'call',
    next_step_label: 'Request an appointment',
    next_step_url: null,
    next_step_phone: '1-888-573-5437',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Stead Family Children's Hospital page lists 200 Hawkins Drive, Iowa City, IA 52242 and 1-888-573-5437.",
  },
  {
    id: 'me-hospital-barbara-bush-childrens',
    name: "MaineHealth Barbara Bush Children's",
    county_id: 'cumberland-me',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '207-662-0111',
    email: null,
    address: '22 Bramhall St., Portland, ME 04102',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.mainehealth.org/barbara-bush-childrens',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'mainehealth.org',
    next_step_type: 'call',
    next_step_label: 'Contact Us',
    next_step_url: null,
    next_step_phone: '207-662-0111',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official MaineHealth Barbara Bush Children's page lists 22 Bramhall St., Portland, ME 04102 and 207-662-0111.",
  },
  {
    id: 'md-hospital-johns-hopkins-childrens-center',
    name: "Johns Hopkins Children's Center",
    county_id: 'baltimore-md',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '443-997-5437',
    email: null,
    address: '1800 Orleans Street, Baltimore, MD 21287',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.hopkinsmedicine.org/johns-hopkins-childrens-center',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'hopkinsmedicine.org',
    next_step_type: 'call',
    next_step_label: 'Schedule an Appointment',
    next_step_url: null,
    next_step_phone: '443-997-5437',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Johns Hopkins Children's Center page lists 1800 Orleans Street, Baltimore, MD 21287 and 443-997-5437 (KIDS).",
  },
  {
    id: 'ma-hospital-mass-general-brigham-children',
    name: 'Mass General Brigham for Children',
    county_id: 'suffolk-ma',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '888-644-3248',
    email: null,
    address: '55 Fruit Street, Boston, MA 02114',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.massgeneral.org/children',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'massgeneral.org',
    next_step_type: 'call',
    next_step_label: 'Request an appointment',
    next_step_url: null,
    next_step_phone: '888-644-3248',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'The official Mass General Brigham for Children page lists 888-644-3248 and the Mass General hospital address 55 Fruit Street, Boston, MA 02114.',
  },
  {
    id: 'mn-hospital-childrens-minneapolis',
    name: "Children's Minnesota - Minneapolis Hospital",
    county_id: 'hennepin-mn',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '612-813-6000',
    email: null,
    address: '2525 Chicago Avenue South, Minneapolis, MN 55404',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.childrensmn.org/locations/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'childrensmn.org',
    next_step_type: 'call',
    next_step_label: 'Hospital information/operator',
    next_step_url: null,
    next_step_phone: '612-813-6000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Children's Minnesota locations page lists Children's Minnesota - Minneapolis Hospital at 2525 Chicago Avenue South, Minneapolis, MN 55404 with hospital information/operator 612-813-6000.",
  },
  {
    id: 'mo-hospital-childrens-mercy',
    name: "Children's Mercy Hospital",
    county_id: 'jackson-mo',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(816) 234-3000',
    email: null,
    address: '2401 Gillham Road, Kansas City, MO 64108',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.childrensmercy.org/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'childrensmercy.org',
    next_step_type: 'call',
    next_step_label: 'For patients and families',
    next_step_url: null,
    next_step_phone: '(816) 234-3000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Children's Mercy homepage lists 2401 Gillham Road, Kansas City, MO 64108 and for patients and families (816) 234-3000.",
  },
  {
    id: 'nv-hospital-umc-las-vegas',
    name: "UMC Children's Hospital",
    county_id: 'clark-nv',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '702-383-7337',
    email: null,
    address: '800 Hope Place, Las Vegas, NV 89106',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://umcsn.com/umc-locations/umc-children-s-hospital',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'umcsn.com',
    next_step_type: 'call',
    next_step_label: "Call children's team",
    next_step_url: null,
    next_step_phone: '702-383-7337',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official UMC Children's Hospital page lists 800 Hope Place, Las Vegas, NV 89106 and says families can call 702-383-PEDS (7337) directly.",
  },
  {
    id: 'wa-hospital-seattle-childrens-autism-center',
    name: "Seattle Children's Autism Center",
    county_id: 'king-wa',
    categories: 'Clinical,Pediatrics,Autism',
    phone: '206-987-2000',
    email: null,
    address: '4800 Sand Point Way NE, Seattle, WA 98105',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.seattlechildrens.org/clinics/autism-center/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'seattlechildrens.org',
    next_step_type: 'call',
    next_step_label: 'Schedule appointment',
    next_step_url: null,
    next_step_phone: '206-987-2000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Seattle Children's Autism Center page lists 4800 Sand Point Way NE, Seattle, WA 98105 and phones 206-987-2000, 866-987-2000 toll-free, and 206-987-0391 TTY.",
  },
  {
    id: 'nj-hospital-childrens-specialized-autism',
    name: "Children's Specialized Hospital Autism Center of Excellence",
    county_id: 'essex-nj',
    categories: 'Clinical,Pediatrics,Autism',
    phone: '(888) 724-7123',
    email: null,
    address: '95 Old Short Hills Road, West Orange, NJ 07052',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.rwjbh.org/childrens-specialized-hospital/treatment-care/autism-center-of-excellence/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'rwjbh.org',
    next_step_type: 'call',
    next_step_label: 'Call autism center',
    next_step_url: null,
    next_step_phone: '(888) 724-7123',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Autism Center of Excellence page footer lists 95 Old Short Hills Road, West Orange, NJ 07052 and phone (888) 724-7123.",
  },
  {
    id: 'ak-hospital-anmc-pediatrics',
    name: 'Alaska Native Medical Center Pediatrics',
    county_id: 'anchorage-ak',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '907-729-1900',
    email: null,
    address: '4000 Ambassador Drive, Anchorage, AK 99508',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.anthc.org/what-we-do/alaska-native-medical-center/pediatrics/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'anthc.org',
    next_step_type: 'call',
    next_step_label: 'Call pediatrics',
    next_step_url: null,
    next_step_phone: '907-729-1900',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'The official Alaska Native Medical Center pediatrics page lists 4000 Ambassador Drive, Anchorage, AK 99508 and phone 907-729-1900.',
  },
  {
    id: 'ar-hospital-arkansas-childrens',
    name: "Arkansas Children's Hospital",
    county_id: 'pulaski-ar',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '501-364-1100',
    email: null,
    address: "1 Children's Way, Little Rock, AR 72202",
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.archildrens.org/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'archildrens.org',
    next_step_type: 'call',
    next_step_label: 'General information',
    next_step_url: null,
    next_step_phone: '501-364-1100',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Arkansas Children's homepage lists 1 Children's Way, Little Rock, AR 72202 and General Information 501-364-1100.",
  },
  {
    id: 'ca-hospital-childrens-hospital-los-angeles',
    name: "Children's Hospital Los Angeles",
    county_id: 'los-angeles',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '323-660-2450',
    email: null,
    address: '4650 Sunset Blvd., Los Angeles, CA 90027',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.chla.org/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'chla.org',
    next_step_type: 'call',
    next_step_label: "Contact Children's Hospital Los Angeles",
    next_step_url: null,
    next_step_phone: '323-660-2450',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Children's Hospital Los Angeles homepage lists the main campus at 4650 Sunset Blvd., Los Angeles, CA 90027 with phone 323-660-2450.",
  },
  {
    id: 'az-hospital-phoenix-childrens-thomas',
    name: "Phoenix Children's Hospital - Thomas Campus",
    county_id: 'maricopa-az',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '602-933-1000',
    email: null,
    address: '1919 E. Thomas Rd., Phoenix, AZ 85016',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://phoenixchildrens.org/locations',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'phoenixchildrens.org',
    next_step_type: 'call',
    next_step_label: "Contact Phoenix Children's Hospital",
    next_step_url: null,
    next_step_phone: '602-933-1000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Phoenix Children's locations page lists Phoenix Children's Hospital - Thomas Campus at 1919 E. Thomas Rd., Phoenix, AZ 85016 with phone 602-933-1000.",
  },
  {
    id: 'ms-hospital-childrens-of-mississippi',
    name: "Children's of Mississippi",
    county_id: 'hinds-ms',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '601-984-1000',
    email: null,
    address: '2500 North State Street, Jackson, MS 39216',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.umc.edu/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'umc.edu',
    next_step_type: 'call',
    next_step_label: "Contact Children's of Mississippi",
    next_step_url: null,
    next_step_phone: '601-984-1000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official UMMC homepage lists Children's of Mississippi at 2500 North State Street, Jackson, MS 39216 with general information phone 601-984-1000.",
  },
  {
    id: 'or-hospital-doernbecher-childrens',
    name: "Doernbecher Children's Hospital",
    county_id: 'multnomah-or',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '503-346-0640',
    email: null,
    address: '700 S.W. Campus Drive, Portland, OR 97239',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.ohsu.edu/doernbecher/doernbecher-hospital-and-clinic-locations',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'ohsu.edu',
    next_step_type: 'call',
    next_step_label: "Contact Doernbecher Children's Hospital",
    next_step_url: null,
    next_step_phone: '503-346-0640',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official OHSU Doernbecher hospital and clinic locations page lists Doernbecher Children's Hospital at 700 S.W. Campus Drive, Portland, OR 97239 with phone 503-346-0640.",
  },
  {
    id: 'mt-hospital-billings-clinic-hospital',
    name: 'Billings Clinic Hospital',
    county_id: 'yellowstone-mt',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '406-238-2500',
    email: null,
    address: '2800 10th Avenue North, Billings, MT 59107-7000',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.billingsclinic.com/contact-us/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'billingsclinic.com',
    next_step_type: 'call',
    next_step_label: 'Contact Billings Clinic Hospital',
    next_step_url: null,
    next_step_phone: '406-238-2500',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'The official Billings Clinic contact page lists Billings Clinic Hospital at 2800 10th Avenue North, Billings, MT 59107-7000 with phone 406-238-2500.',
  },
  {
    id: 'ri-hospital-hasbro-childrens',
    name: "Hasbro Children's",
    county_id: 'providence-ri',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '401-444-4000',
    email: null,
    address: '593 Eddy Street, Providence, RI 02903',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.lifespan.org/locations/hasbro-childrens-hospital',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'brownhealth.org',
    next_step_type: 'call',
    next_step_label: "Contact Hasbro Children's",
    next_step_url: null,
    next_step_phone: '401-444-4000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Brown Health Hasbro Children's page lists 593 Eddy Street, Providence, RI 02903 with phone 401-444-4000.",
  },
  {
    id: 'nm-hospital-unm-childrens',
    name: "UNM Children's Hospital",
    county_id: 'bernalillo-nm',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '505-272-2111',
    email: null,
    address: '2211 Lomas Blvd. NE, Albuquerque, NM 87106',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://unmhealth.org/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'unmhealth.org',
    next_step_type: 'call',
    next_step_label: "Contact UNM Children's Hospital",
    next_step_url: null,
    next_step_phone: '505-272-2111',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official UNM Health page lists UNM Hospital at 2211 Lomas Blvd. NE, Albuquerque, NM 87106 with phone 505-272-2111; the same page also references Children's Hospital.",
  },
  {
    id: 'sd-hospital-sanford-childrens-sioux-falls',
    name: "Sanford Children's Hospital",
    county_id: 'minnehaha-sd',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(605) 312-1000',
    email: null,
    address: '1600 W. 22nd St., Sioux Falls, SD 57105',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.sanfordhealth.org/locations/sanford-childrens-hospital-sioux-falls',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'sanfordhealth.org',
    next_step_type: 'call',
    next_step_label: "Contact Sanford Children's Hospital",
    next_step_url: null,
    next_step_phone: '(605) 312-1000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Sanford Children's Hospital Sioux Falls page includes structured data with address 1600 W. 22nd St., Sioux Falls, SD 57105 and phone (605) 312-1000.",
  },
  {
    id: 'de-hospital-nemours-childrens-delaware',
    name: "Nemours Children's Hospital, Delaware",
    county_id: 'new-castle-de',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(800) 416-4441',
    email: null,
    address: '1600 Rockland Road, Wilmington, DE 19803',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.nemours.org/locations/wilmington-ai-dupont-childrens-hospital.html',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'nemours.org',
    next_step_type: 'call',
    next_step_label: "Contact Nemours Children's Hospital, Delaware",
    next_step_url: null,
    next_step_phone: '(800) 416-4441',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Nemours Children's Hospital, Delaware page lists 1600 Rockland Road, Wilmington, DE 19803 and public contact phone (800) 416-4441.",
  },
  {
    id: 'nh-hospital-elliot',
    name: 'Elliot Hospital',
    county_id: 'hillsborough-nh',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(603) 669-5300',
    email: null,
    address: '1 Elliot Way, Manchester, NH 03103',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.elliothospital.org/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'elliothospital.org',
    next_step_type: 'call',
    next_step_label: 'Contact Elliot Hospital',
    next_step_url: null,
    next_step_phone: '(603) 669-5300',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'The official Elliot Hospital homepage footer lists 1 Elliot Way, Manchester, NH 03103 and phone (603) 669-5300.',
  },
  {
    id: 'vt-hospital-uvm-medical-center',
    name: 'University of Vermont Medical Center',
    county_id: 'chittenden-vt',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '802-847-0000',
    email: null,
    address: '111 Colchester Ave, Burlington, VT 05401',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.uvmhealth.org/medcenter/childrens-hospital',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'uvmhealth.org',
    next_step_type: 'call',
    next_step_label: 'Contact University of Vermont Medical Center',
    next_step_url: null,
    next_step_phone: '802-847-0000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'The official UVM Medical Center children’s hospital page lists University of Vermont Medical Center at 111 Colchester Ave, Burlington, VT 05401 with phone 802-847-0000.',
  },
  {
    id: 'ok-hospital-oklahoma-childrens-ou-health',
    name: "Oklahoma Children's OU Health",
    county_id: 'oklahoma-ok',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(405) 271-4700',
    email: null,
    address: "1200 N. Children's Ave., Oklahoma City, OK 73104",
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.ouhealth.com/find-a-location/oklahoma-childrens-ou-health/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'ouhealth.com',
    next_step_type: 'call',
    next_step_label: "Contact Oklahoma Children's OU Health",
    next_step_url: null,
    next_step_phone: '(405) 271-4700',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official OU Health location page lists Oklahoma Children's OU Health at 1200 N. Children's Ave., Oklahoma City, OK 73104 with phone (405) 271-4700.",
  },
  {
    id: 'ut-hospital-primary-childrens-salt-lake-city',
    name: "Primary Children's Hospital - Salt Lake City",
    county_id: 'salt-lake-ut',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '801-662-1000',
    email: null,
    address: '100 North Mario Capecchi Drive, Salt Lake City, UT 84113',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://intermountainhealthcare.org/locations/primary-childrens-salt-lake-city',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'intermountainhealthcare.org',
    next_step_type: 'call',
    next_step_label: "Contact Primary Children's Hospital",
    next_step_url: null,
    next_step_phone: '801-662-1000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Intermountain page explicitly shows Primary Children's Hospital - Salt Lake City at 100 North Mario Capecchi Drive, Salt Lake City, UT 84113 with phone 801-662-1000.",
  },
  {
    id: 'sc-hospital-musc-shawn-jenkins',
    name: "MUSC Shawn Jenkins Children's Hospital",
    county_id: 'charleston-sc',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '843-792-1414',
    email: null,
    address: '10 McClennan Banks Drive, Charleston, SC 29425',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://musckids.org/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'musckids.org',
    next_step_type: 'call',
    next_step_label: "Contact MUSC Shawn Jenkins Children's Hospital",
    next_step_url: null,
    next_step_phone: '843-792-1414',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official MUSC Children's Health page lists MUSC Shawn Jenkins Children's Hospital at 10 McClennan Banks Drive, Charleston, SC 29425 with phone 843-792-1414.",
  },
  {
    id: 'nd-hospital-sanford-medical-center-fargo',
    name: 'Sanford Medical Center Fargo',
    county_id: 'cass-nd',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(701) 417-2000',
    email: null,
    address: '5225 23rd Ave. S., Fargo, ND 58104',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.sanfordhealth.org/locations/sanford-medical-center-fargo',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'sanfordhealth.org',
    next_step_type: 'call',
    next_step_label: 'Contact Sanford Medical Center Fargo',
    next_step_url: null,
    next_step_phone: '(701) 417-2000',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: 'The official Sanford Medical Center Fargo page includes structured data with address 5225 23rd Ave. S., Fargo, ND 58104 and phone (701) 417-2000.',
  },
  {
    id: 'wy-clinic-cheyenne-childrens-clinic',
    name: "Cheyenne Children's Clinic",
    county_id: 'laramie-wy',
    categories: 'Clinical,Pediatrics',
    phone: '(307) 635-7961',
    email: null,
    address: '2301 House Ave., Cheyenne, WY 82001',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://www.cheyenneregional.org/service/women-and-childrens-services/pediatrics/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'cheyenneregional.org',
    next_step_type: 'call',
    next_step_label: "Contact Cheyenne Children's Clinic",
    next_step_url: 'https://www.cheyenneregional.org/learn-about-mychart/online-scheduling/',
    next_step_phone: '(307) 635-7961',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Cheyenne Regional pediatrics page says pediatric services include two Cheyenne Children's Clinic locations, and the official contact page footer location list includes Cheyenne Children's Clinic at 2301 House Ave., Cheyenne, WY 82001 with phone (307) 635-7961.",
  },
  {
    id: 'wv-hospital-wvu-golisano-childrens',
    name: "WVU Medicine Golisano Children's",
    county_id: 'monongalia-wv',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(855) 988-2273',
    email: null,
    address: '1 Medical Center Dr, Morgantown, WV 26506',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://wvumedicine.org/our-care/institutes/childrens/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'wvumedicine.org',
    next_step_type: 'call',
    next_step_label: "Contact WVU Medicine Golisano Children's",
    next_step_url: 'https://wvumedicine.org/about-us/contact-us/',
    next_step_phone: '(855) 988-2273',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official WVU Medicine Golisano Children's page includes address 1 Medical Center Dr, Morgantown, WV 26506 and the site organization schema lists telephone +18559882273.",
  },
  {
    id: 'mi-clinic-um-autism-spectrum',
    name: 'University of Michigan Health Autism Spectrum Disorders Clinic',
    county_id: 'washtenaw-mi',
    categories: 'developmental_clinic,autism_clinic,diagnostic_center',
    phone: '(734) 764-0231',
    email: null,
    address: "1540 E Hospital Dr, Ann Arbor, MI 48109-4228",
    service_tags: 'therapy',
    serving_tags: 'autism',
    source_url: 'https://www.uofmhealth.org/our-care/specialties-services/autism-spectrum-disorders-appointments',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.92,
    source_name: 'uofmhealth.org',
    next_step_type: 'call',
    next_step_label: 'Call for autism appointments',
    next_step_url: 'https://www.uofmhealth.org/our-care/specialties-services/autism-spectrum-disorders-appointments',
    next_step_phone: '(734) 764-0231',
    next_step_email: null,
    next_step_instructions: 'Children 18 months to 10 years can call (734) 232-7513 or (734) 764-0231. Children 11 years and older should call (734) 764-0231.',
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: 1,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official University of Michigan Health autism appointments page lists Pediatric Development Assessment Clinic | C.S. Mott Children's Hospital at 1540 E Hospital Dr, Ann Arbor, MI 48109-4228 and publishes appointment phone numbers 734-232-7513 and 734-764-0231.",
  },
  {
    id: 'wi-hospital-childrens-wisconsin-milwaukee',
    name: "Children's Wisconsin",
    county_id: 'milwaukee-wi',
    categories: 'Clinical,Pediatrics,Hospital',
    phone: '(877) 607-5280',
    email: null,
    address: '8915 W. Connell Ct., Milwaukee, WI 53226',
    service_tags: null,
    serving_tags: null,
    source_url: 'https://childrenswi.org/',
    source_type: 'hospital_university_directory',
    data_origin: 'hospital_university_directory',
    verification_status: 'source_listed',
    confidence_score: 0.9,
    source_name: 'childrenswi.org',
    next_step_type: 'call',
    next_step_label: 'Schedule an Appointment',
    next_step_url: 'https://childrenswi.org/Find-Care/Request-an-appointment',
    next_step_phone: '(877) 607-5280',
    next_step_email: null,
    next_step_instructions: null,
    requirements: null,
    application_url: null,
    referral_url: null,
    appointment_required: null,
    claim_status: 'unclaimed',
    evidence_level: 'official_source_target',
    data_quality_notes: "The official Children's Wisconsin homepage JSON includes address 8915 W. Connell Ct., Milwaukee, WI 53226 and a Schedule an Appointment modal with specialty care phone (877) 607-5280.",
  },
];

const upsert = db.prepare(`
  INSERT INTO resource_providers (
    id, name, categories, county_id, phone, email, address, accepts_medi_cal,
    regional_center_vendor_ids, source_url, source_type, data_origin, verification_status,
    last_verified_date, last_scraped_at, confidence_score, evidence_level,
    service_tags, serving_tags, checked_at, source_name, next_step_type, next_step_label,
    next_step_url, next_step_phone, next_step_email, next_step_instructions,
    requirements, application_url, referral_url, appointment_required,
    claim_status, manual_review_required, data_quality_notes
  ) VALUES (
    @id, @name, @categories, @county_id, @phone, @email, @address, 0,
    '', @source_url, @source_type, @data_origin, @verification_status,
    @last_verified_date, @last_scraped_at, @confidence_score, @evidence_level,
    @service_tags, @serving_tags, @checked_at, @source_name, @next_step_type, @next_step_label,
    @next_step_url, @next_step_phone, @next_step_email, @next_step_instructions,
    @requirements, @application_url, @referral_url, @appointment_required,
    @claim_status, 0, @data_quality_notes
  )
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    categories = excluded.categories,
    county_id = excluded.county_id,
    phone = excluded.phone,
    email = excluded.email,
    address = excluded.address,
    source_url = excluded.source_url,
    source_type = excluded.source_type,
    data_origin = excluded.data_origin,
    verification_status = excluded.verification_status,
    last_verified_date = excluded.last_verified_date,
    last_scraped_at = excluded.last_scraped_at,
    confidence_score = excluded.confidence_score,
    evidence_level = excluded.evidence_level,
    service_tags = excluded.service_tags,
    serving_tags = excluded.serving_tags,
    checked_at = excluded.checked_at,
    source_name = excluded.source_name,
    next_step_type = excluded.next_step_type,
    next_step_label = excluded.next_step_label,
    next_step_url = excluded.next_step_url,
    next_step_phone = excluded.next_step_phone,
    next_step_email = excluded.next_step_email,
    next_step_instructions = excluded.next_step_instructions,
    requirements = excluded.requirements,
    application_url = excluded.application_url,
    referral_url = excluded.referral_url,
    appointment_required = excluded.appointment_required,
    claim_status = excluded.claim_status,
    manual_review_required = 0,
    data_quality_notes = excluded.data_quality_notes
`);

const tx = db.transaction(() => {
  for (const record of records) {
    upsert.run({
      ...record,
      checked_at: now,
      last_verified_date: today,
      last_scraped_at: now,
    });
  }
});

tx();
db.pragma('wal_checkpoint(TRUNCATE)');
db.close();

if (fs.existsSync(frontendDbPath)) {
  fs.copyFileSync(dbPath, frontendDbPath);
}

console.log(`Seeded or updated ${records.length} Wave A provider rows.`);
