-- Rollback Script for State: Louisiana | Phase: dd_idd
-- Generated At: 2026-06-14T15:48:43.597Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'winn-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'west-feliciana-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'west-carroll-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'west-baton-rouge-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'webster-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'washington-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'vernon-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'vermilion-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'union-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'terrebonne-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'tensas-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'tangipahoa-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'st-tammany-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'st-mary-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'st-martin-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'st-landry-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'st-john-the-baptist-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'st-james-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'st-helena-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'st-charles-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'st-bernard-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'sabine-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'richland-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'red-river-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'rapides-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'pointe-coupee-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'plaquemines-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'ouachita-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'orleans-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'natchitoches-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'morehouse-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'madison-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'livingston-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'lincoln-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'lasalle-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'lafourche-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'lafayette-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'jefferson-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'jefferson-davis-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'jackson-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'iberville-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'iberia-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'grant-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'franklin-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'evangeline-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'east-feliciana-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'east-carroll-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'east-baton-rouge-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'desoto-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'concordia-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'claiborne-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'catahoula-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'cameron-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'caldwell-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'calcasieu-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'caddo-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'bossier-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'bienville-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'beauregard-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'avoyelles-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'assumption-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'ascension-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'allen-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-dd-agency' AND county_id = 'acadia-parish-la';
UPDATE state_resource_agencies SET state_id = 'louisiana', agency_type = 'dd_office', name = 'Louisiana Office for Citizens with Developmental Disabilities', counties_served = 'acadia-parish-la,allen-parish-la,ascension-parish-la,assumption-parish-la,avoyelles-parish-la,beauregard-parish-la,bienville-parish-la,bossier-parish-la,caddo-parish-la,calcasieu-parish-la,caldwell-parish-la,cameron-parish-la,catahoula-parish-la,claiborne-parish-la,concordia-parish-la,desoto-parish-la,east-baton-rouge-parish-la,east-carroll-parish-la,east-feliciana-parish-la,evangeline-parish-la,franklin-parish-la,grant-parish-la,iberia-parish-la,iberville-parish-la,jackson-parish-la,jefferson-parish-la,jefferson-davis-parish-la,lafayette-parish-la,lafourche-parish-la,lasalle-parish-la,lincoln-parish-la,livingston-parish-la,madison-parish-la,morehouse-parish-la,natchitoches-parish-la,orleans-parish-la,ouachita-parish-la,plaquemines-parish-la,pointe-coupee-parish-la,rapides-parish-la,red-river-parish-la,richland-parish-la,sabine-parish-la,st-bernard-parish-la,st-charles-parish-la,st-helena-parish-la,st-james-parish-la,st-john-the-baptist-parish-la,st-landry-parish-la,st-martin-parish-la,st-mary-parish-la,st-tammany-parish-la,tangipahoa-parish-la,tensas-parish-la,terrebonne-parish-la,union-parish-la,vermilion-parish-la,vernon-parish-la,washington-parish-la,webster-parish-la,west-baton-rouge-parish-la,west-carroll-parish-la,west-feliciana-parish-la,winn-parish-la', catchment_boundaries = 'Statewide coverage for all counties in Louisiana.', website = 'https://ldh.la.gov/ocdd', intake_phone = '(800) 555-0100', early_intervention_contact = '(800) 555-0100', agency_intake_contact = '(800) 555-0100', eligibility_info_page = 'https://ldh.la.gov/ocdd/eligibility', services_page = 'https://ldh.la.gov/ocdd', appeals_info = 'Waiver decisions can be appealed within 30 days of notice.', frc_relationship = NULL, office_locations = 'Louisiana State Capitol Office', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://ldh.la.gov/ocdd', source_url = 'https://ldh.la.gov/ocdd', source_type = 'official', data_origin = 'curated_seed', verification_status = 'source_listed', last_scraped_at = '2026-06-13T02:29:27.549Z', confidence_score = 5, evidence_level = NULL WHERE id = 'la-dd-agency';

COMMIT;
