-- Rollback Script for State: Louisiana | Phase: early_intervention
-- Generated At: 2026-06-14T15:48:43.930Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'winn-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'west-feliciana-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'west-carroll-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'west-baton-rouge-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'webster-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'washington-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'vernon-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'vermilion-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'union-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'terrebonne-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'tensas-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'tangipahoa-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'st-tammany-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'st-mary-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'st-martin-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'st-landry-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'st-john-the-baptist-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'st-james-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'st-helena-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'st-charles-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'st-bernard-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'sabine-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'richland-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'red-river-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'rapides-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'pointe-coupee-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'plaquemines-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'ouachita-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'orleans-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'natchitoches-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'morehouse-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'madison-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'livingston-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'lincoln-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'lasalle-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'lafourche-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'lafayette-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'jefferson-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'jefferson-davis-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'jackson-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'iberville-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'iberia-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'grant-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'franklin-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'evangeline-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'east-feliciana-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'east-carroll-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'east-baton-rouge-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'desoto-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'concordia-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'claiborne-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'catahoula-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'cameron-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'caldwell-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'calcasieu-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'caddo-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'bossier-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'bienville-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'beauregard-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'avoyelles-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'assumption-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'ascension-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'allen-parish-la';
DELETE FROM regional_center_counties WHERE regional_center_id = 'la-ei-agency' AND county_id = 'acadia-parish-la';
DELETE FROM state_resource_agencies WHERE id = 'la-ei-agency';

COMMIT;
