-- Rollback Script for State: Arizona | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:49:52.148Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'yuma-az', program_id = 'az-medicaid', office_name = 'Yuma County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-yuma-az-medicaid';
UPDATE county_offices SET county_id = 'yavapai-az', program_id = 'az-medicaid', office_name = 'Yavapai County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-yavapai-az-medicaid';
UPDATE county_offices SET county_id = 'santa-cruz-az', program_id = 'az-medicaid', office_name = 'Santa Cruz County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-santa-cruz-az-medicaid';
UPDATE county_offices SET county_id = 'pinal-az', program_id = 'az-medicaid', office_name = 'Pinal County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-pinal-az-medicaid';
UPDATE county_offices SET county_id = 'pima-az', program_id = 'az-medicaid', office_name = 'Pima County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-pima-az-medicaid';
UPDATE county_offices SET county_id = 'navajo-az', program_id = 'az-medicaid', office_name = 'Navajo County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-navajo-az-medicaid';
UPDATE county_offices SET county_id = 'mohave-az', program_id = 'az-medicaid', office_name = 'Mohave County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-mohave-az-medicaid';
UPDATE county_offices SET county_id = 'maricopa-az', program_id = 'az-medicaid', office_name = 'Maricopa County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-maricopa-az-medicaid';
UPDATE county_offices SET county_id = 'la-paz-az', program_id = 'az-medicaid', office_name = 'La Paz County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-la-paz-az-medicaid';
UPDATE county_offices SET county_id = 'greenlee-az', program_id = 'az-medicaid', office_name = 'Greenlee County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-greenlee-az-medicaid';
UPDATE county_offices SET county_id = 'graham-az', program_id = 'az-medicaid', office_name = 'Graham County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-graham-az-medicaid';
UPDATE county_offices SET county_id = 'gila-az', program_id = 'az-medicaid', office_name = 'Gila County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-gila-az-medicaid';
UPDATE county_offices SET county_id = 'coconino-az', program_id = 'az-medicaid', office_name = 'Coconino County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-coconino-az-medicaid';
UPDATE county_offices SET county_id = 'cochise-az', program_id = 'az-medicaid', office_name = 'Cochise County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-cochise-az-medicaid';
UPDATE county_offices SET county_id = 'apache-az', program_id = 'az-medicaid', office_name = 'Apache County storefront office', address = '', phone = '(855) 432-7587', email = '', website = 'https://www.healthearizonaplus.gov/', source_url = 'https://des.az.gov/find-your-local-office', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-apache-az-medicaid';

COMMIT;
