-- Rollback Script for State: Arizona | Phase: district_replacements
-- Generated At: 2026-06-14T15:41:54.992Z

BEGIN TRANSACTION;

DELETE FROM school_districts WHERE id = 'sd-yuma-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-yuma-az-fallback', 'yuma-az', 'Yuma County School District Special Education', '(800) 555-0199', 'sped-fallback@yuma-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-yuma-az-fallback' WHERE id = 'sd-yuma-az';
DELETE FROM school_districts WHERE id = 'sd-yavapai-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-yavapai-az-fallback', 'yavapai-az', 'Yavapai County School District Special Education', '(800) 555-0199', 'sped-fallback@yavapai-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-yavapai-az-fallback' WHERE id = 'sd-yavapai-az';
DELETE FROM school_districts WHERE id = 'sd-santa-cruz-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-santa-cruz-az-fallback', 'santa-cruz-az', 'Santa Cruz County School District Special Education', '(800) 555-0199', 'sped-fallback@santa-cruz-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-santa-cruz-az-fallback' WHERE id = 'sd-santa-cruz-az';
DELETE FROM school_districts WHERE id = 'sd-pinal-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-pinal-az-fallback', 'pinal-az', 'Pinal County School District Special Education', '(800) 555-0199', 'sped-fallback@pinal-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-pinal-az-fallback' WHERE id = 'sd-pinal-az';
DELETE FROM school_districts WHERE id = 'sd-navajo-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-navajo-az-fallback', 'navajo-az', 'Navajo County School District Special Education', '(800) 555-0199', 'sped-fallback@navajo-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-navajo-az-fallback' WHERE id = 'sd-navajo-az';
DELETE FROM school_districts WHERE id = 'sd-mohave-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-mohave-az-fallback', 'mohave-az', 'Mohave County School District Special Education', '(800) 555-0199', 'sped-fallback@mohave-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-mohave-az-fallback' WHERE id = 'sd-mohave-az';
DELETE FROM school_districts WHERE id = 'sd-la-paz-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-la-paz-az-fallback', 'la-paz-az', 'La Paz County School District Special Education', '(800) 555-0199', 'sped-fallback@la-paz-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-la-paz-az-fallback' WHERE id = 'sd-la-paz-az';
DELETE FROM school_districts WHERE id = 'sd-greenlee-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-greenlee-az-fallback', 'greenlee-az', 'Greenlee County School District Special Education', '(800) 555-0199', 'sped-fallback@greenlee-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-greenlee-az-fallback' WHERE id = 'sd-greenlee-az';
DELETE FROM school_districts WHERE id = 'sd-graham-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-graham-az-fallback', 'graham-az', 'Graham County School District Special Education', '(800) 555-0199', 'sped-fallback@graham-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-graham-az-fallback' WHERE id = 'sd-graham-az';
DELETE FROM school_districts WHERE id = 'sd-gila-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-gila-az-fallback', 'gila-az', 'Gila County School District Special Education', '(800) 555-0199', 'sped-fallback@gila-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-gila-az-fallback' WHERE id = 'sd-gila-az';
DELETE FROM school_districts WHERE id = 'sd-coconino-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-coconino-az-fallback', 'coconino-az', 'Coconino County School District Special Education', '(800) 555-0199', 'sped-fallback@coconino-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-coconino-az-fallback' WHERE id = 'sd-coconino-az';
DELETE FROM school_districts WHERE id = 'sd-cochise-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-cochise-az-fallback', 'cochise-az', 'Cochise County School District Special Education', '(800) 555-0199', 'sped-fallback@cochise-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-cochise-az-fallback' WHERE id = 'sd-cochise-az';
DELETE FROM school_districts WHERE id = 'sd-apache-az';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-apache-az-fallback', 'apache-az', 'Apache County School District Special Education', '(800) 555-0199', 'sped-fallback@apache-az.gov', 'https://www.arizona-education.gov', 5000, 12, 60, 20, 'https://www.arizona-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.536Z', 3, NULL);
UPDATE school_districts SET id = 'sd-apache-az-fallback' WHERE id = 'sd-apache-az';

COMMIT;
