-- Rollback Script for State: Arizona | Phase: district_replacements
-- Generated At: 2026-06-15T21:49:54.471Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'yuma-az', name = 'Yuma County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-yuma-az';
UPDATE school_districts SET county_id = 'yavapai-az', name = 'Yavapai County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-yavapai-az';
UPDATE school_districts SET county_id = 'santa-cruz-az', name = 'Santa Cruz County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-santa-cruz-az';
UPDATE school_districts SET county_id = 'pinal-az', name = 'Pinal County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-pinal-az';
UPDATE school_districts SET county_id = 'navajo-az', name = 'Navajo County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-navajo-az';
UPDATE school_districts SET county_id = 'mohave-az', name = 'Mohave County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-mohave-az';
UPDATE school_districts SET county_id = 'la-paz-az', name = 'La Paz County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-la-paz-az';
UPDATE school_districts SET county_id = 'greenlee-az', name = 'Greenlee County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-greenlee-az';
UPDATE school_districts SET county_id = 'graham-az', name = 'Graham County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-graham-az';
UPDATE school_districts SET county_id = 'gila-az', name = 'Gila County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-gila-az';
UPDATE school_districts SET county_id = 'coconino-az', name = 'Coconino County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-coconino-az';
UPDATE school_districts SET county_id = 'cochise-az', name = 'Cochise County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-cochise-az';
UPDATE school_districts SET county_id = 'apache-az', name = 'Apache County School District', spec_ed_contact_phone = '(602) 542-4013', spec_ed_contact_email = '', website = 'https://www.azed.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.azed.gov/specialeducation', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-apache-az';

COMMIT;
