-- Rollback Script for State: New York | Phase: dd_idd
-- Generated At: 2026-06-15T16:52:46.615Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-longisland' AND county_id = 'suffolk-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-longisland' AND county_id = 'nassau-ny';
UPDATE state_resource_agencies SET state_id = 'new-york', agency_type = 'ddro', name = 'OPWDD Long Island Regional Office (Region 5)', counties_served = 'nassau-ny,suffolk-ny', catchment_boundaries = 'nassau-ny,suffolk-ny', website = 'https://opwdd.ny.gov/get-started/front-door', intake_phone = '(631) 434-6100', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://opwdd.ny.gov/get-started/front-door', source_url = 'https://opwdd.ny.gov/get-started/front-door', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'ny-ddro-longisland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-nyc' AND county_id = 'richmond-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-nyc' AND county_id = 'queens-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-nyc' AND county_id = 'new-york-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-nyc' AND county_id = 'kings-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-nyc' AND county_id = 'bronx-ny';
UPDATE state_resource_agencies SET state_id = 'new-york', agency_type = 'ddro', name = 'OPWDD NYC Regional Office (Region 4)', counties_served = 'bronx-ny,kings-ny,new-york-ny,queens-ny,richmond-ny', catchment_boundaries = 'bronx-ny,kings-ny,new-york-ny,queens-ny,richmond-ny', website = 'https://opwdd.ny.gov/get-started/front-door', intake_phone = '(646) 766-3466', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://opwdd.ny.gov/get-started/front-door', source_url = 'https://opwdd.ny.gov/get-started/front-door', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'ny-ddro-nyc';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-hudson' AND county_id = 'westchester-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-hudson' AND county_id = 'ulster-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-hudson' AND county_id = 'sullivan-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-hudson' AND county_id = 'rockland-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-hudson' AND county_id = 'putnam-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-hudson' AND county_id = 'orange-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-hudson' AND county_id = 'greene-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-hudson' AND county_id = 'dutchess-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-hudson' AND county_id = 'columbia-ny';
UPDATE state_resource_agencies SET state_id = 'new-york', agency_type = 'ddro', name = 'OPWDD Hudson Valley Regional Office (Region 3)', counties_served = 'columbia-ny,dutchess-ny,greene-ny,orange-ny,putnam-ny,rockland-ny,sullivan-ny,ulster-ny,westchester-ny', catchment_boundaries = 'columbia-ny,dutchess-ny,greene-ny,orange-ny,putnam-ny,rockland-ny,sullivan-ny,ulster-ny,westchester-ny', website = 'https://opwdd.ny.gov/get-started/front-door', intake_phone = '(845) 947-6100', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://opwdd.ny.gov/get-started/front-door', source_url = 'https://opwdd.ny.gov/get-started/front-door', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'ny-ddro-hudson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-capital' AND county_id = 'washington-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-capital' AND county_id = 'warren-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-capital' AND county_id = 'schoharie-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-capital' AND county_id = 'schenectady-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-capital' AND county_id = 'saratoga-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-capital' AND county_id = 'rensselaer-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-capital' AND county_id = 'montgomery-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-capital' AND county_id = 'fulton-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-capital' AND county_id = 'albany-ny';
UPDATE state_resource_agencies SET state_id = 'new-york', agency_type = 'ddro', name = 'OPWDD Capital District Regional Office (Region 3)', counties_served = 'albany-ny,fulton-ny,montgomery-ny,rensselaer-ny,saratoga-ny,schenectady-ny,schoharie-ny,warren-ny,washington-ny', catchment_boundaries = 'albany-ny,fulton-ny,montgomery-ny,rensselaer-ny,saratoga-ny,schenectady-ny,schoharie-ny,warren-ny,washington-ny', website = 'https://opwdd.ny.gov/get-started/front-door', intake_phone = '(518) 388-0431', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://opwdd.ny.gov/get-started/front-door', source_url = 'https://opwdd.ny.gov/get-started/front-door', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'ny-ddro-capital';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'tompkins-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'tioga-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'st-lawrence-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'otsego-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'oswego-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'onondaga-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'oneida-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'madison-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'lewis-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'jefferson-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'herkimer-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'hamilton-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'franklin-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'essex-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'delaware-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'cortland-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'clinton-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'chenango-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'cayuga-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-central' AND county_id = 'broome-ny';
UPDATE state_resource_agencies SET state_id = 'new-york', agency_type = 'ddro', name = 'OPWDD Central NY Regional Office (Region 2)', counties_served = 'broome-ny,cayuga-ny,chenango-ny,clinton-ny,cortland-ny,delaware-ny,essex-ny,franklin-ny,hamilton-ny,herkimer-ny,jefferson-ny,lewis-ny,madison-ny,oneida-ny,onondaga-ny,oswego-ny,otsego-ny,st-lawrence-ny,tioga-ny,tompkins-ny', catchment_boundaries = 'broome-ny,cayuga-ny,chenango-ny,clinton-ny,cortland-ny,delaware-ny,essex-ny,franklin-ny,hamilton-ny,herkimer-ny,jefferson-ny,lewis-ny,madison-ny,oneida-ny,onondaga-ny,oswego-ny,otsego-ny,st-lawrence-ny,tioga-ny,tompkins-ny', website = 'https://opwdd.ny.gov/get-started/front-door', intake_phone = '(607) 240-4900', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://opwdd.ny.gov/get-started/front-door', source_url = 'https://opwdd.ny.gov/get-started/front-door', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'ny-ddro-central';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-fingerlakes' AND county_id = 'yates-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-fingerlakes' AND county_id = 'wayne-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-fingerlakes' AND county_id = 'steuben-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-fingerlakes' AND county_id = 'seneca-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-fingerlakes' AND county_id = 'schuyler-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-fingerlakes' AND county_id = 'ontario-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-fingerlakes' AND county_id = 'monroe-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-fingerlakes' AND county_id = 'livingston-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-fingerlakes' AND county_id = 'chemung-ny';
UPDATE state_resource_agencies SET state_id = 'new-york', agency_type = 'ddro', name = 'OPWDD Finger Lakes Regional Office (Region 1)', counties_served = 'chemung-ny,livingston-ny,monroe-ny,ontario-ny,schuyler-ny,seneca-ny,steuben-ny,wayne-ny,yates-ny', catchment_boundaries = 'chemung-ny,livingston-ny,monroe-ny,ontario-ny,schuyler-ny,seneca-ny,steuben-ny,wayne-ny,yates-ny', website = 'https://opwdd.ny.gov/get-started/front-door', intake_phone = '(585) 461-8508', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://opwdd.ny.gov/get-started/front-door', source_url = 'https://opwdd.ny.gov/get-started/front-door', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'ny-ddro-fingerlakes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-western' AND county_id = 'wyoming-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-western' AND county_id = 'orleans-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-western' AND county_id = 'niagara-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-western' AND county_id = 'genesee-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-western' AND county_id = 'erie-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-western' AND county_id = 'chautauqua-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-western' AND county_id = 'cattaraugus-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ddro-western' AND county_id = 'allegany-ny';
UPDATE state_resource_agencies SET state_id = 'new-york', agency_type = 'ddro', name = 'OPWDD Western NY Regional Office (Region 1)', counties_served = 'allegany-ny,cattaraugus-ny,chautauqua-ny,erie-ny,genesee-ny,niagara-ny,orleans-ny,wyoming-ny', catchment_boundaries = 'allegany-ny,cattaraugus-ny,chautauqua-ny,erie-ny,genesee-ny,niagara-ny,orleans-ny,wyoming-ny', website = 'https://opwdd.ny.gov/get-started/front-door', intake_phone = '(716) 517-2010', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://opwdd.ny.gov/get-started/front-door', source_url = 'https://opwdd.ny.gov/get-started/front-door', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'ny-ddro-western';

COMMIT;
