-- Rollback Script for State: New York | Phase: early_intervention
-- Generated At: 2026-06-13T20:50:54.841Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-richmond-ny' AND county_id = 'richmond-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-richmond-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-queens-ny' AND county_id = 'queens-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-queens-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-new-york-ny' AND county_id = 'new-york-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-new-york-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-kings-ny' AND county_id = 'kings-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-kings-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-bronx-ny' AND county_id = 'bronx-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-bronx-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-yates-ny' AND county_id = 'yates-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-yates-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-wyoming-ny' AND county_id = 'wyoming-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-wyoming-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-westchester-ny' AND county_id = 'westchester-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-westchester-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-wayne-ny' AND county_id = 'wayne-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-wayne-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-washington-ny' AND county_id = 'washington-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-washington-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-warren-ny' AND county_id = 'warren-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-warren-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-ulster-ny' AND county_id = 'ulster-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-ulster-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-tompkins-ny' AND county_id = 'tompkins-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-tompkins-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-tioga-ny' AND county_id = 'tioga-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-tioga-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-sullivan-ny' AND county_id = 'sullivan-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-sullivan-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-suffolk-ny' AND county_id = 'suffolk-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-suffolk-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-steuben-ny' AND county_id = 'steuben-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-steuben-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-st-lawrence-ny' AND county_id = 'st-lawrence-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-st-lawrence-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-seneca-ny' AND county_id = 'seneca-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-seneca-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-schuyler-ny' AND county_id = 'schuyler-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-schuyler-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-schoharie-ny' AND county_id = 'schoharie-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-schoharie-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-schenectady-ny' AND county_id = 'schenectady-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-schenectady-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-saratoga-ny' AND county_id = 'saratoga-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-saratoga-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-rockland-ny' AND county_id = 'rockland-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-rockland-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-rensselaer-ny' AND county_id = 'rensselaer-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-rensselaer-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-putnam-ny' AND county_id = 'putnam-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-putnam-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-otsego-ny' AND county_id = 'otsego-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-otsego-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-oswego-ny' AND county_id = 'oswego-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-oswego-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-orleans-ny' AND county_id = 'orleans-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-orleans-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-orange-ny' AND county_id = 'orange-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-orange-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-ontario-ny' AND county_id = 'ontario-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-ontario-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-onondaga-ny' AND county_id = 'onondaga-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-onondaga-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-oneida-ny' AND county_id = 'oneida-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-oneida-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-niagara-ny' AND county_id = 'niagara-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-niagara-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-nassau-ny' AND county_id = 'nassau-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-nassau-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-montgomery-ny' AND county_id = 'montgomery-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-montgomery-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-monroe-ny' AND county_id = 'monroe-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-monroe-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-madison-ny' AND county_id = 'madison-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-madison-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-livingston-ny' AND county_id = 'livingston-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-livingston-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-lewis-ny' AND county_id = 'lewis-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-lewis-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-jefferson-ny' AND county_id = 'jefferson-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-jefferson-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-herkimer-ny' AND county_id = 'herkimer-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-herkimer-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-hamilton-ny' AND county_id = 'hamilton-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-hamilton-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-greene-ny' AND county_id = 'greene-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-greene-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-genesee-ny' AND county_id = 'genesee-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-genesee-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-fulton-ny' AND county_id = 'fulton-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-fulton-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-franklin-ny' AND county_id = 'franklin-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-franklin-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-essex-ny' AND county_id = 'essex-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-essex-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-erie-ny' AND county_id = 'erie-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-erie-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-dutchess-ny' AND county_id = 'dutchess-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-dutchess-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-delaware-ny' AND county_id = 'delaware-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-delaware-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-cortland-ny' AND county_id = 'cortland-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-cortland-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-columbia-ny' AND county_id = 'columbia-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-columbia-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-clinton-ny' AND county_id = 'clinton-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-clinton-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-chenango-ny' AND county_id = 'chenango-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-chenango-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-chemung-ny' AND county_id = 'chemung-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-chemung-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-chautauqua-ny' AND county_id = 'chautauqua-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-chautauqua-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-cayuga-ny' AND county_id = 'cayuga-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-cayuga-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-cattaraugus-ny' AND county_id = 'cattaraugus-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-cattaraugus-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-broome-ny' AND county_id = 'broome-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-broome-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-allegany-ny' AND county_id = 'allegany-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-allegany-ny';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ny-ei-albany-ny' AND county_id = 'albany-ny';
DELETE FROM state_resource_agencies WHERE id = 'ny-ei-albany-ny';

COMMIT;
