-- Rollback Script for State: New York | Phase: education_regional
-- Generated At: 2026-06-13T20:53:03.228Z

BEGIN TRANSACTION;

DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-western-suffolk' AND county_id = 'suffolk-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-western-suffolk';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-wayne-finger-lakes' AND county_id = 'wayne-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-wayne-finger-lakes';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-wswhe' AND county_id = 'warren-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-wswhe' AND county_id = 'washington-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-wswhe';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-ulster' AND county_id = 'ulster-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-ulster';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-tst' AND county_id = 'seneca-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-tst' AND county_id = 'tompkins-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-tst';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-sullivan' AND county_id = 'sullivan-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-sullivan';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-greater-southern-tier' AND county_id = 'steuben-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-greater-southern-tier' AND county_id = 'schuyler-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-greater-southern-tier' AND county_id = 'chemung-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-greater-southern-tier';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-st-lawrence' AND county_id = 'st-lawrence-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-st-lawrence';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-rockland' AND county_id = 'rockland-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-rockland';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-questar-iii' AND county_id = 'greene-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-questar-iii' AND county_id = 'columbia-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-questar-iii' AND county_id = 'rensselaer-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-questar-iii';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-putnam-westchester' AND county_id = 'putnam-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-putnam-westchester';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-onc' AND county_id = 'otsego-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-onc';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-oswego' AND county_id = 'oswego-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-oswego';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-orleans-niagara' AND county_id = 'niagara-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-orleans-niagara';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-orange-ulster' AND county_id = 'orange-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-orange-ulster';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-oneida-herkimer' AND county_id = 'oneida-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-oneida-herkimer';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-monroe-2-orleans' AND county_id = 'orleans-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-monroe-2-orleans';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-madison-oneida' AND county_id = 'madison-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-madison-oneida';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-jefferson-lewis' AND county_id = 'lewis-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-jefferson-lewis' AND county_id = 'jefferson-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-jefferson-lewis';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-herkimer' AND county_id = 'herkimer-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-herkimer';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-hfm' AND county_id = 'montgomery-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-hfm' AND county_id = 'fulton-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-hfm';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-genesee-valley' AND county_id = 'livingston-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-genesee-valley' AND county_id = 'genesee-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-genesee-valley';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-franklin-essex' AND county_id = 'hamilton-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-franklin-essex' AND county_id = 'franklin-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-franklin-essex';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-erie-2-chautauqua' AND county_id = 'chautauqua-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-erie-2-chautauqua';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-dutchess' AND county_id = 'dutchess-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-dutchess';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-dcmo' AND county_id = 'otsego-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-dcmo' AND county_id = 'chenango-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-dcmo' AND county_id = 'delaware-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-dcmo';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-champlain-valley' AND county_id = 'essex-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-champlain-valley' AND county_id = 'clinton-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-champlain-valley';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-cayuga-onondaga' AND county_id = 'cayuga-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-cayuga-onondaga';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-cattaraugus-allegany' AND county_id = 'wyoming-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-cattaraugus-allegany' AND county_id = 'allegany-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-cattaraugus-allegany' AND county_id = 'cattaraugus-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-cattaraugus-allegany';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-broome-tioga' AND county_id = 'tioga-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-broome-tioga' AND county_id = 'broome-ny';
DELETE FROM regional_education_agencies WHERE id = 'ny-ed-boces-broome-tioga';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-albany' AND county_id = 'saratoga-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-albany' AND county_id = 'schenectady-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-albany' AND county_id = 'schoharie-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-albany' AND county_id = 'albany-ny';
UPDATE regional_education_agencies SET state_id = 'new-york', agency_type = 'boces', name = 'Capital Region BOCES', counties_served = 'albany-ny', website = 'https://www.capitalregionboces.org', source_url = 'https://www.capitalregionboces.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'ny-ed-boces-albany';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-onondaga' AND county_id = 'madison-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-onondaga' AND county_id = 'cortland-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-onondaga' AND county_id = 'onondaga-ny';
UPDATE regional_education_agencies SET state_id = 'new-york', agency_type = 'boces', name = 'OCM BOCES Special Education', counties_served = 'onondaga-ny', website = 'https://www.ocmboces.org', source_url = 'https://www.ocmboces.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'ny-ed-boces-onondaga';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-monroe' AND county_id = 'monroe-ny';
UPDATE regional_education_agencies SET state_id = 'new-york', agency_type = 'boces', name = 'Monroe 1 BOCES Special Education', counties_served = 'monroe-ny', website = 'https://www.monroe.edu', source_url = 'https://www.monroe.edu', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'ny-ed-boces-monroe';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-erie' AND county_id = 'erie-ny';
UPDATE regional_education_agencies SET state_id = 'new-york', agency_type = 'boces', name = 'Erie 1 BOCES Special Education', counties_served = 'erie-ny', website = 'https://www.e1b.org', source_url = 'https://www.e1b.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'ny-ed-boces-erie';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-westchester' AND county_id = 'westchester-ny';
UPDATE regional_education_agencies SET state_id = 'new-york', agency_type = 'boces', name = 'Southern Westchester BOCES', counties_served = 'westchester-ny', website = 'https://www.swboces.org', source_url = 'https://www.swboces.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'ny-ed-boces-westchester';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-suffolk' AND county_id = 'suffolk-ny';
UPDATE regional_education_agencies SET state_id = 'new-york', agency_type = 'boces', name = 'Eastern Suffolk BOCES', counties_served = 'suffolk-ny', website = 'https://www.esboces.org', source_url = 'https://www.esboces.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'ny-ed-boces-suffolk';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-nassau' AND county_id = 'nassau-ny';
UPDATE regional_education_agencies SET state_id = 'new-york', agency_type = 'boces', name = 'Nassau BOCES Special Education', counties_served = 'nassau-ny', website = 'https://www.nassauboces.org', source_url = 'https://www.nassauboces.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'ny-ed-boces-nassau';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-nyc' AND county_id = 'richmond-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-nyc' AND county_id = 'queens-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-nyc' AND county_id = 'new-york-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-nyc' AND county_id = 'kings-ny';
DELETE FROM selpa_counties WHERE selpa_id = 'ny-ed-boces-nyc' AND county_id = 'bronx-ny';
UPDATE regional_education_agencies SET state_id = 'new-york', agency_type = 'boces', name = 'NYC Committee on Special Education (CSE)', counties_served = 'kings-ny,queens-ny,new-york-ny,bronx-ny,richmond-ny', website = 'https://www.schools.nyc.gov/learning/special-education', source_url = 'https://www.schools.nyc.gov/learning/special-education', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'ny-ed-boces-nyc';

COMMIT;
