-- Rollback Script for State: Vermont | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:56:19.006Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'windsor-vt', program_id = 'vt-medicaid', office_name = 'Windsor County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-windsor-vt-medicaid';
UPDATE county_offices SET county_id = 'windham-vt', program_id = 'vt-medicaid', office_name = 'Windham County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-windham-vt-medicaid';
UPDATE county_offices SET county_id = 'washington-vt', program_id = 'vt-medicaid', office_name = 'Washington County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-washington-vt-medicaid';
UPDATE county_offices SET county_id = 'rutland-vt', program_id = 'vt-medicaid', office_name = 'Rutland County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-rutland-vt-medicaid';
UPDATE county_offices SET county_id = 'orleans-vt', program_id = 'vt-medicaid', office_name = 'Orleans County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-orleans-vt-medicaid';
UPDATE county_offices SET county_id = 'orange-vt', program_id = 'vt-medicaid', office_name = 'Orange County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-orange-vt-medicaid';
UPDATE county_offices SET county_id = 'lamoille-vt', program_id = 'vt-medicaid', office_name = 'Lamoille County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lamoille-vt-medicaid';
UPDATE county_offices SET county_id = 'grand-isle-vt', program_id = 'vt-medicaid', office_name = 'Grand Isle County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-grand-isle-vt-medicaid';
UPDATE county_offices SET county_id = 'franklin-vt', program_id = 'vt-medicaid', office_name = 'Franklin County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-franklin-vt-medicaid';
UPDATE county_offices SET county_id = 'essex-vt', program_id = 'vt-medicaid', office_name = 'Essex County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-essex-vt-medicaid';
UPDATE county_offices SET county_id = 'chittenden-vt', program_id = 'vt-medicaid', office_name = 'Chittenden County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-chittenden-vt-medicaid';
UPDATE county_offices SET county_id = 'caledonia-vt', program_id = 'vt-medicaid', office_name = 'Caledonia County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-caledonia-vt-medicaid';
UPDATE county_offices SET county_id = 'bennington-vt', program_id = 'vt-medicaid', office_name = 'Bennington County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-bennington-vt-medicaid';
UPDATE county_offices SET county_id = 'addison-vt', program_id = 'vt-medicaid', office_name = 'Addison County storefront office', address = '', phone = '(800) 250-8427', email = '', website = 'https://dvha.vermont.gov/', source_url = 'https://dvha.vermont.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-addison-vt-medicaid';

COMMIT;
