-- Rollback Script for State: Vermont | Phase: district_replacements
-- Generated At: 2026-06-15T21:56:20.674Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'windsor-vt', name = 'Windsor County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-windsor-vt';
UPDATE school_districts SET county_id = 'windham-vt', name = 'Windham County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-windham-vt';
UPDATE school_districts SET county_id = 'washington-vt', name = 'Washington County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-washington-vt';
UPDATE school_districts SET county_id = 'orleans-vt', name = 'Orleans County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-orleans-vt';
UPDATE school_districts SET county_id = 'orange-vt', name = 'Orange County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-orange-vt';
UPDATE school_districts SET county_id = 'lamoille-vt', name = 'Lamoille County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-lamoille-vt';
UPDATE school_districts SET county_id = 'grand-isle-vt', name = 'Grand Isle County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-grand-isle-vt';
UPDATE school_districts SET county_id = 'franklin-vt', name = 'Franklin County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-franklin-vt';
UPDATE school_districts SET county_id = 'essex-vt', name = 'Essex County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-essex-vt';
UPDATE school_districts SET county_id = 'caledonia-vt', name = 'Caledonia County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-caledonia-vt';
UPDATE school_districts SET county_id = 'bennington-vt', name = 'Bennington County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-bennington-vt';
UPDATE school_districts SET county_id = 'addison-vt', name = 'Addison County School District', spec_ed_contact_phone = '(802) 828-1130', spec_ed_contact_email = '', website = 'https://education.vermont.gov/student-support/special-education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.vermont.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-addison-vt';

COMMIT;
