-- Rollback Script for State: Vermont | Phase: district_replacements
-- Generated At: 2026-06-14T15:41:23.396Z

BEGIN TRANSACTION;

DELETE FROM school_districts WHERE id = 'sd-windsor-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-windsor-vt-fallback', 'windsor-vt', 'Windsor County School District Special Education', '(800) 555-0199', 'sped-fallback@windsor-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-windsor-vt-fallback' WHERE id = 'sd-windsor-vt';
DELETE FROM school_districts WHERE id = 'sd-windham-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-windham-vt-fallback', 'windham-vt', 'Windham County School District Special Education', '(800) 555-0199', 'sped-fallback@windham-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-windham-vt-fallback' WHERE id = 'sd-windham-vt';
DELETE FROM school_districts WHERE id = 'sd-washington-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-washington-vt-fallback', 'washington-vt', 'Washington County School District Special Education', '(800) 555-0199', 'sped-fallback@washington-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-washington-vt-fallback' WHERE id = 'sd-washington-vt';
DELETE FROM school_districts WHERE id = 'sd-orleans-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-orleans-vt-fallback', 'orleans-vt', 'Orleans County School District Special Education', '(800) 555-0199', 'sped-fallback@orleans-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-orleans-vt-fallback' WHERE id = 'sd-orleans-vt';
DELETE FROM school_districts WHERE id = 'sd-orange-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-orange-vt-fallback', 'orange-vt', 'Orange County School District Special Education', '(800) 555-0199', 'sped-fallback@orange-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-orange-vt-fallback' WHERE id = 'sd-orange-vt';
DELETE FROM school_districts WHERE id = 'sd-lamoille-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-lamoille-vt-fallback', 'lamoille-vt', 'Lamoille County School District Special Education', '(800) 555-0199', 'sped-fallback@lamoille-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-lamoille-vt-fallback' WHERE id = 'sd-lamoille-vt';
DELETE FROM school_districts WHERE id = 'sd-grand-isle-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-grand-isle-vt-fallback', 'grand-isle-vt', 'Grand Isle County School District Special Education', '(800) 555-0199', 'sped-fallback@grand-isle-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-grand-isle-vt-fallback' WHERE id = 'sd-grand-isle-vt';
DELETE FROM school_districts WHERE id = 'sd-franklin-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-franklin-vt-fallback', 'franklin-vt', 'Franklin County School District Special Education', '(800) 555-0199', 'sped-fallback@franklin-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-franklin-vt-fallback' WHERE id = 'sd-franklin-vt';
DELETE FROM school_districts WHERE id = 'sd-essex-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-essex-vt-fallback', 'essex-vt', 'Essex County School District Special Education', '(800) 555-0199', 'sped-fallback@essex-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-essex-vt-fallback' WHERE id = 'sd-essex-vt';
DELETE FROM school_districts WHERE id = 'sd-caledonia-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-caledonia-vt-fallback', 'caledonia-vt', 'Caledonia County School District Special Education', '(800) 555-0199', 'sped-fallback@caledonia-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-caledonia-vt-fallback' WHERE id = 'sd-caledonia-vt';
DELETE FROM school_districts WHERE id = 'sd-bennington-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-bennington-vt-fallback', 'bennington-vt', 'Bennington County School District Special Education', '(800) 555-0199', 'sped-fallback@bennington-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-bennington-vt-fallback' WHERE id = 'sd-bennington-vt';
DELETE FROM school_districts WHERE id = 'sd-addison-vt';
INSERT INTO school_districts (id, county_id, name, spec_ed_contact_phone, spec_ed_contact_email, website, total_enrollment, special_ed_pct, inclusion_rate_pct, self_contained_rate_pct, source_url, source_type, data_origin, verification_status, last_verified_date, last_scraped_at, confidence_score, evidence_level) VALUES ('sd-addison-vt-fallback', 'addison-vt', 'Addison County School District Special Education', '(800) 555-0199', 'sped-fallback@addison-vt.gov', 'https://www.vermont-education.gov', 5000, 12, 60, 20, 'https://www.vermont-education.gov', 'official', 'programmatic_fallback', 'generated_county_fallback', '2026-06-12', '2026-06-13T02:29:27.575Z', 3, NULL);
UPDATE school_districts SET id = 'sd-addison-vt-fallback' WHERE id = 'sd-addison-vt';

COMMIT;
