-- Rollback Script for State: North Carolina | Phase: dd_idd
-- Generated At: 2026-06-13T21:28:31.939Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-yancey' AND county_id = 'yancey-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-yancey';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-yadkin' AND county_id = 'yadkin-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-yadkin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-wilson' AND county_id = 'wilson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-wilson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-wilkes' AND county_id = 'wilkes-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-wilkes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-wayne' AND county_id = 'wayne-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-watauga' AND county_id = 'watauga-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-watauga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-washington' AND county_id = 'washington-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-warren' AND county_id = 'warren-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-wake' AND county_id = 'wake-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-wake';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-vance' AND county_id = 'vance-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-vance';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-union' AND county_id = 'union-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-union';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-tyrrell' AND county_id = 'tyrrell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-tyrrell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-transylvania' AND county_id = 'transylvania-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-transylvania';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-swain' AND county_id = 'swain-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-swain';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-surry' AND county_id = 'surry-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-surry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-stokes' AND county_id = 'stokes-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-stokes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-stanly' AND county_id = 'stanly-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-stanly';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-scotland' AND county_id = 'scotland-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-scotland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-sampson' AND county_id = 'sampson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-sampson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-rutherford' AND county_id = 'rutherford-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-rutherford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-rowan' AND county_id = 'rowan-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-rowan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-rockingham' AND county_id = 'rockingham-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-rockingham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-robeson' AND county_id = 'robeson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-robeson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-richmond' AND county_id = 'richmond-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-richmond';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-randolph' AND county_id = 'randolph-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-randolph';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-polk' AND county_id = 'polk-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-polk';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-pitt' AND county_id = 'pitt-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-pitt';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-person' AND county_id = 'person-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-person';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-perquimans' AND county_id = 'perquimans-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-perquimans';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-pender' AND county_id = 'pender-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-pender';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-pasquotank' AND county_id = 'pasquotank-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-pasquotank';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-pamlico' AND county_id = 'pamlico-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-pamlico';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-orange' AND county_id = 'orange-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-orange';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-onslow' AND county_id = 'onslow-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-onslow';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-northampton' AND county_id = 'northampton-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-northampton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-new-hanover' AND county_id = 'new-hanover-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-new-hanover';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-nash' AND county_id = 'nash-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-nash';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-moore' AND county_id = 'moore-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-moore';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-montgomery' AND county_id = 'montgomery-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-mitchell' AND county_id = 'mitchell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-mitchell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-mecklenburg' AND county_id = 'mecklenburg-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-mecklenburg';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-mcdowell' AND county_id = 'mcdowell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-mcdowell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-martin' AND county_id = 'martin-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-martin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-madison' AND county_id = 'madison-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-madison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-macon' AND county_id = 'macon-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-macon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-lincoln' AND county_id = 'lincoln-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-lincoln';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-lenoir' AND county_id = 'lenoir-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-lenoir';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-lee' AND county_id = 'lee-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-lee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-jones' AND county_id = 'jones-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-jones';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-johnston' AND county_id = 'johnston-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-johnston';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-jackson' AND county_id = 'jackson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-jackson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-iredell' AND county_id = 'iredell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-iredell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-hyde' AND county_id = 'hyde-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-hyde';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-hoke' AND county_id = 'hoke-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-hoke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-hertford' AND county_id = 'hertford-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-hertford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-henderson' AND county_id = 'henderson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-henderson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-haywood' AND county_id = 'haywood-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-haywood';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-harnett' AND county_id = 'harnett-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-harnett';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-halifax' AND county_id = 'halifax-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-halifax';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-guilford' AND county_id = 'guilford-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-guilford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-greene' AND county_id = 'greene-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-granville' AND county_id = 'granville-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-granville';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-graham' AND county_id = 'graham-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-graham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-gates' AND county_id = 'gates-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-gates';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-gaston' AND county_id = 'gaston-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-gaston';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-franklin' AND county_id = 'franklin-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-franklin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-forsyth' AND county_id = 'forsyth-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-forsyth';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-edgecombe' AND county_id = 'edgecombe-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-edgecombe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-durham' AND county_id = 'durham-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-durham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-duplin' AND county_id = 'duplin-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-duplin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-davie' AND county_id = 'davie-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-davie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-davidson' AND county_id = 'davidson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-davidson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-dare' AND county_id = 'dare-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-dare';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-currituck' AND county_id = 'currituck-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-currituck';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-cumberland' AND county_id = 'cumberland-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-cumberland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-craven' AND county_id = 'craven-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-craven';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-columbus' AND county_id = 'columbus-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-columbus';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-cleveland' AND county_id = 'cleveland-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-cleveland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-clay' AND county_id = 'clay-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-clay';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-chowan' AND county_id = 'chowan-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-chowan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-cherokee' AND county_id = 'cherokee-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-cherokee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-chatham' AND county_id = 'chatham-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-chatham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-catawba' AND county_id = 'catawba-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-catawba';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-caswell' AND county_id = 'caswell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-caswell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-carteret' AND county_id = 'carteret-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-carteret';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-camden' AND county_id = 'camden-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-camden';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-caldwell' AND county_id = 'caldwell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-caldwell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-cabarrus' AND county_id = 'cabarrus-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-cabarrus';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-burke' AND county_id = 'burke-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-burke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-buncombe' AND county_id = 'buncombe-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-buncombe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-brunswick' AND county_id = 'brunswick-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-brunswick';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-bladen' AND county_id = 'bladen-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-bladen';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-bertie' AND county_id = 'bertie-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-bertie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-beaufort' AND county_id = 'beaufort-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-beaufort';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-avery' AND county_id = 'avery-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-avery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-ashe' AND county_id = 'ashe-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-ashe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-anson' AND county_id = 'anson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-anson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-alleghany' AND county_id = 'alleghany-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-alleghany';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-alexander' AND county_id = 'alexander-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-alexander';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-dd-alamance' AND county_id = 'alamance-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-dd-alamance';

COMMIT;
