-- Rollback Script for State: North Carolina | Phase: early_intervention
-- Generated At: 2026-06-13T21:27:57.230Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-yancey' AND county_id = 'yancey-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-yancey';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-yadkin' AND county_id = 'yadkin-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-yadkin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-wilson' AND county_id = 'wilson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-wilson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-wilkes' AND county_id = 'wilkes-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-wilkes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-wayne' AND county_id = 'wayne-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-watauga' AND county_id = 'watauga-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-watauga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-washington' AND county_id = 'washington-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-warren' AND county_id = 'warren-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-wake' AND county_id = 'wake-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-wake';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-vance' AND county_id = 'vance-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-vance';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-union' AND county_id = 'union-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-union';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-tyrrell' AND county_id = 'tyrrell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-tyrrell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-transylvania' AND county_id = 'transylvania-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-transylvania';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-swain' AND county_id = 'swain-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-swain';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-surry' AND county_id = 'surry-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-surry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-stokes' AND county_id = 'stokes-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-stokes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-stanly' AND county_id = 'stanly-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-stanly';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-scotland' AND county_id = 'scotland-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-scotland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-sampson' AND county_id = 'sampson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-sampson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-rutherford' AND county_id = 'rutherford-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-rutherford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-rowan' AND county_id = 'rowan-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-rowan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-rockingham' AND county_id = 'rockingham-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-rockingham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-robeson' AND county_id = 'robeson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-robeson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-richmond' AND county_id = 'richmond-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-richmond';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-randolph' AND county_id = 'randolph-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-randolph';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-polk' AND county_id = 'polk-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-polk';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-pitt' AND county_id = 'pitt-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-pitt';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-person' AND county_id = 'person-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-person';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-perquimans' AND county_id = 'perquimans-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-perquimans';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-pender' AND county_id = 'pender-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-pender';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-pasquotank' AND county_id = 'pasquotank-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-pasquotank';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-pamlico' AND county_id = 'pamlico-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-pamlico';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-orange' AND county_id = 'orange-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-orange';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-onslow' AND county_id = 'onslow-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-onslow';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-northampton' AND county_id = 'northampton-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-northampton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-new-hanover' AND county_id = 'new-hanover-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-new-hanover';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-nash' AND county_id = 'nash-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-nash';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-moore' AND county_id = 'moore-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-moore';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-montgomery' AND county_id = 'montgomery-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-mitchell' AND county_id = 'mitchell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-mitchell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-mecklenburg' AND county_id = 'mecklenburg-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-mecklenburg';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-mcdowell' AND county_id = 'mcdowell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-mcdowell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-martin' AND county_id = 'martin-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-martin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-madison' AND county_id = 'madison-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-madison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-macon' AND county_id = 'macon-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-macon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-lincoln' AND county_id = 'lincoln-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-lincoln';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-lenoir' AND county_id = 'lenoir-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-lenoir';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-lee' AND county_id = 'lee-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-lee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-jones' AND county_id = 'jones-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-jones';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-johnston' AND county_id = 'johnston-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-johnston';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-jackson' AND county_id = 'jackson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-jackson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-iredell' AND county_id = 'iredell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-iredell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-hyde' AND county_id = 'hyde-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-hyde';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-hoke' AND county_id = 'hoke-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-hoke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-hertford' AND county_id = 'hertford-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-hertford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-henderson' AND county_id = 'henderson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-henderson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-haywood' AND county_id = 'haywood-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-haywood';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-harnett' AND county_id = 'harnett-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-harnett';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-halifax' AND county_id = 'halifax-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-halifax';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-guilford' AND county_id = 'guilford-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-guilford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-greene' AND county_id = 'greene-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-granville' AND county_id = 'granville-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-granville';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-graham' AND county_id = 'graham-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-graham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-gates' AND county_id = 'gates-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-gates';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-gaston' AND county_id = 'gaston-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-gaston';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-franklin' AND county_id = 'franklin-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-franklin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-forsyth' AND county_id = 'forsyth-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-forsyth';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-edgecombe' AND county_id = 'edgecombe-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-edgecombe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-durham' AND county_id = 'durham-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-durham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-duplin' AND county_id = 'duplin-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-duplin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-davie' AND county_id = 'davie-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-davie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-davidson' AND county_id = 'davidson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-davidson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-dare' AND county_id = 'dare-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-dare';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-currituck' AND county_id = 'currituck-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-currituck';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-cumberland' AND county_id = 'cumberland-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-cumberland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-craven' AND county_id = 'craven-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-craven';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-columbus' AND county_id = 'columbus-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-columbus';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-cleveland' AND county_id = 'cleveland-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-cleveland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-clay' AND county_id = 'clay-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-clay';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-chowan' AND county_id = 'chowan-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-chowan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-cherokee' AND county_id = 'cherokee-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-cherokee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-chatham' AND county_id = 'chatham-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-chatham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-catawba' AND county_id = 'catawba-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-catawba';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-caswell' AND county_id = 'caswell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-caswell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-carteret' AND county_id = 'carteret-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-carteret';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-camden' AND county_id = 'camden-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-camden';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-caldwell' AND county_id = 'caldwell-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-caldwell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-cabarrus' AND county_id = 'cabarrus-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-cabarrus';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-burke' AND county_id = 'burke-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-burke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-buncombe' AND county_id = 'buncombe-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-buncombe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-brunswick' AND county_id = 'brunswick-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-brunswick';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-bladen' AND county_id = 'bladen-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-bladen';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-bertie' AND county_id = 'bertie-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-bertie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-beaufort' AND county_id = 'beaufort-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-beaufort';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-avery' AND county_id = 'avery-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-avery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-ashe' AND county_id = 'ashe-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-ashe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-anson' AND county_id = 'anson-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-anson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-alleghany' AND county_id = 'alleghany-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-alleghany';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-alexander' AND county_id = 'alexander-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-alexander';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nc-ei-alamance' AND county_id = 'alamance-nc';
DELETE FROM state_resource_agencies WHERE id = 'nc-ei-alamance';

COMMIT;
