-- Rollback Script for State: Rhode Island | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:55:52.881Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'washington-ri', program_id = 'ri-medicaid', office_name = 'Washington County storefront office', address = '', phone = '(855) 697-4347', email = '', website = 'https://healthyrhode.ri.gov/', source_url = 'https://healthyrhode.ri.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-washington-ri-medicaid';
UPDATE county_offices SET county_id = 'providence-ri', program_id = 'ri-medicaid', office_name = 'Providence County storefront office', address = '', phone = '(855) 697-4347', email = '', website = 'https://healthyrhode.ri.gov/', source_url = 'https://healthyrhode.ri.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-providence-ri-medicaid';
UPDATE county_offices SET county_id = 'newport-ri', program_id = 'ri-medicaid', office_name = 'Newport County storefront office', address = '', phone = '(855) 697-4347', email = '', website = 'https://healthyrhode.ri.gov/', source_url = 'https://healthyrhode.ri.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-newport-ri-medicaid';
UPDATE county_offices SET county_id = 'kent-ri', program_id = 'ri-medicaid', office_name = 'Kent County storefront office', address = '', phone = '(855) 697-4347', email = '', website = 'https://healthyrhode.ri.gov/', source_url = 'https://healthyrhode.ri.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-kent-ri-medicaid';
UPDATE county_offices SET county_id = 'bristol-ri', program_id = 'ri-medicaid', office_name = 'Bristol County storefront office', address = '', phone = '(855) 697-4347', email = '', website = 'https://healthyrhode.ri.gov/', source_url = 'https://healthyrhode.ri.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-bristol-ri-medicaid';

COMMIT;
