-- Rollback Script for State: Utah | Phase: benefits_hhs
-- Generated At: 2026-06-15T19:14:37.451Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'weber-ut', program_id = 'ut-medicaid', office_name = 'Weber County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-weber-ut-medicaid';
UPDATE county_offices SET county_id = 'wayne-ut', program_id = 'ut-medicaid', office_name = 'Wayne County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-wayne-ut-medicaid';
UPDATE county_offices SET county_id = 'washington-ut', program_id = 'ut-medicaid', office_name = 'Washington County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-washington-ut-medicaid';
UPDATE county_offices SET county_id = 'wasatch-ut', program_id = 'ut-medicaid', office_name = 'Wasatch County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-wasatch-ut-medicaid';
UPDATE county_offices SET county_id = 'utah-ut', program_id = 'ut-medicaid', office_name = 'Utah County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-utah-ut-medicaid';
UPDATE county_offices SET county_id = 'uintah-ut', program_id = 'ut-medicaid', office_name = 'Uintah County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-uintah-ut-medicaid';
UPDATE county_offices SET county_id = 'tooele-ut', program_id = 'ut-medicaid', office_name = 'Tooele County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-tooele-ut-medicaid';
UPDATE county_offices SET county_id = 'summit-ut', program_id = 'ut-medicaid', office_name = 'Summit County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-summit-ut-medicaid';
UPDATE county_offices SET county_id = 'sevier-ut', program_id = 'ut-medicaid', office_name = 'Sevier County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-sevier-ut-medicaid';
UPDATE county_offices SET county_id = 'sanpete-ut', program_id = 'ut-medicaid', office_name = 'Sanpete County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-sanpete-ut-medicaid';
UPDATE county_offices SET county_id = 'san-juan-ut', program_id = 'ut-medicaid', office_name = 'San Juan County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-san-juan-ut-medicaid';
UPDATE county_offices SET county_id = 'salt-lake-ut', program_id = 'ut-medicaid', office_name = 'Salt Lake County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-salt-lake-ut-medicaid';
UPDATE county_offices SET county_id = 'rich-ut', program_id = 'ut-medicaid', office_name = 'Rich County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-rich-ut-medicaid';
UPDATE county_offices SET county_id = 'piute-ut', program_id = 'ut-medicaid', office_name = 'Piute County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-piute-ut-medicaid';
UPDATE county_offices SET county_id = 'morgan-ut', program_id = 'ut-medicaid', office_name = 'Morgan County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-morgan-ut-medicaid';
UPDATE county_offices SET county_id = 'millard-ut', program_id = 'ut-medicaid', office_name = 'Millard County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-millard-ut-medicaid';
UPDATE county_offices SET county_id = 'kane-ut', program_id = 'ut-medicaid', office_name = 'Kane County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-kane-ut-medicaid';
UPDATE county_offices SET county_id = 'juab-ut', program_id = 'ut-medicaid', office_name = 'Juab County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-juab-ut-medicaid';
UPDATE county_offices SET county_id = 'iron-ut', program_id = 'ut-medicaid', office_name = 'Iron County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-iron-ut-medicaid';
UPDATE county_offices SET county_id = 'grand-ut', program_id = 'ut-medicaid', office_name = 'Grand County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-grand-ut-medicaid';
UPDATE county_offices SET county_id = 'garfield-ut', program_id = 'ut-medicaid', office_name = 'Garfield County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-garfield-ut-medicaid';
UPDATE county_offices SET county_id = 'emery-ut', program_id = 'ut-medicaid', office_name = 'Emery County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-emery-ut-medicaid';
UPDATE county_offices SET county_id = 'duchesne-ut', program_id = 'ut-medicaid', office_name = 'Duchesne County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-duchesne-ut-medicaid';
UPDATE county_offices SET county_id = 'davis-ut', program_id = 'ut-medicaid', office_name = 'Davis County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-davis-ut-medicaid';
UPDATE county_offices SET county_id = 'daggett-ut', program_id = 'ut-medicaid', office_name = 'Daggett County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-daggett-ut-medicaid';
UPDATE county_offices SET county_id = 'carbon-ut', program_id = 'ut-medicaid', office_name = 'Carbon County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-carbon-ut-medicaid';
UPDATE county_offices SET county_id = 'cache-ut', program_id = 'ut-medicaid', office_name = 'Cache County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-cache-ut-medicaid';
UPDATE county_offices SET county_id = 'box-elder-ut', program_id = 'ut-medicaid', office_name = 'Box Elder County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-box-elder-ut-medicaid';
UPDATE county_offices SET county_id = 'beaver-ut', program_id = 'ut-medicaid', office_name = 'Beaver County storefront office', address = '', phone = '(800) 662-9651', email = '', website = 'https://medicaid.utah.gov/', source_url = 'https://medicaid.utah.gov/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-beaver-ut-medicaid';

COMMIT;
