-- Rollback Script for State: Utah | Phase: district_replacements
-- Generated At: 2026-06-15T19:14:38.746Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'weber-ut', name = 'Weber County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-weber-ut';
UPDATE school_districts SET county_id = 'wayne-ut', name = 'Wayne County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-wayne-ut';
UPDATE school_districts SET county_id = 'washington-ut', name = 'Washington County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-washington-ut';
UPDATE school_districts SET county_id = 'wasatch-ut', name = 'Wasatch County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-wasatch-ut';
UPDATE school_districts SET county_id = 'uintah-ut', name = 'Uintah County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-uintah-ut';
UPDATE school_districts SET county_id = 'tooele-ut', name = 'Tooele County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-tooele-ut';
UPDATE school_districts SET county_id = 'summit-ut', name = 'Summit County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-summit-ut';
UPDATE school_districts SET county_id = 'sevier-ut', name = 'Sevier County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-sevier-ut';
UPDATE school_districts SET county_id = 'sanpete-ut', name = 'Sanpete County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-sanpete-ut';
UPDATE school_districts SET county_id = 'san-juan-ut', name = 'San Juan County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-san-juan-ut';
UPDATE school_districts SET county_id = 'rich-ut', name = 'Rich County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-rich-ut';
UPDATE school_districts SET county_id = 'piute-ut', name = 'Piute County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-piute-ut';
UPDATE school_districts SET county_id = 'morgan-ut', name = 'Morgan County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-morgan-ut';
UPDATE school_districts SET county_id = 'millard-ut', name = 'Millard County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-millard-ut';
UPDATE school_districts SET county_id = 'kane-ut', name = 'Kane County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-kane-ut';
UPDATE school_districts SET county_id = 'juab-ut', name = 'Juab County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-juab-ut';
UPDATE school_districts SET county_id = 'iron-ut', name = 'Iron County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-iron-ut';
UPDATE school_districts SET county_id = 'grand-ut', name = 'Grand County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-grand-ut';
UPDATE school_districts SET county_id = 'garfield-ut', name = 'Garfield County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-garfield-ut';
UPDATE school_districts SET county_id = 'emery-ut', name = 'Emery County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-emery-ut';
UPDATE school_districts SET county_id = 'duchesne-ut', name = 'Duchesne County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-duchesne-ut';
UPDATE school_districts SET county_id = 'davis-ut', name = 'Davis County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-davis-ut';
UPDATE school_districts SET county_id = 'daggett-ut', name = 'Daggett County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-daggett-ut';
UPDATE school_districts SET county_id = 'carbon-ut', name = 'Carbon County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-carbon-ut';
UPDATE school_districts SET county_id = 'cache-ut', name = 'Cache County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-cache-ut';
UPDATE school_districts SET county_id = 'box-elder-ut', name = 'Box Elder County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-box-elder-ut';
UPDATE school_districts SET county_id = 'beaver-ut', name = 'Beaver County School District', spec_ed_contact_phone = '(801) 538-7587', spec_ed_contact_email = '', website = 'https://schools.utah.gov/specialeducation', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://schools.utah.gov/', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'sd-beaver-ut';

COMMIT;
