-- Rollback Script for State: Arkansas | Phase: dd_idd
-- Generated At: 2026-06-14T15:50:02.358Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'yell-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'woodruff-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'white-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'washington-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'van-buren-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'union-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'stone-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'st-francis-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'sharp-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'sevier-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'sebastian-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'searcy-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'scott-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'saline-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'randolph-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'pulaski-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'prairie-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'pope-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'polk-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'poinsett-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'pike-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'phillips-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'perry-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'ouachita-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'newton-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'nevada-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'montgomery-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'monroe-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'mississippi-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'miller-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'marion-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'madison-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'lonoke-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'logan-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'little-river-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'lincoln-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'lee-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'lawrence-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'lafayette-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'johnson-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'jefferson-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'jackson-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'izard-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'independence-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'howard-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'hot-spring-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'hempstead-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'greene-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'grant-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'garland-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'fulton-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'franklin-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'faulkner-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'drew-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'desha-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'dallas-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'cross-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'crittenden-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'crawford-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'craighead-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'conway-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'columbia-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'cleveland-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'cleburne-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'clay-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'clark-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'chicot-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'carroll-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'calhoun-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'bradley-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'boone-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'benton-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'baxter-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'ashley-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-dd-agency' AND county_id = 'arkansas-ar';
UPDATE state_resource_agencies SET state_id = 'arkansas', agency_type = 'dd_office', name = 'Arkansas Division of Developmental Disabilities Services', counties_served = 'arkansas-ar,ashley-ar,baxter-ar,benton-ar,boone-ar,bradley-ar,calhoun-ar,carroll-ar,chicot-ar,clark-ar,clay-ar,cleburne-ar,cleveland-ar,columbia-ar,conway-ar,craighead-ar,crawford-ar,crittenden-ar,cross-ar,dallas-ar,desha-ar,drew-ar,faulkner-ar,franklin-ar,fulton-ar,garland-ar,grant-ar,greene-ar,hempstead-ar,hot-spring-ar,howard-ar,independence-ar,izard-ar,jackson-ar,jefferson-ar,johnson-ar,lafayette-ar,lawrence-ar,lee-ar,lincoln-ar,little-river-ar,logan-ar,lonoke-ar,madison-ar,marion-ar,miller-ar,mississippi-ar,monroe-ar,montgomery-ar,nevada-ar,newton-ar,ouachita-ar,perry-ar,phillips-ar,pike-ar,poinsett-ar,polk-ar,pope-ar,prairie-ar,pulaski-ar,randolph-ar,st-francis-ar,saline-ar,scott-ar,searcy-ar,sebastian-ar,sevier-ar,sharp-ar,stone-ar,union-ar,van-buren-ar,washington-ar,white-ar,woodruff-ar,yell-ar', catchment_boundaries = 'Statewide coverage for all counties in Arkansas.', website = 'https://humanservices.arkansas.gov/dds', intake_phone = '(800) 555-0100', early_intervention_contact = '(800) 555-0100', agency_intake_contact = '(800) 555-0100', eligibility_info_page = 'https://humanservices.arkansas.gov/dds/eligibility', services_page = 'https://humanservices.arkansas.gov/dds', appeals_info = 'Waiver decisions can be appealed within 30 days of notice.', frc_relationship = NULL, office_locations = 'Arkansas State Capitol Office', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://humanservices.arkansas.gov/dds', source_url = 'https://humanservices.arkansas.gov/dds', source_type = 'official', data_origin = 'curated_seed', verification_status = 'source_listed', last_scraped_at = '2026-06-13T02:29:27.536Z', confidence_score = 5, evidence_level = NULL WHERE id = 'ar-dd-agency';

COMMIT;
