-- Rollback Script for State: Arkansas | Phase: early_intervention
-- Generated At: 2026-06-15T00:29:21.542Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'yell-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'woodruff-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'white-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'washington-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'van-buren-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'union-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'stone-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'st-francis-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'sharp-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'sevier-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'sebastian-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'searcy-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'scott-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'saline-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'randolph-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'pulaski-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'prairie-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'pope-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'polk-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'poinsett-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'pike-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'phillips-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'perry-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'ouachita-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'newton-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'nevada-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'montgomery-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'monroe-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'mississippi-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'miller-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'marion-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'madison-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'lonoke-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'logan-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'little-river-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'lincoln-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'lee-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'lawrence-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'lafayette-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'johnson-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'jefferson-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'jackson-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'izard-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'independence-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'howard-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'hot-spring-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'hempstead-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'greene-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'grant-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'garland-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'fulton-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'franklin-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'faulkner-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'drew-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'desha-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'dallas-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'cross-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'crittenden-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'crawford-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'craighead-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'conway-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'columbia-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'cleveland-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'cleburne-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'clay-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'clark-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'chicot-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'carroll-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'calhoun-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'bradley-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'boone-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'benton-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'baxter-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'ashley-ar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'ar-ei-agency' AND county_id = 'arkansas-ar';
UPDATE state_resource_agencies SET state_id = 'arkansas', agency_type = 'early_intervention', name = 'Arkansas Early Intervention State Office', counties_served = 'statewide', catchment_boundaries = 'statewide', website = 'https://dhhs.arkansas.gov/earlystart', intake_phone = '', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://dhhs.arkansas.gov/earlystart', source_url = 'https://dhhs.arkansas.gov/earlystart', source_type = 'official_website', data_origin = 'scraped', verification_status = 'manual_review_required', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'ar-ei-agency';

COMMIT;
