-- Rollback Script for State: Wisconsin | Phase: dd_idd
-- Generated At: 2026-06-15T19:58:33.599Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'wood-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'winnebago-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'waushara-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'waupaca-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'waukesha-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'washington-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'washburn-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'walworth-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'vilas-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'vernon-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'trempealeau-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'taylor-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'st-croix-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'sheboygan-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'shawano-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'sawyer-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'sauk-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'rusk-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'rock-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'richland-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'racine-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'price-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'portage-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'polk-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'pierce-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'pepin-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'ozaukee-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'outagamie-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'oneida-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'oconto-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'monroe-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'milwaukee-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'menominee-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'marquette-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'marinette-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'marathon-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'manitowoc-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'lincoln-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'langlade-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'lafayette-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'la-crosse-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'kewaunee-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'kenosha-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'juneau-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'jefferson-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'jackson-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'iron-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'iowa-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'green-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'green-lake-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'grant-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'forest-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'fond-du-lac-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'florence-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'eau-claire-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'dunn-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'douglas-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'door-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'dodge-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'dane-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'crawford-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'columbia-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'clark-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'chippewa-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'calumet-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'burnett-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'buffalo-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'brown-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'bayfield-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'barron-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'ashland-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-dd-agency' AND county_id = 'adams-wi';
UPDATE state_resource_agencies SET state_id = 'wisconsin', agency_type = 'dd_intake', name = 'Wisconsin Developmental Services Intake', counties_served = 'statewide', catchment_boundaries = 'statewide', website = 'https://dhhs.wisconsin.gov/dd', intake_phone = '', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://dhhs.wisconsin.gov/dd', source_url = 'https://dhhs.wisconsin.gov/dd', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'wi-dd-agency';

COMMIT;
