-- Rollback Script for State: Wisconsin | Phase: early_intervention
-- Generated At: 2026-06-14T15:49:43.074Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'wood-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'winnebago-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'waushara-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'waupaca-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'waukesha-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'washington-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'washburn-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'walworth-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'vilas-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'vernon-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'trempealeau-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'taylor-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'st-croix-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'sheboygan-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'shawano-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'sawyer-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'sauk-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'rusk-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'rock-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'richland-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'racine-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'price-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'portage-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'polk-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'pierce-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'pepin-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'ozaukee-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'outagamie-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'oneida-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'oconto-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'monroe-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'milwaukee-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'menominee-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'marquette-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'marinette-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'marathon-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'manitowoc-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'lincoln-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'langlade-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'lafayette-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'la-crosse-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'kewaunee-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'kenosha-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'juneau-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'jefferson-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'jackson-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'iron-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'iowa-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'green-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'green-lake-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'grant-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'forest-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'fond-du-lac-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'florence-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'eau-claire-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'dunn-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'douglas-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'door-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'dodge-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'dane-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'crawford-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'columbia-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'clark-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'chippewa-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'calumet-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'burnett-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'buffalo-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'brown-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'bayfield-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'barron-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'ashland-wi';
DELETE FROM regional_center_counties WHERE regional_center_id = 'wi-ei-agency' AND county_id = 'adams-wi';
DELETE FROM state_resource_agencies WHERE id = 'wi-ei-agency';

COMMIT;
