-- Rollback Script for State: Idaho | Phase: benefits_hhs
-- Generated At: 2026-06-15T00:04:15.109Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'washington-id', program_id = 'id-medicaid', office_name = 'Washington County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-washington-id-medicaid';
UPDATE county_offices SET county_id = 'valley-id', program_id = 'id-medicaid', office_name = 'Valley County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-valley-id-medicaid';
UPDATE county_offices SET county_id = 'twin-falls-id', program_id = 'id-medicaid', office_name = 'Twin Falls County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-twin-falls-id-medicaid';
UPDATE county_offices SET county_id = 'teton-id', program_id = 'id-medicaid', office_name = 'Teton County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-teton-id-medicaid';
UPDATE county_offices SET county_id = 'shoshone-id', program_id = 'id-medicaid', office_name = 'Shoshone County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-shoshone-id-medicaid';
UPDATE county_offices SET county_id = 'power-id', program_id = 'id-medicaid', office_name = 'Power County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-power-id-medicaid';
UPDATE county_offices SET county_id = 'payette-id', program_id = 'id-medicaid', office_name = 'Payette County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-payette-id-medicaid';
UPDATE county_offices SET county_id = 'owyhee-id', program_id = 'id-medicaid', office_name = 'Owyhee County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-owyhee-id-medicaid';
UPDATE county_offices SET county_id = 'oneida-id', program_id = 'id-medicaid', office_name = 'Oneida County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-oneida-id-medicaid';
UPDATE county_offices SET county_id = 'nez-perce-id', program_id = 'id-medicaid', office_name = 'Nez Perce County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-nez-perce-id-medicaid';
UPDATE county_offices SET county_id = 'minidoka-id', program_id = 'id-medicaid', office_name = 'Minidoka County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-minidoka-id-medicaid';
UPDATE county_offices SET county_id = 'madison-id', program_id = 'id-medicaid', office_name = 'Madison County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-madison-id-medicaid';
UPDATE county_offices SET county_id = 'lincoln-id', program_id = 'id-medicaid', office_name = 'Lincoln County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lincoln-id-medicaid';
UPDATE county_offices SET county_id = 'lewis-id', program_id = 'id-medicaid', office_name = 'Lewis County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lewis-id-medicaid';
UPDATE county_offices SET county_id = 'lemhi-id', program_id = 'id-medicaid', office_name = 'Lemhi County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lemhi-id-medicaid';
UPDATE county_offices SET county_id = 'latah-id', program_id = 'id-medicaid', office_name = 'Latah County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-latah-id-medicaid';
UPDATE county_offices SET county_id = 'kootenai-id', program_id = 'id-medicaid', office_name = 'Kootenai County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-kootenai-id-medicaid';
UPDATE county_offices SET county_id = 'jerome-id', program_id = 'id-medicaid', office_name = 'Jerome County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-jerome-id-medicaid';
UPDATE county_offices SET county_id = 'jefferson-id', program_id = 'id-medicaid', office_name = 'Jefferson County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-jefferson-id-medicaid';
UPDATE county_offices SET county_id = 'idaho-id', program_id = 'id-medicaid', office_name = 'Idaho County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-idaho-id-medicaid';
UPDATE county_offices SET county_id = 'gooding-id', program_id = 'id-medicaid', office_name = 'Gooding County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-gooding-id-medicaid';
UPDATE county_offices SET county_id = 'gem-id', program_id = 'id-medicaid', office_name = 'Gem County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-gem-id-medicaid';
UPDATE county_offices SET county_id = 'fremont-id', program_id = 'id-medicaid', office_name = 'Fremont County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-fremont-id-medicaid';
UPDATE county_offices SET county_id = 'franklin-id', program_id = 'id-medicaid', office_name = 'Franklin County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-franklin-id-medicaid';
UPDATE county_offices SET county_id = 'elmore-id', program_id = 'id-medicaid', office_name = 'Elmore County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-elmore-id-medicaid';
UPDATE county_offices SET county_id = 'custer-id', program_id = 'id-medicaid', office_name = 'Custer County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-custer-id-medicaid';
UPDATE county_offices SET county_id = 'clearwater-id', program_id = 'id-medicaid', office_name = 'Clearwater County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-clearwater-id-medicaid';
UPDATE county_offices SET county_id = 'clark-id', program_id = 'id-medicaid', office_name = 'Clark County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-clark-id-medicaid';
UPDATE county_offices SET county_id = 'cassia-id', program_id = 'id-medicaid', office_name = 'Cassia County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-cassia-id-medicaid';
UPDATE county_offices SET county_id = 'caribou-id', program_id = 'id-medicaid', office_name = 'Caribou County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-caribou-id-medicaid';
UPDATE county_offices SET county_id = 'canyon-id', program_id = 'id-medicaid', office_name = 'Canyon County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-canyon-id-medicaid';
UPDATE county_offices SET county_id = 'camas-id', program_id = 'id-medicaid', office_name = 'Camas County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-camas-id-medicaid';
UPDATE county_offices SET county_id = 'butte-id', program_id = 'id-medicaid', office_name = 'Butte County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-butte-id-medicaid';
UPDATE county_offices SET county_id = 'boundary-id', program_id = 'id-medicaid', office_name = 'Boundary County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-boundary-id-medicaid';
UPDATE county_offices SET county_id = 'bonneville-id', program_id = 'id-medicaid', office_name = 'Bonneville County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-bonneville-id-medicaid';
UPDATE county_offices SET county_id = 'bonner-id', program_id = 'id-medicaid', office_name = 'Bonner County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-bonner-id-medicaid';
UPDATE county_offices SET county_id = 'boise-id', program_id = 'id-medicaid', office_name = 'Boise County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-boise-id-medicaid';
UPDATE county_offices SET county_id = 'blaine-id', program_id = 'id-medicaid', office_name = 'Blaine County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-blaine-id-medicaid';
UPDATE county_offices SET county_id = 'bingham-id', program_id = 'id-medicaid', office_name = 'Bingham County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-bingham-id-medicaid';
UPDATE county_offices SET county_id = 'benewah-id', program_id = 'id-medicaid', office_name = 'Benewah County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-benewah-id-medicaid';
UPDATE county_offices SET county_id = 'bear-lake-id', program_id = 'id-medicaid', office_name = 'Bear Lake County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-bear-lake-id-medicaid';
UPDATE county_offices SET county_id = 'bannock-id', program_id = 'id-medicaid', office_name = 'Bannock County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-bannock-id-medicaid';
UPDATE county_offices SET county_id = 'adams-id', program_id = 'id-medicaid', office_name = 'Adams County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-adams-id-medicaid';
UPDATE county_offices SET county_id = 'ada-id', program_id = 'id-medicaid', office_name = 'Ada County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.idaho.gov/locations', source_url = 'https://dhhs.idaho.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-ada-id-medicaid';

COMMIT;
