-- Rollback Script for State: Oregon | Phase: benefits_hhs
-- Generated At: 2026-06-15T00:02:06.739Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'yamhill-or', program_id = 'or-medicaid', office_name = 'Yamhill County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-yamhill-or-medicaid';
UPDATE county_offices SET county_id = 'wheeler-or', program_id = 'or-medicaid', office_name = 'Wheeler County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-wheeler-or-medicaid';
UPDATE county_offices SET county_id = 'washington-or', program_id = 'or-medicaid', office_name = 'Washington County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-washington-or-medicaid';
UPDATE county_offices SET county_id = 'wasco-or', program_id = 'or-medicaid', office_name = 'Wasco County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-wasco-or-medicaid';
UPDATE county_offices SET county_id = 'wallowa-or', program_id = 'or-medicaid', office_name = 'Wallowa County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-wallowa-or-medicaid';
UPDATE county_offices SET county_id = 'union-or', program_id = 'or-medicaid', office_name = 'Union County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-union-or-medicaid';
UPDATE county_offices SET county_id = 'umatilla-or', program_id = 'or-medicaid', office_name = 'Umatilla County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-umatilla-or-medicaid';
UPDATE county_offices SET county_id = 'tillamook-or', program_id = 'or-medicaid', office_name = 'Tillamook County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-tillamook-or-medicaid';
UPDATE county_offices SET county_id = 'sherman-or', program_id = 'or-medicaid', office_name = 'Sherman County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-sherman-or-medicaid';
UPDATE county_offices SET county_id = 'polk-or', program_id = 'or-medicaid', office_name = 'Polk County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-polk-or-medicaid';
UPDATE county_offices SET county_id = 'multnomah-or', program_id = 'or-medicaid', office_name = 'Multnomah County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-multnomah-or-medicaid';
UPDATE county_offices SET county_id = 'morrow-or', program_id = 'or-medicaid', office_name = 'Morrow County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-morrow-or-medicaid';
UPDATE county_offices SET county_id = 'marion-or', program_id = 'or-medicaid', office_name = 'Marion County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-marion-or-medicaid';
UPDATE county_offices SET county_id = 'malheur-or', program_id = 'or-medicaid', office_name = 'Malheur County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-malheur-or-medicaid';
UPDATE county_offices SET county_id = 'linn-or', program_id = 'or-medicaid', office_name = 'Linn County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-linn-or-medicaid';
UPDATE county_offices SET county_id = 'lincoln-or', program_id = 'or-medicaid', office_name = 'Lincoln County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lincoln-or-medicaid';
UPDATE county_offices SET county_id = 'lane-or', program_id = 'or-medicaid', office_name = 'Lane County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lane-or-medicaid';
UPDATE county_offices SET county_id = 'lake-or', program_id = 'or-medicaid', office_name = 'Lake County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lake-or-medicaid';
UPDATE county_offices SET county_id = 'klamath-or', program_id = 'or-medicaid', office_name = 'Klamath County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-klamath-or-medicaid';
UPDATE county_offices SET county_id = 'josephine-or', program_id = 'or-medicaid', office_name = 'Josephine County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-josephine-or-medicaid';
UPDATE county_offices SET county_id = 'jefferson-or', program_id = 'or-medicaid', office_name = 'Jefferson County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-jefferson-or-medicaid';
UPDATE county_offices SET county_id = 'jackson-or', program_id = 'or-medicaid', office_name = 'Jackson County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-jackson-or-medicaid';
UPDATE county_offices SET county_id = 'hood-river-or', program_id = 'or-medicaid', office_name = 'Hood River County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-hood-river-or-medicaid';
UPDATE county_offices SET county_id = 'harney-or', program_id = 'or-medicaid', office_name = 'Harney County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-harney-or-medicaid';
UPDATE county_offices SET county_id = 'grant-or', program_id = 'or-medicaid', office_name = 'Grant County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-grant-or-medicaid';
UPDATE county_offices SET county_id = 'gilliam-or', program_id = 'or-medicaid', office_name = 'Gilliam County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-gilliam-or-medicaid';
UPDATE county_offices SET county_id = 'douglas-or', program_id = 'or-medicaid', office_name = 'Douglas County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-douglas-or-medicaid';
UPDATE county_offices SET county_id = 'deschutes-or', program_id = 'or-medicaid', office_name = 'Deschutes County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-deschutes-or-medicaid';
UPDATE county_offices SET county_id = 'curry-or', program_id = 'or-medicaid', office_name = 'Curry County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-curry-or-medicaid';
UPDATE county_offices SET county_id = 'crook-or', program_id = 'or-medicaid', office_name = 'Crook County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-crook-or-medicaid';
UPDATE county_offices SET county_id = 'coos-or', program_id = 'or-medicaid', office_name = 'Coos County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-coos-or-medicaid';
UPDATE county_offices SET county_id = 'columbia-or', program_id = 'or-medicaid', office_name = 'Columbia County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-columbia-or-medicaid';
UPDATE county_offices SET county_id = 'clatsop-or', program_id = 'or-medicaid', office_name = 'Clatsop County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-clatsop-or-medicaid';
UPDATE county_offices SET county_id = 'clackamas-or', program_id = 'or-medicaid', office_name = 'Clackamas County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-clackamas-or-medicaid';
UPDATE county_offices SET county_id = 'benton-or', program_id = 'or-medicaid', office_name = 'Benton County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-benton-or-medicaid';
UPDATE county_offices SET county_id = 'baker-or', program_id = 'or-medicaid', office_name = 'Baker County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.oregon.gov/locations', source_url = 'https://dhhs.oregon.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-baker-or-medicaid';

COMMIT;
