-- Rollback Script for State: South Carolina | Phase: benefits_hhs
-- Generated At: 2026-06-15T00:22:59.299Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'york-sc', program_id = 'sc-medicaid', office_name = 'York County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-york-sc-medicaid';
UPDATE county_offices SET county_id = 'williamsburg-sc', program_id = 'sc-medicaid', office_name = 'Williamsburg County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-williamsburg-sc-medicaid';
UPDATE county_offices SET county_id = 'union-sc', program_id = 'sc-medicaid', office_name = 'Union County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-union-sc-medicaid';
UPDATE county_offices SET county_id = 'sumter-sc', program_id = 'sc-medicaid', office_name = 'Sumter County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-sumter-sc-medicaid';
UPDATE county_offices SET county_id = 'spartanburg-sc', program_id = 'sc-medicaid', office_name = 'Spartanburg County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-spartanburg-sc-medicaid';
UPDATE county_offices SET county_id = 'saluda-sc', program_id = 'sc-medicaid', office_name = 'Saluda County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-saluda-sc-medicaid';
UPDATE county_offices SET county_id = 'richland-sc', program_id = 'sc-medicaid', office_name = 'Richland County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-richland-sc-medicaid';
UPDATE county_offices SET county_id = 'pickens-sc', program_id = 'sc-medicaid', office_name = 'Pickens County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-pickens-sc-medicaid';
UPDATE county_offices SET county_id = 'orangeburg-sc', program_id = 'sc-medicaid', office_name = 'Orangeburg County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-orangeburg-sc-medicaid';
UPDATE county_offices SET county_id = 'oconee-sc', program_id = 'sc-medicaid', office_name = 'Oconee County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-oconee-sc-medicaid';
UPDATE county_offices SET county_id = 'newberry-sc', program_id = 'sc-medicaid', office_name = 'Newberry County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-newberry-sc-medicaid';
UPDATE county_offices SET county_id = 'marlboro-sc', program_id = 'sc-medicaid', office_name = 'Marlboro County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-marlboro-sc-medicaid';
UPDATE county_offices SET county_id = 'marion-sc', program_id = 'sc-medicaid', office_name = 'Marion County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-marion-sc-medicaid';
UPDATE county_offices SET county_id = 'mccormick-sc', program_id = 'sc-medicaid', office_name = 'McCormick County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-mccormick-sc-medicaid';
UPDATE county_offices SET county_id = 'lexington-sc', program_id = 'sc-medicaid', office_name = 'Lexington County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lexington-sc-medicaid';
UPDATE county_offices SET county_id = 'lee-sc', program_id = 'sc-medicaid', office_name = 'Lee County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lee-sc-medicaid';
UPDATE county_offices SET county_id = 'laurens-sc', program_id = 'sc-medicaid', office_name = 'Laurens County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-laurens-sc-medicaid';
UPDATE county_offices SET county_id = 'lancaster-sc', program_id = 'sc-medicaid', office_name = 'Lancaster County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-lancaster-sc-medicaid';
UPDATE county_offices SET county_id = 'kershaw-sc', program_id = 'sc-medicaid', office_name = 'Kershaw County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-kershaw-sc-medicaid';
UPDATE county_offices SET county_id = 'jasper-sc', program_id = 'sc-medicaid', office_name = 'Jasper County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-jasper-sc-medicaid';
UPDATE county_offices SET county_id = 'horry-sc', program_id = 'sc-medicaid', office_name = 'Horry County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-horry-sc-medicaid';
UPDATE county_offices SET county_id = 'hampton-sc', program_id = 'sc-medicaid', office_name = 'Hampton County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-hampton-sc-medicaid';
UPDATE county_offices SET county_id = 'greenwood-sc', program_id = 'sc-medicaid', office_name = 'Greenwood County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-greenwood-sc-medicaid';
UPDATE county_offices SET county_id = 'greenville-sc', program_id = 'sc-medicaid', office_name = 'Greenville County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-greenville-sc-medicaid';
UPDATE county_offices SET county_id = 'georgetown-sc', program_id = 'sc-medicaid', office_name = 'Georgetown County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-georgetown-sc-medicaid';
UPDATE county_offices SET county_id = 'florence-sc', program_id = 'sc-medicaid', office_name = 'Florence County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-florence-sc-medicaid';
UPDATE county_offices SET county_id = 'fairfield-sc', program_id = 'sc-medicaid', office_name = 'Fairfield County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-fairfield-sc-medicaid';
UPDATE county_offices SET county_id = 'edgefield-sc', program_id = 'sc-medicaid', office_name = 'Edgefield County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-edgefield-sc-medicaid';
UPDATE county_offices SET county_id = 'dorchester-sc', program_id = 'sc-medicaid', office_name = 'Dorchester County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-dorchester-sc-medicaid';
UPDATE county_offices SET county_id = 'dillon-sc', program_id = 'sc-medicaid', office_name = 'Dillon County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-dillon-sc-medicaid';
UPDATE county_offices SET county_id = 'darlington-sc', program_id = 'sc-medicaid', office_name = 'Darlington County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-darlington-sc-medicaid';
UPDATE county_offices SET county_id = 'colleton-sc', program_id = 'sc-medicaid', office_name = 'Colleton County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-colleton-sc-medicaid';
UPDATE county_offices SET county_id = 'clarendon-sc', program_id = 'sc-medicaid', office_name = 'Clarendon County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-clarendon-sc-medicaid';
UPDATE county_offices SET county_id = 'chesterfield-sc', program_id = 'sc-medicaid', office_name = 'Chesterfield County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-chesterfield-sc-medicaid';
UPDATE county_offices SET county_id = 'chester-sc', program_id = 'sc-medicaid', office_name = 'Chester County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-chester-sc-medicaid';
UPDATE county_offices SET county_id = 'cherokee-sc', program_id = 'sc-medicaid', office_name = 'Cherokee County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-cherokee-sc-medicaid';
UPDATE county_offices SET county_id = 'charleston-sc', program_id = 'sc-medicaid', office_name = 'Charleston County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-charleston-sc-medicaid';
UPDATE county_offices SET county_id = 'calhoun-sc', program_id = 'sc-medicaid', office_name = 'Calhoun County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-calhoun-sc-medicaid';
UPDATE county_offices SET county_id = 'berkeley-sc', program_id = 'sc-medicaid', office_name = 'Berkeley County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-berkeley-sc-medicaid';
UPDATE county_offices SET county_id = 'beaufort-sc', program_id = 'sc-medicaid', office_name = 'Beaufort County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-beaufort-sc-medicaid';
UPDATE county_offices SET county_id = 'barnwell-sc', program_id = 'sc-medicaid', office_name = 'Barnwell County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-barnwell-sc-medicaid';
UPDATE county_offices SET county_id = 'bamberg-sc', program_id = 'sc-medicaid', office_name = 'Bamberg County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-bamberg-sc-medicaid';
UPDATE county_offices SET county_id = 'anderson-sc', program_id = 'sc-medicaid', office_name = 'Anderson County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-anderson-sc-medicaid';
UPDATE county_offices SET county_id = 'allendale-sc', program_id = 'sc-medicaid', office_name = 'Allendale County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-allendale-sc-medicaid';
UPDATE county_offices SET county_id = 'aiken-sc', program_id = 'sc-medicaid', office_name = 'Aiken County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-aiken-sc-medicaid';
UPDATE county_offices SET county_id = 'abbeville-sc', program_id = 'sc-medicaid', office_name = 'Abbeville County storefront office', address = '', phone = '', email = NULL, website = 'https://dhhs.south-carolina.gov/locations', source_url = 'https://dhhs.south-carolina.gov/locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'off-abbeville-sc-medicaid';

COMMIT;
