-- Rollback Script for State: Washington | Phase: benefits_hhs
-- Generated At: 2026-06-15T19:15:36.937Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'yakima-wa', program_id = 'wa-medicaid', office_name = 'Yakima County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-yakima-wa-medicaid';
UPDATE county_offices SET county_id = 'whitman-wa', program_id = 'wa-medicaid', office_name = 'Whitman County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-whitman-wa-medicaid';
UPDATE county_offices SET county_id = 'whatcom-wa', program_id = 'wa-medicaid', office_name = 'Whatcom County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-whatcom-wa-medicaid';
DELETE FROM county_offices WHERE id = 'off-wallalla-wa-wa-medicaid';
UPDATE county_offices SET county_id = 'wahkiakum-wa', program_id = 'wa-medicaid', office_name = 'Wahkiakum County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-wahkiakum-wa-medicaid';
UPDATE county_offices SET county_id = 'thurston-wa', program_id = 'wa-medicaid', office_name = 'Thurston County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-thurston-wa-medicaid';
UPDATE county_offices SET county_id = 'stevens-wa', program_id = 'wa-medicaid', office_name = 'Stevens County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-stevens-wa-medicaid';
UPDATE county_offices SET county_id = 'spokane-wa', program_id = 'wa-medicaid', office_name = 'Spokane County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-spokane-wa-medicaid';
UPDATE county_offices SET county_id = 'snohomish-wa', program_id = 'wa-medicaid', office_name = 'Snohomish County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-snohomish-wa-medicaid';
UPDATE county_offices SET county_id = 'skamania-wa', program_id = 'wa-medicaid', office_name = 'Skamania County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-skamania-wa-medicaid';
UPDATE county_offices SET county_id = 'skagit-wa', program_id = 'wa-medicaid', office_name = 'Skagit County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-skagit-wa-medicaid';
UPDATE county_offices SET county_id = 'san-juan-wa', program_id = 'wa-medicaid', office_name = 'San Juan County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-san-juan-wa-medicaid';
UPDATE county_offices SET county_id = 'pierce-wa', program_id = 'wa-medicaid', office_name = 'Pierce County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-pierce-wa-medicaid';
UPDATE county_offices SET county_id = 'pend-oreille-wa', program_id = 'wa-medicaid', office_name = 'Pend Oreille County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-pend-oreille-wa-medicaid';
UPDATE county_offices SET county_id = 'pacific-wa', program_id = 'wa-medicaid', office_name = 'Pacific County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-pacific-wa-medicaid';
UPDATE county_offices SET county_id = 'okanogan-wa', program_id = 'wa-medicaid', office_name = 'Okanogan County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-okanogan-wa-medicaid';
UPDATE county_offices SET county_id = 'mason-wa', program_id = 'wa-medicaid', office_name = 'Mason County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-mason-wa-medicaid';
UPDATE county_offices SET county_id = 'lincoln-wa', program_id = 'wa-medicaid', office_name = 'Lincoln County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lincoln-wa-medicaid';
UPDATE county_offices SET county_id = 'lewis-wa', program_id = 'wa-medicaid', office_name = 'Lewis County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-lewis-wa-medicaid';
UPDATE county_offices SET county_id = 'klickitat-wa', program_id = 'wa-medicaid', office_name = 'Klickitat County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-klickitat-wa-medicaid';
UPDATE county_offices SET county_id = 'kittitas-wa', program_id = 'wa-medicaid', office_name = 'Kittitas County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-kittitas-wa-medicaid';
UPDATE county_offices SET county_id = 'kitsap-wa', program_id = 'wa-medicaid', office_name = 'Kitsap County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-kitsap-wa-medicaid';
UPDATE county_offices SET county_id = 'king-wa', program_id = 'wa-medicaid', office_name = 'King County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-king-wa-medicaid';
UPDATE county_offices SET county_id = 'jefferson-wa', program_id = 'wa-medicaid', office_name = 'Jefferson County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-jefferson-wa-medicaid';
UPDATE county_offices SET county_id = 'island-wa', program_id = 'wa-medicaid', office_name = 'Island County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-island-wa-medicaid';
UPDATE county_offices SET county_id = 'grays-harbor-wa', program_id = 'wa-medicaid', office_name = 'Grays Harbor County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-grays-harbor-wa-medicaid';
UPDATE county_offices SET county_id = 'grant-wa', program_id = 'wa-medicaid', office_name = 'Grant County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-grant-wa-medicaid';
UPDATE county_offices SET county_id = 'garfield-wa', program_id = 'wa-medicaid', office_name = 'Garfield County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-garfield-wa-medicaid';
UPDATE county_offices SET county_id = 'franklin-wa', program_id = 'wa-medicaid', office_name = 'Franklin County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-franklin-wa-medicaid';
UPDATE county_offices SET county_id = 'ferry-wa', program_id = 'wa-medicaid', office_name = 'Ferry County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-ferry-wa-medicaid';
UPDATE county_offices SET county_id = 'douglas-wa', program_id = 'wa-medicaid', office_name = 'Douglas County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-douglas-wa-medicaid';
UPDATE county_offices SET county_id = 'cowlitz-wa', program_id = 'wa-medicaid', office_name = 'Cowlitz County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-cowlitz-wa-medicaid';
UPDATE county_offices SET county_id = 'columbia-wa', program_id = 'wa-medicaid', office_name = 'Columbia County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-columbia-wa-medicaid';
UPDATE county_offices SET county_id = 'clark-wa', program_id = 'wa-medicaid', office_name = 'Clark County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-clark-wa-medicaid';
UPDATE county_offices SET county_id = 'clallam-wa', program_id = 'wa-medicaid', office_name = 'Clallam County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-clallam-wa-medicaid';
UPDATE county_offices SET county_id = 'chelan-wa', program_id = 'wa-medicaid', office_name = 'Chelan County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-chelan-wa-medicaid';
UPDATE county_offices SET county_id = 'benton-wa', program_id = 'wa-medicaid', office_name = 'Benton County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-benton-wa-medicaid';
UPDATE county_offices SET county_id = 'asotin-wa', program_id = 'wa-medicaid', office_name = 'Asotin County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-asotin-wa-medicaid';
UPDATE county_offices SET county_id = 'adams-wa', program_id = 'wa-medicaid', office_name = 'Adams County storefront office', address = '', phone = '(877) 501-2233', email = '', website = 'https://www.washingtonconnection.org/', source_url = 'https://www.dshs.wa.gov/office-locations', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-adams-wa-medicaid';

COMMIT;
