export const DIAGNOSES = [
  // Developmental & Behavioral
  'Autism Spectrum Disorder (ASD)',
  'Attention Deficit Hyperactivity Disorder (ADHD)',
  'Sensory Processing Disorder (SPD)',
  'Speech and Language Delay',
  'Global Developmental Delay (GDD)',
  'Developmental Coordination Disorder (Dyspraxia)',
  'Pervasive Developmental Disorder (PDD-NOS)',
  'Oppositional Defiant Disorder (ODD)',
  'Reactive Attachment Disorder (RAD)',
  'Apraxia of Speech',
  'Social Communication Disorder',
  
  // Genetic & Chromosomal
  'Down Syndrome (Trisomy 21)',
  'Fragile X Syndrome',
  'Rett Syndrome',
  'Prader-Willi Syndrome',
  'Angelman Syndrome',
  'Williams Syndrome',
  'Turner Syndrome',
  'Klinefelter Syndrome (XXY)',
  'Cri-du-Chat Syndrome',
  'DiGeorge Syndrome (22q11.2 deletion)',
  'Trisomy 18 (Edwards Syndrome)',
  'Trisomy 13 (Patau Syndrome)',
  'Noonan Syndrome',
  'Rabin-Kopp Syndrome',
  
  // Neurological & Physical
  'Cerebral Palsy (CP)',
  'Spina Bifida',
  'Muscular Dystrophy (Duchenne)',
  'Muscular Dystrophy (Becker)',
  'Spinal Muscular Atrophy (SMA)',
  'Microcephaly',
  'Hydrocephalus',
  'Epilepsy / Seizure Disorder',
  'Tourette Syndrome',
  'Traumatic Brain Injury (TBI)',
  'Arthrogryposis Multiplex Congenita',
  'Neurofibromatosis Type 1 (NF1)',
  'Neurofibromatosis Type 2 (NF2)',
  'Mitochondrial Disease',
  'Rasmussen Encephalitis',
  'Lennox-Gastaut Syndrome',
  'Dravet Syndrome',
  'Landau-Kleffner Syndrome',
  'Aicardi Syndrome',
  
  // Sensory Impairments
  'Hearing Loss / Deafness',
  'Visual Impairment / Blindness',
  'Cortical Visual Impairment (CVI)',
  'Deaf-Blindness',
  'Auditory Processing Disorder (APD)',
  'Optic Nerve Hypoplasia (ONH)',
  'Retinopathy of Prematurity (ROP)',
  'Usher Syndrome',
  
  // Learning & Cognitive
  'Intellectual Disability (ID)',
  'Dyslexia',
  'Dysgraphia',
  'Dyscalculia',
  'Executive Function Disorder',
  'Nonverbal Learning Disability (NVLD)',
  'Auditory Dyslexia',
  
  // Congenital & Medical Fragility
  'Congenital Heart Disease (CHD)',
  'Cystic Fibrosis (CF)',
  'Sickle Cell Disease',
  'Type 1 Diabetes',
  'Severe Persistent Asthma',
  'Pediatric Cancer / Leukemia',
  'Tracheostomy Dependency',
  'Ventilator Dependency',
  'Short Bowel Syndrome',
  'Chronic Kidney Disease (CKD)',
  'Gastrostomy (G-tube) Dependency',
  'Severe Hemophilia',
  'Juvenile Idiopathic Arthritis (JIA)',
  
  // Other IDEA special education categories
  'Orthopedic Impairment',
  'Other Health Impairment (OHI)',
  'Specific Learning Disability (SLD)',
  'Emotional Disturbance (ED)',
  'Multiple Disabilities',
  'Developmental Delay (CA Education Code)'
].sort();
