export interface SEOPageData {
  slug: string;
  category: 'programs' | 'conditions' | 'forms' | 'deadlines' | 'situations' | 'counties';
  title: string;
  metaTitle: string;
  metaDescription: string;
  quickAnswer: string;
  tldrPoints: { label: string; value: string }[];
  whenThisMatters: string;
  signsThisMayApply: string[];
  whatToDoFirst: string[];
  documentsToGather: { name: string; description: string; downloadUrl?: string }[];
  whoToCall: { name: string; number?: string; description: string }[];
  whatToSay: string;
  commonMistakes: string[];
  relatedGuides: { title: string; url: string }[];
  officialSources: { name: string; url: string }[];
  lastReviewedDate: string;
  callScriptTemplate: {
    intro: string;
    script: string;
    tips: string;
  };
  letterTemplate?: {
    title: string;
    description: string;
    fields: { key: string; label: string; placeholder: string; defaultValue?: string }[];
    generateFn: (fields: Record<string, string>) => string;
  };
  eligibilityQuiz: {
    question: string;
    options: { text: string; score: 'high' | 'med' | 'low'; reason: string }[];
  }[];
}

export const SEO_CLUSTERS: Record<string, SEOPageData> = {
  'down-syndrome-benefits-california': {
    slug: 'down-syndrome-benefits-california',
    category: 'situations',
    title: 'Down Syndrome Benefits in California: Complete Guide to State Aid',
    metaTitle: 'Down Syndrome Benefits California | Public Programs & Aid Guide',
    metaDescription: 'Complete guide for California parents on securing Regional Center services, IHSS, Institutional Deeming Medi-Cal, SSI, and CalABLE for children with Down Syndrome.',
    quickAnswer: 'Yes. In California, children with Down Syndrome (Trisomy 21) are legally entitled to comprehensive public benefits and developmental supports. This includes Regional Center services (respite, speech therapy, IFSP/IPP planning), In-Home Supportive Services (IHSS - tax-free monthly stipends for parent caregivers), Medi-Cal via the Institutional Deeming Waiver (ignoring family income), federal SSI monthly payments, and CalABLE savings accounts.',
    tldrPoints: [
      { label: 'Est. IHSS Payout', value: '$2,000 - $5,200/mo' },
      { label: 'Medi-Cal Income Waiver', value: 'Parent Income Ignored' },
      { label: 'SSI Child Payout', value: 'Up to $1,100+/mo' },
      { label: 'Regional Center Age', value: '0 - Lifetime eligibility' }
    ],
    whenThisMatters: 'Immediately upon birth or clinical diagnosis. Early intervention services under the IFSP cover ages 0 to 3, and Lanterman Act services apply from age 3 throughout adulthood.',
    signsThisMayApply: [
      'Genetic testing showing Trisomy 21, translocation Down syndrome, or mosaic Down syndrome.',
      'Significant delays in gross motor skills (rolling, sitting, walking) or speech.',
      'Medical co-morbidities such as congenital heart defects, thyroid conditions, or sleep apnea.',
      'Difficulty navigating school classroom tasks or community environments.'
    ],
    whatToDoFirst: [
      'Contact your local California Regional Center to request a Lanterman Act eligibility assessment.',
      'Submit a written request to your local school district special education department for an IEP psycho-educational assessment.',
      'Open a tax-free CalABLE account to protect future asset limits for government aid.',
      'Apply for the Medi-Cal Institutional Deeming Waiver through your Regional Center coordinator to bypass parental income limits.'
    ],
    documentsToGather: [
      { name: 'Genetic Karyotype Diagnostic Report', description: 'Confirming diagnosis of Trisomy 21 or equivalent translocation.' },
      { name: 'Pediatric Medical Records & Clinical Summaries', description: 'Including cardiology, audiology, and speech therapy clinical reports.' },
      { name: 'Individualized Family Service Plan (IFSP) / IPP', description: 'The official service plans generated by your local Regional Center coordinator.' },
      { name: 'School District IEP Report', description: 'The latest assessment report showing academic and speech goals.' }
    ],
    whoToCall: [
      { name: 'California Department of Developmental Services (DDS)', number: '(916) 654-1690', description: 'State administrative office for California\'s 21 Regional Centers.' },
      { name: 'County DPSS / Social Services Intake', description: 'Select your county below for direct phone lines to begin your child\'s IHSS application.' }
    ],
    whatToSay: 'I am calling to request a Lanterman Act intake assessment for my child who has Down Syndrome. I want to establish Regional Center services, coordinate physical and speech therapies, and apply for the Institutional Deeming Medi-Cal waiver.',
    commonMistakes: [
      'Assuming your family income is too high to qualify for Medi-Cal. The Institutional Deeming Waiver bypasses parental income, evaluating only the child\'s assets.',
      'Waiting until school age to contact the Regional Center. Early Start intervention provides speech and motor support starting at birth.',
      'Failing to specify cognitive and safety deficits when applying for IHSS hours.'
    ],
    relatedGuides: [
      { title: 'IHSS for Children in California', url: '/programs/ihss-for-children' },
      { title: 'Understanding Form SOC 873', url: '/forms/soc-873' },
      { title: 'CalABLE Disability Accounts', url: '/programs/calable' }
    ],
    officialSources: [
      { name: 'California DDS Lanterman Act Resources', url: 'https://www.dds.ca.gov/transparency/lanterman-act-rules-and-regulations/' },
      { name: 'California Department of Social Services (CDSS) IHSS', url: 'https://www.cdss.ca.gov/in-home-supportive-services' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'Regional Center Lanterman Intake Call Script',
      script: 'Hello, my name is [Parent Name]. I am calling to request a Lanterman Act intake assessment for my child, [Child Name], who was born on [DOB] and has a clinical diagnosis of Down Syndrome. I would like to request an intake coordinator be assigned to establish services, coordinate speech and physical therapy evaluations, and initiate the institutional deeming waiver application for Medi-Cal. Please send me the intake packet and details of next steps.',
      tips: 'Always ask for the email address of the intake coordinator and send a follow-up email confirming your verbal request. Under California law, Regional Centers have strict timelines to act on written intake requests.'
    },
    letterTemplate: {
      title: 'Lanterman Regional Center Intake Request Letter',
      description: 'Formal written request to establish Regional Center services under the Lanterman Act.',
      fields: [
        { key: 'parentName', label: 'Parent/Guardian Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child\'s Name', placeholder: 'Tommy Doe' },
        { key: 'dob', label: 'Child\'s Date of Birth', placeholder: '10/12/2021' },
        { key: 'rcName', label: 'Regional Center Name', placeholder: 'Westside Regional Center' },
        { key: 'concerns', label: 'Developmental Concerns', placeholder: 'Speech delay, hypotonia, and cardiac anomalies associated with Down Syndrome.' }
      ],
      generateFn: (f) => `Date: ${new Date().toLocaleDateString()}

To: Intake Coordinator
${f.rcName || 'Local Regional Center'}

RE: Request for Lanterman Act Eligibility Assessment
Child's Name: ${f.childName || '[Child Name]'}
Date of Birth: ${f.dob || '[DOB]'}

Dear Intake Coordinator,

I am writing to formally request a Lanterman Act eligibility assessment for my child, ${f.childName || '[Child Name]'}, who has a clinical diagnosis of Down Syndrome (Trisomy 21).

My child exhibits developmental delays and functional limitations in the following areas:
${f.concerns || 'Speech and language delays, motor coordination difficulties, and self-care limitations.'}

Under the Lanterman Developmental Disabilities Services Act (California Welfare and Institutions Code Section 4500 et seq.), my child is entitled to a diagnostic assessment to establish eligibility for Regional Center services. Please contact me within the statutory 15-day timeline to schedule the intake interview and assessment.

Thank you for your assistance.

Sincerely,

${f.parentName || '[Parent Name]'}
Phone: [Insert Phone Number]
Email: [Insert Email Address]`
    },
    eligibilityQuiz: [
      {
        question: 'Does your child have a genetic karyotype report confirming Down Syndrome?',
        options: [
          { text: 'Yes, Trisomy 21 or Translocation confirmed', score: 'high', reason: 'This establishes clinical diagnosis, making Regional Center and Medical eligibility highly probable.' },
          { text: 'Diagnosis is suspected but genetic test is pending', score: 'med', reason: 'You should request the genetic report from your pediatrician to speed up intake approval.' },
          { text: 'No genetic test has been performed', score: 'low', reason: 'Genetic validation is required for direct condition-based eligibility, though delays alone can still qualify.' }
        ]
      },
      {
        question: 'Is your child currently receiving services from a Regional Center?',
        options: [
          { text: 'Yes, on an active IFSP or IPP', score: 'high', reason: 'Existing RC enrollment makes bypassing parent income via the Institutional Deeming Medi-Cal waiver straightforward.' },
          { text: 'No, we have never applied', score: 'med', reason: 'Your first priority should be establishing Regional Center intake, as other waivers depend on it.' }
        ]
      }
    ]
  },
  'ihss-for-children': {
    slug: 'ihss-for-children',
    category: 'programs',
    title: 'In-Home Supportive Services (IHSS) for Children in California',
    metaTitle: 'IHSS for Children California | Complete Caregiver Pay Guide',
    metaDescription: 'Learn how parent caregivers of minor children can receive paid IHSS caregiving hours in California. Calculate wages, understand eligibility, and apply.',
    quickAnswer: 'Yes, minor children under age 18 with developmental disabilities can qualify for the California In-Home Supportive Services (IHSS) program. The program pays parent caregivers to provide essential physical care (bathing, dressing, feeding) and safety monitoring. Monthly hours can range from 20 to 283 hours, paid at local county minimum wages ($18.00–$22.00/hour) and exempt from federal and state income taxes under IRS Notice 2014-7.',
    tldrPoints: [
      { label: 'Max Monthly Hours', value: '283 Hours' },
      { label: 'Est. Monthly Wage', value: '$3,200 - $5,800/mo' },
      { label: 'Income Tax Status', value: '100% Tax-Exempt' },
      { label: 'Parent Eligibility', value: 'Paid to parent if co-residing' }
    ],
    whenThisMatters: 'When your child\'s care needs exceed those of a typically developing child of the same age. Usually, application begins after age 2 when developmental delays and behavior safety risks become clear.',
    signsThisMayApply: [
      'The child has a developmental disability (Autism, Cerebral Palsy, Down Syndrome).',
      'The child requires significantly more time to feed, bathe, diaper, or dress than typical peers.',
      'The child exhibits dangerous self-injurious, aggressive, or elopement behaviors.',
      'The child is enrolled in Medi-Cal (or qualifies via a Regional Center waiver).'
    ],
    whatToDoFirst: [
      'Ensure your child has active Medi-Cal coverage (standard or waiver-based).',
      'Call your local County IHSS intake office to request an initial application packet.',
      'Schedule a pediatrician appointment to have Form SOC 873 signed.',
      'Start tracking your child\'s daily physical care routines and behavioral safety events.'
    ],
    documentsToGather: [
      { name: 'Form SOC 873 (Medical Certification)', description: 'Signed and dated by your pediatrician confirming medical necessity.' },
      { name: 'Medi-Cal Card or Approval Notice', description: 'Confirming active coverage under a valid case number.' },
      { name: 'School IEP & Developmental Reports', description: 'Documenting behavioral deficits and specialized school support.' },
      { name: 'Daily Care Logs & Symptom Notebooks', description: 'Detailing extra hours spent on bathing, feeding, and medical care.' }
    ],
    whoToCall: [
      { name: 'County Social Services / DPSS', description: 'Call the local intake line for your county to request an intake packet.' }
    ],
    whatToSay: 'I want to apply for In-Home Supportive Services (IHSS) for my minor child who has developmental disabilities. They are active on Medi-Cal and require significant physical care and constant supervision due to cognitive deficits.',
    commonMistakes: [
      'Assuming minor children are excluded because of standard parental responsibility rules. The county must evaluate the extra care required beyond typical parenting.',
      'Failing to obtain the signed Form SOC 873 within the strict 45-day intake window.',
      'Neglecting to document self-direction deficits (lack of safety awareness).'
    ],
    relatedGuides: [
      { title: 'IHSS Protective Supervision Guide', url: '/situations/ihss-protective-supervision' },
      { title: 'Form SOC 873 Requirements', url: '/forms/soc-873' },
      { title: 'Medi-Cal EPSDT Benefits', url: '/programs/medi-cal-epsdt' }
    ],
    officialSources: [
      { name: 'California CDSS IHSS Information', url: 'https://www.cdss.ca.gov/in-home-supportive-services' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'IHSS Minor Intake Request Script',
      script: 'Hello, I am calling to apply for In-Home Supportive Services (IHSS) on behalf of my minor child, [Child Name], who has [Diagnosis]. They are [Age] years old and active on Medi-Cal under case number [Medi-Cal #]. Due to their developmental disability, they require substantial extra care for feeding, bathing, and hygiene, and they have severe safety risks requiring constant monitoring. Please mail me the IHSS intake packet and SOC 873 form.',
      tips: 'Ensure the intake worker notes down your child\'s Medi-Cal number. If your child is not yet on Medi-Cal, establish Regional Center waiver status first.'
    },
    letterTemplate: {
      title: 'Pediatrician Request for SOC 873 Signature',
      description: 'A template letter to send to your child\'s pediatrician to explain the importance of Form SOC 873.',
      fields: [
        { key: 'doctorName', label: 'Pediatrician\'s Name', placeholder: 'Dr. Sarah Smith' },
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child\'s Name', placeholder: 'Tommy Doe' },
        { key: 'diagnosis', label: 'Child\'s Diagnosis', placeholder: 'Autism Spectrum Disorder' }
      ],
      generateFn: (f) => `Date: ${new Date().toLocaleDateString()}

Dear ${f.doctorName || 'Doctor'},

I am applying for In-Home Supportive Services (IHSS) on behalf of my child, ${f.childName || '[Child Name]'}, who is under your care for ${f.diagnosis || 'their developmental condition'}.

The California Department of Social Services requires a completed Form SOC 873 (Medical Certification) to process our application. This form verifies that my child has a chronic physical or mental impairment that limits their ability to perform activities of daily living safely.

Given my child's severe cognitive delays, lack of safety awareness, and substantial physical care needs (which far exceed those of a typically developing child of the same age), I would appreciate it if you could complete and sign the attached SOC 873 form. 

Please pay specific attention to the section indicating if the child requires constant supervision to prevent self-harm or accidental injury.

Once completed, please return it to me or fax it directly to the county office.

Thank you for your continuous support of my child's health and development.

Sincerely,

${f.parentName || '[Parent Name]'}`
    },
    eligibilityQuiz: [
      {
        question: 'Does your child have active Medi-Cal coverage?',
        options: [
          { text: 'Yes, full scope Medi-Cal', score: 'high', reason: 'Medi-Cal is the primary funding source for IHSS. You are ready to apply.' },
          { text: 'No, but enrolled in a Regional Center', score: 'med', reason: 'You can bypass family income limits via the Institutional Deeming waiver to get Medi-Cal, then apply for IHSS.' },
          { text: 'No, family income is too high', score: 'low', reason: 'Standard Medi-Cal has low income limits. Apply for Regional Center services first to get the income waiver.' }
        ]
      },
      {
        question: 'How much physical care does your child need compared to typical peers?',
        options: [
          { text: 'Significantly more (diapers at age 5, total feeding assistance, etc.)', score: 'high', reason: 'This establishes the "extraordinary care" threshold required to authorize IHSS hours for minors.' },
          { text: 'Slightly more (needs prompting but physically capable)', score: 'med', reason: 'Prompts can qualify for hours, but you must document the severe cognitive direction deficits.' }
        ]
      }
    ]
  },
  'ihss-protective-supervision': {
    slug: 'ihss-protective-supervision',
    category: 'situations',
    title: 'IHSS Protective Supervision California: How to Secure 24/7 Hours',
    metaTitle: 'IHSS Protective Supervision | Secure 24/7 Caregiver Pay',
    metaDescription: 'A complete step-by-step parent advocate guide to qualifying for IHSS Protective Supervision in California. Download templates, checklists, and forms.',
    quickAnswer: 'IHSS Protective Supervision is a specialized benefit tier in California that pays parent caregivers up to 195 or 283 hours monthly (worth $3,500 to $5,800/mo tax-free) to monitor children with severe cognitive impairments. To qualify, you must prove your child lacks safety awareness, is "non-self-directing," and is prone to dangerous, impulsive behaviors (wandering, climbing, eating non-food items) requiring constant visual monitoring.',
    tldrPoints: [
      { label: 'Max Monthly Pay', value: 'Up to $5,800/mo tax-free' },
      { label: 'Mandatory Physician Form', value: 'Form SOC 821' },
      { label: 'Evidence Needed', value: '24-Hour Safety Incident Log' },
      { label: 'Statutory Authority', value: 'CDSS MPP Section 30-757' }
    ],
    whenThisMatters: 'If your child has a developmental condition (Autism, Down Syndrome, GDD, TBI) and frequently engages in behaviors that put them in physical danger (elopement, pica, playing with stoves, climbing heights).',
    signsThisMayApply: [
      'The child runs out of the house into traffic or parking lots without stopping.',
      'The child attempts to swallow non-food items (coins, Lego bricks, dirt, cleaners).',
      'The child climbs tall shelves or window ledges without understanding fall risks.',
      'The child dial hot stoves, plays with electrical outlets, or tries to touch open wires.'
    ],
    whatToDoFirst: [
      'Request Form SOC 821 (Assessment of Need for Protective Supervision) from your IHSS caseworker.',
      'Schedule a clinical consultation with your pediatrician to complete the SOC 821 form.',
      'Begin keeping a detailed 24-Hour Safety Incident Log for at least 14 days.',
      'Review your child\'s IEP for goals related to safety awareness, wandering, or self-injurious actions.'
    ],
    documentsToGather: [
      { name: 'Form SOC 821', description: 'Physician assessment of memory, orientation, and judgment. Critical legal document.' },
      { name: '24-Hour Safety Incident Log', description: 'User-created table of incidents, actions, and avoided injuries.' },
      { name: 'IEP and Regional Center IPP Documents', description: 'Official reports demonstrating cognitive delays and visual structure needs.' },
      { name: 'Home modification receipts', description: 'Invoices for security locks, window bars, alarms, or padded rooms.' }
    ],
    whoToCall: [
      { name: 'County IHSS Office Coordinator', description: 'Request the Protective Supervision evaluation packet from your assigned caseworker.' }
    ],
    whatToSay: 'I am requesting a Protective Supervision assessment for my child who is non-self-directing due to cognitive delays. They have zero safety awareness and perform hazardous behaviors daily, requiring constant visual monitoring to prevent injury.',
    commonMistakes: [
      'Arguing that the child needs supervision for physical limitations. Physical issues (e.g. wheelchair bounds) are covered under basic personal care, not Protective Supervision.',
      'Failing to write down safety incidents because you "prevented them in time." The county needs to see the child\'s raw impulses, not just the successful block.',
      'Having the pediatrician write "child needs 24/7 care" without clinical justifications on the SOC 821.'
    ],
    relatedGuides: [
      { title: 'IHSS for Children Guide', url: '/programs/ihss-for-children' },
      { title: 'How to Complete Form SOC 873', url: '/forms/soc-873' },
      { title: 'Form SOC 821 Deep-Dive', url: '/forms/soc-821' }
    ],
    officialSources: [
      { name: 'CDSS MPP Manual Section 30-757', url: 'https://www.cdss.ca.gov/ord/entres/getinfo/pdf/ippm2.pdf' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'Requesting Protective Supervision Evaluation',
      script: 'Hello, I am calling my child\'s IHSS caseworker to formally request a reassessment of hours to include Protective Supervision. My child has displayed severe cognitive deficits and a complete lack of safety awareness. They are engaging in dangerous behaviors, including eloping and pica, which require my constant visual monitoring to avoid serious injury. Please send me Form SOC 821 to have completed by our doctor.',
      tips: 'State clearly that your child is "non-self-directing" as this is the exact legal keyword the caseworker looks for.'
    },
    letterTemplate: {
      title: 'Pediatrician Briefing Document for SOC 821 Completion',
      description: 'A template explaining the exact legal requirements to share with your pediatrician when they complete Form SOC 821.',
      fields: [
        { key: 'doctorName', label: 'Pediatrician Name', placeholder: 'Dr. Smith' },
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child Name', placeholder: 'Tommy Doe' },
        { key: 'behaviors', label: 'Dangerous Behaviors Summary', placeholder: ' Tommy attempts to swallow small metal objects, run into the street, and climb bookcases.' }
      ],
      generateFn: (f) => `Dear ${f.doctorName || 'Doctor'},

I am requesting your assistance in completing Form SOC 821 (Assessment of Need for Protective Supervision) for my child, ${f.childName || '[Child Name]'}.

To qualify under California state law (CDSS MPP 30-757), the county requires medical certification that my child has a severe cognitive impairment and is "non-self-directing." This means they cannot assess danger and require constant monitoring to prevent severe self-harm or injury.

Please note the following behaviors my child frequently exhibits:
${f.behaviors || 'Elopement, pica, and unsafe climbing.'}

When filling out the SOC 821 form, please ensure that you rate my child as "severely impaired" in the categories of Memory, Orientation, and Judgment, as these relate to their developmental age and safety deficits.

Your clinical assessment is the most critical piece of evidence to secure these essential home care resources.

Thank you,

${f.parentName || '[Parent Name]'}`
    },
    eligibilityQuiz: [
      {
        question: 'Does your child understand basic danger (e.g. will they stop at a red light or touch a hot iron)?',
        options: [
          { text: 'No, they will walk into traffic or touch a hot stove without hesitation', score: 'high', reason: 'This confirms they are non-self-directing, which is the core criteria for Protective Supervision.' },
          { text: 'They understand some rules but ignore them when distracted', score: 'med', reason: 'You must show their disobedience is a cognitive deficit, not just standard toddler behavior.' },
          { text: 'Yes, they understand danger but choose to push boundaries', score: 'low', reason: 'If they can evaluate danger, the county will deny Protective Supervision, classifying it as discipline issues.' }
        ]
      },
      {
        question: 'Has your child attempted to escape the home, eat non-food items, or injure themselves?',
        options: [
          { text: 'Yes, multiple times per week', score: 'high', reason: 'These active dangerous behaviors justify the need for 24/7 visual monitoring.' },
          { text: 'Rarely, but we have high security locks to prevent it', score: 'med', reason: 'You must document the impulses they would act on if the locks were not there.' }
        ]
      }
    ]
  },
  'soc-873': {
    slug: 'soc-873',
    category: 'forms',
    title: 'Form SOC 873: IHSS Medical Certification Guide',
    metaTitle: 'Form SOC 873 California | IHSS Medical Certification Guide',
    metaDescription: 'Step-by-step parent guide to completing California Form SOC 873 for In-Home Supportive Services. Download forms and pediatric letters.',
    quickAnswer: 'Form SOC 873 is the official California In-Home Supportive Services (IHSS) Medical Certification form. Under Welfare and Institutions Code Section 12301.24, you must submit this signed form to the county within 45 days of initiating your application. Without a completed SOC 873 signed by a licensed doctor, psychologist, or nurse practitioner confirming the child has a chronic impairment, the county cannot conduct a home assessment.',
    tldrPoints: [
      { label: 'Forms PDF Link', value: 'Download CDSS official' },
      { label: 'Submission Window', value: 'Strict 45 calendar days' },
      { label: 'Authorized Signer', value: 'Licensed MD, DO, or Psychologist' },
      { label: 'Form Objective', value: 'Verify chronic impairment' }
    ],
    whenThisMatters: 'Immediately after calling the county to apply for IHSS. The county will mail you the form, but downloading and filling it out early speeds up approval.',
    signsThisMayApply: [
      'You are initiating a new IHSS application for your child.',
      'Your child has an official diagnosis of Autism, Cerebral Palsy, or Down Syndrome.',
      'The child has active Medi-Cal coverage established.'
    ],
    whatToDoFirst: [
      'Download the official Form SOC 873 PDF.',
      'Schedule an urgent pediatrician visit specifically to get the form signed.',
      'Brief the doctor on the child\'s daily functional deficits so they complete it accurately.',
      'Keep a copy of the signed form for your records before faxing it to the county.'
    ],
    documentsToGather: [
      { name: 'Form SOC 873 PDF', description: 'The official blank form to be filled out by the clinician.', downloadUrl: 'https://www.cdss.ca.gov/Portals/9/FMUD/Forms/Form-English/SOC873.pdf' },
      { name: 'Pediatric Clinical Notes', description: 'Supporting diagnostic files to verify the physician\'s ratings.' }
    ],
    whoToCall: [
      { name: 'County IHSS Office Fax Intake', description: 'Request the local intake fax number from your county worker.' }
    ],
    whatToSay: 'I am requesting my pediatrician review my child\'s functional care needs and sign the SOC 873 Medical Certification form to submit to the county IHSS office within the 45-day deadline.',
    commonMistakes: [
      'Allowing the pediatrician to leave the "Out-of-Home Care" recommendation blank. If they do, the county may deny the case.',
      'Missing the 45-day filing deadline, which cancels the application and forces you to start over.',
      'Failing to verify that the doctor\'s license number is written clearly on the form.'
    ],
    relatedGuides: [
      { title: 'IHSS for Children Guide', url: '/programs/ihss-for-children' },
      { title: 'Form SOC 821 Assessment Guide', url: '/forms/soc-821' },
      { title: 'IHSS Protective Supervision', url: '/situations/ihss-protective-supervision' }
    ],
    officialSources: [
      { name: 'California CDSS Forms Portal', url: 'https://www.cdss.ca.gov/inforesources/forms-licensing/dss-forms-by-number/soc' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'Pediatrician Office Call Script for SOC 873',
      script: 'Hello, I am calling to schedule an appointment or request a signed document from Dr. [Doctor Name] for my child, [Child Name]. We are applying for California\'s IHSS program, and the state requires a completed Form SOC 873 Medical Certification signed by their pediatrician. I have the form ready. Can I drop it off, or should I schedule a brief telehealth visit to review it?',
      tips: 'Let the receptionist know that this form does not require complex medical billing, it is a standard state disability verification form.'
    },
    letterTemplate: {
      title: 'Form SOC 873 Follow-up Email to Medical Office',
      description: 'A formal template to follow up with your doctor\'s administrative staff regarding the signature status of your SOC 873.',
      fields: [
        { key: 'doctorName', label: 'Doctor\'s Name', placeholder: 'Dr. Smith' },
        { key: 'childName', label: 'Child\'s Name', placeholder: 'Tommy Doe' },
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'daysLeft', label: 'Days Left in Deadline', placeholder: '15' }
      ],
      generateFn: (f) => `Subject: URGENT: Form SOC 873 for ${f.childName || '[Child Name]'} - 45-day County Deadline

Dear ${f.doctorName || 'Doctor\'s Office Staff'},

I am writing to follow up on the In-Home Supportive Services (IHSS) Medical Certification (Form SOC 873) that I submitted for ${f.childName || '[Child Name]\'s'} signature.

As a reminder, California law mandates that this signed form be received by the county social services office within 45 days of our intake. We currently have only ${f.daysLeft || '15'} days remaining to submit the certified form or our case will be closed.

Please let me know if Dr. ${f.doctorName || 'Smith'} has had a chance to sign the form, or if you need me to provide any additional clinical records or schedule a brief consultation.

Thank you for your prompt assistance with this crucial deadline.

Best regards,

${f.parentName || '[Parent Name]'}
Phone: [Insert Phone Number]`
    },
    eligibilityQuiz: [
      {
        question: 'Who will sign your child\'s medical certification form?',
        options: [
          { text: 'Licensed Pediatrician or MD', score: 'high', reason: 'Licensed MDs and DOs are fully recognized by CDSS to certify disability.' },
          { text: 'Licensed Clinical Psychologist', score: 'high', reason: 'Psychologists are authorized to sign, especially for cognitive and behavior cases.' },
          { text: 'Therapist (OT, PT, Speech) or Social Worker', score: 'low', reason: 'Caseworkers and therapists are NOT authorized to sign the SOC 873. It must be a licensed physician or clinical psychologist.' }
        ]
      }
    ]
  },
  'iep-evaluation-request': {
    slug: 'iep-evaluation-request',
    category: 'situations',
    title: 'California IEP Evaluation Request: Step-by-Step Parent Guide',
    metaTitle: 'IEP Evaluation Request California | Form Assessment Letter',
    metaDescription: 'Complete guide for California parents on requesting a school district special education IEP assessment. Download letter templates.',
    quickAnswer: 'In California, if your child has a developmental disability or learning delay, you have the legal right under the IDEA Act to request a free, comprehensive psycho-educational evaluation from your local school district. To start this process, you must submit a written IEP evaluation request. The district is legally mandated to provide an Assessment Plan within 15 calendar days of receiving your request.',
    tldrPoints: [
      { label: 'District Deadline', value: '15 Days to provide Assessment Plan' },
      { label: 'Evaluation Timeline', value: '60 Days from consent' },
      { label: 'Legal Authority', value: 'IDEA Act / CA Ed Code 56321' },
      { label: 'Assessment Cost', value: '100% Free' }
    ],
    whenThisMatters: 'As soon as your child reaches age 2.9 (if transitioning from Early Start) or at any point during preschool or K-12 if they struggle with speech, focus, motor skills, or social-emotional dynamics.',
    signsThisMayApply: [
      'The child is struggling to keep up academically or socially in school.',
      'The child has a clinical diagnosis (Autism, ADHD, Dyslexia, Speech Delay).',
      'The teacher reports frequent behavioral challenges or sensory dysregulation.',
      'The child has difficulty communicating, reading, or processing instructions.'
    ],
    whatToDoFirst: [
      'Identify the Special Education Director or Principal for your local school district.',
      'Draft a formal IEP evaluation request letter detailing all areas of suspected disability.',
      'Submit the letter via email (providing a timestamped paper trail) or certified mail.',
      'Follow up if you do not receive the Assessment Plan within the 15-day timeline.'
    ],
    documentsToGather: [
      { name: 'Formal Written Request Letter', description: 'Written template requesting assessments under Ed Code 56321.' },
      { name: 'Private medical and therapy reports', description: 'Clinical proof of ADHD, speech delays, or sensory needs.' },
      { name: 'Sample school work & teacher feedback', description: 'Exhibits showing difficulties in classroom learning.' }
    ],
    whoToCall: [
      { name: 'Local School District Special Education Coordinator', description: 'Call the district office to find the specific contact details for intakes.' }
    ],
    whatToSay: 'I am requesting a comprehensive special education assessment for my child under the IDEA Child Find mandate. I want speech, occupational therapy, and psycho-educational testing scheduled.',
    commonMistakes: [
      'Making the request verbally. School districts are not bound by verbal requests; the 15-day statutory timeline only begins upon receipt of a written letter.',
      'Allowing the school to steer you toward a 504 Plan instead of an IEP if your child needs specialized instruction.',
      'Signing an Assessment Plan that excludes critical testing areas (e.g. omitting speech or OT).'
    ],
    relatedGuides: [
      { title: 'California IEP Timeline Rules', url: '/deadlines/california-iep-timeline' },
      { title: 'Early Start Transition (IFSP to IEP)', url: '/situations/early-start-age-3-transition' },
      { title: 'IEP Goal Library', url: '/dashboard?tab=iep' }
    ],
    officialSources: [
      { name: 'California Department of Education Special Ed', url: 'https://www.cde.ca.gov/sp/se/' },
      { name: 'Disability Rights California IEP Pubs', url: 'https://www.disabilityrightsca.org/publications/special-education-iep' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'School District Special Ed Intake Call',
      script: 'Hello, I am calling to find the name and email address of the Director of Special Education for [School District]. I want to submit a formal written request for a comprehensive special education evaluation for my child. Could you please provide the correct intake coordinator\'s contact details?',
      tips: 'Always direct your request to the district office rather than the individual classroom teacher to ensure the 15-day timeline is tracked by administrators.'
    },
    letterTemplate: {
      title: 'Special Education Assessment Request Letter',
      description: 'Formal letter to submit to the School District Special Ed Director to trigger the 15-day Assessment Plan timeline.',
      fields: [
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child Name', placeholder: 'Tommy Doe' },
        { key: 'dob', label: 'Child\'s DOB', placeholder: '04/15/2021' },
        { key: 'districtName', label: 'School District Name', placeholder: 'Los Angeles Unified School District' },
        { key: 'schoolName', label: 'Current School (if any)', placeholder: 'Sunset Elementary' },
        { key: 'concerns', label: 'Suspected Disability Areas', placeholder: 'speech articulation, motor planning delays, and significant sensory sensitivities' }
      ],
      generateFn: (f) => `Date: ${new Date().toLocaleDateString()}

To: Director of Special Education
${f.districtName || 'Local School District'}
Current School: ${f.schoolName || 'Not Enrolled / Preschool'}

RE: Written Request for Special Education Assessment (IDEA / CA Ed Code)
Child's Name: ${f.childName || '[Child Name]'}
Date of Birth: ${f.dob || '[DOB]'}

Dear Director of Special Education,

I am writing to formally request a comprehensive educational evaluation for my child, ${f.childName || '[Child Name]'}, to determine eligibility for special education and related services under the Individuals with Disabilities Education Act (IDEA) and California Education Code Section 56321.

I suspect my child has a disability in the following areas:
${f.concerns || 'Speech delay, social-emotional difficulties, and motor control deficits.'}

I request evaluations in all areas of suspected disability, including but not limited to:
1. Psycho-educational / Cognitive Assessment
2. Speech and Language Assessment
3. Occupational Therapy (Sensory and Fine Motor) Assessment
4. Social-Emotional / Behavioral Assessment

Please note that under California Education Code Section 56321, the school district must provide me with an Assessment Plan within 15 calendar days of receiving this request. I look forward to receiving the plan for my review and signature.

Thank you,

${f.parentName || '[Parent Name]'}
Phone: [Insert Phone]
Email: [Insert Email]`
    },
    eligibilityQuiz: [
      {
        question: 'Has your child received a clinical diagnosis outside of school?',
        options: [
          { text: 'Yes, Autism/ADHD/Down Syndrome diagnosed by a doctor', score: 'high', reason: 'A clinical report strongly supports the request and forces the district to assess, though it does not guarantee IEP placement on its own.' },
          { text: 'No, but we suspect delays', score: 'med', reason: 'The district is legally bound to assess based on "suspected disability" even without a formal medical diagnosis.' }
        ]
      }
    ]
  },
  'california-iep-timeline': {
    slug: 'california-iep-timeline',
    category: 'deadlines',
    title: 'California IEP Timelines & Deadlines: A Parent\'s Cheat Sheet',
    metaTitle: 'California IEP Timeline | School Special Education Deadlines',
    metaDescription: 'A complete cheat sheet on California special education timelines. Know your rights regarding assessment plans, IEP meetings, and annual reviews.',
    quickAnswer: 'California school districts are governed by strict statutory timelines. From your written evaluation request, the district has exactly 15 calendar days to provide an Assessment Plan. Once you sign and return the consent plan, the district has 60 calendar days (excluding school breaks over 5 days) to complete all testing and hold the initial IEP meeting to determine placement.',
    tldrPoints: [
      { label: 'Assessment Plan', value: '15 Calendar Days' },
      { label: 'Consent to Meeting', value: '60 Calendar Days' },
      { label: 'IEP Review', value: 'Annually (365 Days)' },
      { label: 'Re-evaluations', value: 'Every 3 Years (Triennial)' }
    ],
    whenThisMatters: 'During the initial special education application or when requesting new evaluations (speech, OT, behavior) for an existing IEP.',
    signsThisMayApply: [
      'You recently submitted a written request for school testing.',
      'Your school district is stalling or delaying assessments.',
      'Your annual IEP review date is approaching.',
      'You disagree with district findings and want to schedule a due process hearing.'
    ],
    whatToDoFirst: [
      'Keep a detailed calendar log of the exact date your written request was received by the district.',
      'Check the 15-day calendar deadline for the Assessment Plan.',
      'Sign and return the Assessment Plan immediately to start the 60-day testing clock.',
      'Request draft evaluation reports 5 business days prior to the IEP meeting.'
    ],
    documentsToGather: [
      { name: 'Initial Written Request Receipt', description: 'Copy of email showing date submitted to school administration.' },
      { name: 'Signed Assessment Plan Consent', description: 'With date of parent signature establishing the consent timeline.' },
      { name: 'District Progress Reports & Report Cards', description: 'Demonstrating developmental or academic struggles.' }
    ],
    whoToCall: [
      { name: 'District SELPA (Special Education Local Plan Area) Office', description: 'Contact your SELPA if the district violates statutory timelines.' }
    ],
    whatToSay: 'The district is currently past the 15-day statutory deadline to deliver an Assessment Plan. I want this scheduled immediately or I will submit a compliance complaint to the California Department of Education.',
    commonMistakes: [
      'Failing to count calendar days versus school days. The 15-day assessment plan deadline runs on calendar days, whereas the 60-day testing clock pauses during summer and winter breaks.',
      'Assuming the school has all summer to complete testing. The clock freezes when school is out of session for more than 5 consecutive days.',
      'Failing to file a CDE Compliance Complaint when timelines are violated.'
    ],
    relatedGuides: [
      { title: 'IEP Assessment Request Guide', url: '/situations/iep-evaluation-request' },
      { title: 'Early Start Transition Timelines', url: '/situations/early-start-age-3-transition' },
      { title: 'Advocates Directory', url: '/advocates' }
    ],
    officialSources: [
      { name: 'CDE Special Education Timelines', url: 'https://www.cde.ca.gov/sp/se/qa/ieptimelines.asp' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'Timeline Violation Escalation Call',
      script: 'Hello, I am calling to speak with the Special Education program specialist. I submitted a written request for my child\'s IEP assessment on [Request Date]. It has been over 15 calendar days, and I have not received the Assessment Plan. Under California Education Code Section 56321, this timeline is mandatory. Please let me know when the plan will be emailed to me today before I file a compliance complaint.',
      tips: 'Keep the call polite but firm. Timelines are black-and-white, and districts fear CDE audit findings.'
    },
    letterTemplate: {
      title: 'Timeline Delay Escalation Letter',
      description: 'Formal letter to submit when the district fails to deliver the Assessment Plan within 15 days.',
      fields: [
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child Name', placeholder: 'Tommy Doe' },
        { key: 'requestDate', label: 'Original Request Date', placeholder: 'May 10, 2026' },
        { key: 'districtName', label: 'School District Name', placeholder: 'Los Angeles Unified School District' }
      ],
      generateFn: (f) => `Date: ${new Date().toLocaleDateString()}

To: Director of Special Education
${f.districtName || 'Local School District'}

RE: NOTICE OF TIMELINE VIOLATION (California Education Code 56321)
Child's Name: ${f.childName || '[Child Name]'}
Date of Original Request: ${f.requestDate || '[Date]'}

Dear Special Education Director,

On ${f.requestDate || '[Request Date]'}, I submitted a written request for a comprehensive special education evaluation for my child, ${f.childName || '[Child Name]'}.

Under California Education Code Section 56321(a), the school district has 15 calendar days from receipt of a request to provide the parent with an Assessment Plan. As of today, that timeline has elapsed, and I have not received the plan.

Please email the completed Assessment Plan to me immediately so we can begin the assessment phase without further delay. If I do not receive the plan within 48 hours, I will file a formal Compliance Complaint with the California Department of Education (CDE).

Thank you for your immediate attention.

Sincerely,

${f.parentName || '[Parent Name]'}
Email: [Insert Email]
Phone: [Insert Phone]`
    },
    eligibilityQuiz: [
      {
        question: 'How many calendar days have passed since you submitted your written request?',
        options: [
          { text: 'More than 15 calendar days', score: 'high', reason: 'The district is in violation. You should formally escalate using our letter builder.' },
          { text: 'Fewer than 15 calendar days', score: 'med', reason: 'The district is still within their legal window. Use this time to gather medical documents.' }
        ]
      }
    ]
  },
  'regional-center-eligibility': {
    slug: 'regional-center-eligibility',
    category: 'situations',
    title: 'California Regional Center Eligibility: Lanterman Act Requirements',
    metaTitle: 'Regional Center Eligibility California | Lanterman Act Rules',
    metaDescription: 'A complete breakdown of eligibility rules for California Regional Centers. Learn how to qualify for services under the Lanterman Act.',
    quickAnswer: 'California Regional Centers coordinate and fund long-term services for individuals with developmental disabilities. To qualify for lifetime services under the Lanterman Act, an individual must have a disability that originates before age 18, is expected to continue indefinitely, and constitutes a substantial disability in three or more functional areas (self-care, language, learning, mobility, self-direction, capacity for independent living, or economic self-sufficiency).',
    tldrPoints: [
      { label: 'Intake Clock', value: '15 Days to respond; 120 Days to assess' },
      { label: 'Functional Needs', value: 'Deficits in 3+ major life areas' },
      { label: 'Eligible Conditions', value: '5 developmental categories' },
      { label: 'Cost of Services', value: '100% State-Funded ($0 parent cost)' }
    ],
    whenThisMatters: 'As soon as a developmental delay or developmental condition (Autism, Down Syndrome, CP, Epilepsy) is diagnosed. If child is under 3, Early Start criteria apply; at age 3, the more stringent Lanterman rules take over.',
    signsThisMayApply: [
      'The child has Autism, Down Syndrome, Cerebral Palsy, or Epilepsy.',
      'The child exhibits severe intellectual delays (ID).',
      'The child requires significant support to communicate, learn, or walk.',
      'The child is non-self-directing and requires constant supervision.'
    ],
    whatToDoFirst: [
      'Find your local Regional Center based on your county zip code.',
      'Submit a formal written intake request detailing developmental deficits.',
      'Coordinate with the intake officer to schedule diagnostic assessments.',
      'Obtain copies of medical diagnoses and private developmental therapist evaluations.'
    ],
    documentsToGather: [
      { name: 'Pediatric diagnostic reports', description: 'Detailing clinical diagnosis (ASD, CP, Epilepsy).' },
      { name: 'Speech and occupational therapy reports', description: 'Documenting functional deficits in life areas.' },
      { name: 'School IEP records', description: 'Showing cognitive and academic support details.' }
    ],
    whoToCall: [
      { name: 'California Association of Regional Centers (ARCA)', number: '(916) 446-7961', description: 'Association representing all 21 centers.' }
    ],
    whatToSay: 'I am requesting a Lanterman Act eligibility assessment for my child. They have a developmental delay originating before age 18 that impacts their communication, learning, and self-care.',
    commonMistakes: [
      'Assuming ADHD qualifies for Regional Center. Under DDS rules, ADHD is generally not a qualifying condition unless accompanied by an intellectual disability or eligible Autism.',
      'Allowing the center to deny you verbally. Always demand a written Notice of Action (NOA) of eligibility denial so you can file an appeal.',
      'Understating the child\'s deficits during the intake interview.'
    ],
    relatedGuides: [
      { title: 'Early Start Transition Guide', url: '/situations/early-start-age-3-transition' },
      { title: 'Medi-Cal Institutional Deeming Waiver', url: '/situations/down-syndrome-benefits-california' },
      { title: 'DDS Funding & Respite Planner', url: '/dashboard?tab=dds' }
    ],
    officialSources: [
      { name: 'California DDS Eligibility Rules', url: 'https://www.dds.ca.gov/general/eligibility/' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'Regional Center Intake Request Call',
      script: 'Hello, I want to initiate an intake application for my child, [Child Name], who has [Diagnosis] and is [Age] years old. They have significant developmental delays affecting their communication, ability to learn, and self-care skills. Please connect me with the intake department to request an application packet and schedule our intake interview.',
      tips: 'Be prepared to outline exactly how the child\'s delays affect daily life. Use the term "substantial disability" as defined in the Lanterman Act.'
    },
    letterTemplate: {
      title: 'Lanterman Act Intake Request Letter',
      description: 'Formal letter to submit to the Regional Center to initiate eligibility review.',
      fields: [
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child Name', placeholder: 'Tommy Doe' },
        { key: 'dob', label: 'Child\'s DOB', placeholder: '11/02/2021' },
        { key: 'rcName', label: 'Regional Center Name', placeholder: 'Regional Center of the East Bay' },
        { key: 'symptoms', label: 'Substantial Functional Limitations', placeholder: 'receptive language, social communication, and self-care (toileting/feeding)' }
      ],
      generateFn: (f) => `Date: ${new Date().toLocaleDateString()}

To: Intake Department
${f.rcName || 'Local Regional Center'}

RE: Formal Written Request for Lanterman Act Assessment
Child's Name: ${f.childName || '[Child Name]'}
Date of Birth: ${f.dob || '[DOB]'}

Dear Intake Coordinator,

I am writing to formally request an eligibility assessment under the Lanterman Act for my child, ${f.childName || '[Child Name]'}.

My child has been diagnosed with, or is suspected of having, a developmental disability that constitutes a substantial handicap in the following functional areas:
${f.symptoms || 'Communication, Learning, and Self-Care.'}

As defined under California Welfare and Institutions Code Section 4646, the Regional Center must respond to this written intake request within 15 days. Please send me the required intake forms and contact me to schedule our diagnostic evaluations.

Thank you for your assistance.

Sincerely,

${f.parentName || '[Parent Name]'}
Email: [Insert Email]
Phone: [Insert Phone]`
    },
    eligibilityQuiz: [
      {
        question: 'What is your child\'s diagnosed developmental condition?',
        options: [
          { text: 'Autism, Cerebral Palsy, Down Syndrome, Epilepsy, or Intellectual Disability', score: 'high', reason: 'These conditions fit directly within the DDS "5 qualifying categories" under the Lanterman Act.' },
          { text: 'ADHD, Sensory Processing, or Learning Disability only', score: 'low', reason: 'These conditions are generally excluded from Lanterman eligibility unless you can prove cognitive/adaptive scores fall in the intellectual disability range.' }
        ]
      },
      {
        question: 'Does your child require significant help in 3 or more functional areas (Speech, Learning, Mobility, Self-Care)?',
        options: [
          { text: 'Yes, they have severe delays in 3 or more of these areas', score: 'high', reason: 'This meets the "substantial disability" statutory requirement for Lanterman eligibility.' },
          { text: 'No, they struggle only with speech and motor skills', score: 'med', reason: 'If they have only 1 or 2 areas of delay, they may be eligible under Early Start (under 3) but may struggle to qualify for Lanterman services (3+).' }
        ]
      }
    ]
  },
  'early-start-age-3-transition': {
    slug: 'early-start-age-3-transition',
    category: 'situations',
    title: 'California Early Start Age 3 Transition: Moving from IFSP to IEP',
    metaTitle: 'Early Start Transition California | IFSP to School District IEP',
    metaDescription: 'Step-by-step parent transition guide for California children turning 3. Transition from Regional Center Early Start (IFSP) to School District (IEP).',
    quickAnswer: 'In California, early intervention services (speech, OT, physical therapy) funded by the Regional Center\'s Early Start program end on the child\'s 3rd birthday. To ensure services do not drop, the transition process must start at age 2.9. A transition meeting is held, and the local public school district must evaluate the child and hold an initial IEP meeting before they turn 3.',
    tldrPoints: [
      { label: 'Transition Kickoff', value: 'Age 2 years, 9 months' },
      { label: 'IFSP Expiration', value: 'Exact 3rd Birthday' },
      { label: 'Assessing Entity', value: 'Local School District' },
      { label: 'Service Continuity', value: 'IEP must be active by age 3' }
    ],
    whenThisMatters: 'When your toddler currently receives therapies through California Early Start (IFSP) and is approaching age 2.5 to 3.',
    signsThisMayApply: [
      'Your child is enrolled in Early Start with an active IFSP.',
      'The child is turning 2 years and 9 months old.',
      'Your Regional Center coordinator schedules a transition conference.'
    ],
    whatToDoFirst: [
      'Request your Regional Center coordinator schedule a Transition Conference immediately.',
      'Consent to sharing your child\'s records with the local school district.',
      'Follow up with the school district special education department to ensure they received the referral.',
      'Sign the school district\'s Assessment Plan immediately upon receipt.'
    ],
    documentsToGather: [
      { name: 'Latest IFSP Plan', description: 'Review the current service grid and therapy hours.' },
      { name: 'Regional Center Developmental Progress Reports', description: 'To serve as baseline evidence for the school district.' },
      { name: 'Private clinical evaluations', description: 'Confirming ongoing therapeutic needs.' }
    ],
    whoToCall: [
      { name: 'Your assigned Regional Center Service Coordinator', description: 'They are legally required to lead the transition process.' }
    ],
    whatToSay: 'I want to confirm that my child\'s school district transition referral has been submitted. We need the transition conference scheduled as they are turning 2 years, 9 months next week.',
    commonMistakes: [
      'Allowing the coordinator to delay the transition conference until after age 2.9, which can cause a service gap.',
      'Believing the school district automatically provides the same hours as the Regional Center. School districts evaluate educational necessity, which is narrower than developmental necessity.',
      'Failing to request independent school assessments in all areas.'
    ],
    relatedGuides: [
      { title: 'IEP Evaluation Request Guide', url: '/situations/iep-evaluation-request' },
      { title: 'California IEP Timeline Rules', url: '/deadlines/california-iep-timeline' },
      { title: 'Regional Center Eligibility', url: '/situations/regional-center-eligibility' }
    ],
    officialSources: [
      { name: 'California DDS Early Start Transition Portal', url: 'https://www.dds.ca.gov/services/early-start/transition-information-for-parents/' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'Regional Center Service Coordinator Transition Call',
      script: 'Hello, I am calling about my child, [Child Name]\'s transition from Early Start. They are turning 2.9 on [Date] and I want to verify that the referral has been sent to [School District Name] and that we have scheduled our transition conference. I want to make sure there is no gap in speech and physical therapy services when they turn 3.',
      tips: 'Record the date the referral was officially sent. This determines when the school district\'s timeline starts.'
    },
    letterTemplate: {
      title: 'Consent for Regional Center Record Release to School District',
      description: 'Formal written consent to expedite sharing IFSP records to the public school system.',
      fields: [
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child Name', placeholder: 'Tommy Doe' },
        { key: 'dob', label: 'Child\'s DOB', placeholder: '12/15/2023' },
        { key: 'districtName', label: 'School District Name', placeholder: 'San Francisco Unified School District' },
        { key: 'coordinatorName', label: 'RC Coordinator Name', placeholder: 'Mary Johnson' }
      ],
      generateFn: (f) => `Date: ${new Date().toLocaleDateString()}

To: ${f.coordinatorName || 'Service Coordinator'}
Local Regional Center

RE: Written Consent to Release Early Start Records for Transition
Child's Name: ${f.childName || '[Child Name]'}
Date of Birth: ${f.dob || '[DOB]'}

Dear ${f.coordinatorName || 'Service Coordinator'},

I am writing to provide formal written consent to release my child\'s Early Start records, including the current IFSP, all developmental progress reports, and clinical evaluations, to the special education department of ${f.districtName || 'the local school district'}.

My child is approaching age 2 years, 9 months. I request that you submit the official transition referral and schedule our Transition Conference as mandated under California Early Start regulations. 

Please confirm the date this referral is submitted to the district.

Sincerely,

${f.parentName || '[Parent Name]'}
Email: [Insert Email]
Phone: [Insert Phone]`
    },
    eligibilityQuiz: [
      {
        question: 'How old is your child currently?',
        options: [
          { text: 'Between 2.6 and 2.9 years old', score: 'high', reason: 'This is the perfect window to start the transition to avoid any gap in speech or physical therapy.' },
          { text: 'Older than 2.10 years old', score: 'med', reason: 'You are close to the transition deadline. Request the district referral immediately to prevent a gap at age 3.' },
          { text: 'Under 2.5 years old', score: 'low', reason: 'Your child is still fully covered under Early Start. Continue tracking progress on your IFSP.' }
        ]
      }
    ]
  },
  'ssi-for-children': {
    slug: 'ssi-for-children',
    category: 'programs',
    title: 'Supplemental Security Income (SSI) for Children with Disabilities in California',
    metaTitle: 'SSI for Children with Disabilities California | Pay & Rules Guide',
    metaDescription: 'Learn how to secure monthly federal SSI disability cash payments for children with disabilities in California. Understand parental income deeming rules.',
    quickAnswer: 'Supplemental Security Income (SSI) is a federal program administered by the Social Security Administration (SSA) that provides monthly cash payments to children with severe disabilities. In California, children who qualify automatically receive full-scope Medi-Cal coverage. However, the child must meet both strict clinical criteria (marked or extreme functional limitations) and household income/asset limits (parental resource deeming).',
    tldrPoints: [
      { label: 'Max Monthly Payment', value: 'Up to $1,100+/mo (State supplement included)' },
      { label: 'Asset Limit', value: '$2,000 parent (single) / $3,000 (married)' },
      { label: 'Clinical Criteria', value: 'Marked or extreme limitation' },
      { label: 'Medi-Cal Link', value: 'Auto-enrolled in Medi-Cal' }
    ],
    whenThisMatters: 'When your household income and assets fall below the SSA limits, or when your child turns 18 (at age 18, parental income is ignored entirely and only the child\'s income/assets are evaluated).',
    signsThisMayApply: [
      'The child has a severe genetic, physical, or cognitive disability.',
      'The family meets the SSA household income limits (sliding scale based on family size).',
      'The family\'s countable resources are below $2,000 (single parent) or $3,000 (two parents).',
      'The child is unable to perform basic age-appropriate developmental tasks.'
    ],
    whatToDoFirst: [
      'Check the SSA Child Deeming Chart to evaluate if household income is within limits.',
      'Gather medical diagnostic summaries, clinical evaluations, and IEP records.',
      'Submit the Child Disability Report online through the SSA website.',
      'Schedule an intake interview with your local Social Security office.'
    ],
    documentsToGather: [
      { name: 'Child Disability Report', description: 'The formal online application detailing medical history.' },
      { name: 'Household tax records & paystubs', description: 'Required to calculate parental income deeming.' },
      { name: 'Pediatric specialist diagnostics', description: 'Confirming marked/extreme functional deficits.' }
    ],
    whoToCall: [
      { name: 'Social Security Administration Toll-Free', number: '1-800-772-1213', description: 'Call to request an intake appointment or check application status.' }
    ],
    whatToSay: 'I want to apply for Supplemental Security Income (SSI) on behalf of my minor child who has a severe developmental disability. I have completed the online Child Disability Report and need to schedule our intake interview.',
    commonMistakes: [
      'Assuming your child is ineligible because your income is too high. At age 18, parental income deeming stops completely. Every child with a disability should apply on their 18th birthday regardless of parent wealth.',
      'Understating the child\'s limitations on the Disability Report.',
      'Failing to open a CalABLE account to hold excess savings above the $2,000 individual asset limit.'
    ],
    relatedGuides: [
      { title: 'CalABLE Disability Accounts', url: '/programs/calable' },
      { title: 'IHSS for Children Guide', url: '/programs/ihss-for-children' },
      { title: 'Appeals and Letter Builder', url: '/dashboard?tab=appeals' }
    ],
    officialSources: [
      { name: 'Social Security Administration Children\'s SSI', url: 'https://www.ssa.gov/benefits/disability/apply-child.html' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'SSA Intake Appointment Setup',
      script: 'Hello, I am calling to schedule an appointment to apply for Supplemental Security Income (SSI) on behalf of my child, [Child Name]. I have already submitted the online Child Disability Report with tracking number [Tracking #]. I want to set up an interview at our local office to submit our financial documentation and verify income eligibility.',
      tips: 'Ensure you write down the date and time of your interview, as well as the name of the agent assigned to your case.'
    },
    letterTemplate: {
      title: 'SSI Denial Appeal Request (Request for Reconsideration)',
      description: 'Formal letter to submit to SSA within the 60-day limit to contest an SSI medical denial.',
      fields: [
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child Name', placeholder: 'Tommy Doe' },
        { key: 'ssn', label: 'Child\'s SSN', placeholder: '000-11-2222' },
        { key: 'denialDate', label: 'Date on Denial Notice', placeholder: 'May 5, 2026' }
      ],
      generateFn: (f) => `Date: ${new Date().toLocaleDateString()}

To: Social Security Administration
Local Branch Office

RE: Request for Reconsideration (SSI Medical Denial)
Claimant Name: ${f.childName || '[Child Name]'}
SSN: ${f.ssn || '[SSN]'}
Date of Denial Notice: ${f.denialDate || '[Denial Date]'}

Dear Claims Representative,

I am writing to formally request a reconsideration of the medical eligibility decision dated ${f.denialDate || '[Date]'} regarding my child\'s application for Supplemental Security Income (SSI).

I disagree with the finding that my child\'s impairment does not meet, medically equal, or functionally equal the listings. My child has a severe developmental condition that causes marked and extreme limitations in several functional domains, including communication, learning, and self-care.

I request that our case files be re-evaluated by the Disability Determination Services (DDS). I am in the process of gathering updated clinical reports and school IEP records, which I will submit directly to our caseworker.

Thank you for your assistance.

Sincerely,

${f.parentName || '[Parent Name]'}
Phone: [Insert Phone]`
    },
    eligibilityQuiz: [
      {
        question: 'What is your monthly gross household income?',
        options: [
          { text: 'Below $3,500/mo (approx. for single parent, varies by kids)', score: 'high', reason: 'Your income likely falls within the SSA deeming thresholds. Focus on clinical proof.' },
          { text: 'Above $5,000/mo', score: 'low', reason: 'Your household income exceeds standard deeming limits. You may need to wait until the child turns 18 (when parent income is ignored).' }
        ]
      }
    ]
  },
  'medi-cal-epsdt': {
    slug: 'medi-cal-epsdt',
    category: 'programs',
    title: 'Medi-Cal EPSDT (Early and Periodic Screening, Diagnostic, and Treatment) Benefit',
    metaTitle: 'Medi-Cal EPSDT California | Medically Necessary Care Guide',
    metaDescription: 'A complete parent guide to securing therapies, ABA, speech, and medical equipment under the federal Medi-Cal EPSDT mandate in California.',
    quickAnswer: 'EPSDT (Early and Periodic Screening, Diagnostic, and Treatment) is a federally mandated Medi-Cal benefit for children under 21. Under federal law, Medi-Cal must cover any medically necessary service to correct or improve a child\'s physical, developmental, or mental health condition, even if the service is not normally covered under California\'s standard adult Medi-Cal program.',
    tldrPoints: [
      { label: 'Eligibility Age', value: 'All youth under 21 on Medi-Cal' },
      { label: 'Mandate Standard', value: 'Correct or ameliorate condition' },
      { label: 'Services Covered', value: 'ABA, Speech, OT, Home Nursing' },
      { label: 'Co-payments', value: '$0 for all approved services' }
    ],
    whenThisMatters: 'When your insurance or Medi-Cal managed care plan denies a therapy, behavioral support (like ABA), speech therapy, or medical device, claiming it exceeds local benefit limits.',
    signsThisMayApply: [
      'Your child is enrolled in Medi-Cal.',
      'The child has a clinical need for intensive speech, physical, occupational, or ABA therapy.',
      'Standard insurance limits the number of therapy sessions allowed per year.',
      'A physician certifies that the service is necessary to prevent regression.'
    ],
    whatToDoFirst: [
      'Obtain a detailed letter of medical necessity from your child\'s pediatrician.',
      'Request prior authorization for the therapy or service through your Medi-Cal Managed Care Plan.',
      'If denied, file an internal appeal citing the federal EPSDT mandate.',
      'File for a State Fair Hearing if the managed care plan upholds the denial.'
    ],
    documentsToGather: [
      { name: 'Letter of Medical Necessity', description: 'Written by a licensed pediatrician stating that services "ameliorate" the condition.' },
      { name: 'Managed Care Plan Denial Notice (NOA)', description: 'The official document showing the service denial.' },
      { name: 'Private clinical evaluations', description: 'Recommending specific weekly therapy frequencies.' }
    ],
    whoToCall: [
      { name: 'Medi-Cal Managed Care Ombudsman', number: '1-888-452-8609', description: 'Call to escalate billing disputes or authorization denials.' }
    ],
    whatToSay: 'I am requesting this service under the federal EPSDT mandate. This therapy is medically necessary to correct or improve my child\'s developmental delay, and California is legally obligated to fund it.',
    commonMistakes: [
      'Accepting a denial that claims a service is "not a covered benefit." Under EPSDT, if it is medically necessary to correct or improve a condition for a minor, it must be covered.',
      'Failing to obtain a doctor\'s signature explicitly using the word "ameliorate" or "improve".',
      'Missing the 90-day State Fair Hearing appeal window.'
    ],
    relatedGuides: [
      { title: 'IHSS for Children Guide', url: '/programs/ihss-for-children' },
      { title: 'California Children\'s Services (CCS)', url: '/programs/ccs' },
      { title: 'Appeals & Letter Builder', url: '/dashboard?tab=appeals' }
    ],
    officialSources: [
      { name: 'DHCS EPSDT Information Page', url: 'https://www.dhcs.ca.gov/services/medi-cal/Pages/EPSDT.aspx' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'Ombudsman Escalation for Therapy Denial',
      script: 'Hello, I am calling the Medi-Cal Managed Care Ombudsman to appeal a denial of [Service Type] for my child, [Child Name], who has [Diagnosis]. The plan denied authorization saying it is not a covered benefit. However, my child is under 21 and active on Medi-Cal. Under the federal EPSDT mandate, the state must fund any service that is medically necessary to improve or correct their condition. My pediatrician has signed a letter of medical necessity. Please open an investigation.',
      tips: 'Always write down the reference number of your ombudsman complaint for future hearing evidence.'
    },
    letterTemplate: {
      title: 'EPSDT Medical Necessity Request to Pediatrician',
      description: 'A template letter to request your pediatrician draft a letter containing the exact federal legal keywords required for EPSDT approval.',
      fields: [
        { key: 'doctorName', label: 'Doctor Name', placeholder: 'Dr. Smith' },
        { key: 'childName', label: 'Child Name', placeholder: 'Tommy Doe' },
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'serviceRequested', label: 'Requested Service', placeholder: 'intensive speech therapy (3 sessions/week)' }
      ],
      generateFn: (f) => `Dear ${f.doctorName || 'Doctor'},

I am applying for funding for ${f.serviceRequested || 'specialized therapy'} through Medi-Cal on behalf of my child, ${f.childName || '[Child Name]'}.

To qualify under the federal EPSDT (Early and Periodic Screening, Diagnostic, and Treatment) mandate, Medi-Cal requires a letter of medical necessity from a treating physician. The letter must state that the requested service is necessary to "correct or ameliorate" (improve, manage, or prevent regression of) my child's physical or developmental condition.

Could you please draft a brief letter on your office letterhead that includes the following details:
1. Diagnosis: [Child\'s Diagnosis]
2. Service requested: ${f.serviceRequested || 'Service'}
3. Clinical rationale: How this service will help correct or ameliorate their condition.
4. The specific term: "This service is medically necessary to correct or ameliorate the child\'s developmental delay."

This wording is critical to bypass standard plan limitations. 

Thank you for your help,

${f.parentName || '[Parent Name]'}`
    },
    eligibilityQuiz: [
      {
        question: 'Is your child under 21 years old and active on Medi-Cal?',
        options: [
          { text: 'Yes, both apply', score: 'high', reason: 'Your child is fully covered by the federal EPSDT mandate. Any medically necessary service must be approved.' },
          { text: 'No, they are older than 21 or not on Medi-Cal', score: 'low', reason: 'EPSDT is strictly a child benefit under Medicaid. Adult rules apply once they turn 21.' }
        ]
      }
    ]
  },
  'ccs': {
    slug: 'ccs',
    category: 'programs',
    title: 'California Children\'s Services (CCS): Medical Therapy Program Guide',
    metaTitle: 'California Children\'s Services (CCS) | School Therapy Guide',
    metaDescription: 'Complete guide for parents on California Children\'s Services (CCS). Learn how to get free physical and occupational therapy in schools.',
    quickAnswer: 'California Children\'s Services (CCS) is a state-county program that coordinates and funds medical care, equipment, and physical/occupational therapy for children under 21 with eligible chronic physical disabilities. A key benefit is the Medical Therapy Program (MTP), which provides free physical and occupational therapy at school-based Medical Therapy Units (MTUs) regardless of family income.',
    tldrPoints: [
      { label: 'MTU Income Limit', value: 'None ($0 cost for school therapy)' },
      { label: 'Eligible Age', value: 'Under 21 years old' },
      { label: 'Services Covered', value: 'Therapy, orthotics, medical equipment' },
      { label: 'Clinical Focus', value: 'Neuromuscular/orthopedic conditions' }
    ],
    whenThisMatters: 'If your child has Cerebral Palsy, Spina Bifida, Muscular Dystrophy, or another orthopedic/neurological condition and requires physical or occupational therapy to sit, walk, or adapt to the school classroom.',
    signsThisMayApply: [
      'The child has a physical neurological or muscular disability.',
      'The child requires specialized orthotics, braces, or a wheelchair.',
      'The school IEP team recommends occupational or physical therapy for mobility.',
      'Family income is under $40,000/year (for standard medical case coverage; note that MTU school therapy has no income cap).'
    ],
    whatToDoFirst: [
      'Submit a CCS application form signed by your child\'s physical medicine specialist.',
      'Provide diagnostic summaries, MRIs, and clinical letters verifying the neuromuscular condition.',
      'Request an evaluation by the CCS Medical Therapy Unit (MTU) at your local public school.',
      'Coordinate the CCS therapy plan with the school district IEP team.'
    ],
    documentsToGather: [
      { name: 'CCS Application Form (DHCS 4480)', description: 'The official state application form signed by parent.', downloadUrl: 'https://www.dhcs.ca.gov/formsandpubs/forms/Forms/dhcs4480.pdf' },
      { name: 'Neurologist or Orthopedic Specialist Reports', description: 'Confirming diagnosis and clinical physical limitations.' },
      { name: 'Current IEP Document', description: 'Confirming school attendance and mobility accommodations.' }
    ],
    whoToCall: [
      { name: 'County CCS Office Liaison', description: 'Call the local health department to get the phone number for your county\'s CCS program.' }
    ],
    whatToSay: 'I want to apply for the CCS Medical Therapy Program for my child who has Cerebral Palsy. We need an evaluation at the local Medical Therapy Unit to schedule physical therapy.',
    commonMistakes: [
      'Assuming you do not qualify because of your income. The CCS Medical Therapy Unit (MTU) therapy program is 100% free and has NO family income limit.',
      'Failing to coordinate CCS therapy with IEP goals, leading to conflicting therapy strategies between school staff and CCS specialists.',
      'Failing to apply for CCS early, which can delay equipment authorization (braces/wheelchairs) for months.'
    ],
    relatedGuides: [
      { title: 'IEP Evaluation Guide', url: '/situations/iep-evaluation-request' },
      { title: 'Medi-Cal EPSDT Benefits', url: '/programs/medi-cal-epsdt' },
      { title: 'Saved Plans Dashboard', url: '/dashboard' }
    ],
    officialSources: [
      { name: 'DHCS CCS Program Details', url: 'https://www.dhcs.ca.gov/services/ccs/Pages/default.aspx' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'Requesting Local MTU School Evaluation',
      script: 'Hello, I am calling my county CCS office to request an eligibility evaluation for the Medical Therapy Program on behalf of my child, [Child Name]. They have a diagnosis of [Diagnosis] and attend [School Name]. I want to set up an evaluation at our local Medical Therapy Unit for physical and occupational therapy. Please let me know where to fax their diagnostic neurologist reports.',
      tips: 'Ask for the name of the MTU supervisor at your child\'s school campus to coordinate scheduling directly.'
    },
    letterTemplate: {
      title: 'CCS Medical Therapy Program Intake Request',
      description: 'Formal letter to submit to your county health department to request a school-based therapy evaluation.',
      fields: [
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child Name', placeholder: 'Tommy Doe' },
        { key: 'dob', label: 'Child\'s DOB', placeholder: '08/20/2020' },
        { key: 'diagnosis', label: 'Neuromuscular Diagnosis', placeholder: 'Cerebral Palsy' },
        { key: 'countyName', label: 'County Name', placeholder: 'Alameda County' }
      ],
      generateFn: (f) => `Date: ${new Date().toLocaleDateString()}

To: California Children's Services (CCS)
${f.countyName || 'Local County'} Health Department

RE: Request for Medical Therapy Program (MTP) Evaluation
Child's Name: ${f.childName || '[Child Name]'}
Date of Birth: ${f.dob || '[DOB]'}
Diagnosis: ${f.diagnosis || 'Neuromuscular Condition'}

Dear CCS Intake Coordinator,

I am writing to formally request an eligibility evaluation for the CCS Medical Therapy Program (MTP) on behalf of my child, ${f.childName || '[Child Name]'}, who has a clinical diagnosis of ${f.diagnosis || 'Cerebral Palsy'}.

My child exhibits physical motor delays and requires therapeutic support to sit, stand, and navigate their educational environment. We request an assessment at our local school-based Medical Therapy Unit (MTU) to determine eligibility for physical and/or occupational therapy.

I have attached my child's latest clinical neurologist report and orthopedic assessment to verify diagnostic eligibility.

Thank you,

${f.parentName || '[Parent Name]'}
Email: [Insert Email]
Phone: [Insert Phone]`
    },
    eligibilityQuiz: [
      {
        question: 'Does your child have a physical orthopedic or neurological condition (e.g. Cerebral Palsy, Spina Bifida)?',
        options: [
          { text: 'Yes, physical motor delay confirmed by specialist', score: 'high', reason: 'This fits directly within the CCS Medical Therapy Program eligibility guidelines.' },
          { text: 'No, they have developmental delays without physical motor deficits', score: 'low', reason: 'CCS is strictly for physical/orthopedic medical conditions. General cognitive delays do not qualify.' }
        ]
      }
    ]
  },
  'calable': {
    slug: 'calable',
    category: 'programs',
    title: 'CalABLE California: Tax-Advantaged Disability Savings Accounts',
    metaTitle: 'CalABLE Accounts California | Disability Savings Rules',
    metaDescription: 'Learn how to save money without losing SSI or Medi-Cal eligibility in California. Set up a tax-advantaged CalABLE account.',
    quickAnswer: 'CalABLE (California\'s Achieving a Better Life Experience program) allows individuals with disabilities to save up to $18,000 per year (and hold up to $100,000 total) in a tax-advantaged investment account without losing resource-tested benefits like SSI and Medi-Cal. Normally, saving more than $2,000 disqualifies a child from SSI, but CalABLE bypasses this rule completely.',
    tldrPoints: [
      { label: 'Annual Deposit Limit', value: '$18,000' },
      { label: 'SSI Asset Cap Waiver', value: 'Up to $100,000 excluded' },
      { label: 'Medi-Cal Asset Waiver', value: 'No limit' },
      { label: 'Tax Status', value: '100% Tax-Free growth' }
    ],
    whenThisMatters: 'Whenever you want to build savings for your child\'s future, deposit inheritance funds, or protect their eligibility for monthly SSI cash and Medi-Cal when household assets exceed limits.',
    signsThisMayApply: [
      'The child has a disability that occurred before age 26 (moving to age 46 in 2026).',
      'The child is receiving SSI or Medi-Cal benefits.',
      'The family wants to save money for the child\'s future education, therapies, or housing.',
      'The child is active on a Regional Center caseload.'
    ],
    whatToDoFirst: [
      'Verify that your child\'s disability onset occurred before age 26.',
      'Visit the official CalABLE website to open an account.',
      'Select your investment portfolios (conservative interest-bearing or market-linked).',
      'Set up automatic monthly contributions or link parent accounts.'
    ],
    documentsToGather: [
      { name: 'Social Security Disability Verification', description: 'Proof of SSI eligibility, or a signed physician disability certification letter.' },
      { name: 'Parent identity and SSN documentation', description: 'Required to open the account as a representative on behalf of a minor.' }
    ],
    whoToCall: [
      { name: 'CalABLE Board Client Service Helpline', number: '1-833-225-3253', description: 'Call for assistance setting up accounts or processing withdrawals.' }
    ],
    whatToSay: 'I want to open a CalABLE account on behalf of my minor child who has a developmental disability. I want to confirm the contribution limits and verify how to link our bank accounts.',
    commonMistakes: [
      'Depositing more than $18,000 per year, which triggers tax penalties (unless the child is working, in which case they can save more under ABLE to Work).',
      'Allowing the account balance to exceed $100,000 if receiving SSI. If the balance exceeds $100,000, your monthly SSI checks will be suspended until the balance drops back down.',
      'Using the funds for non-qualified expenses. CalABLE funds must be spent on "qualified disability expenses" (housing, education, transit, assistive tech, health care).'
    ],
    relatedGuides: [
      { title: 'SSI for Children Guide', url: '/programs/ssi-for-children' },
      { title: 'IHSS Caregiver Pay Guide', url: '/programs/ihss-for-children' },
      { title: 'DDS Funding and Respite', url: '/dashboard?tab=dds' }
    ],
    officialSources: [
      { name: 'Official CalABLE Portal', url: 'https://www.calable.ca.gov' }
    ],
    lastReviewedDate: '2026-06-01',
    callScriptTemplate: {
      intro: 'CalABLE Setup Assistance Call',
      script: 'Hello, I am calling to get assistance with opening a CalABLE account for my minor child who has a developmental disability. I am their legal guardian. I want to walk through the online registration process, verify the required clinical certifications, and understand the fees associated with the investment options. Thank you.',
      tips: 'Ensure you register the account under the child\'s SSN, not the parent\'s SSN, to properly exclude the assets for the child\'s SSI determinations.'
    },
    letterTemplate: {
      title: 'ABLE Account Verification for Social Security Administration',
      description: 'Letter template to notify the SSA of funds held in a tax-excluded CalABLE account.',
      fields: [
        { key: 'parentName', label: 'Parent Name', placeholder: 'Jane Doe' },
        { key: 'childName', label: 'Child Name', placeholder: 'Tommy Doe' },
        { key: 'ssn', label: 'Child\'s SSN', placeholder: '000-11-2222' },
        { key: 'ableNumber', label: 'CalABLE Account Number', placeholder: 'CA-12345' },
        { key: 'balance', label: 'Current Account Balance', placeholder: '$12,500' }
      ],
      generateFn: (f) => `Date: ${new Date().toLocaleDateString()}

To: Social Security Administration
Local Office

RE: Verification of Excluded Assets under IRC Section 529A (ABLE Account)
Claimant Name: ${f.childName || '[Child Name]'}
SSN: ${f.ssn || '[SSN]'}
CalABLE Account Number: ${f.ableNumber || '[Account #]'}

Dear Claims Representative,

I am writing to report the financial assets held by my child, ${f.childName || '[Child Name]'}, to ensure correct calculation of resources for their Supplemental Security Income (SSI) eligibility.

Please find attached the latest statement for CalABLE Account Number ${f.ableNumber || '[Account #]'}, showing a current balance of ${f.balance || '[Balance]'}.

Under Section 102 of the Achieving a Better Life Experience (ABLE) Act of 2014, codified at Internal Revenue Code Section 529A, assets held in a registered ABLE account up to $100,000 are completely excluded from resource calculations for the SSI program. Furthermore, all investment earnings are tax-exempt.

Please update my child's file to show that these resources are excluded.

Sincerely,

${f.parentName || '[Parent Name]'}
Email: [Insert Email]
Phone: [Insert Phone]`
    },
    eligibilityQuiz: [
      {
        question: 'Did your child\'s disability onset occur before age 26?',
        options: [
          { text: 'Yes, diagnosis was established in early childhood', score: 'high', reason: 'This meets the age of onset qualification for ABLE accounts.' },
          { text: 'No, onset occurred in adulthood (after age 26)', score: 'low', reason: 'Currently, ABLE requires onset before age 26. Note: Starting in 2026, the age limit increases to 46.' }
        ]
      }
    ]
  }
};
