-- Rollback Script for State: Ohio | Phase: dd_idd
-- Generated At: 2026-06-13T21:15:28.341Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-wyandot' AND county_id = 'wyandot-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-wyandot';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-wood' AND county_id = 'wood-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-wood';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-williams' AND county_id = 'williams-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-williams';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-wayne' AND county_id = 'wayne-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-washington' AND county_id = 'washington-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-warren' AND county_id = 'warren-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-vinton' AND county_id = 'vinton-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-vinton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-van-wert' AND county_id = 'van-wert-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-van-wert';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-union' AND county_id = 'union-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-union';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-tuscarawas' AND county_id = 'tuscarawas-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-tuscarawas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-trumbull' AND county_id = 'trumbull-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-trumbull';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-summit' AND county_id = 'summit-oh';
UPDATE state_resource_agencies SET state_id = 'ohio', agency_type = 'cbdd', name = 'Summit County Board of Developmental Disabilities', counties_served = 'summit-oh', catchment_boundaries = 'Serves Akron and Summit County.', website = 'https://www.summitdd.org', intake_phone = '(330) 634-8000', early_intervention_contact = '(330) 634-8000', agency_intake_contact = '(330) 634-8000', eligibility_info_page = 'https://www.summitdd.org/', services_page = 'https://www.summitdd.org/', appeals_info = 'Waiver denials can be appealed to the state administrative hearing system within 30 days of the decision.', frc_relationship = NULL, office_locations = 'Summit County Board of Developmental Disabilities office address', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://www.summitdd.org', source_url = 'https://www.summitdd.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-cbdd-summit';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-stark' AND county_id = 'stark-oh';
UPDATE state_resource_agencies SET state_id = 'ohio', agency_type = 'cbdd', name = 'Stark County Board of Developmental Disabilities', counties_served = 'stark-oh', catchment_boundaries = 'Serves Canton and Stark County.', website = 'https://www.starkdd.org', intake_phone = '(330) 477-5200', early_intervention_contact = '(330) 477-5200', agency_intake_contact = '(330) 477-5200', eligibility_info_page = 'https://www.starkdd.org/', services_page = 'https://www.starkdd.org/', appeals_info = 'Waiver denials can be appealed to the state administrative hearing system within 30 days of the decision.', frc_relationship = NULL, office_locations = 'Stark County Board of Developmental Disabilities office address', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://www.starkdd.org', source_url = 'https://www.starkdd.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-cbdd-stark';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-shelby' AND county_id = 'shelby-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-shelby';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-seneca' AND county_id = 'seneca-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-seneca';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-scioto' AND county_id = 'scioto-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-scioto';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-sandusky' AND county_id = 'sandusky-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-sandusky';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-ross' AND county_id = 'ross-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-ross';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-richland' AND county_id = 'richland-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-richland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-putnam' AND county_id = 'putnam-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-putnam';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-preble' AND county_id = 'preble-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-preble';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-portage' AND county_id = 'portage-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-portage';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-pike' AND county_id = 'pike-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-pike';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-pickaway' AND county_id = 'pickaway-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-pickaway';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-perry' AND county_id = 'perry-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-perry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-paulding' AND county_id = 'paulding-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-paulding';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-ottawa' AND county_id = 'ottawa-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-ottawa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-noble' AND county_id = 'noble-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-noble';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-muskingum' AND county_id = 'muskingum-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-muskingum';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-morrow' AND county_id = 'morrow-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-morrow';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-morgan' AND county_id = 'morgan-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-morgan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-montgomery' AND county_id = 'montgomery-oh';
UPDATE state_resource_agencies SET state_id = 'ohio', agency_type = 'cbdd', name = 'Montgomery County Board of Developmental Disabilities', counties_served = 'montgomery-oh', catchment_boundaries = 'Serves Dayton and Montgomery County.', website = 'https://www.mcbdds.org', intake_phone = '(937) 837-9200', early_intervention_contact = '(937) 837-9200', agency_intake_contact = '(937) 837-9200', eligibility_info_page = 'https://www.mcbdds.org/', services_page = 'https://www.mcbdds.org/', appeals_info = 'Waiver denials can be appealed to the state administrative hearing system within 30 days of the decision.', frc_relationship = NULL, office_locations = 'Montgomery County Board of Developmental Disabilities office address', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://www.mcbdds.org', source_url = 'https://www.mcbdds.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-cbdd-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-monroe' AND county_id = 'monroe-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-monroe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-miami' AND county_id = 'miami-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-miami';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-mercer' AND county_id = 'mercer-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-mercer';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-meigs' AND county_id = 'meigs-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-meigs';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-medina' AND county_id = 'medina-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-medina';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-marion' AND county_id = 'marion-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-marion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-mahoning' AND county_id = 'mahoning-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-mahoning';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-madison' AND county_id = 'madison-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-madison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-lucas' AND county_id = 'lucas-oh';
UPDATE state_resource_agencies SET state_id = 'ohio', agency_type = 'cbdd', name = 'Lucas County Board of Developmental Disabilities', counties_served = 'lucas-oh', catchment_boundaries = 'Serves Toledo and Lucas County.', website = 'https://www.lucasdd.info', intake_phone = '(419) 380-4000', early_intervention_contact = '(419) 380-4000', agency_intake_contact = '(419) 380-4000', eligibility_info_page = 'https://www.lucasdd.info/', services_page = 'https://www.lucasdd.info/', appeals_info = 'Waiver denials can be appealed to the state administrative hearing system within 30 days of the decision.', frc_relationship = NULL, office_locations = 'Lucas County Board of Developmental Disabilities office address', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://www.lucasdd.info', source_url = 'https://www.lucasdd.info', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-cbdd-lucas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-lorain' AND county_id = 'lorain-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-lorain';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-logan' AND county_id = 'logan-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-logan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-licking' AND county_id = 'licking-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-licking';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-lawrence' AND county_id = 'lawrence-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-lawrence';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-lake' AND county_id = 'lake-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-lake';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-knox' AND county_id = 'knox-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-knox';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-jefferson' AND county_id = 'jefferson-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-jefferson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-jackson' AND county_id = 'jackson-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-jackson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-huron' AND county_id = 'huron-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-huron';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-holmes' AND county_id = 'holmes-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-holmes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-hocking' AND county_id = 'hocking-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-hocking';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-highland' AND county_id = 'highland-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-highland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-henry' AND county_id = 'henry-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-henry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-harrison' AND county_id = 'harrison-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-harrison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-hardin' AND county_id = 'hardin-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-hardin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-hancock' AND county_id = 'hancock-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-hancock';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-hamilton' AND county_id = 'hamilton-oh';
UPDATE state_resource_agencies SET state_id = 'ohio', agency_type = 'cbdd', name = 'Hamilton County Developmental Disabilities Services', counties_served = 'hamilton-oh', catchment_boundaries = 'Serves Cincinnati and Hamilton County.', website = 'https://www.hamiltondds.org', intake_phone = '(513) 794-3300', early_intervention_contact = '(513) 794-3300', agency_intake_contact = '(513) 794-3300', eligibility_info_page = 'https://www.hamiltondds.org/', services_page = 'https://www.hamiltondds.org/', appeals_info = 'Waiver denials can be appealed to the state administrative hearing system within 30 days of the decision.', frc_relationship = NULL, office_locations = 'Hamilton County Developmental Disabilities Services office address', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://www.hamiltondds.org', source_url = 'https://www.hamiltondds.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-cbdd-hamilton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-guernsey' AND county_id = 'guernsey-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-guernsey';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-greene' AND county_id = 'greene-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-geauga' AND county_id = 'geauga-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-geauga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-gallia' AND county_id = 'gallia-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-gallia';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-fulton' AND county_id = 'fulton-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-fulton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-franklin' AND county_id = 'franklin-oh';
UPDATE state_resource_agencies SET state_id = 'ohio', agency_type = 'cbdd', name = 'Franklin County Board of Developmental Disabilities', counties_served = 'franklin-oh', catchment_boundaries = 'Serves Columbus and Franklin County.', website = 'https://fcbdd.org', intake_phone = '(614) 475-6050', early_intervention_contact = '(614) 475-6050', agency_intake_contact = '(614) 475-6050', eligibility_info_page = 'https://fcbdd.org/intake-eligibility/', services_page = 'https://fcbdd.org/services/', appeals_info = 'Waiver denials can be appealed to the state administrative hearing system within 30 days of the decision.', frc_relationship = NULL, office_locations = 'Franklin County Board of Developmental Disabilities office address', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://fcbdd.org', source_url = 'https://fcbdd.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-cbdd-franklin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-fayette' AND county_id = 'fayette-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-fayette';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-fairfield' AND county_id = 'fairfield-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-fairfield';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-erie' AND county_id = 'erie-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-erie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-delaware' AND county_id = 'delaware-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-delaware';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-defiance' AND county_id = 'defiance-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-defiance';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-darke' AND county_id = 'darke-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-darke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-cuyahoga' AND county_id = 'cuyahoga-oh';
UPDATE state_resource_agencies SET state_id = 'ohio', agency_type = 'cbdd', name = 'Cuyahoga County Board of Developmental Disabilities', counties_served = 'cuyahoga-oh', catchment_boundaries = 'Serves Cleveland and Cuyahoga County.', website = 'https://cuyahogabdd.org', intake_phone = '(216) 241-8230', early_intervention_contact = '(216) 241-8230', agency_intake_contact = '(216) 241-8230', eligibility_info_page = 'https://cuyahogabdd.org/start-services/', services_page = 'https://cuyahogabdd.org/', appeals_info = 'Waiver denials can be appealed to the state administrative hearing system within 30 days of the decision.', frc_relationship = NULL, office_locations = 'Cuyahoga County Board of Developmental Disabilities office address', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://cuyahogabdd.org', source_url = 'https://cuyahogabdd.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-cbdd-cuyahoga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-crawford' AND county_id = 'crawford-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-crawford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-coshocton' AND county_id = 'coshocton-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-coshocton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-columbiana' AND county_id = 'columbiana-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-columbiana';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-clinton' AND county_id = 'clinton-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-clinton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-clermont' AND county_id = 'clermont-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-clermont';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-clark' AND county_id = 'clark-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-clark';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-champaign' AND county_id = 'champaign-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-champaign';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-carroll' AND county_id = 'carroll-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-carroll';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-butler' AND county_id = 'butler-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-butler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-brown' AND county_id = 'brown-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-brown';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-belmont' AND county_id = 'belmont-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-belmont';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-auglaize' AND county_id = 'auglaize-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-auglaize';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-athens' AND county_id = 'athens-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-athens';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-ashtabula' AND county_id = 'ashtabula-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-ashtabula';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-ashland' AND county_id = 'ashland-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-ashland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-allen' AND county_id = 'allen-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-allen';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-cbdd-adams' AND county_id = 'adams-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-cbdd-adams';

COMMIT;
