-- Rollback Script for State: Ohio | Phase: district_replacements
-- Generated At: 2026-06-13T21:23:37.695Z

BEGIN TRANSACTION;

DELETE FROM school_districts WHERE id = 'rec-wyandot-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-wood-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-williams-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-wayne-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-washington-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-warren-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-vinton-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-van-wert-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-union-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-tuscarawas-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-trumbull-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-summit-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-stark-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-shelby-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-seneca-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-scioto-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-sandusky-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-ross-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-richland-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-putnam-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-preble-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-portage-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-pike-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-pickaway-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-perry-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-paulding-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-ottawa-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-noble-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-muskingum-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-morrow-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-morgan-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-montgomery-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-monroe-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-miami-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-mercer-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-meigs-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-medina-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-marion-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-mahoning-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-madison-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-lucas-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-lorain-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-logan-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-licking-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-lawrence-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-lake-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-knox-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-jefferson-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-jackson-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-huron-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-holmes-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-hocking-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-highland-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-henry-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-harrison-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-hardin-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-hancock-oh-oh';
UPDATE school_districts SET county_id = 'hamilton-oh', name = 'Oak Hills Local School District', spec_ed_contact_phone = '(513) 574-3200', spec_ed_contact_email = 'contact@ohlsd.us', website = 'https://education.ohio.gov/Topics/Special-Education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.ohio.gov/Topics/Special-Education', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-13', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'source_listed' WHERE id = 'rec-hamilton-oh-oh';
UPDATE school_districts SET county_id = 'hamilton-oh', name = 'Cincinnati Public Schools', spec_ed_contact_phone = '(513) 363-0000', spec_ed_contact_email = 'sped@cps-k12.org', website = 'https://education.ohio.gov/Topics/Special-Education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.ohio.gov/Topics/Special-Education', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-13', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'source_listed' WHERE id = 'rec-hamilton-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-hamilton-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-guernsey-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-greene-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-geauga-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-gallia-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-fulton-oh-oh';
UPDATE school_districts SET county_id = 'franklin-oh', name = 'Worthington City School District', spec_ed_contact_phone = '(614) 450-6000', spec_ed_contact_email = 'contact@worthington.k12.oh.us', website = 'https://education.ohio.gov/Topics/Special-Education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.ohio.gov/Topics/Special-Education', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-13', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'source_listed' WHERE id = 'rec-franklin-oh-oh';
UPDATE school_districts SET county_id = 'franklin-oh', name = 'Upper Arlington City School District', spec_ed_contact_phone = '(614) 487-5000', spec_ed_contact_email = 'sped@uaschools.org', website = 'https://education.ohio.gov/Topics/Special-Education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.ohio.gov/Topics/Special-Education', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-13', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'source_listed' WHERE id = 'rec-franklin-oh-oh';
UPDATE school_districts SET county_id = 'franklin-oh', name = 'Columbus City Schools', spec_ed_contact_phone = '(614) 365-5000', spec_ed_contact_email = 'spec.ed@ccsoh.us', website = 'https://education.ohio.gov/Topics/Special-Education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.ohio.gov/Topics/Special-Education', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-13', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'source_listed' WHERE id = 'rec-franklin-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-franklin-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-fayette-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-fairfield-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-erie-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-delaware-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-defiance-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-darke-oh-oh';
UPDATE school_districts SET county_id = 'cuyahoga-oh', name = 'Lakewood City School District', spec_ed_contact_phone = '(216) 529-4000', spec_ed_contact_email = 'special.ed@lakewoodcityschools.org', website = 'https://education.ohio.gov/Topics/Special-Education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.ohio.gov/Topics/Special-Education', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-13', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'source_listed' WHERE id = 'rec-cuyahoga-oh-oh';
UPDATE school_districts SET county_id = 'cuyahoga-oh', name = 'Cleveland Metropolitan School District', spec_ed_contact_phone = '(216) 838-0000', spec_ed_contact_email = 'sped@clevelandmetroschools.org', website = 'https://education.ohio.gov/Topics/Special-Education', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://education.ohio.gov/Topics/Special-Education', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-13', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'source_listed' WHERE id = 'rec-cuyahoga-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-cuyahoga-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-crawford-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-coshocton-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-columbiana-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-clinton-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-clermont-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-clark-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-champaign-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-carroll-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-butler-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-brown-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-belmont-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-auglaize-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-athens-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-ashtabula-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-ashland-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-allen-oh-oh';
DELETE FROM school_districts WHERE id = 'rec-adams-oh-oh';

COMMIT;
