-- Rollback Script for State: Ohio | Phase: early_intervention
-- Generated At: 2026-06-13T21:15:46.008Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-wyandot' AND county_id = 'wyandot-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-wyandot';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-wood' AND county_id = 'wood-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-wood';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-williams' AND county_id = 'williams-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-williams';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-wayne' AND county_id = 'wayne-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-washington' AND county_id = 'washington-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-warren' AND county_id = 'warren-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-vinton' AND county_id = 'vinton-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-vinton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-van-wert' AND county_id = 'van-wert-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-van-wert';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-union' AND county_id = 'union-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-union';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-tuscarawas' AND county_id = 'tuscarawas-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-tuscarawas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-trumbull' AND county_id = 'trumbull-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-trumbull';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-summit' AND county_id = 'summit-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-summit';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-stark' AND county_id = 'stark-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-stark';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-shelby' AND county_id = 'shelby-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-shelby';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-seneca' AND county_id = 'seneca-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-seneca';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-scioto' AND county_id = 'scioto-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-scioto';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-sandusky' AND county_id = 'sandusky-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-sandusky';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-ross' AND county_id = 'ross-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-ross';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-richland' AND county_id = 'richland-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-richland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-putnam' AND county_id = 'putnam-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-putnam';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-preble' AND county_id = 'preble-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-preble';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-portage' AND county_id = 'portage-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-portage';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-pike' AND county_id = 'pike-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-pike';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-pickaway' AND county_id = 'pickaway-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-pickaway';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-perry' AND county_id = 'perry-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-perry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-paulding' AND county_id = 'paulding-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-paulding';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-ottawa' AND county_id = 'ottawa-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-ottawa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-noble' AND county_id = 'noble-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-noble';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-muskingum' AND county_id = 'muskingum-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-muskingum';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-morrow' AND county_id = 'morrow-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-morrow';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-morgan' AND county_id = 'morgan-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-morgan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-montgomery' AND county_id = 'montgomery-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-monroe' AND county_id = 'monroe-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-monroe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-miami' AND county_id = 'miami-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-miami';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-mercer' AND county_id = 'mercer-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-mercer';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-meigs' AND county_id = 'meigs-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-meigs';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-medina' AND county_id = 'medina-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-medina';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-marion' AND county_id = 'marion-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-marion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-mahoning' AND county_id = 'mahoning-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-mahoning';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-madison' AND county_id = 'madison-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-madison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-lucas' AND county_id = 'lucas-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-lucas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-lorain' AND county_id = 'lorain-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-lorain';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-logan' AND county_id = 'logan-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-logan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-licking' AND county_id = 'licking-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-licking';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-lawrence' AND county_id = 'lawrence-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-lawrence';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-lake' AND county_id = 'lake-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-lake';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-knox' AND county_id = 'knox-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-knox';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-jefferson' AND county_id = 'jefferson-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-jefferson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-jackson' AND county_id = 'jackson-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-jackson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-huron' AND county_id = 'huron-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-huron';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-holmes' AND county_id = 'holmes-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-holmes';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-hocking' AND county_id = 'hocking-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-hocking';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-highland' AND county_id = 'highland-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-highland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-henry' AND county_id = 'henry-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-henry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-harrison' AND county_id = 'harrison-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-harrison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-hardin' AND county_id = 'hardin-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-hardin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-hancock' AND county_id = 'hancock-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-hancock';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-hamilton' AND county_id = 'hamilton-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-hamilton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-guernsey' AND county_id = 'guernsey-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-guernsey';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-greene' AND county_id = 'greene-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-geauga' AND county_id = 'geauga-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-geauga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-gallia' AND county_id = 'gallia-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-gallia';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-fulton' AND county_id = 'fulton-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-fulton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-franklin' AND county_id = 'franklin-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-franklin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-fayette' AND county_id = 'fayette-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-fayette';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-fairfield' AND county_id = 'fairfield-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-fairfield';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-erie' AND county_id = 'erie-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-erie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-delaware' AND county_id = 'delaware-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-delaware';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-defiance' AND county_id = 'defiance-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-defiance';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-darke' AND county_id = 'darke-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-darke';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-cuyahoga' AND county_id = 'cuyahoga-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-cuyahoga';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-crawford' AND county_id = 'crawford-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-crawford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-coshocton' AND county_id = 'coshocton-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-coshocton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-columbiana' AND county_id = 'columbiana-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-columbiana';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-clinton' AND county_id = 'clinton-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-clinton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-clermont' AND county_id = 'clermont-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-clermont';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-clark' AND county_id = 'clark-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-clark';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-champaign' AND county_id = 'champaign-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-champaign';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-carroll' AND county_id = 'carroll-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-carroll';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-butler' AND county_id = 'butler-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-butler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-brown' AND county_id = 'brown-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-brown';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-belmont' AND county_id = 'belmont-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-belmont';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-auglaize' AND county_id = 'auglaize-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-auglaize';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-athens' AND county_id = 'athens-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-athens';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-ashtabula' AND county_id = 'ashtabula-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-ashtabula';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-ashland' AND county_id = 'ashland-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-ashland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-allen' AND county_id = 'allen-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-allen';
DELETE FROM regional_center_counties WHERE regional_center_id = 'oh-ei-adams' AND county_id = 'adams-oh';
DELETE FROM state_resource_agencies WHERE id = 'oh-ei-adams';

COMMIT;
