-- Rollback Script for State: Ohio | Phase: education_regional
-- Generated At: 2026-06-13T21:16:04.337Z

BEGIN TRANSACTION;

DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-union' AND county_id = 'union-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-union';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-shelby' AND county_id = 'shelby-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-shelby';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-seneca' AND county_id = 'seneca-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-seneca';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-ross' AND county_id = 'ross-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-ross';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-medina' AND county_id = 'medina-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-medina';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-knox' AND county_id = 'knox-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-knox';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-guernsey' AND county_id = 'guernsey-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-guernsey';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-gallia-vinton' AND county_id = 'gallia-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-gallia-vinton';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-darke' AND county_id = 'darke-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-darke';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-ashtabula' AND county_id = 'ashtabula-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-ashtabula';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-wood' AND county_id = 'wood-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-wood';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-warren' AND county_id = 'warren-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-warren';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-trumbull' AND county_id = 'trumbull-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-trumbull';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-tri-county' AND county_id = 'wayne-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-tri-county';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-southern-ohio' AND county_id = 'clinton-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-southern-ohio';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-putnam' AND county_id = 'putnam-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-putnam';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-preble' AND county_id = 'preble-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-preble';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-pickaway' AND county_id = 'pickaway-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-pickaway';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-northwest' AND county_id = 'fulton-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-northwest';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-north-central' AND county_id = 'seneca-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-north-central';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-muskingum' AND county_id = 'muskingum-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-muskingum';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-mid-ohio' AND county_id = 'richland-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-mid-ohio';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-miami' AND county_id = 'miami-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-miami';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-mercer' AND county_id = 'mercer-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-mercer';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-madison-champaign' AND county_id = 'madison-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-madison-champaign';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-lorain' AND county_id = 'lorain-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-lorain';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-logan' AND county_id = 'logan-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-logan';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-licking' AND county_id = 'licking-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-licking';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-lawrence' AND county_id = 'lawrence-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-lawrence';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-jefferson' AND county_id = 'jefferson-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-jefferson';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-hancock' AND county_id = 'hancock-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-hancock';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-greene' AND county_id = 'greene-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-greene';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-geauga' AND county_id = 'geauga-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-geauga';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-fairfield' AND county_id = 'fairfield-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-fairfield';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-eastern-ohio' AND county_id = 'mahoning-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-eastern-ohio';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-east-central' AND county_id = 'tuscarawas-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-east-central';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-columbiana' AND county_id = 'columbiana-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-columbiana';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-clermont' AND county_id = 'clermont-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-clermont';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-clark' AND county_id = 'clark-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-clark';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-butler' AND county_id = 'butler-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-butler';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-brown' AND county_id = 'brown-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-brown';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-auglaize' AND county_id = 'auglaize-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-auglaize';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-athens' AND county_id = 'athens-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-athens';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-allen' AND county_id = 'allen-oh';
DELETE FROM regional_education_agencies WHERE id = 'oh-ed-esc-allen';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-stark' AND county_id = 'stark-oh';
UPDATE regional_education_agencies SET state_id = 'ohio', agency_type = 'esc', name = 'Stark County Educational Service Center', counties_served = 'stark-oh', website = 'https://www.starkcountyesc.org', source_url = 'https://www.starkcountyesc.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-ed-esc-stark';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-lucas' AND county_id = 'lucas-oh';
UPDATE regional_education_agencies SET state_id = 'ohio', agency_type = 'esc', name = 'Educational Service Center of Lake Erie West', counties_served = 'lucas-oh', website = 'https://www.esclew.org', source_url = 'https://www.esclew.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-ed-esc-lucas';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-montgomery' AND county_id = 'montgomery-oh';
UPDATE regional_education_agencies SET state_id = 'ohio', agency_type = 'esc', name = 'Montgomery County Educational Service Center', counties_served = 'montgomery-oh', website = 'https://www.mcesc.org', source_url = 'https://www.mcesc.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-ed-esc-montgomery';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-summit' AND county_id = 'summit-oh';
UPDATE regional_education_agencies SET state_id = 'ohio', agency_type = 'esc', name = 'Summit County Educational Service Center', counties_served = 'summit-oh', website = 'https://www.summitesc.org', source_url = 'https://www.summitesc.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-ed-esc-summit';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-hamilton' AND county_id = 'hamilton-oh';
UPDATE regional_education_agencies SET state_id = 'ohio', agency_type = 'esc', name = 'Hamilton County Educational Service Center', counties_served = 'hamilton-oh', website = 'https://www.hcesc.org', source_url = 'https://www.hcesc.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-ed-esc-hamilton';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-cuyahoga' AND county_id = 'cuyahoga-oh';
UPDATE regional_education_agencies SET state_id = 'ohio', agency_type = 'esc', name = 'ESC of Northeast Ohio', counties_served = 'cuyahoga-oh', website = 'https://www.escneo.org', source_url = 'https://www.escneo.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-ed-esc-cuyahoga';
DELETE FROM selpa_counties WHERE selpa_id = 'oh-ed-esc-franklin' AND county_id = 'franklin-oh';
UPDATE regional_education_agencies SET state_id = 'ohio', agency_type = 'esc', name = 'Educational Service Center of Central Ohio', counties_served = 'franklin-oh', website = 'https://www.escco.org', source_url = 'https://www.escco.org', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'oh-ed-esc-franklin';

COMMIT;
