-- Rollback Script for State: Illinois | Phase: dd_idd
-- Generated At: 2026-06-14T14:58:58.203Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'williamson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'white-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'wayne-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'washington-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'wabash-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'union-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'saline-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'richland-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'randolph-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'pulaski-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'pope-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'perry-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'monroe-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'massac-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'marion-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'lawrence-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'johnson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'jefferson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'jasper-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'jackson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'hardin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'hamilton-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'gallatin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'franklin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'fayette-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'edwards-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'crawford-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'clinton-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'clay-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'bond-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'alexander-il';
DELETE FROM state_resource_agencies WHERE id = 'il-isc-siccs';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'woodford-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'tazewell-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'scott-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'schuyler-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'sangamon-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'pike-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'morgan-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'montgomery-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'menard-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'mclean-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'mason-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'macoupin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'logan-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'jersey-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'hancock-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'greene-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'christian-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'cass-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'calhoun-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'brown-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'adams-il';
DELETE FROM state_resource_agencies WHERE id = 'il-isc-cisa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'st-clair-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'madison-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'vermilion-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'shelby-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'piatt-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'moultrie-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'macon-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'iroquois-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'ford-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'effingham-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'edgar-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'douglas-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'dewitt-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'cumberland-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'coles-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'clark-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'champaign-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'warren-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'stark-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'rock-island-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'peoria-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'mercer-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'mcdonough-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'knox-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'henry-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'henderson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'fulton-il';
UPDATE state_resource_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Prairieland ISC Agency', counties_served = 'sangamon-il', catchment_boundaries = 'Serves Springfield and Central IL.', website = 'https://www.dhs.state.il.us/', intake_phone = '(217) 525-1313', early_intervention_contact = '(217) 525-1313', agency_intake_contact = '(217) 525-1313', eligibility_info_page = 'https://www.dhs.state.il.us/', services_page = 'https://www.dhs.state.il.us/', appeals_info = 'Waiver denials can be appealed to the state administrative hearing system within 30 days of the decision.', frc_relationship = NULL, office_locations = 'Prairieland ISC Agency office address', languages = 'English, Spanish', last_verified_date = '2026-06-12', source_urls = 'https://www.dhs.state.il.us/', source_url = 'https://www.dhs.state.il.us/', source_type = 'official', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = '2026-06-13T01:29:19.415Z', confidence_score = 5, evidence_level = NULL WHERE id = 'il-isc-prairieland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-suburbanaccess' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-isc-suburbanaccess';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cso' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-isc-cso';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cau' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-isc-cau';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'will-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'livingston-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'kankakee-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'grundy-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'kendall-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'kane-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'dupage-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'winnebago-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'whiteside-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'stephenson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'putnam-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'ogle-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'mchenry-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'marshall-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'lee-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'lasalle-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'jo-daviess-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'dekalb-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'carroll-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'bureau-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'boone-il';
DELETE FROM state_resource_agencies WHERE id = 'il-isc-serviceinc';

COMMIT;
