-- Rollback Script for State: Illinois | Phase: dd_idd
-- Generated At: 2026-06-13T21:28:30.707Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-woodford' AND county_id = 'woodford-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-woodford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-winnebago' AND county_id = 'winnebago-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-winnebago';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-williamson' AND county_id = 'williamson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-williamson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-will' AND county_id = 'will-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-will';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-whiteside' AND county_id = 'whiteside-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-whiteside';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-white' AND county_id = 'white-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-white';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-wayne' AND county_id = 'wayne-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-washington' AND county_id = 'washington-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-warren' AND county_id = 'warren-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-wabash' AND county_id = 'wabash-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-wabash';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-vermilion' AND county_id = 'vermilion-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-vermilion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-union' AND county_id = 'union-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-union';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-tazewell' AND county_id = 'tazewell-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-tazewell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-stephenson' AND county_id = 'stephenson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-stephenson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-stark' AND county_id = 'stark-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-stark';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-st-clair' AND county_id = 'st-clair-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-st-clair';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-shelby' AND county_id = 'shelby-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-shelby';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-scott' AND county_id = 'scott-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-scott';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-schuyler' AND county_id = 'schuyler-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-schuyler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-sangamon' AND county_id = 'sangamon-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-sangamon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-saline' AND county_id = 'saline-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-saline';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-rock-island' AND county_id = 'rock-island-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-rock-island';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-richland' AND county_id = 'richland-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-richland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-randolph' AND county_id = 'randolph-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-randolph';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-putnam' AND county_id = 'putnam-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-putnam';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-pulaski' AND county_id = 'pulaski-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-pulaski';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-pope' AND county_id = 'pope-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-pope';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-pike' AND county_id = 'pike-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-pike';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-piatt' AND county_id = 'piatt-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-piatt';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-perry' AND county_id = 'perry-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-perry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-peoria' AND county_id = 'peoria-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-peoria';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-ogle' AND county_id = 'ogle-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-ogle';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-moultrie' AND county_id = 'moultrie-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-moultrie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-morgan' AND county_id = 'morgan-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-morgan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-montgomery' AND county_id = 'montgomery-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-monroe' AND county_id = 'monroe-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-monroe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-mercer' AND county_id = 'mercer-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-mercer';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-menard' AND county_id = 'menard-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-menard';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-mclean' AND county_id = 'mclean-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-mclean';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-mchenry' AND county_id = 'mchenry-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-mchenry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-mcdonough' AND county_id = 'mcdonough-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-mcdonough';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-massac' AND county_id = 'massac-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-massac';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-mason' AND county_id = 'mason-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-mason';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-marshall' AND county_id = 'marshall-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-marshall';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-marion' AND county_id = 'marion-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-marion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-madison' AND county_id = 'madison-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-madison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-macoupin' AND county_id = 'macoupin-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-macoupin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-macon' AND county_id = 'macon-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-macon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-logan' AND county_id = 'logan-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-logan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-livingston' AND county_id = 'livingston-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-livingston';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-lee' AND county_id = 'lee-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-lee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-lawrence' AND county_id = 'lawrence-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-lawrence';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-lasalle' AND county_id = 'lasalle-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-lasalle';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-lake' AND county_id = 'lake-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-lake';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-knox' AND county_id = 'knox-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-knox';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-kendall' AND county_id = 'kendall-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-kendall';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-kankakee' AND county_id = 'kankakee-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-kankakee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-kane' AND county_id = 'kane-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-kane';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-johnson' AND county_id = 'johnson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-johnson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-jo-daviess' AND county_id = 'jo-daviess-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-jo-daviess';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-jersey' AND county_id = 'jersey-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-jersey';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-jefferson' AND county_id = 'jefferson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-jefferson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-jasper' AND county_id = 'jasper-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-jasper';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-jackson' AND county_id = 'jackson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-jackson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-iroquois' AND county_id = 'iroquois-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-iroquois';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-henry' AND county_id = 'henry-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-henry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-henderson' AND county_id = 'henderson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-henderson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-hardin' AND county_id = 'hardin-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-hardin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-hancock' AND county_id = 'hancock-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-hancock';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-hamilton' AND county_id = 'hamilton-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-hamilton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-grundy' AND county_id = 'grundy-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-grundy';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-greene' AND county_id = 'greene-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-gallatin' AND county_id = 'gallatin-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-gallatin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-fulton' AND county_id = 'fulton-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-fulton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-franklin' AND county_id = 'franklin-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-franklin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-ford' AND county_id = 'ford-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-ford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-fayette' AND county_id = 'fayette-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-fayette';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-effingham' AND county_id = 'effingham-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-effingham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-edwards' AND county_id = 'edwards-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-edwards';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-edgar' AND county_id = 'edgar-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-edgar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-dupage' AND county_id = 'dupage-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-dupage';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-douglas' AND county_id = 'douglas-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-douglas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-dewitt' AND county_id = 'dewitt-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-dewitt';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-dekalb' AND county_id = 'dekalb-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-dekalb';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-cumberland' AND county_id = 'cumberland-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-cumberland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-crawford' AND county_id = 'crawford-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-crawford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-cook' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-cook';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-coles' AND county_id = 'coles-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-coles';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-clinton' AND county_id = 'clinton-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-clinton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-clay' AND county_id = 'clay-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-clay';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-clark' AND county_id = 'clark-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-clark';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-christian' AND county_id = 'christian-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-christian';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-champaign' AND county_id = 'champaign-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-champaign';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-cass' AND county_id = 'cass-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-cass';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-carroll' AND county_id = 'carroll-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-carroll';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-calhoun' AND county_id = 'calhoun-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-calhoun';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-bureau' AND county_id = 'bureau-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-bureau';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-brown' AND county_id = 'brown-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-brown';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-boone' AND county_id = 'boone-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-boone';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-bond' AND county_id = 'bond-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-bond';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-alexander' AND county_id = 'alexander-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-alexander';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-dd-adams' AND county_id = 'adams-il';
DELETE FROM state_resource_agencies WHERE id = 'il-dd-adams';

COMMIT;
