-- Rollback Script for State: Illinois | Phase: dd_idd
-- Generated At: 2026-06-14T23:43:07.578Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'williamson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'white-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'wayne-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'washington-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'wabash-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'union-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'saline-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'richland-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'randolph-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'pulaski-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'pope-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'perry-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'monroe-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'massac-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'marion-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'lawrence-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'johnson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'jefferson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'jasper-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'jackson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'hardin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'hamilton-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'gallatin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'franklin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'fayette-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'edwards-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'crawford-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'clinton-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'clay-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'bond-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-siccs' AND county_id = 'alexander-il';
UPDATE state_resource_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Southern Illinois Case Coordination Services (SICCS) (Southern Region)', counties_served = 'alexander-il,bond-il,clay-il,clinton-il,crawford-il,edwards-il,fayette-il,franklin-il,gallatin-il,hamilton-il,hardin-il,jackson-il,jasper-il,jefferson-il,johnson-il,lawrence-il,marion-il,massac-il,monroe-il,perry-il,pope-il,pulaski-il,randolph-il,richland-il,saline-il,union-il,wabash-il,washington-il,wayne-il,white-il,williamson-il', catchment_boundaries = 'alexander-il,bond-il,clay-il,clinton-il,crawford-il,edwards-il,fayette-il,franklin-il,gallatin-il,hamilton-il,hardin-il,jackson-il,jasper-il,jefferson-il,johnson-il,lawrence-il,marion-il,massac-il,monroe-il,perry-il,pope-il,pulaski-il,randolph-il,richland-il,saline-il,union-il,wabash-il,washington-il,wayne-il,white-il,williamson-il', website = 'http://www.siccs.org', intake_phone = '(618) 532-4300', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'http://www.siccs.org', source_url = 'http://www.siccs.org', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'il-isc-siccs';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'woodford-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'tazewell-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'scott-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'schuyler-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'sangamon-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'pike-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'morgan-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'montgomery-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'menard-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'mclean-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'mason-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'macoupin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'logan-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'jersey-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'hancock-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'greene-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'christian-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'cass-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'calhoun-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'brown-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cisa' AND county_id = 'adams-il';
UPDATE state_resource_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Central Illinois Service Access (CISA) (Central/West Region)', counties_served = 'adams-il,brown-il,calhoun-il,cass-il,christian-il,greene-il,hancock-il,jersey-il,logan-il,macoupin-il,mason-il,mclean-il,menard-il,montgomery-il,morgan-il,pike-il,sangamon-il,schuyler-il,scott-il,tazewell-il,woodford-il', catchment_boundaries = 'adams-il,brown-il,calhoun-il,cass-il,christian-il,greene-il,hancock-il,jersey-il,logan-il,macoupin-il,mason-il,mclean-il,menard-il,montgomery-il,morgan-il,pike-il,sangamon-il,schuyler-il,scott-il,tazewell-il,woodford-il', website = 'https://www.cisagroup.org', intake_phone = '(217) 732-4731', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://www.cisagroup.org', source_url = 'https://www.cisagroup.org', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'il-isc-cisa';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'st-clair-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'madison-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'vermilion-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'shelby-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'piatt-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'moultrie-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'macon-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'iroquois-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'ford-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'effingham-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'edgar-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'douglas-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'dewitt-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'cumberland-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'coles-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'clark-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'champaign-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'warren-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'stark-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'rock-island-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'peoria-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'mercer-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'mcdonough-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'knox-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'henry-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'henderson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-prairieland' AND county_id = 'fulton-il';
UPDATE state_resource_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Prairieland Service Coordination (Central/East Region)', counties_served = 'fulton-il,henderson-il,henry-il,knox-il,mcdonough-il,mercer-il,peoria-il,rock-island-il,stark-il,warren-il,champaign-il,clark-il,coles-il,cumberland-il,dewitt-il,douglas-il,edgar-il,effingham-il,ford-il,iroquois-il,macon-il,moultrie-il,piatt-il,shelby-il,vermilion-il,madison-il,st-clair-il', catchment_boundaries = 'fulton-il,henderson-il,henry-il,knox-il,mcdonough-il,mercer-il,peoria-il,rock-island-il,stark-il,warren-il,champaign-il,clark-il,coles-il,cumberland-il,dewitt-il,douglas-il,edgar-il,effingham-il,ford-il,iroquois-il,macon-il,moultrie-il,piatt-il,shelby-il,vermilion-il,madison-il,st-clair-il', website = 'http://psci.info', intake_phone = '(217) 362-6128', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'http://psci.info', source_url = 'http://psci.info', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'il-isc-prairieland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-suburbanaccess' AND county_id = 'cook-il';
UPDATE state_resource_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Suburban Access Inc. (Chicagoland South)', counties_served = 'cook-il', catchment_boundaries = 'cook-il', website = 'http://www.subacc.org', intake_phone = '(708) 799-9190', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'http://www.subacc.org', source_url = 'http://www.subacc.org', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'il-isc-suburbanaccess';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cso' AND county_id = 'cook-il';
UPDATE state_resource_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Community Service Options (CSO) (Chicagoland Central)', counties_served = 'cook-il', catchment_boundaries = 'cook-il', website = 'http://www.cso1.org', intake_phone = '(773) 471-4700', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'http://www.cso1.org', source_url = 'http://www.cso1.org', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'il-isc-cso';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-cau' AND county_id = 'cook-il';
UPDATE state_resource_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Community Alternatives Unlimited (CAU) (Chicagoland North/West)', counties_served = 'cook-il', catchment_boundaries = 'cook-il', website = 'http://www.cau.org', intake_phone = '(773) 867-4000', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'http://www.cau.org', source_url = 'http://www.cau.org', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'il-isc-cau';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'will-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'livingston-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'kankakee-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'grundy-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'kendall-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'kane-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'dupage-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'winnebago-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'whiteside-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'stephenson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'putnam-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'ogle-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'mchenry-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'marshall-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'lee-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'lasalle-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'jo-daviess-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'dekalb-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'carroll-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'bureau-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-isc-serviceinc' AND county_id = 'boone-il';
UPDATE state_resource_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Service Inc. of Illinois (Northern/Will Region)', counties_served = 'boone-il,bureau-il,carroll-il,dekalb-il,jo-daviess-il,lasalle-il,lee-il,marshall-il,mchenry-il,ogle-il,putnam-il,stephenson-il,whiteside-il,winnebago-il,dupage-il,kane-il,kendall-il,grundy-il,kankakee-il,livingston-il,will-il', catchment_boundaries = 'boone-il,bureau-il,carroll-il,dekalb-il,jo-daviess-il,lasalle-il,lee-il,marshall-il,mchenry-il,ogle-il,putnam-il,stephenson-il,whiteside-il,winnebago-il,dupage-il,kane-il,kendall-il,grundy-il,kankakee-il,livingston-il,will-il', website = 'http://www.svcincofil.org', intake_phone = '(815) 741-0800', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'http://www.svcincofil.org', source_url = 'http://www.svcincofil.org', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'direct_official_page' WHERE id = 'il-isc-serviceinc';

COMMIT;
