-- Rollback Script for State: Illinois | Phase: early_intervention
-- Generated At: 2026-06-14T14:58:58.231Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-25' AND county_id = 'dupage-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-25';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-24' AND county_id = 'union-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-24' AND county_id = 'pulaski-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-24' AND county_id = 'pope-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-24' AND county_id = 'perry-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-24' AND county_id = 'massac-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-24' AND county_id = 'johnson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-24' AND county_id = 'jackson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-24' AND county_id = 'hardin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-24' AND county_id = 'alexander-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-24';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-23' AND county_id = 'gallatin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-23' AND county_id = 'saline-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-23' AND county_id = 'hardin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-23' AND county_id = 'pope-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-23' AND county_id = 'johnson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-23' AND county_id = 'massac-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-23' AND county_id = 'pulaski-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-23' AND county_id = 'alexander-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-23';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-22' AND county_id = 'williamson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-22' AND county_id = 'jefferson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-22' AND county_id = 'franklin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-22' AND county_id = 'washington-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-22' AND county_id = 'clinton-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-22' AND county_id = 'marion-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-22';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-21' AND county_id = 'st-clair-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-21' AND county_id = 'randolph-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-21' AND county_id = 'monroe-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-21' AND county_id = 'madison-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-21';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-20' AND county_id = 'richland-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-20' AND county_id = 'lawrence-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-20' AND county_id = 'jasper-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-20' AND county_id = 'fayette-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-20' AND county_id = 'crawford-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-20' AND county_id = 'clay-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-20' AND county_id = 'effingham-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-20';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-19' AND county_id = 'shelby-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-19' AND county_id = 'moultrie-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-19' AND county_id = 'edgar-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-19' AND county_id = 'douglas-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-19' AND county_id = 'cumberland-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-19' AND county_id = 'clark-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-19' AND county_id = 'coles-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-19';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-18' AND county_id = 'macoupin-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-18' AND county_id = 'montgomery-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-18' AND county_id = 'christian-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-18' AND county_id = 'menard-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-18' AND county_id = 'logan-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-18' AND county_id = 'sangamon-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-18';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-17' AND county_id = 'schuyler-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-17' AND county_id = 'hancock-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-17' AND county_id = 'brown-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-17' AND county_id = 'pike-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-17' AND county_id = 'adams-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-17';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-16' AND county_id = 'livingston-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-16' AND county_id = 'mclean-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-16' AND county_id = 'vermilion-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-16' AND county_id = 'iroquois-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-16' AND county_id = 'ford-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-16' AND county_id = 'champaign-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-16';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-15' AND county_id = 'lasalle-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-15' AND county_id = 'kankakee-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-15' AND county_id = 'grundy-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-15' AND county_id = 'will-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-15';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-14' AND county_id = 'henry-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-14' AND county_id = 'woodford-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-14' AND county_id = 'tazewell-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-14' AND county_id = 'stark-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-14' AND county_id = 'peoria-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-14';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-13' AND county_id = 'warren-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-13' AND county_id = 'mcdonough-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-13' AND county_id = 'knox-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-13' AND county_id = 'henderson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-13';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-12' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-12';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-11' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-11';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-10' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-10';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-9' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-9';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-8' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-8';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-7' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-7';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-6' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-6';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-5' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-5';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-4' AND county_id = 'kendall-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-4' AND county_id = 'kane-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-4';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-3' AND county_id = 'whiteside-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-3' AND county_id = 'stephenson-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-3' AND county_id = 'lee-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-3' AND county_id = 'jo-daviess-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-3' AND county_id = 'dekalb-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-3' AND county_id = 'carroll-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-3';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-2' AND county_id = 'lake-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-2';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-1' AND county_id = 'winnebago-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-1' AND county_id = 'putnam-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-1' AND county_id = 'ogle-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-1' AND county_id = 'marshall-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-1' AND county_id = 'bureau-il';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-cfc-1' AND county_id = 'boone-il';
DELETE FROM state_resource_agencies WHERE id = 'il-cfc-1';

COMMIT;
