-- Rollback Script for State: Illinois | Phase: early_intervention
-- Generated At: 2026-06-13T21:27:56.193Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-woodford' AND county_id = 'woodford-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-woodford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-winnebago' AND county_id = 'winnebago-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-winnebago';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-williamson' AND county_id = 'williamson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-williamson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-will' AND county_id = 'will-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-will';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-whiteside' AND county_id = 'whiteside-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-whiteside';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-white' AND county_id = 'white-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-white';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-wayne' AND county_id = 'wayne-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-wayne';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-washington' AND county_id = 'washington-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-washington';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-warren' AND county_id = 'warren-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-warren';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-wabash' AND county_id = 'wabash-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-wabash';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-vermilion' AND county_id = 'vermilion-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-vermilion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-union' AND county_id = 'union-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-union';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-tazewell' AND county_id = 'tazewell-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-tazewell';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-stephenson' AND county_id = 'stephenson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-stephenson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-stark' AND county_id = 'stark-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-stark';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-st-clair' AND county_id = 'st-clair-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-st-clair';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-shelby' AND county_id = 'shelby-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-shelby';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-scott' AND county_id = 'scott-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-scott';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-schuyler' AND county_id = 'schuyler-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-schuyler';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-sangamon' AND county_id = 'sangamon-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-sangamon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-saline' AND county_id = 'saline-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-saline';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-rock-island' AND county_id = 'rock-island-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-rock-island';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-richland' AND county_id = 'richland-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-richland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-randolph' AND county_id = 'randolph-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-randolph';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-putnam' AND county_id = 'putnam-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-putnam';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-pulaski' AND county_id = 'pulaski-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-pulaski';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-pope' AND county_id = 'pope-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-pope';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-pike' AND county_id = 'pike-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-pike';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-piatt' AND county_id = 'piatt-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-piatt';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-perry' AND county_id = 'perry-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-perry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-peoria' AND county_id = 'peoria-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-peoria';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-ogle' AND county_id = 'ogle-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-ogle';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-moultrie' AND county_id = 'moultrie-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-moultrie';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-morgan' AND county_id = 'morgan-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-morgan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-montgomery' AND county_id = 'montgomery-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-montgomery';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-monroe' AND county_id = 'monroe-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-monroe';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-mercer' AND county_id = 'mercer-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-mercer';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-menard' AND county_id = 'menard-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-menard';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-mclean' AND county_id = 'mclean-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-mclean';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-mchenry' AND county_id = 'mchenry-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-mchenry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-mcdonough' AND county_id = 'mcdonough-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-mcdonough';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-massac' AND county_id = 'massac-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-massac';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-mason' AND county_id = 'mason-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-mason';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-marshall' AND county_id = 'marshall-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-marshall';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-marion' AND county_id = 'marion-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-marion';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-madison' AND county_id = 'madison-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-madison';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-macoupin' AND county_id = 'macoupin-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-macoupin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-macon' AND county_id = 'macon-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-macon';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-logan' AND county_id = 'logan-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-logan';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-livingston' AND county_id = 'livingston-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-livingston';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-lee' AND county_id = 'lee-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-lee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-lawrence' AND county_id = 'lawrence-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-lawrence';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-lasalle' AND county_id = 'lasalle-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-lasalle';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-lake' AND county_id = 'lake-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-lake';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-knox' AND county_id = 'knox-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-knox';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-kendall' AND county_id = 'kendall-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-kendall';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-kankakee' AND county_id = 'kankakee-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-kankakee';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-kane' AND county_id = 'kane-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-kane';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-johnson' AND county_id = 'johnson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-johnson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-jo-daviess' AND county_id = 'jo-daviess-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-jo-daviess';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-jersey' AND county_id = 'jersey-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-jersey';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-jefferson' AND county_id = 'jefferson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-jefferson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-jasper' AND county_id = 'jasper-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-jasper';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-jackson' AND county_id = 'jackson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-jackson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-iroquois' AND county_id = 'iroquois-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-iroquois';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-henry' AND county_id = 'henry-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-henry';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-henderson' AND county_id = 'henderson-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-henderson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-hardin' AND county_id = 'hardin-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-hardin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-hancock' AND county_id = 'hancock-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-hancock';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-hamilton' AND county_id = 'hamilton-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-hamilton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-grundy' AND county_id = 'grundy-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-grundy';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-greene' AND county_id = 'greene-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-greene';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-gallatin' AND county_id = 'gallatin-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-gallatin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-fulton' AND county_id = 'fulton-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-fulton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-franklin' AND county_id = 'franklin-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-franklin';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-ford' AND county_id = 'ford-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-ford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-fayette' AND county_id = 'fayette-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-fayette';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-effingham' AND county_id = 'effingham-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-effingham';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-edwards' AND county_id = 'edwards-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-edwards';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-edgar' AND county_id = 'edgar-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-edgar';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-dupage' AND county_id = 'dupage-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-dupage';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-douglas' AND county_id = 'douglas-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-douglas';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-dewitt' AND county_id = 'dewitt-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-dewitt';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-dekalb' AND county_id = 'dekalb-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-dekalb';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-cumberland' AND county_id = 'cumberland-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-cumberland';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-crawford' AND county_id = 'crawford-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-crawford';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-cook' AND county_id = 'cook-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-cook';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-coles' AND county_id = 'coles-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-coles';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-clinton' AND county_id = 'clinton-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-clinton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-clay' AND county_id = 'clay-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-clay';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-clark' AND county_id = 'clark-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-clark';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-christian' AND county_id = 'christian-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-christian';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-champaign' AND county_id = 'champaign-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-champaign';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-cass' AND county_id = 'cass-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-cass';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-carroll' AND county_id = 'carroll-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-carroll';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-calhoun' AND county_id = 'calhoun-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-calhoun';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-bureau' AND county_id = 'bureau-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-bureau';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-brown' AND county_id = 'brown-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-brown';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-boone' AND county_id = 'boone-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-boone';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-bond' AND county_id = 'bond-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-bond';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-alexander' AND county_id = 'alexander-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-alexander';
DELETE FROM regional_center_counties WHERE regional_center_id = 'il-ei-adams' AND county_id = 'adams-il';
DELETE FROM state_resource_agencies WHERE id = 'il-ei-adams';

COMMIT;
