-- Rollback Script for State: Illinois | Phase: education_regional
-- Generated At: 2026-06-14T14:58:58.261Z

BEGIN TRANSACTION;

DELETE FROM selpa_counties WHERE selpa_id = 'il-isc-3' AND county_id = 'cook-il';
DELETE FROM regional_education_agencies WHERE id = 'il-isc-3';
DELETE FROM selpa_counties WHERE selpa_id = 'il-isc-2' AND county_id = 'cook-il';
DELETE FROM regional_education_agencies WHERE id = 'il-isc-2';
DELETE FROM selpa_counties WHERE selpa_id = 'il-isc-1' AND county_id = 'cook-il';
DELETE FROM regional_education_agencies WHERE id = 'il-isc-1';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-56' AND county_id = 'will-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-56';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-51' AND county_id = 'menard-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-51' AND county_id = 'sangamon-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-51';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-50' AND county_id = 'st-clair-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-50';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-48' AND county_id = 'peoria-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-48';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-47' AND county_id = 'whiteside-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-47' AND county_id = 'ogle-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-47' AND county_id = 'lee-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-47';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-41' AND county_id = 'madison-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-41';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-40' AND county_id = 'macoupin-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-40' AND county_id = 'jersey-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-40' AND county_id = 'greene-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-40' AND county_id = 'calhoun-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-40';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-35' AND county_id = 'putnam-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-35' AND county_id = 'marshall-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-35' AND county_id = 'lasalle-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-35';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-34' AND county_id = 'lake-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-34';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-33' AND county_id = 'warren-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-33' AND county_id = 'mercer-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-33' AND county_id = 'knox-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-33' AND county_id = 'henderson-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-33';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-31' AND county_id = 'kane-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-31';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'union-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'pulaski-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'perry-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'jackson-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'alexander-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-30';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-26' AND county_id = 'schuyler-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-26' AND county_id = 'fulton-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-26' AND county_id = 'mcdonough-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-26' AND county_id = 'hancock-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-26';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-21' AND county_id = 'williamson-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-21' AND county_id = 'massac-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-21' AND county_id = 'johnson-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-21' AND county_id = 'franklin-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-21';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-19' AND county_id = 'dupage-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-19';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'woodford-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'mclean-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'logan-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'livingston-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'dewitt-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-17';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-9' AND county_id = 'ford-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-9' AND county_id = 'champaign-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-9';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-8' AND county_id = 'stephenson-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-8' AND county_id = 'jo-daviess-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-8' AND county_id = 'carroll-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-8';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-4' AND county_id = 'winnebago-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-4' AND county_id = 'boone-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-4';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'montgomery-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'fayette-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'effingham-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'christian-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'bond-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-3';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'scott-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'pike-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'morgan-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'cass-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'brown-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'adams-il';
DELETE FROM regional_education_agencies WHERE id = 'il-roe-1';

COMMIT;
