-- Rollback Script for State: Illinois | Phase: education_regional
-- Generated At: 2026-06-14T23:43:17.438Z

BEGIN TRANSACTION;

DELETE FROM selpa_counties WHERE selpa_id = 'il-isc-3' AND county_id = 'cook-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Intermediate Service Center (ISC) 3 - South Cook', counties_served = 'cook-il', website = 'https://www.southcook.org', source_url = 'https://www.southcook.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-isc-3';
DELETE FROM selpa_counties WHERE selpa_id = 'il-isc-2' AND county_id = 'cook-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Intermediate Service Center (ISC) 2 - West Cook', counties_served = 'cook-il', website = 'https://www.westcook.org', source_url = 'https://www.westcook.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-isc-2';
DELETE FROM selpa_counties WHERE selpa_id = 'il-isc-1' AND county_id = 'cook-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'isc', name = 'Intermediate Service Center (ISC) 1 - North Cook', counties_served = 'cook-il', website = 'https://www.northcook.org', source_url = 'https://www.northcook.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-isc-1';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-56' AND county_id = 'will-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Will Regional Office of Education (ROE 56)', counties_served = 'will-il', website = 'https://www.willroe.org', source_url = 'https://www.willroe.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-56';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-51' AND county_id = 'menard-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-51' AND county_id = 'sangamon-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Sangamon/Menard Regional Office of Education (ROE 51)', counties_served = 'sangamon-il,menard-il', website = 'https://www.roe51.org', source_url = 'https://www.roe51.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-51';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-50' AND county_id = 'st-clair-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'St. Clair Regional Office of Education (ROE 50)', counties_served = 'st-clair-il', website = 'https://www.sclair.k12.il.us', source_url = 'https://www.sclair.k12.il.us', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-50';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-48' AND county_id = 'peoria-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Peoria Regional Office of Education (ROE 48)', counties_served = 'peoria-il', website = 'https://www.peoriacounty.org/roe', source_url = 'https://www.peoriacounty.org/roe', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-48';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-47' AND county_id = 'whiteside-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-47' AND county_id = 'ogle-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-47' AND county_id = 'lee-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Lee/Ogle/Whiteside Regional Office of Education (ROE 47)', counties_served = 'lee-il,ogle-il,whiteside-il', website = 'https://www.roe47.org', source_url = 'https://www.roe47.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-47';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-41' AND county_id = 'madison-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Madison Regional Office of Education (ROE 41)', counties_served = 'madison-il', website = 'https://www.madisoncountyil.gov', source_url = 'https://www.madisoncountyil.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-41';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-40' AND county_id = 'macoupin-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-40' AND county_id = 'jersey-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-40' AND county_id = 'greene-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-40' AND county_id = 'calhoun-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Calhoun/Greene/Jersey Regional Office of Education (ROE 40)', counties_served = 'calhoun-il,greene-il,jersey-il,macoupin-il', website = 'https://www.roe40.com', source_url = 'https://www.roe40.com', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-40';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-35' AND county_id = 'putnam-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-35' AND county_id = 'marshall-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-35' AND county_id = 'lasalle-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'LaSalle/Marshall/Putnam Regional Office of Education (ROE 35)', counties_served = 'lasalle-il,marshall-il,putnam-il', website = 'https://www.roe35.org', source_url = 'https://www.roe35.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-35';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-34' AND county_id = 'lake-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Lake Regional Office of Education (ROE 34)', counties_served = 'lake-il', website = 'https://www.lake.k12.il.us', source_url = 'https://www.lake.k12.il.us', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-34';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-33' AND county_id = 'warren-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-33' AND county_id = 'mercer-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-33' AND county_id = 'knox-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-33' AND county_id = 'henderson-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Henderson/Knox/Mercer/Warren Regional Office of Education (ROE 33)', counties_served = 'henderson-il,knox-il,mercer-il,warren-il', website = 'https://www.roe33.net', source_url = 'https://www.roe33.net', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-33';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-31' AND county_id = 'kane-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Kane Regional Office of Education (ROE 31)', counties_served = 'kane-il', website = 'https://www.kaneroe.org', source_url = 'https://www.kaneroe.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-31';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'union-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'pulaski-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'perry-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'jackson-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-30' AND county_id = 'alexander-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Alexander/Jackson/Perry Regional Office of Education (ROE 30)', counties_served = 'alexander-il,jackson-il,perry-il,pulaski-il,union-il', website = 'https://www.roe30.org', source_url = 'https://www.roe30.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-30';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-26' AND county_id = 'schuyler-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-26' AND county_id = 'fulton-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-26' AND county_id = 'mcdonough-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-26' AND county_id = 'hancock-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Hancock/McDonough Regional Office of Education (ROE 26)', counties_served = 'hancock-il,mcdonough-il,fulton-il,schuyler-il', website = 'https://www.roe26.net', source_url = 'https://www.roe26.net', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-26';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-21' AND county_id = 'williamson-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-21' AND county_id = 'massac-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-21' AND county_id = 'johnson-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-21' AND county_id = 'franklin-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Franklin/Johnson/Massac Regional Office of Education (ROE 21)', counties_served = 'franklin-il,johnson-il,massac-il,williamson-il', website = 'https://www.roe21.org', source_url = 'https://www.roe21.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-21';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-19' AND county_id = 'dupage-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'DuPage Regional Office of Education (ROE 19)', counties_served = 'dupage-il', website = 'https://www.dupageROE.org', source_url = 'https://www.dupageROE.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-19';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'woodford-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'mclean-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'logan-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'livingston-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-17' AND county_id = 'dewitt-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'DeWitt/Livingston/McLean Regional Office of Education (ROE 17)', counties_served = 'dewitt-il,livingston-il,logan-il,mclean-il,woodford-il', website = 'https://www.roe17.org', source_url = 'https://www.roe17.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-17';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-9' AND county_id = 'ford-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-9' AND county_id = 'champaign-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Champaign/Ford Regional Office of Education (ROE 9)', counties_served = 'champaign-il,ford-il', website = 'https://www.roe9.org', source_url = 'https://www.roe9.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-9';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-8' AND county_id = 'stephenson-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-8' AND county_id = 'jo-daviess-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-8' AND county_id = 'carroll-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Carroll/Jo Daviess/Stephenson Regional Office of Education (ROE 8)', counties_served = 'carroll-il,jo-daviess-il,stephenson-il', website = 'https://www.roe8.org', source_url = 'https://www.roe8.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-8';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-4' AND county_id = 'winnebago-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-4' AND county_id = 'boone-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Boone/Winnebago Regional Office of Education (ROE 4)', counties_served = 'boone-il,winnebago-il', website = 'https://www.roe4.org', source_url = 'https://www.roe4.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-4';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'montgomery-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'fayette-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'effingham-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'christian-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-3' AND county_id = 'bond-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Bond/Christian/Effingham Regional Office of Education (ROE 3)', counties_served = 'bond-il,christian-il,effingham-il,fayette-il,montgomery-il', website = 'https://www.roe3.org', source_url = 'https://www.roe3.org', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-3';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'scott-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'pike-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'morgan-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'cass-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'brown-il';
DELETE FROM selpa_counties WHERE selpa_id = 'il-roe-1' AND county_id = 'adams-il';
UPDATE regional_education_agencies SET state_id = 'illinois', agency_type = 'roe', name = 'Adams/Pike Regional Office of Education (ROE 1)', counties_served = 'adams-il,brown-il,cass-il,morgan-il,pike-il,scott-il', website = 'https://www.roe1.net', source_url = 'https://www.roe1.net', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'il-roe-1';

COMMIT;
