-- Rollback Script for State: New Jersey | Phase: benefits_hhs
-- Generated At: 2026-06-15T21:55:14.080Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'warren-nj', program_id = 'nj-medicaid', office_name = 'Warren County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-warren-nj-medicaid';
UPDATE county_offices SET county_id = 'union-nj', program_id = 'nj-medicaid', office_name = 'Union County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-union-nj-medicaid';
UPDATE county_offices SET county_id = 'sussex-nj', program_id = 'nj-medicaid', office_name = 'Sussex County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-sussex-nj-medicaid';
UPDATE county_offices SET county_id = 'somerset-nj', program_id = 'nj-medicaid', office_name = 'Somerset County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-somerset-nj-medicaid';
UPDATE county_offices SET county_id = 'salem-nj', program_id = 'nj-medicaid', office_name = 'Salem County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-salem-nj-medicaid';
UPDATE county_offices SET county_id = 'passaic-nj', program_id = 'nj-medicaid', office_name = 'Passaic County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-passaic-nj-medicaid';
UPDATE county_offices SET county_id = 'ocean-nj', program_id = 'nj-medicaid', office_name = 'Ocean County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-ocean-nj-medicaid';
UPDATE county_offices SET county_id = 'morris-nj', program_id = 'nj-medicaid', office_name = 'Morris County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-morris-nj-medicaid';
UPDATE county_offices SET county_id = 'monmouth-nj', program_id = 'nj-medicaid', office_name = 'Monmouth County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-monmouth-nj-medicaid';
UPDATE county_offices SET county_id = 'middlesex-nj', program_id = 'nj-medicaid', office_name = 'Middlesex County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-middlesex-nj-medicaid';
UPDATE county_offices SET county_id = 'mercer-nj', program_id = 'nj-medicaid', office_name = 'Mercer County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-mercer-nj-medicaid';
UPDATE county_offices SET county_id = 'hunterdon-nj', program_id = 'nj-medicaid', office_name = 'Hunterdon County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-hunterdon-nj-medicaid';
UPDATE county_offices SET county_id = 'hudson-nj', program_id = 'nj-medicaid', office_name = 'Hudson County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-hudson-nj-medicaid';
UPDATE county_offices SET county_id = 'gloucester-nj', program_id = 'nj-medicaid', office_name = 'Gloucester County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-gloucester-nj-medicaid';
UPDATE county_offices SET county_id = 'essex-nj', program_id = 'nj-medicaid', office_name = 'Essex County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-essex-nj-medicaid';
UPDATE county_offices SET county_id = 'cumberland-nj', program_id = 'nj-medicaid', office_name = 'Cumberland County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-cumberland-nj-medicaid';
UPDATE county_offices SET county_id = 'cape-may-nj', program_id = 'nj-medicaid', office_name = 'Cape May County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-cape-may-nj-medicaid';
UPDATE county_offices SET county_id = 'camden-nj', program_id = 'nj-medicaid', office_name = 'Camden County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-camden-nj-medicaid';
UPDATE county_offices SET county_id = 'burlington-nj', program_id = 'nj-medicaid', office_name = 'Burlington County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-burlington-nj-medicaid';
UPDATE county_offices SET county_id = 'bergen-nj', program_id = 'nj-medicaid', office_name = 'Bergen County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-bergen-nj-medicaid';
UPDATE county_offices SET county_id = 'atlantic-nj', program_id = 'nj-medicaid', office_name = 'Atlantic County storefront office', address = '', phone = '(800) 356-1561', email = '', website = 'https://www.njhelps.org/', source_url = 'https://www.state.nj.us/humanservices/dfd/counties/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-15', last_scraped_at = '2026-06-15', confidence_score = 0.85, evidence_level = 'official_locator_derived' WHERE id = 'off-atlantic-nj-medicaid';

COMMIT;
