-- Rollback Script for State: New Jersey | Phase: benefits_hhs
-- Generated At: 2026-06-14T22:50:06.685Z

BEGIN TRANSACTION;

UPDATE county_offices SET county_id = 'warren-nj', program_id = 'nj-medicaid', office_name = 'Warren County Board of Social Services', address = '3 Shotwell Dr., Belvidere, NJ 07823', phone = '(908) 475-6301', email = NULL, website = 'https://www.warrencountynj.gov/government/human-services/division-of-temporary-assistance-and-social-services/social-services', source_url = 'https://www.warrencountynj.gov/government/human-services/division-of-temporary-assistance-and-social-services/social-services', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-warren-nj-medicaid';
UPDATE county_offices SET county_id = 'union-nj', program_id = 'nj-medicaid', office_name = 'Union County Board of Social Services', address = '342 Westminster Avenue, Elizabeth, NJ 07208-3290', phone = '(908) 558-2288', email = NULL, website = 'https://ucnj.org/', source_url = 'https://ucnj.org/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-union-nj-medicaid';
UPDATE county_offices SET county_id = 'sussex-nj', program_id = 'nj-medicaid', office_name = 'Sussex County Board of Social Services', address = '83 Spring Street, Suite 203, PO Box 218, Newton, NJ 07860', phone = '(973) 383-3600', email = NULL, website = 'https://sussex.nj.us/cn/webpage.cfm?tpid=994', source_url = 'https://sussex.nj.us/cn/webpage.cfm?tpid=994', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-sussex-nj-medicaid';
UPDATE county_offices SET county_id = 'somerset-nj', program_id = 'nj-medicaid', office_name = 'Somerset County Board of Social Services', address = '73 East High Street, PO Box 936, Somerville, NJ 08876-0936', phone = '(908) 526-8800', email = NULL, website = 'https://www.co.somerset.nj.us/government/affiliated-agencies/social-services', source_url = 'https://www.co.somerset.nj.us/government/affiliated-agencies/social-services', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-somerset-nj-medicaid';
UPDATE county_offices SET county_id = 'salem-nj', program_id = 'nj-medicaid', office_name = 'Salem County Board of Social Services', address = '147 South Virginia Avenue, Penns Grove, NJ 08069-1797', phone = '(856) 299-7200', email = NULL, website = 'https://www.scbssnj.org/', source_url = 'https://www.scbssnj.org/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-salem-nj-medicaid';
UPDATE county_offices SET county_id = 'passaic-nj', program_id = 'nj-medicaid', office_name = 'Passaic County Board of Social Services', address = '80 Hamilton Street, Paterson, NJ 07505-2060', phone = '(973) 881-0100', email = NULL, website = 'http://pcbss.org/', source_url = 'http://pcbss.org/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-passaic-nj-medicaid';
UPDATE county_offices SET county_id = 'ocean-nj', program_id = 'nj-medicaid', office_name = 'Ocean County Board of Social Services', address = '1005 Hooper Avenue, P.O. Box 547, Toms River, NJ 08753', phone = '(732) 349-1500', email = NULL, website = 'https://co.ocean.nj.us/socialservices/', source_url = 'https://co.ocean.nj.us/socialservices/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-ocean-nj-medicaid';
UPDATE county_offices SET county_id = 'morris-nj', program_id = 'nj-medicaid', office_name = 'Morris County Board of Social Services', address = '340 W. Hanover Ave (Morris Township), PO Box 900, Morristown, NJ 07963-0900', phone = '(973) 326-7800', email = NULL, website = 'https://www.morriscountynj.gov/Residents/Community-Information/Public-Assistance', source_url = 'https://www.morriscountynj.gov/Residents/Community-Information/Public-Assistance', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-morris-nj-medicaid';
UPDATE county_offices SET county_id = 'monmouth-nj', program_id = 'nj-medicaid', office_name = 'Monmouth County Board of Social Services', address = '3000 Kozloski Road, PO Box 3000, Freehold, NJ 07728', phone = '(732) 431-6000', email = NULL, website = 'https://www.visitmonmouth.com/Page.aspx?Id=163', source_url = 'https://www.visitmonmouth.com/Page.aspx?Id=163', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-monmouth-nj-medicaid';
UPDATE county_offices SET county_id = 'middlesex-nj', program_id = 'nj-medicaid', office_name = 'Middlesex County Board of Social Services', address = '181 How Lane, PO Box 509, New Brunswick, NJ 08903', phone = '(732) 745-3500', email = NULL, website = 'http://middlesexsocialservices.com/', source_url = 'http://middlesexsocialservices.com/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-middlesex-nj-medicaid';
UPDATE county_offices SET county_id = 'mercer-nj', program_id = 'nj-medicaid', office_name = 'Mercer County Board of Social Services', address = '200 Woolverton Street, PO Box 1450, Trenton, NJ 08650-2099', phone = '(609) 989-4320', email = NULL, website = 'https://www.mcboss.org/', source_url = 'https://www.mcboss.org/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-mercer-nj-medicaid';
UPDATE county_offices SET county_id = 'hunterdon-nj', program_id = 'nj-medicaid', office_name = 'Hunterdon County Department of Human Services', address = 'Division of Social Services, 6 Gauntt Place, PO Box 2900, Flemington, NJ 08822-2900', phone = '(908) 788-1300', email = NULL, website = 'https://www.co.hunterdon.nj.us/depts/social/socserv.htm', source_url = 'https://www.co.hunterdon.nj.us/depts/social/socserv.htm', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-hunterdon-nj-medicaid';
UPDATE county_offices SET county_id = 'hudson-nj', program_id = 'nj-medicaid', office_name = 'Hudson County Department of Family Services', address = 'Welfare Division, 257 Cornelison Ave., Jersey City, NJ 07302', phone = '(201) 420-3000', email = NULL, website = 'https://www.hcnj.us/family-services/welfare/', source_url = 'https://www.hcnj.us/family-services/welfare/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-hudson-nj-medicaid';
UPDATE county_offices SET county_id = 'gloucester-nj', program_id = 'nj-medicaid', office_name = 'Gloucester County Board of Social Services', address = '400 Hollydell Drive, Sewell, NJ 08080', phone = '(856) 582-9200', email = NULL, website = 'https://www.gloucestercountynj.gov/510/Social-Services', source_url = 'https://www.gloucestercountynj.gov/510/Social-Services', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-gloucester-nj-medicaid';
UPDATE county_offices SET county_id = 'essex-nj', program_id = 'nj-medicaid', office_name = 'Essex County Department of Citizen Services', address = 'Division of Family Assistance and Benefits, 320 University Avenue - 2nd Floor, Newark, NJ 07102', phone = '(973) 395-8000', email = NULL, website = 'https://essexcountynj.org/welfare/', source_url = 'https://essexcountynj.org/welfare/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-essex-nj-medicaid';
UPDATE county_offices SET county_id = 'cumberland-nj', program_id = 'nj-medicaid', office_name = 'Cumberland County Board of Social Services', address = '275 North Delsea Dr., Vineland, NJ 08360-3607', phone = '(856) 691-4600', email = NULL, website = 'http://www.co.cumberland.nj.us/socialservices', source_url = 'http://www.co.cumberland.nj.us/socialservices', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-cumberland-nj-medicaid';
UPDATE county_offices SET county_id = 'cape-may-nj', program_id = 'nj-medicaid', office_name = 'Cape May County Department of Social Services', address = 'Social Services Building, 3801 Route 9 South - Unit 4, Rio Grande, NJ 08242-1911', phone = '(609) 886-6200', email = NULL, website = 'https://capemaycountynj.gov/984/Cape-May-County-Social-Services', source_url = 'https://capemaycountynj.gov/984/Cape-May-County-Social-Services', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-cape-may-nj-medicaid';
UPDATE county_offices SET county_id = 'camden-nj', program_id = 'nj-medicaid', office_name = 'Camden County Board of Social Services', address = '101 Woodcrest Road, Suite 161, Cherry Hill, NJ 08003', phone = '(856) 225-8800', email = NULL, website = 'https://www.camdencounty.com/service/social-services/', source_url = 'https://www.camdencounty.com/service/social-services/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-camden-nj-medicaid';
UPDATE county_offices SET county_id = 'burlington-nj', program_id = 'nj-medicaid', office_name = 'Burlington County Board of Social Services', address = 'Human Services Facility, 795 Woodlane Road, Mount Holly, NJ 08060-3335', phone = '(609) 261-1000', email = NULL, website = 'http://www.bcbss.org/', source_url = 'http://www.bcbss.org/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-burlington-nj-medicaid';
UPDATE county_offices SET county_id = 'bergen-nj', program_id = 'nj-medicaid', office_name = 'Bergen County Board of Social Services', address = '218 Route 17 North, Rochelle Park, NJ 07662-3300', phone = '(201) 368-4200', email = NULL, website = 'https://bcbss.com/', source_url = 'https://bcbss.com/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-bergen-nj-medicaid';
UPDATE county_offices SET county_id = 'atlantic-nj', program_id = 'nj-medicaid', office_name = 'Department of Family and Community Development', address = '1333 Atlantic Avenue, Atlantic City, NJ 08401-8297', phone = '(609) 348-3001', email = NULL, website = 'https://www.atlantic-county.org/family-community-development/', source_url = 'https://www.atlantic-county.org/family-community-development/', source_type = 'official_locator', data_origin = 'scraped', verification_status = 'source_listed', last_verified_date = '2026-06-14', last_scraped_at = '2026-06-14', confidence_score = 10, evidence_level = 'official_locator_derived' WHERE id = 'off-atlantic-nj-medicaid';

COMMIT;
