-- Rollback Script for State: New Jersey | Phase: dd_idd
-- Generated At: 2026-06-14T22:50:07.004Z

BEGIN TRANSACTION;

DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-voorhees' AND county_id = 'gloucester-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-voorhees' AND county_id = 'camden-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-voorhees' AND county_id = 'burlington-nj';
UPDATE state_resource_agencies SET state_id = 'new-jersey', agency_type = 'regional_center', name = 'Voorhees Community Services Office', counties_served = 'burlington-nj, camden-nj, gloucester-nj', catchment_boundaries = 'burlington-nj, camden-nj, gloucester-nj', website = 'https://nj.gov/humanservices/ddd/', intake_phone = '(856) 770-5404', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://nj.gov/humanservices/ddd/', source_url = 'https://nj.gov/humanservices/ddd/', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 10, evidence_level = 'direct_official_page' WHERE id = 'nj-ddd-voorhees';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-egg-harbor' AND county_id = 'salem-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-egg-harbor' AND county_id = 'cumberland-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-egg-harbor' AND county_id = 'cape-may-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-egg-harbor' AND county_id = 'atlantic-nj';
UPDATE state_resource_agencies SET state_id = 'new-jersey', agency_type = 'regional_center', name = 'Egg Harbor Community Services Office', counties_served = 'atlantic-nj, cape-may-nj, cumberland-nj, salem-nj', catchment_boundaries = 'atlantic-nj, cape-may-nj, cumberland-nj, salem-nj', website = 'https://nj.gov/humanservices/ddd/', intake_phone = '(609) 300-1898', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://nj.gov/humanservices/ddd/', source_url = 'https://nj.gov/humanservices/ddd/', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 10, evidence_level = 'direct_official_page' WHERE id = 'nj-ddd-egg-harbor';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-trenton' AND county_id = 'middlesex-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-trenton' AND county_id = 'mercer-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-trenton' AND county_id = 'hunterdon-nj';
UPDATE state_resource_agencies SET state_id = 'new-jersey', agency_type = 'regional_center', name = 'Trenton Community Services Office', counties_served = 'hunterdon-nj, mercer-nj, middlesex-nj', catchment_boundaries = 'hunterdon-nj, mercer-nj, middlesex-nj', website = 'https://nj.gov/humanservices/ddd/', intake_phone = '(609) 292-1922', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://nj.gov/humanservices/ddd/', source_url = 'https://nj.gov/humanservices/ddd/', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 10, evidence_level = 'direct_official_page' WHERE id = 'nj-ddd-trenton';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-freehold' AND county_id = 'monmouth-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-freehold' AND county_id = 'ocean-nj';
UPDATE state_resource_agencies SET state_id = 'new-jersey', agency_type = 'regional_center', name = 'Freehold Community Services Office', counties_served = 'ocean-nj, monmouth-nj', catchment_boundaries = 'ocean-nj, monmouth-nj', website = 'https://nj.gov/humanservices/ddd/', intake_phone = '(732) 863-4500', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://nj.gov/humanservices/ddd/', source_url = 'https://nj.gov/humanservices/ddd/', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 10, evidence_level = 'direct_official_page' WHERE id = 'nj-ddd-freehold';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-green-brook' AND county_id = 'somerset-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-green-brook' AND county_id = 'union-nj';
UPDATE state_resource_agencies SET state_id = 'new-jersey', agency_type = 'regional_center', name = 'Green Brook Community Services Office', counties_served = 'union-nj, somerset-nj', catchment_boundaries = 'union-nj, somerset-nj', website = 'https://nj.gov/humanservices/ddd/', intake_phone = '(908) 226-7800', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://nj.gov/humanservices/ddd/', source_url = 'https://nj.gov/humanservices/ddd/', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 10, evidence_level = 'direct_official_page' WHERE id = 'nj-ddd-green-brook';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-newark' AND county_id = 'essex-nj';
UPDATE state_resource_agencies SET state_id = 'new-jersey', agency_type = 'regional_center', name = 'Newark Community Services Office', counties_served = 'essex-nj', catchment_boundaries = 'essex-nj', website = 'https://nj.gov/humanservices/ddd/', intake_phone = '(973) 693-5080', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://nj.gov/humanservices/ddd/', source_url = 'https://nj.gov/humanservices/ddd/', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 10, evidence_level = 'direct_official_page' WHERE id = 'nj-ddd-newark';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-paterson' AND county_id = 'passaic-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-paterson' AND county_id = 'hudson-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-paterson' AND county_id = 'bergen-nj';
UPDATE state_resource_agencies SET state_id = 'new-jersey', agency_type = 'regional_center', name = 'Paterson Community Services Office', counties_served = 'bergen-nj, hudson-nj, passaic-nj', catchment_boundaries = 'bergen-nj, hudson-nj, passaic-nj', website = 'https://nj.gov/humanservices/ddd/', intake_phone = '(973) 977-4004', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://nj.gov/humanservices/ddd/', source_url = 'https://nj.gov/humanservices/ddd/', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 10, evidence_level = 'direct_official_page' WHERE id = 'nj-ddd-paterson';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-flanders' AND county_id = 'warren-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-flanders' AND county_id = 'sussex-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-flanders' AND county_id = 'morris-nj';
UPDATE state_resource_agencies SET state_id = 'new-jersey', agency_type = 'regional_center', name = 'Flanders Community Services Office', counties_served = 'morris-nj, sussex-nj, warren-nj', catchment_boundaries = 'morris-nj, sussex-nj, warren-nj', website = 'https://nj.gov/humanservices/ddd/', intake_phone = '(973) 927-2600', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://nj.gov/humanservices/ddd/', source_url = 'https://nj.gov/humanservices/ddd/', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 10, evidence_level = 'direct_official_page' WHERE id = 'nj-ddd-flanders';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'warren-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'union-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'sussex-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'somerset-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'salem-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'passaic-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'ocean-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'morris-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'monmouth-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'middlesex-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'mercer-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'hunterdon-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'hudson-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'gloucester-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'essex-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'cumberland-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'cape-may-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'camden-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'burlington-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'bergen-nj';
DELETE FROM regional_center_counties WHERE regional_center_id = 'nj-ddd-admin' AND county_id = 'atlantic-nj';
UPDATE state_resource_agencies SET state_id = 'new-jersey', agency_type = 'regional_center', name = 'New Jersey Division of Developmental Disabilities', counties_served = 'statewide', catchment_boundaries = 'statewide', website = 'https://nj.gov/humanservices/ddd/', intake_phone = '(609) 633-1482', early_intervention_contact = '', agency_intake_contact = '', eligibility_info_page = '', services_page = '', appeals_info = '', frc_relationship = NULL, office_locations = NULL, languages = '', last_verified_date = '2026-06-14', source_urls = 'https://nj.gov/humanservices/ddd/', source_url = 'https://nj.gov/humanservices/ddd/', source_type = 'official_website', data_origin = 'scraped', verification_status = 'source_listed', last_scraped_at = NULL, confidence_score = 10, evidence_level = 'direct_official_page' WHERE id = 'nj-ddd-admin';

COMMIT;
