-- Rollback Script for State: New Jersey | Phase: district_replacements
-- Generated At: 2026-06-14T22:50:07.922Z

BEGIN TRANSACTION;

UPDATE school_districts SET county_id = 'warren-nj', name = 'Warren County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-warren-nj';
UPDATE school_districts SET county_id = 'union-nj', name = 'Union County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-union-nj';
UPDATE school_districts SET county_id = 'sussex-nj', name = 'Sussex County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-sussex-nj';
UPDATE school_districts SET county_id = 'somerset-nj', name = 'Somerset County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-somerset-nj';
UPDATE school_districts SET county_id = 'salem-nj', name = 'Salem County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-salem-nj';
UPDATE school_districts SET county_id = 'passaic-nj', name = 'Passaic County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-passaic-nj';
UPDATE school_districts SET county_id = 'ocean-nj', name = 'Ocean County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-ocean-nj';
UPDATE school_districts SET county_id = 'morris-nj', name = 'Morris County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-morris-nj';
UPDATE school_districts SET county_id = 'monmouth-nj', name = 'Monmouth County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-monmouth-nj';
UPDATE school_districts SET county_id = 'middlesex-nj', name = 'Middlesex Public Schools Special Education', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = 20000, special_ed_pct = 13.5, inclusion_rate_pct = 65, self_contained_rate_pct = 15, source_url = 'https://www.education.new-jersey.gov', source_type = 'official', data_origin = 'curated_seed', verification_status = 'manual_review_required', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T02:29:27.562Z', confidence_score = 5, evidence_level = NULL WHERE id = 'sd-middlesex-nj';
UPDATE school_districts SET county_id = 'mercer-nj', name = 'Mercer County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-mercer-nj';
UPDATE school_districts SET county_id = 'hunterdon-nj', name = 'Hunterdon County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-hunterdon-nj';
UPDATE school_districts SET county_id = 'hudson-nj', name = 'Hudson County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-hudson-nj';
UPDATE school_districts SET county_id = 'gloucester-nj', name = 'Gloucester County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-gloucester-nj';
UPDATE school_districts SET county_id = 'essex-nj', name = 'Essex County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-essex-nj';
UPDATE school_districts SET county_id = 'cumberland-nj', name = 'Cumberland County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-cumberland-nj';
UPDATE school_districts SET county_id = 'cape-may-nj', name = 'Cape May County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-cape-may-nj';
UPDATE school_districts SET county_id = 'camden-nj', name = 'Camden County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-camden-nj';
UPDATE school_districts SET county_id = 'burlington-nj', name = 'Burlington County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-burlington-nj';
UPDATE school_districts SET county_id = 'bergen-nj', name = 'Bergen Public Schools Special Education', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = 20000, special_ed_pct = 13.5, inclusion_rate_pct = 65, self_contained_rate_pct = 15, source_url = 'https://www.education.new-jersey.gov', source_type = 'official', data_origin = 'curated_seed', verification_status = 'manual_review_required', last_verified_date = '2026-06-12', last_scraped_at = '2026-06-13T02:29:27.562Z', confidence_score = 5, evidence_level = NULL WHERE id = 'sd-bergen-nj';
UPDATE school_districts SET county_id = 'atlantic-nj', name = 'Atlantic County School District', spec_ed_contact_phone = '', spec_ed_contact_email = '', website = 'https://www.education.new-jersey.gov', total_enrollment = NULL, special_ed_pct = NULL, inclusion_rate_pct = NULL, self_contained_rate_pct = NULL, source_url = 'https://www.education.new-jersey.gov', source_type = 'official_directory', data_origin = 'scraped', verification_status = 'manual_review_required', last_verified_date = '2026-06-14', last_scraped_at = NULL, confidence_score = 9.5, evidence_level = 'official_locator_derived' WHERE id = 'sd-atlantic-nj';

COMMIT;
