-- Rollback Script for State: New Jersey | Phase: trusted_nonprofits
-- Generated At: 2026-06-14T15:45:01.634Z

BEGIN TRANSACTION;

DELETE FROM nonprofit_organizations WHERE id = 'np-local-middlesex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'np-local-bergen-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-warren-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-union-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-sussex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-somerset-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-salem-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-passaic-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-ocean-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-morris-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-monmouth-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-middlesex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-mercer-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-hunterdon-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-hudson-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-gloucester-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-essex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-cumberland-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-cape-may-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-camden-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-burlington-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-bergen-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-arc-atlantic-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-warren-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-union-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-sussex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-somerset-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-salem-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-passaic-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-ocean-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-morris-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-monmouth-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-middlesex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-mercer-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-hunterdon-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-hudson-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-gloucester-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-essex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-cumberland-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-cape-may-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-camden-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-burlington-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-bergen-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-parent-atlantic-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-warren-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-union-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-sussex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-somerset-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-salem-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-passaic-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-ocean-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-morris-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-monmouth-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-middlesex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-mercer-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-hunterdon-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-hudson-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-gloucester-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-essex-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-cumberland-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-cape-may-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-camden-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-burlington-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-bergen-nj';
DELETE FROM nonprofit_organizations WHERE id = 'nj-np-rights-atlantic-nj';

COMMIT;
